package ws.daley.genealogy.db.places;

import java.util.ArrayList;

import ws.daley.genealogy.db.places.abstrct.PlaceStructure;
import ws.daley.genealogy.util.Util;

public class CountyUSLToN
{
	public static ArrayList<PlaceStructure> us()
	{
		ArrayList<PlaceStructure> louisiana = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Acadia Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"Allen Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"Ascension Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"Assumption Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"Avoyelles Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"Beauregard Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"Bienville Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"Bossier Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"Caddo Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"Calcasieu Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"Caldwell Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"Cameron Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"Catahoula Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"Claiborne Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"Concordia Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"De Soto Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"East Baton Rouge Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"East Carroll Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"East Feliciana Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"Evangeline Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"Franklin Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"Grant Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"Iberia Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"Iberville Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"Jackson Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"Jefferson Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"Jefferson Davis Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"Lafayette Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"Lafourche Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"La Salle Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"Lincoln Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"Livingston Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"Madison Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"Morehouse Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"Natchitoches Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"Orleans Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"Ouachita Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"Plaquemines Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"Pointe Coupee Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"Rapides Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"Red River Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"Richland Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"Sabine Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"Saint Bernard Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"Saint Charles Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"Saint Helena Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"Saint James Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"Saint John the Baptist Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"Saint Landry Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"Saint Martin Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"Saint Mary Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"Saint Tammany Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"Tangipahoa Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"Tensas Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"Terrebonne Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"Union Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"Vermilion Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"Vernon Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"Washington Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"Webster Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"West Baton Rouge Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"West Carroll Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"West Feliciana Parish", "Louisiana", "United States"}, ""),
				new County(new String[]{"Winn Parish", "Louisiana", "United States"}, "")
			});
		
		ArrayList<PlaceStructure> maine = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Androscoggin County", "Maine", "United States"}, ""),
				new County(new String[]{"Aroostook County", "Maine", "United States"}, ""),
				new County(new String[]{"Cumberland County", "Maine", "United States"}, ""),
				new County(new String[]{"Franklin County", "Maine", "United States"}, ""),
				new County(new String[]{"Hancock County", "Maine", "United States"}, ""),
				new County(new String[]{"Kennebec County", "Maine", "United States"}, ""),
				new County(new String[]{"Knox County", "Maine", "United States"}, ""),
				new County(new String[]{"Lincoln County", "Maine", "United States"}, ""),
				new County(new String[]{"Oxford County", "Maine", "United States"}, ""),
				new County(new String[]{"Penobscot County", "Maine", "United States"}, ""),
				new County(new String[]{"Piscataquis County", "Maine", "United States"}, ""),
				new County(new String[]{"Sagadahoc County", "Maine", "United States"}, ""),
				new County(new String[]{"Somerset County", "Maine", "United States"}, ""),
				new County(new String[]{"Waldo County", "Maine", "United States"}, ""),
				new County(new String[]{"Washington County", "Maine", "United States"}, ""),
				new County(new String[]{"York County", "Maine", "United States"}, "")
			});
		
		ArrayList<PlaceStructure> marshallIslands = Util.arrayList(new PlaceStructure[]{
//				new County(new String[]{"MARSHALL ISLANDS", "United States"}, "")
			});
		
		ArrayList<PlaceStructure> maryland = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Allegany County", "Maryland", "United States"}, ""),
				new County(new String[]{"Anne Arundel County", "Maryland", "United States"}, ""),
				new County(new String[]{"Baltimore County", "Maryland", "United States"}, ""),
				new County(new String[]{"Calvert County", "Maryland", "United States"}, ""),
				new County(new String[]{"Caroline County", "Maryland", "United States"}, ""),
				new County(new String[]{"Carroll County", "Maryland", "United States"}, ""),
				new County(new String[]{"Cecil County", "Maryland", "United States"}, ""),
				new County(new String[]{"Charles County", "Maryland", "United States"}, ""),
				new County(new String[]{"Dorchester County", "Maryland", "United States"}, ""),
				new County(new String[]{"Frederick County", "Maryland", "United States"}, ""),
				new County(new String[]{"Garrett County", "Maryland", "United States"}, ""),
				new County(new String[]{"Harford County", "Maryland", "United States"}, ""),
				new County(new String[]{"Howard County", "Maryland", "United States"}, ""),
				new County(new String[]{"Kent County", "Maryland", "United States"}, ""),
				new County(new String[]{"Montgomery County", "Maryland", "United States"}, ""),
				new County(new String[]{"Prince George''s County", "Maryland", "United States"}, ""),
				new County(new String[]{"Queen Anne''s County", "Maryland", "United States"}, ""),
				new County(new String[]{"Saint Mary''s County", "Maryland", "United States"}, ""),
				new County(new String[]{"Somerset County", "Maryland", "United States"}, ""),
				new County(new String[]{"Talbot County", "Maryland", "United States"}, ""),
				new County(new String[]{"Washington County", "Maryland", "United States"}, ""),
				new County(new String[]{"Wicomico County", "Maryland", "United States"}, ""),
				new County(new String[]{"Worcester County", "Maryland", "United States"}, "")
			});
		
		ArrayList<PlaceStructure> massachusetts = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Barnstable County", "Massachusetts", "United States"}, ""),
				new County(new String[]{"Berkshire County", "Massachusetts", "United States"}, ""),
				new County(new String[]{"Bristol County", "Massachusetts", "United States"}, ""),
				new County(new String[]{"Dukes County", "Massachusetts", "United States"}, ""),
				new County(new String[]{"Essex County", "Massachusetts", "United States"}, ""),
				new County(new String[]{"Franklin County", "Massachusetts", "United States"}, ""),
				new County(new String[]{"Hampden County", "Massachusetts", "United States"}, ""),
				new County(new String[]{"Hampshire County", "Massachusetts", "United States"}, ""),
				new County(new String[]{"Middlesex County", "Massachusetts", "United States"}, ""),
				new County(new String[]{"Nantucket County", "Massachusetts", "United States"}, ""),
				new County(new String[]{"Norfolk County", "Massachusetts", "United States"}, ""),
				new County(new String[]{"Plymouth County", "Massachusetts", "United States"}, ""),
				new County(new String[]{"Suffolk County", "Massachusetts", "United States"}, ""),
				new County(new String[]{"Worcester County", "Massachusetts", "United States"}, "")
			});
		
		ArrayList<PlaceStructure> michigan = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Alcona County", "Michigan", "United States"}, ""),
				new County(new String[]{"Alger County", "Michigan", "United States"}, ""),
				new County(new String[]{"Allegan County", "Michigan", "United States"}, ""),
				new County(new String[]{"Alpena County", "Michigan", "United States"}, ""),
				new County(new String[]{"Antrim County", "Michigan", "United States"}, ""),
				new County(new String[]{"Arenac County", "Michigan", "United States"}, ""),
				new County(new String[]{"Baraga County", "Michigan", "United States"}, ""),
				new County(new String[]{"Barry County", "Michigan", "United States"}, ""),
				new County(new String[]{"Bay County", "Michigan", "United States"}, ""),
				new County(new String[]{"Benzie County", "Michigan", "United States"}, ""),
				new County(new String[]{"Berrien County", "Michigan", "United States"}, ""),
				new County(new String[]{"Branch County", "Michigan", "United States"}, ""),
				new County(new String[]{"Calhoun County", "Michigan", "United States"}, ""),
				new County(new String[]{"Cass County", "Michigan", "United States"}, ""),
				new County(new String[]{"Charlevoix County", "Michigan", "United States"}, ""),
				new County(new String[]{"Cheboygan County", "Michigan", "United States"}, ""),
				new County(new String[]{"Chippewa County", "Michigan", "United States"}, ""),
				new County(new String[]{"Clare County", "Michigan", "United States"}, ""),
				new County(new String[]{"Clinton County", "Michigan", "United States"}, ""),
				new County(new String[]{"Crawford County", "Michigan", "United States"}, ""),
				new County(new String[]{"Delta County", "Michigan", "United States"}, ""),
				new County(new String[]{"Dickinson County", "Michigan", "United States"}, ""),
				new County(new String[]{"Eaton County", "Michigan", "United States"}, ""),
				new County(new String[]{"Emmet County", "Michigan", "United States"}, ""),
				new County(new String[]{"Genesee County", "Michigan", "United States"}, ""),
				new County(new String[]{"Gladwin County", "Michigan", "United States"}, ""),
				new County(new String[]{"Gogebic County", "Michigan", "United States"}, ""),
				new County(new String[]{"Grand Traverse County", "Michigan", "United States"}, ""),
				new County(new String[]{"Gratiot County", "Michigan", "United States"}, ""),
				new County(new String[]{"Hillsdale County", "Michigan", "United States"}, ""),
				new County(new String[]{"Houghton County", "Michigan", "United States"}, ""),
				new County(new String[]{"Huron County", "Michigan", "United States"}, ""),
				new County(new String[]{"Ingham County", "Michigan", "United States"}, ""),
				new County(new String[]{"Ionia County", "Michigan", "United States"}, ""),
				new County(new String[]{"Iosco County", "Michigan", "United States"}, ""),
				new County(new String[]{"Iron County", "Michigan", "United States"}, ""),
				new County(new String[]{"Isabella County", "Michigan", "United States"}, ""),
				new County(new String[]{"Jackson County", "Michigan", "United States"}, ""),
				new County(new String[]{"Kalamazoo County", "Michigan", "United States"}, ""),
				new County(new String[]{"Kalkaska County", "Michigan", "United States"}, ""),
				new County(new String[]{"Kent County", "Michigan", "United States"}, ""),
				new County(new String[]{"Keweenaw County", "Michigan", "United States"}, ""),
				new County(new String[]{"Lake County", "Michigan", "United States"}, ""),
				new County(new String[]{"Lapeer County", "Michigan", "United States"}, ""),
				new County(new String[]{"Leelanau County", "Michigan", "United States"}, ""),
				new County(new String[]{"Lenawee County", "Michigan", "United States"}, ""),
				new County(new String[]{"Livingston County", "Michigan", "United States"}, ""),
				new County(new String[]{"Luce County", "Michigan", "United States"}, ""),
				new County(new String[]{"Mackinac County", "Michigan", "United States"}, ""),
				new County(new String[]{"Macomb County", "Michigan", "United States"}, ""),
				new County(new String[]{"Manistee County", "Michigan", "United States"}, ""),
				new County(new String[]{"Marquette County", "Michigan", "United States"}, ""),
				new County(new String[]{"Mason County", "Michigan", "United States"}, ""),
				new County(new String[]{"Mecosta County", "Michigan", "United States"}, ""),
				new County(new String[]{"Menominee County", "Michigan", "United States"}, ""),
				new County(new String[]{"Midland County", "Michigan", "United States"}, ""),
				new County(new String[]{"Missaukee County", "Michigan", "United States"}, ""),
				new County(new String[]{"Monroe County", "Michigan", "United States"}, ""),
				new County(new String[]{"Montcalm County", "Michigan", "United States"}, ""),
				new County(new String[]{"Montmorency County", "Michigan", "United States"}, ""),
				new County(new String[]{"Muskegon County", "Michigan", "United States"}, ""),
				new County(new String[]{"Newaygo County", "Michigan", "United States"}, ""),
				new County(new String[]{"Oakland County", "Michigan", "United States"}, ""),
				new County(new String[]{"Oceana County", "Michigan", "United States"}, ""),
				new County(new String[]{"Ogemaw County", "Michigan", "United States"}, ""),
				new County(new String[]{"Ontonagon County", "Michigan", "United States"}, ""),
				new County(new String[]{"Osceola County", "Michigan", "United States"}, ""),
				new County(new String[]{"Oscoda County", "Michigan", "United States"}, ""),
				new County(new String[]{"Otsego County", "Michigan", "United States"}, ""),
				new County(new String[]{"Ottawa County", "Michigan", "United States"}, ""),
				new County(new String[]{"Presque Isle County", "Michigan", "United States"}, ""),
				new County(new String[]{"Roscommon County", "Michigan", "United States"}, ""),
				new County(new String[]{"Saginaw County", "Michigan", "United States"}, ""),
				new County(new String[]{"St. Clair County", "Michigan", "United States"}, ""),
				new County(new String[]{"St. Joseph County", "Michigan", "United States"}, ""),
				new County(new String[]{"Sanilac County", "Michigan", "United States"}, ""),
				new County(new String[]{"Schoolcraft County", "Michigan", "United States"}, ""),
				new County(new String[]{"Shiawassee County", "Michigan", "United States"}, ""),
				new County(new String[]{"Tuscola County", "Michigan", "United States"}, ""),
				new County(new String[]{"Van Buren County", "Michigan", "United States"}, ""),
				new County(new String[]{"Washtenaw County", "Michigan", "United States"}, ""),
				new County(new String[]{"Wayne County", "Michigan", "United States"}, ""),
				new County(new String[]{"Wexford County", "Michigan", "United States"}, "")
			});
		
		ArrayList<PlaceStructure> micronesia = Util.arrayList(new PlaceStructure[]{
//				new County(new String[]{"FEDERATED STATES OF MICRONESIA", "United States"}, "")
			});
		
		ArrayList<PlaceStructure> minnesota = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Aitkin County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Anoka County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Becker County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Beltrami County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Benton County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Big Stone County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Blue Earth County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Brown County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Carlton County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Carver County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Cass County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Chippewa County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Chisago County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Clay County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Clearwater County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Cook County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Cottonwood County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Crow Wing County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Dakota County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Dodge County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Douglas County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Faribault County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Fillmore County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Freeborn County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Goodhue County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Grant County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Hennepin County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Houston County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Hubbard County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Isanti County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Itasca County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Jackson County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Kanabec County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Kandiyohi County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Kittson County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Koochiching County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Lac qui Parle County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Lake County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Lake of the Woods County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Le Sueur County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Lincoln County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Lyon County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Mahnomen County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Marshall County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Martin County", "Minnesota", "United States"}, ""),
				new County(new String[]{"McLeod County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Meeker County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Mille Lacs County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Morrison County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Mower County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Murray County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Nicollet County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Nobles County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Norman County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Olmsted County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Otter Tail County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Pennington County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Pine County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Pipestone County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Polk County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Pope County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Ramsey County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Red Lake County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Redwood County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Renville County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Rice County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Rock County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Roseau County", "Minnesota", "United States"}, ""),
				new County(new String[]{"St. Louis County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Scott County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Sherburne County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Sibley County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Stearns County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Steele County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Stevens County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Swift County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Todd County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Traverse County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Wabasha County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Wadena County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Waseca County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Washington County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Watonwan County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Wilkin County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Winona County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Wright County", "Minnesota", "United States"}, ""),
				new County(new String[]{"Yellow Medicine County", "Minnesota", "United States"}, "")
			});
		
		ArrayList<PlaceStructure> mississippi = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Adams County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Alcorn County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Amite County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Attala County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Benton County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Bolivar County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Calhoun County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Carroll County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Chickasaw County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Choctaw County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Claiborne County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Clarke County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Clay County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Coahoma County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Copiah County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Covington County", "Mississippi", "United States"}, ""),
				new County(new String[]{"DeSoto County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Forrest County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Franklin County", "Mississippi", "United States"}, ""),
				new County(new String[]{"George County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Greene County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Grenada County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Hancock County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Harrison County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Hinds County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Holmes County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Humphreys County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Issaquena County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Itawamba County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Jackson County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Jasper County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Jefferson County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Jefferson Davis County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Jones County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Kemper County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Lafayette County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Lamar County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Lauderdale County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Lawrence County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Leake County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Lee County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Leflore County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Lincoln County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Lowndes County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Madison County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Marion County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Marshall County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Monroe County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Montgomery County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Neshoba County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Newton County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Noxubee County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Oktibbeha County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Panola County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Pearl River County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Perry County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Pike County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Pontotoc County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Prentiss County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Quitman County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Rankin County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Scott County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Sharkey County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Simpson County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Smith County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Stone County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Sunflower County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Tallahatchie County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Tate County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Tippah County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Tishomingo County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Tunica County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Union County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Walthall County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Warren County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Washington County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Wayne County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Webster County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Wilkinson County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Winston County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Yalobusha County", "Mississippi", "United States"}, ""),
				new County(new String[]{"Yazoo County", "Mississippi", "United States"}, "")
			});
		
		ArrayList<PlaceStructure> missouri = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Adair County", "Missouri", "United States"}, ""),
				new County(new String[]{"Andrew County", "Missouri", "United States"}, ""),
				new County(new String[]{"Atchison County", "Missouri", "United States"}, ""),
				new County(new String[]{"Audrain County", "Missouri", "United States"}, ""),
				new County(new String[]{"Barry County", "Missouri", "United States"}, ""),
				new County(new String[]{"Barton County", "Missouri", "United States"}, ""),
				new County(new String[]{"Bates County", "Missouri", "United States"}, ""),
				new County(new String[]{"Benton County", "Missouri", "United States"}, ""),
				new County(new String[]{"Bollinger County", "Missouri", "United States"}, ""),
				new County(new String[]{"Boone County", "Missouri", "United States"}, ""),
				new County(new String[]{"Buchanan County", "Missouri", "United States"}, ""),
				new County(new String[]{"Butler County", "Missouri", "United States"}, ""),
				new County(new String[]{"Caldwell County", "Missouri", "United States"}, ""),
				new County(new String[]{"Callaway County", "Missouri", "United States"}, ""),
				new County(new String[]{"Camden County", "Missouri", "United States"}, ""),
				new County(new String[]{"Cape Girardeau County", "Missouri", "United States"}, ""),
				new County(new String[]{"Carroll County", "Missouri", "United States"}, ""),
				new County(new String[]{"Carter County", "Missouri", "United States"}, ""),
				new County(new String[]{"Cass County", "Missouri", "United States"}, ""),
				new County(new String[]{"Cedar County", "Missouri", "United States"}, ""),
				new County(new String[]{"Chariton County", "Missouri", "United States"}, ""),
				new County(new String[]{"Christian County", "Missouri", "United States"}, ""),
				new County(new String[]{"Clark County", "Missouri", "United States"}, ""),
				new County(new String[]{"Clay County", "Missouri", "United States"}, ""),
				new County(new String[]{"Clinton County", "Missouri", "United States"}, ""),
				new County(new String[]{"Cole County", "Missouri", "United States"}, ""),
				new County(new String[]{"Cooper County", "Missouri", "United States"}, ""),
				new County(new String[]{"Crawford County", "Missouri", "United States"}, ""),
				new County(new String[]{"Dade County", "Missouri", "United States"}, ""),
				new County(new String[]{"Dallas County", "Missouri", "United States"}, ""),
				new County(new String[]{"Daviess County", "Missouri", "United States"}, ""),
				new County(new String[]{"DeKalb County", "Missouri", "United States"}, ""),
				new County(new String[]{"Dent County", "Missouri", "United States"}, ""),
				new County(new String[]{"Douglas County", "Missouri", "United States"}, ""),
				new County(new String[]{"Dunklin County", "Missouri", "United States"}, ""),
				new County(new String[]{"Franklin County", "Missouri", "United States"}, ""),
				new County(new String[]{"Gasconade County", "Missouri", "United States"}, ""),
				new County(new String[]{"Gentry County", "Missouri", "United States"}, ""),
				new County(new String[]{"Greene County", "Missouri", "United States"}, ""),
				new County(new String[]{"Grundy County", "Missouri", "United States"}, ""),
				new County(new String[]{"Harrison County", "Missouri", "United States"}, ""),
				new County(new String[]{"Henry County", "Missouri", "United States"}, ""),
				new County(new String[]{"Hickory County", "Missouri", "United States"}, ""),
				new County(new String[]{"Holt County", "Missouri", "United States"}, ""),
				new County(new String[]{"Howard County", "Missouri", "United States"}, ""),
				new County(new String[]{"Howell County", "Missouri", "United States"}, ""),
				new County(new String[]{"Iron County", "Missouri", "United States"}, ""),
				new County(new String[]{"Jackson County", "Missouri", "United States"}, ""),
				new County(new String[]{"Jasper County", "Missouri", "United States"}, ""),
				new County(new String[]{"Jefferson County", "Missouri", "United States"}, ""),
				new County(new String[]{"Johnson County", "Missouri", "United States"}, ""),
				new County(new String[]{"Knox County", "Missouri", "United States"}, ""),
				new County(new String[]{"Laclede County", "Missouri", "United States"}, ""),
				new County(new String[]{"Lafayette County", "Missouri", "United States"}, ""),
				new County(new String[]{"Lawrence County", "Missouri", "United States"}, ""),
				new County(new String[]{"Lewis County", "Missouri", "United States"}, ""),
				new County(new String[]{"Lincoln County", "Missouri", "United States"}, ""),
				new County(new String[]{"Linn County", "Missouri", "United States"}, ""),
				new County(new String[]{"Livingston County", "Missouri", "United States"}, ""),
				new County(new String[]{"Macon County", "Missouri", "United States"}, ""),
				new County(new String[]{"Madison County", "Missouri", "United States"}, ""),
				new County(new String[]{"Maries County", "Missouri", "United States"}, ""),
				new County(new String[]{"Marion County", "Missouri", "United States"}, ""),
				new County(new String[]{"McDonald County", "Missouri", "United States"}, ""),
				new County(new String[]{"Mercer County", "Missouri", "United States"}, ""),
				new County(new String[]{"Miller County", "Missouri", "United States"}, ""),
				new County(new String[]{"Mississippi County", "Missouri", "United States"}, ""),
				new County(new String[]{"Moniteau County", "Missouri", "United States"}, ""),
				new County(new String[]{"Monroe County", "Missouri", "United States"}, ""),
				new County(new String[]{"Montgomery County", "Missouri", "United States"}, ""),
				new County(new String[]{"Morgan County", "Missouri", "United States"}, ""),
				new County(new String[]{"New Madrid County", "Missouri", "United States"}, ""),
				new County(new String[]{"Newton County", "Missouri", "United States"}, ""),
				new County(new String[]{"Nodaway County", "Missouri", "United States"}, ""),
				new County(new String[]{"Oregon County", "Missouri", "United States"}, ""),
				new County(new String[]{"Osage County", "Missouri", "United States"}, ""),
				new County(new String[]{"Ozark County", "Missouri", "United States"}, ""),
				new County(new String[]{"Pemiscot County", "Missouri", "United States"}, ""),
				new County(new String[]{"Perry County", "Missouri", "United States"}, ""),
				new County(new String[]{"Pettis County", "Missouri", "United States"}, ""),
				new County(new String[]{"Phelps County", "Missouri", "United States"}, ""),
				new County(new String[]{"Pike County", "Missouri", "United States"}, ""),
				new County(new String[]{"Platte County", "Missouri", "United States"}, ""),
				new County(new String[]{"Polk County", "Missouri", "United States"}, ""),
				new County(new String[]{"Pulaski County", "Missouri", "United States"}, ""),
				new County(new String[]{"Putnam County", "Missouri", "United States"}, ""),
				new County(new String[]{"Ralls County", "Missouri", "United States"}, ""),
				new County(new String[]{"Randolph County", "Missouri", "United States"}, ""),
				new County(new String[]{"Ray County", "Missouri", "United States"}, ""),
				new County(new String[]{"Reynolds County", "Missouri", "United States"}, ""),
				new County(new String[]{"Ripley County", "Missouri", "United States"}, ""),
				new County(new String[]{"Saint Charles County", "Missouri", "United States"}, ""),
				new County(new String[]{"Saint Clair County", "Missouri", "United States"}, ""),
				new County(new String[]{"Saint Francois County", "Missouri", "United States"}, ""),
				new County(new String[]{"Saint Louis County", "Missouri", "United States"}, ""),
				new County(new String[]{"Sainte Genevieve County", "Missouri", "United States"}, ""),
				new County(new String[]{"Saline County", "Missouri", "United States"}, ""),
				new County(new String[]{"Schuyler County", "Missouri", "United States"}, ""),
				new County(new String[]{"Scotland County", "Missouri", "United States"}, ""),
				new County(new String[]{"Scott County", "Missouri", "United States"}, ""),
				new County(new String[]{"Shannon County", "Missouri", "United States"}, ""),
				new County(new String[]{"Shelby County", "Missouri", "United States"}, ""),
				new County(new String[]{"Stoddard County", "Missouri", "United States"}, ""),
				new County(new String[]{"Stone County", "Missouri", "United States"}, ""),
				new County(new String[]{"Sullivan County", "Missouri", "United States"}, ""),
				new County(new String[]{"Taney County", "Missouri", "United States"}, ""),
				new County(new String[]{"Texas County", "Missouri", "United States"}, ""),
				new County(new String[]{"Vernon County", "Missouri", "United States"}, ""),
				new County(new String[]{"Warren County", "Missouri", "United States"}, ""),
				new County(new String[]{"Washington County", "Missouri", "United States"}, ""),
				new County(new String[]{"Wayne County", "Missouri", "United States"}, ""),
				new County(new String[]{"Webster County", "Missouri", "United States"}, ""),
				new County(new String[]{"Worth County", "Missouri", "United States"}, ""),
				new County(new String[]{"Wright County", "Missouri", "United States"}, "")
			});
		
		ArrayList<PlaceStructure> montana = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Beaverhead County", "Montana", "United States"}, ""),
				new County(new String[]{"Big Horn County", "Montana", "United States"}, ""),
				new County(new String[]{"Blaine County", "Montana", "United States"}, ""),
				new County(new String[]{"Broadwater County", "Montana", "United States"}, ""),
				new County(new String[]{"Carbon County", "Montana", "United States"}, ""),
				new County(new String[]{"Carter County", "Montana", "United States"}, ""),
				new County(new String[]{"Cascade County", "Montana", "United States"}, ""),
				new County(new String[]{"Chouteau County", "Montana", "United States"}, ""),
				new County(new String[]{"Custer County", "Montana", "United States"}, ""),
				new County(new String[]{"Daniels County", "Montana", "United States"}, ""),
				new County(new String[]{"Dawson County", "Montana", "United States"}, ""),
				new County(new String[]{"Deer Lodge County", "Montana", "United States"}, ""),
				new County(new String[]{"Fallon County", "Montana", "United States"}, ""),
				new County(new String[]{"Fergus County", "Montana", "United States"}, ""),
				new County(new String[]{"Flathead County", "Montana", "United States"}, ""),
				new County(new String[]{"Gallatin County", "Montana", "United States"}, ""),
				new County(new String[]{"Garfield County", "Montana", "United States"}, ""),
				new County(new String[]{"Glacier County", "Montana", "United States"}, ""),
				new County(new String[]{"Golden Valley County", "Montana", "United States"}, ""),
				new County(new String[]{"Granite County", "Montana", "United States"}, ""),
				new County(new String[]{"Hill County", "Montana", "United States"}, ""),
				new County(new String[]{"Jefferson County", "Montana", "United States"}, ""),
				new County(new String[]{"Judith Basin County", "Montana", "United States"}, ""),
				new County(new String[]{"Lake County", "Montana", "United States"}, ""),
				new County(new String[]{"Lewis and Clark County", "Montana", "United States"}, ""),
				new County(new String[]{"Liberty County", "Montana", "United States"}, ""),
				new County(new String[]{"Lincoln County", "Montana", "United States"}, ""),
				new County(new String[]{"Madison County", "Montana", "United States"}, ""),
				new County(new String[]{"McCone County", "Montana", "United States"}, ""),
				new County(new String[]{"Meagher County", "Montana", "United States"}, ""),
				new County(new String[]{"Mineral County", "Montana", "United States"}, ""),
				new County(new String[]{"Missoula County", "Montana", "United States"}, ""),
				new County(new String[]{"Musselshell County", "Montana", "United States"}, ""),
				new County(new String[]{"Park County", "Montana", "United States"}, ""),
				new County(new String[]{"Petroleum County", "Montana", "United States"}, ""),
				new County(new String[]{"Phillips County", "Montana", "United States"}, ""),
				new County(new String[]{"Pondera County", "Montana", "United States"}, ""),
				new County(new String[]{"Powder River County", "Montana", "United States"}, ""),
				new County(new String[]{"Powell County", "Montana", "United States"}, ""),
				new County(new String[]{"Prairie County", "Montana", "United States"}, ""),
				new County(new String[]{"Ravalli County", "Montana", "United States"}, ""),
				new County(new String[]{"Richland County", "Montana", "United States"}, ""),
				new County(new String[]{"Roosevelt County", "Montana", "United States"}, ""),
				new County(new String[]{"Rosebud County", "Montana", "United States"}, ""),
				new County(new String[]{"Sanders County", "Montana", "United States"}, ""),
				new County(new String[]{"Sheridan County", "Montana", "United States"}, ""),
				new County(new String[]{"Silver Bow County", "Montana", "United States"}, ""),
				new County(new String[]{"Stillwater County", "Montana", "United States"}, ""),
				new County(new String[]{"Sweet Grass County", "Montana", "United States"}, ""),
				new County(new String[]{"Teton County", "Montana", "United States"}, ""),
				new County(new String[]{"Toole County", "Montana", "United States"}, ""),
				new County(new String[]{"Treasure County", "Montana", "United States"}, ""),
				new County(new String[]{"Valley County", "Montana", "United States"}, ""),
				new County(new String[]{"Wheatland County", "Montana", "United States"}, ""),
				new County(new String[]{"Wibaux County", "Montana", "United States"}, ""),
				new County(new String[]{"Yellowstone County", "Montana", "United States"}, "")
			});
		
		ArrayList<PlaceStructure> nebraska = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Adams County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Antelope County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Arthur County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Banner County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Blaine County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Boone County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Box Butte County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Boyd County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Brown County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Buffalo County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Burt County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Butler County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Cass County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Cedar County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Chase County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Cherry County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Cheyenne County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Clay County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Colfax County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Cuming County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Custer County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Dakota County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Dawes County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Dawson County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Deuel County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Dixon County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Dodge County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Douglas County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Dundy County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Fillmore County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Franklin County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Frontier County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Furnas County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Gage County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Garden County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Garfield County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Gosper County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Grant County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Greeley County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Hall County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Hamilton County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Harlan County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Hayes County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Hitchcock County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Holt County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Hooker County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Howard County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Jefferson County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Johnson County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Kearney County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Keith County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Keya Paha County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Kimball County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Knox County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Lancaster County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Lincoln County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Logan County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Loup County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Madison County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"McPherson County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Merrick County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Morrill County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Nance County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Nemaha County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Nuckolls County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Otoe County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Pawnee County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Perkins County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Phelps County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Pierce County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Platte County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Polk County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Red Willow County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Richardson County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Rock County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Saline County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Sarpy County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Saunders County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Scotts Bluff County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Seward County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Sheridan County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Sherman County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Sioux County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Stanton County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Thayer County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Thomas County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Thurston County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Valley County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Washington County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Wayne County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Webster County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"Wheeler County", "Nebraska", "Unite States"}, ""),
				new County(new String[]{"York County", "Nebraska", "Unite States"}, "")
			});
		
		ArrayList<PlaceStructure> nevada = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Carson City", "Nevada", "United States"}, ""),
				new County(new String[]{"Churchill County", "Nevada", "United States"}, ""),
				new County(new String[]{"Clark County", "Nevada", "United States"}, ""),
				new County(new String[]{"Douglas County", "Nevada", "United States"}, ""),
				new County(new String[]{"Elko County", "Nevada", "United States"}, ""),
				new County(new String[]{"Esmeralda County", "Nevada", "United States"}, ""),
				new County(new String[]{"Eureka County", "Nevada", "United States"}, ""),
				new County(new String[]{"Humboldt County", "Nevada", "United States"}, ""),
				new County(new String[]{"Lander County", "Nevada", "United States"}, ""),
				new County(new String[]{"Lincoln County", "Nevada", "United States"}, ""),
				new County(new String[]{"Lyon County", "Nevada", "United States"}, ""),
				new County(new String[]{"Mineral County", "Nevada", "United States"}, ""),
				new County(new String[]{"Nye County", "Nevada", "United States"}, ""),
				new County(new String[]{"Pershing County", "Nevada", "United States"}, ""),
				new County(new String[]{"Storey County", "Nevada", "United States"}, ""),
				new County(new String[]{"Washoe County", "Nevada", "United States"}, ""),
				new County(new String[]{"White Pine County", "Nevada", "United States"}, "")
			});
		
		ArrayList<PlaceStructure> newHampshire = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Belknap County", "New Hampshire", "United States"}, ""),
				new County(new String[]{"Carroll County", "New Hampshire", "United States"}, ""),
				new County(new String[]{"Cheshire County", "New Hampshire", "United States"}, ""),
				new County(new String[]{"Coos County", "New Hampshire", "United States"}, ""),
				new County(new String[]{"Grafton County", "New Hampshire", "United States"}, ""),
				new County(new String[]{"Hillsborough County", "New Hampshire", "United States"}, ""),
				new County(new String[]{"Merrimack County", "New Hampshire", "United States"}, ""),
				new County(new String[]{"Rockingham County", "New Hampshire", "United States"}, ""),
				new County(new String[]{"Strafford County", "New Hampshire", "United States"}, ""),
				new County(new String[]{"Sullivan County", "New Hampshire", "United States"}, "")
			});
		
		ArrayList<PlaceStructure> newJersey = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Atlantic County", "New Jersey", "United States"}, ""),
				new County(new String[]{"Bergen County", "New Jersey", "United States"}, ""),
				new County(new String[]{"Burlington County", "New Jersey", "United States"}, ""),
				new County(new String[]{"Camden County", "New Jersey", "United States"}, ""),
				new County(new String[]{"Cape May County", "New Jersey", "United States"}, ""),
				new County(new String[]{"Cumberland County", "New Jersey", "United States"}, ""),
				new County(new String[]{"Essex County", "New Jersey", "United States"}, ""),
				new County(new String[]{"Gloucester County", "New Jersey", "United States"}, ""),
				new County(new String[]{"Hudson County", "New Jersey", "United States"}, ""),
				new County(new String[]{"Hunterdon County", "New Jersey", "United States"}, ""),
				new County(new String[]{"Mercer County", "New Jersey", "United States"}, ""),
				new County(new String[]{"Middlesex County", "New Jersey", "United States"}, ""),
				new County(new String[]{"Monmouth County", "New Jersey", "United States"}, ""),
				new County(new String[]{"Morris County", "New Jersey", "United States"}, ""),
				new County(new String[]{"Ocean County", "New Jersey", "United States"}, ""),
				new County(new String[]{"Passaic County", "New Jersey", "United States"}, ""),
				new County(new String[]{"Salem County", "New Jersey", "United States"}, ""),
				new County(new String[]{"Somerset County", "New Jersey", "United States"}, ""),
				new County(new String[]{"Sussex County", "New Jersey", "United States"}, ""),
				new County(new String[]{"Union County", "New Jersey", "United States"}, ""),
				new County(new String[]{"Warren County", "New Jersey", "United States"}, "")
			});
		
		ArrayList<PlaceStructure> newMexico = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Bernalillo County", "New Mexico", "United States"}, ""),
				new County(new String[]{"Catron County", "New Mexico", "United States"}, ""),
				new County(new String[]{"Chaves County", "New Mexico", "United States"}, ""),
				new County(new String[]{"Cibola County", "New Mexico", "United States"}, ""),
				new County(new String[]{"Colfax County", "New Mexico", "United States"}, ""),
				new County(new String[]{"Curry County", "New Mexico", "United States"}, ""),
				new County(new String[]{"De Baca County", "New Mexico", "United States"}, ""),
				new County(new String[]{"Doña Ana County", "New Mexico", "United States"}, ""),
				new County(new String[]{"Eddy County", "New Mexico", "United States"}, ""),
				new County(new String[]{"Grant County", "New Mexico", "United States"}, ""),
				new County(new String[]{"Guadalupe County", "New Mexico", "United States"}, ""),
				new County(new String[]{"Harding County", "New Mexico", "United States"}, ""),
				new County(new String[]{"Hidalgo County", "New Mexico", "United States"}, ""),
				new County(new String[]{"Lea County", "New Mexico", "United States"}, ""),
				new County(new String[]{"Lincoln County", "New Mexico", "United States"}, ""),
				new County(new String[]{"Los Alamos County", "New Mexico", "United States"}, ""),
				new County(new String[]{"Luna County", "New Mexico", "United States"}, ""),
				new County(new String[]{"McKinley County", "New Mexico", "United States"}, ""),
				new County(new String[]{"Mora County", "New Mexico", "United States"}, ""),
				new County(new String[]{"Otero County", "New Mexico", "United States"}, ""),
				new County(new String[]{"Quay County", "New Mexico", "United States"}, ""),
				new County(new String[]{"Rio Arriba County", "New Mexico", "United States"}, ""),
				new County(new String[]{"Roosevelt County", "New Mexico", "United States"}, ""),
				new County(new String[]{"Sandoval County", "New Mexico", "United States"}, ""),
				new County(new String[]{"San Juan County", "New Mexico", "United States"}, ""),
				new County(new String[]{"San Miguel County", "New Mexico", "United States"}, ""),
				new County(new String[]{"Santa Fe County", "New Mexico", "United States"}, ""),
				new County(new String[]{"Sierra County", "New Mexico", "United States"}, ""),
				new County(new String[]{"Socorro County", "New Mexico", "United States"}, ""),
				new County(new String[]{"Taos County", "New Mexico", "United States"}, ""),
				new County(new String[]{"Torrance County", "New Mexico", "United States"}, ""),
				new County(new String[]{"Union County", "New Mexico", "United States"}, ""),
				new County(new String[]{"Valencia County", "New Mexico", "United States"}, "")
			});
		
		ArrayList<PlaceStructure> newYork = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Albany County", "New York", "United States"}, ""),
				new County(new String[]{"Allegany County", "New York", "United States"}, ""),
				new County(new String[]{"Bronx County", "New York", "United States"}, ""),
				new County(new String[]{"Broome County", "New York", "United States"}, ""),
				new County(new String[]{"Cattaraugus County", "New York", "United States"}, ""),
				new County(new String[]{"Cayuga County", "New York", "United States"}, ""),
				new County(new String[]{"Chautauqua County", "New York", "United States"}, ""),
				new County(new String[]{"Chemung County", "New York", "United States"}, ""),
				new County(new String[]{"Chenango County", "New York", "United States"}, ""),
				new County(new String[]{"Clinton County", "New York", "United States"}, ""),
				new County(new String[]{"Columbia County", "New York", "United States"}, ""),
				new County(new String[]{"Cortland County", "New York", "United States"}, ""),
				new County(new String[]{"Delaware County", "New York", "United States"}, ""),
				new County(new String[]{"Dutchess County", "New York", "United States"}, ""),
				new County(new String[]{"Erie County", "New York", "United States"}, ""),
				new County(new String[]{"Essex County", "New York", "United States"}, ""),
				new County(new String[]{"Franklin County", "New York", "United States"}, ""),
				new County(new String[]{"Fulton County", "New York", "United States"}, ""),
				new County(new String[]{"Genesee County", "New York", "United States"}, ""),
				new County(new String[]{"Greene County", "New York", "United States"}, ""),
				new County(new String[]{"Hamilton County", "New York", "United States"}, ""),
				new County(new String[]{"Herkimer County", "New York", "United States"}, ""),
				new County(new String[]{"Jefferson County", "New York", "United States"}, ""),
				new County(new String[]{"Kings County", "New York", "United States"}, ""),
				new County(new String[]{"Brooklyn", "New York", "United States"}, ""),
				new County(new String[]{"Lewis County", "New York", "United States"}, ""),
				new County(new String[]{"Livingston County", "New York", "United States"}, ""),
				new County(new String[]{"Madison County", "New York", "United States"}, ""),
				new County(new String[]{"Monroe County", "New York", "United States"}, ""),
				new County(new String[]{"Montgomery County", "New York", "United States"}, ""),
				new County(new String[]{"Nassau County", "New York", "United States"}, ""),
				new County(new String[]{"New York County", "New York", "United States"}, ""),
				new County(new String[]{"Manhattan", "New York", "United States"}, ""),
				new County(new String[]{"Niagara County", "New York", "United States"}, ""),
				new County(new String[]{"Oneida County", "New York", "United States"}, ""),
				new County(new String[]{"Onondaga County", "New York", "United States"}, ""),
				new County(new String[]{"Ontario County", "New York", "United States"}, ""),
				new County(new String[]{"Orange County", "New York", "United States"}, ""),
				new County(new String[]{"Orleans County", "New York", "United States"}, ""),
				new County(new String[]{"Oswego County", "New York", "United States"}, ""),
				new County(new String[]{"Otsego County", "New York", "United States"}, ""),
				new County(new String[]{"Putnam County", "New York", "United States"}, ""),
				new County(new String[]{"Queens County", "New York", "United States"}, ""),
				new County(new String[]{"Rensselaer County", "New York", "United States"}, ""),
				new County(new String[]{"Richmond County", "New York", "United States"}, ""),
				new County(new String[]{"Staten Island", "New York", "United States"}, ""),
				new County(new String[]{"Rockland County", "New York", "United States"}, ""),
				new County(new String[]{"St. Lawrence County", "New York", "United States"}, ""),
				new County(new String[]{"Saratoga County", "New York", "United States"}, ""),
				new County(new String[]{"Schenectady County", "New York", "United States"}, ""),
				new County(new String[]{"Schoharie County", "New York", "United States"}, ""),
				new County(new String[]{"Schuyler County", "New York", "United States"}, ""),
				new County(new String[]{"Seneca County", "New York", "United States"}, ""),
				new County(new String[]{"Steuben County", "New York", "United States"}, ""),
				new County(new String[]{"Suffolk County", "New York", "United States"}, ""),
				new County(new String[]{"Sullivan County", "New York", "United States"}, ""),
				new County(new String[]{"Tioga County", "New York", "United States"}, ""),
				new County(new String[]{"Tompkins County", "New York", "United States"}, ""),
				new County(new String[]{"Ulster County", "New York", "United States"}, ""),
				new County(new String[]{"Warren County", "New York", "United States"}, ""),
				new County(new String[]{"Washington County", "New York", "United States"}, ""),
				new County(new String[]{"Wayne County", "New York", "United States"}, ""),
				new County(new String[]{"Westchester County", "New York", "United States"}, ""),
				new County(new String[]{"Wyoming County", "New York", "United States"}, ""),
				new County(new String[]{"Yates County", "New York", "United States"}, "")
			});
		
		ArrayList<PlaceStructure> northCarolina = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Alamance County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Alexander County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Alleghany County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Anson County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Ashe County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Avery County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Beaufort County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Bertie County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Bladen County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Brunswick County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Buncombe County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Burke County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Cabarrus County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Caldwell County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Camden County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Carteret County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Caswell County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Catawba County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Chatham County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Cherokee County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Chowan County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Clay County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Cleveland County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Columbus County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Craven County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Cumberland County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Currituck County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Dare County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Davidson County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Davie County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Duplin County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Durham County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Edgecombe County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Forsyth County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Franklin County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Gaston County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Gates County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Graham County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Granville County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Greene County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Guilford County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Halifax County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Harnett County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Haywood County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Henderson County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Hertford County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Hoke County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Hyde County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Iredell County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Jackson County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Johnston County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Jones County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Lee County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Lenoir County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Lincoln County", "North Carolina", "New York"}, ""),
				new County(new String[]{"McDowell County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Macon County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Madison County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Martin County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Mecklenburg County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Mitchell County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Montgomery County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Moore County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Nash County", "North Carolina", "New York"}, ""),
				new County(new String[]{"New Hanover County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Northampton County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Onslow County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Orange County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Pamlico County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Pasquotank County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Pender County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Perquimans County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Person County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Pitt County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Polk County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Randolph County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Richmond County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Robeson County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Rockingham County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Rowan County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Rutherford County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Sampson County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Scotland County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Stanly County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Stokes County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Surry County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Swain County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Transylvania County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Tyrrell County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Union County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Vance County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Wake County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Warren County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Washington County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Watauga County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Wayne County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Wilkes County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Wilson County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Yadkin County", "North Carolina", "New York"}, ""),
				new County(new String[]{"Yancey County", "North Carolina", "New York"}, "")
			});
		
		ArrayList<PlaceStructure> northDakota = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Adams County", "North Dakota", "United States"}, ""),
				new County(new String[]{"Barnes County", "North Dakota", "United States"}, ""),
				new County(new String[]{"Benson County", "North Dakota", "United States"}, ""),
				new County(new String[]{"Billings County", "North Dakota", "United States"}, ""),
				new County(new String[]{"Bottineau County", "North Dakota", "United States"}, ""),
				new County(new String[]{"Bowman County", "North Dakota", "United States"}, ""),
				new County(new String[]{"Burke County", "North Dakota", "United States"}, ""),
				new County(new String[]{"Burleigh County", "North Dakota", "United States"}, ""),
				new County(new String[]{"Cass County", "North Dakota", "United States"}, ""),
				new County(new String[]{"Cavalier County", "North Dakota", "United States"}, ""),
				new County(new String[]{"Dickey County", "North Dakota", "United States"}, ""),
				new County(new String[]{"Divide County", "North Dakota", "United States"}, ""),
				new County(new String[]{"Dunn County", "North Dakota", "United States"}, ""),
				new County(new String[]{"Eddy County", "North Dakota", "United States"}, ""),
				new County(new String[]{"Emmons County", "North Dakota", "United States"}, ""),
				new County(new String[]{"Foster County", "North Dakota", "United States"}, ""),
				new County(new String[]{"Golden Valley County", "North Dakota", "United States"}, ""),
				new County(new String[]{"Grand Forks County", "North Dakota", "United States"}, ""),
				new County(new String[]{"Grant County", "North Dakota", "United States"}, ""),
				new County(new String[]{"Griggs County", "North Dakota", "United States"}, ""),
				new County(new String[]{"Hettinger County", "North Dakota", "United States"}, ""),
				new County(new String[]{"Kidder County", "North Dakota", "United States"}, ""),
				new County(new String[]{"LaMoure County", "North Dakota", "United States"}, ""),
				new County(new String[]{"Logan County", "North Dakota", "United States"}, ""),
				new County(new String[]{"McHenry County", "North Dakota", "United States"}, ""),
				new County(new String[]{"McIntosh County", "North Dakota", "United States"}, ""),
				new County(new String[]{"McKenzie County", "North Dakota", "United States"}, ""),
				new County(new String[]{"McLean County", "North Dakota", "United States"}, ""),
				new County(new String[]{"Mercer County", "North Dakota", "United States"}, ""),
				new County(new String[]{"Morton County", "North Dakota", "United States"}, ""),
				new County(new String[]{"Mountrail County", "North Dakota", "United States"}, ""),
				new County(new String[]{"Nelson County", "North Dakota", "United States"}, ""),
				new County(new String[]{"Oliver County", "North Dakota", "United States"}, ""),
				new County(new String[]{"Pembina County", "North Dakota", "United States"}, ""),
				new County(new String[]{"Pierce County", "North Dakota", "United States"}, ""),
				new County(new String[]{"Ramsey County", "North Dakota", "United States"}, ""),
				new County(new String[]{"Ransom County", "North Dakota", "United States"}, ""),
				new County(new String[]{"Renville County", "North Dakota", "United States"}, ""),
				new County(new String[]{"Richland County", "North Dakota", "United States"}, ""),
				new County(new String[]{"Rolette County", "North Dakota", "United States"}, ""),
				new County(new String[]{"Sargent County", "North Dakota", "United States"}, ""),
				new County(new String[]{"Sheridan County", "North Dakota", "United States"}, ""),
				new County(new String[]{"Sioux County", "North Dakota", "United States"}, ""),
				new County(new String[]{"Slope County", "North Dakota", "United States"}, ""),
				new County(new String[]{"Stark County", "North Dakota", "United States"}, ""),
				new County(new String[]{"Steele County", "North Dakota", "United States"}, ""),
				new County(new String[]{"Stutsman County", "North Dakota", "United States"}, ""),
				new County(new String[]{"Towner County", "North Dakota", "United States"}, ""),
				new County(new String[]{"Traill County", "North Dakota", "United States"}, ""),
				new County(new String[]{"Walsh County", "North Dakota", "United States"}, ""),
				new County(new String[]{"Ward County", "North Dakota", "United States"}, ""),
				new County(new String[]{"Wells County", "North Dakota", "United States"}, ""),
				new County(new String[]{"Williams County", "North Dakota", "United States"}, "")
			});
		
		ArrayList<PlaceStructure> northernMarianaIslands = Util.arrayList(new PlaceStructure[]{
//				new County(new String[]{"NORTHERN MARIANA ISLANDS", "United States"}, "")
			});
		
		ArrayList<PlaceStructure> list = new ArrayList<PlaceStructure>();
		list = Util.arrayList(list, louisiana);
		list = Util.arrayList(list, maine);
		list = Util.arrayList(list, marshallIslands);
		list = Util.arrayList(list, maryland);
		list = Util.arrayList(list, massachusetts);
		list = Util.arrayList(list, michigan);
		list = Util.arrayList(list, micronesia);
		list = Util.arrayList(list, minnesota);
		list = Util.arrayList(list, mississippi);
		list = Util.arrayList(list, missouri);
		list = Util.arrayList(list, montana);
		list = Util.arrayList(list, nebraska);
		list = Util.arrayList(list, nevada);
		list = Util.arrayList(list, newHampshire);
		list = Util.arrayList(list, newJersey);
		list = Util.arrayList(list, newMexico);
		list = Util.arrayList(list, newYork);
		list = Util.arrayList(list, northCarolina);
		list = Util.arrayList(list, northDakota);
		list = Util.arrayList(list, northernMarianaIslands);
		return list;
	}
}
