package ws.daley.genealogy.db.places;

import java.util.ArrayList;

import ws.daley.genealogy.db.places.abstrct.PlaceStructure;
import ws.daley.genealogy.util.Util;

public class CountyUSOToZ
{
	public static ArrayList<PlaceStructure> us()
	{
		
		ArrayList<PlaceStructure> ohio = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Adams County", "Ohio", "United States"}, ""),
				new County(new String[]{"Allen County", "Ohio", "United States"}, ""),
				new County(new String[]{"Ashland County", "Ohio", "United States"}, ""),
				new County(new String[]{"Ashtabula County", "Ohio", "United States"}, ""),
				new County(new String[]{"Athens County", "Ohio", "United States"}, ""),
				new County(new String[]{"Auglaize County", "Ohio", "United States"}, ""),
				new County(new String[]{"Belmont County", "Ohio", "United States"}, ""),
				new County(new String[]{"Brown County", "Ohio", "United States"}, ""),
				new County(new String[]{"Butler County", "Ohio", "United States"}, ""),
				new County(new String[]{"Carroll County", "Ohio", "United States"}, ""),
				new County(new String[]{"Champaign County", "Ohio", "United States"}, ""),
				new County(new String[]{"Clark County", "Ohio", "United States"}, ""),
				new County(new String[]{"Clermont County", "Ohio", "United States"}, ""),
				new County(new String[]{"Clinton County", "Ohio", "United States"}, ""),
				new County(new String[]{"Columbiana County", "Ohio", "United States"}, ""),
				new County(new String[]{"Coshocton County", "Ohio", "United States"}, ""),
				new County(new String[]{"Crawford County", "Ohio", "United States"}, ""),
				new County(new String[]{"Cuyahoga County", "Ohio", "United States"}, ""),
				new County(new String[]{"Darke County", "Ohio", "United States"}, ""),
				new County(new String[]{"Defiance County", "Ohio", "United States"}, ""),
				new County(new String[]{"Delaware County", "Ohio", "United States"}, ""),
				new County(new String[]{"Erie County", "Ohio", "United States"}, ""),
				new County(new String[]{"Fairfield County", "Ohio", "United States"}, ""),
				new County(new String[]{"Fayette County", "Ohio", "United States"}, ""),
				new County(new String[]{"Franklin County", "Ohio", "United States"}, ""),
				new County(new String[]{"Fulton County", "Ohio", "United States"}, ""),
				new County(new String[]{"Gallia County", "Ohio", "United States"}, ""),
				new County(new String[]{"Geauga County", "Ohio", "United States"}, ""),
				new County(new String[]{"Greene County", "Ohio", "United States"}, ""),
				new County(new String[]{"Guernsey County", "Ohio", "United States"}, ""),
				new County(new String[]{"Hamilton County", "Ohio", "United States"}, ""),
				new County(new String[]{"Hancock County", "Ohio", "United States"}, ""),
				new County(new String[]{"Hardin County", "Ohio", "United States"}, ""),
				new County(new String[]{"Harrison County", "Ohio", "United States"}, ""),
				new County(new String[]{"Henry County", "Ohio", "United States"}, ""),
				new County(new String[]{"Highland County", "Ohio", "United States"}, ""),
				new County(new String[]{"Hocking County", "Ohio", "United States"}, ""),
				new County(new String[]{"Holmes County", "Ohio", "United States"}, ""),
				new County(new String[]{"Huron County", "Ohio", "United States"}, ""),
				new County(new String[]{"Jackson County", "Ohio", "United States"}, ""),
				new County(new String[]{"Jefferson County", "Ohio", "United States"}, ""),
				new County(new String[]{"Knox County", "Ohio", "United States"}, ""),
				new County(new String[]{"Lake County", "Ohio", "United States"}, ""),
				new County(new String[]{"Lawrence County", "Ohio", "United States"}, ""),
				new County(new String[]{"Licking County", "Ohio", "United States"}, ""),
				new County(new String[]{"Logan County", "Ohio", "United States"}, ""),
				new County(new String[]{"Lorain County", "Ohio", "United States"}, ""),
				new County(new String[]{"Lucas County", "Ohio", "United States"}, ""),
				new County(new String[]{"Madison County", "Ohio", "United States"}, ""),
				new County(new String[]{"Mahoning County", "Ohio", "United States"}, ""),
				new County(new String[]{"Marion County", "Ohio", "United States"}, ""),
				new County(new String[]{"Medina County", "Ohio", "United States"}, ""),
				new County(new String[]{"Meigs County", "Ohio", "United States"}, ""),
				new County(new String[]{"Mercer County", "Ohio", "United States"}, ""),
				new County(new String[]{"Miami County", "Ohio", "United States"}, ""),
				new County(new String[]{"Monroe County", "Ohio", "United States"}, ""),
				new County(new String[]{"Montgomery County", "Ohio", "United States"}, ""),
				new County(new String[]{"Morgan County", "Ohio", "United States"}, ""),
				new County(new String[]{"Morrow County", "Ohio", "United States"}, ""),
				new County(new String[]{"Muskingum County", "Ohio", "United States"}, ""),
				new County(new String[]{"Noble County", "Ohio", "United States"}, ""),
				new County(new String[]{"Ottawa County", "Ohio", "United States"}, ""),
				new County(new String[]{"Paulding County", "Ohio", "United States"}, ""),
				new County(new String[]{"Perry County", "Ohio", "United States"}, ""),
				new County(new String[]{"Pickaway County", "Ohio", "United States"}, ""),
				new County(new String[]{"Pike County", "Ohio", "United States"}, ""),
				new County(new String[]{"Portage County", "Ohio", "United States"}, ""),
				new County(new String[]{"Preble County", "Ohio", "United States"}, ""),
				new County(new String[]{"Putnam County", "Ohio", "United States"}, ""),
				new County(new String[]{"Richland County", "Ohio", "United States"}, ""),
				new County(new String[]{"Ross County", "Ohio", "United States"}, ""),
				new County(new String[]{"Sandusky County", "Ohio", "United States"}, ""),
				new County(new String[]{"Scioto County", "Ohio", "United States"}, ""),
				new County(new String[]{"Seneca County", "Ohio", "United States"}, ""),
				new County(new String[]{"Shelby County", "Ohio", "United States"}, ""),
				new County(new String[]{"Stark County", "Ohio", "United States"}, ""),
				new County(new String[]{"Summit County", "Ohio", "United States"}, ""),
				new County(new String[]{"Trumbull County", "Ohio", "United States"}, ""),
				new County(new String[]{"Tuscarawas County", "Ohio", "United States"}, ""),
				new County(new String[]{"Union County", "Ohio", "United States"}, ""),
				new County(new String[]{"Van Wert County", "Ohio", "United States"}, ""),
				new County(new String[]{"Vinton County", "Ohio", "United States"}, ""),
				new County(new String[]{"Warren County", "Ohio", "United States"}, ""),
				new County(new String[]{"Washington County", "Ohio", "United States"}, ""),
				new County(new String[]{"Wayne County", "Ohio", "United States"}, ""),
				new County(new String[]{"Williams County", "Ohio", "United States"}, ""),
				new County(new String[]{"Wood County", "Ohio", "United States"}, ""),
				new County(new String[]{"Wyandot County", "Ohio", "United States"}, "")
			});
		
		ArrayList<PlaceStructure> oklahoma = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Adair County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Alfalfa County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Atoka County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Beaver County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Beckham County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Blaine County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Bryan County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Caddo County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Canadian County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Carter County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Cherokee County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Choctaw County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Cimarron County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Cleveland County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Coal County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Comanche County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Cotton County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Craig County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Creek County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Custer County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Delaware County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Dewey County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Ellis County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Garfield County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Garvin County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Grady County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Grant County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Greer County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Harmon County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Harper County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Haskell County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Hughes County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Jackson County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Jefferson County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Johnston County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Kay County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Kingfisher County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Kiowa County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Latimer County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Le Flore County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Lincoln County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Logan County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Love County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Major County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Marshall County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Mayes County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"McClain County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"McCurtain County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"McIntosh County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Murray County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Muskogee County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Noble County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Nowata County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Okfuskee County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Oklahoma County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Okmulgee County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Osage County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Ottawa County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Pawnee County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Payne County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Pittsburg County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Pontotoc County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Pottawatomie County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Pushmataha County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Roger Mills County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Rogers County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Seminole County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Sequoyah County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Stephens County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Texas County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Tillman County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Tulsa County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Wagoner County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Washington County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Washita County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Woods County", "Oklahoma", "United States"}, ""),
				new County(new String[]{"Woodward County", "Oklahoma", "United States"}, "")
			});
		
		ArrayList<PlaceStructure> oregon = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Baker County", "Oregon", "United States"}, ""),
				new County(new String[]{"Benton County", "Oregon", "United States"}, ""),
				new County(new String[]{"Clackamas County", "Oregon", "United States"}, ""),
				new County(new String[]{"Clatsop County", "Oregon", "United States"}, ""),
				new County(new String[]{"Columbia County", "Oregon", "United States"}, ""),
				new County(new String[]{"Coos County", "Oregon", "United States"}, ""),
				new County(new String[]{"Crook County", "Oregon", "United States"}, ""),
				new County(new String[]{"Curry County", "Oregon", "United States"}, ""),
				new County(new String[]{"Deschutes County", "Oregon", "United States"}, ""),
				new County(new String[]{"Douglas County", "Oregon", "United States"}, ""),
				new County(new String[]{"Gilliam County", "Oregon", "United States"}, ""),
				new County(new String[]{"Grant County", "Oregon", "United States"}, ""),
				new County(new String[]{"Harney County", "Oregon", "United States"}, ""),
				new County(new String[]{"Hood River County", "Oregon", "United States"}, ""),
				new County(new String[]{"Jackson County", "Oregon", "United States"}, ""),
				new County(new String[]{"Jefferson County", "Oregon", "United States"}, ""),
				new County(new String[]{"Josephine County", "Oregon", "United States"}, ""),
				new County(new String[]{"Klamath County", "Oregon", "United States"}, ""),
				new County(new String[]{"Lake County", "Oregon", "United States"}, ""),
				new County(new String[]{"Lane County", "Oregon", "United States"}, ""),
				new County(new String[]{"Lincoln County", "Oregon", "United States"}, ""),
				new County(new String[]{"Linn County", "Oregon", "United States"}, ""),
				new County(new String[]{"Malheur County", "Oregon", "United States"}, ""),
				new County(new String[]{"Marion County", "Oregon", "United States"}, ""),
				new County(new String[]{"Morrow County", "Oregon", "United States"}, ""),
				new County(new String[]{"Multnomah County", "Oregon", "United States"}, ""),
				new County(new String[]{"Polk County", "Oregon", "United States"}, ""),
				new County(new String[]{"Sherman County", "Oregon", "United States"}, ""),
				new County(new String[]{"Tillamook County", "Oregon", "United States"}, ""),
				new County(new String[]{"Umatilla County", "Oregon", "United States"}, ""),
				new County(new String[]{"Union County", "Oregon", "United States"}, ""),
				new County(new String[]{"Wallowa County", "Oregon", "United States"}, ""),
				new County(new String[]{"Wasco County", "Oregon", "United States"}, ""),
				new County(new String[]{"Washington County", "Oregon", "United States"}, ""),
				new County(new String[]{"Wheeler County", "Oregon", "United States"}, ""),
				new County(new String[]{"Yamhill County", "Oregon", "United States"}, "")
			});
		
		ArrayList<PlaceStructure> pennsylvania = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Adams County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Allegheny County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Armstrong County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Beaver County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Bedford County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Berks County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Blair County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Bradford County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Bucks County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Butler County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Cambria County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Cameron County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Carbon County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Centre County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Chester County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Clarion County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Clearfield County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Clinton County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Columbia County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Crawford County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Cumberland County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Dauphin County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Delaware County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Elk County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Erie County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Fayette County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Forest County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Franklin County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Fulton County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Greene County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Huntingdon County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Indiana County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Jefferson County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Juniata County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Lackawanna County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Lancaster County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Lawrence County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Lebanon County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Lehigh County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Luzerne County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Lycoming County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"McKean County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Mercer County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Mifflin County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Monroe County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Montgomery County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Montour County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Northampton County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Northumberland County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Perry County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Philadelphia County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Pike County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Potter County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Schuylkill County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Snyder County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Somerset County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Sullivan County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Susquehanna County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Tioga County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Union County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Venango County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Warren County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Washington County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Wayne County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Westmoreland County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"Wyoming County", "Pennsylvania", "United States"}, ""),
				new County(new String[]{"York County", "Pennsylvania", "United States"}, "")
			});
		
		ArrayList<PlaceStructure> rhodeIsland = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Bristol County", "Rhode Island", "United States"}, ""),
				new County(new String[]{"Kent County", "Rhode Island", "United States"}, ""),
				new County(new String[]{"Newport County", "Rhode Island", "United States"}, ""),
				new County(new String[]{"Providence County", "Rhode Island", "United States"}, ""),
				new County(new String[]{"Washington County", "Rhode Island", "United States"}, "")
			});
		
		ArrayList<PlaceStructure> southCarolina = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Abbeville County", "South Carolina", "United States"}, ""),
				new County(new String[]{"Aiken County", "South Carolina", "United States"}, ""),
				new County(new String[]{"Allendale County", "South Carolina", "United States"}, ""),
				new County(new String[]{"Anderson County", "South Carolina", "United States"}, ""),
				new County(new String[]{"Bamberg County", "South Carolina", "United States"}, ""),
				new County(new String[]{"Barnwell County", "South Carolina", "United States"}, ""),
				new County(new String[]{"Beaufort County", "South Carolina", "United States"}, ""),
				new County(new String[]{"Berkeley County", "South Carolina", "United States"}, ""),
				new County(new String[]{"Calhoun County", "South Carolina", "United States"}, ""),
				new County(new String[]{"Charleston County", "South Carolina", "United States"}, ""),
				new County(new String[]{"Cherokee County", "South Carolina", "United States"}, ""),
				new County(new String[]{"Chester County", "South Carolina", "United States"}, ""),
				new County(new String[]{"Chesterfield County", "South Carolina", "United States"}, ""),
				new County(new String[]{"Clarendon County", "South Carolina", "United States"}, ""),
				new County(new String[]{"Colleton County", "South Carolina", "United States"}, ""),
				new County(new String[]{"Darlington County", "South Carolina", "United States"}, ""),
				new County(new String[]{"Dillon County", "South Carolina", "United States"}, ""),
				new County(new String[]{"Dorchester County", "South Carolina", "United States"}, ""),
				new County(new String[]{"Edgefield County", "South Carolina", "United States"}, ""),
				new County(new String[]{"Fairfield County", "South Carolina", "United States"}, ""),
				new County(new String[]{"Florence County", "South Carolina", "United States"}, ""),
				new County(new String[]{"Georgetown County", "South Carolina", "United States"}, ""),
				new County(new String[]{"Greenville County", "South Carolina", "United States"}, ""),
				new County(new String[]{"Greenwood County", "South Carolina", "United States"}, ""),
				new County(new String[]{"Hampton County", "South Carolina", "United States"}, ""),
				new County(new String[]{"Horry County", "South Carolina", "United States"}, ""),
				new County(new String[]{"Jasper County", "South Carolina", "United States"}, ""),
				new County(new String[]{"Kershaw County", "South Carolina", "United States"}, ""),
				new County(new String[]{"Lancaster County", "South Carolina", "United States"}, ""),
				new County(new String[]{"Laurens County", "South Carolina", "United States"}, ""),
				new County(new String[]{"Lee County", "South Carolina", "United States"}, ""),
				new County(new String[]{"Lexington County", "South Carolina", "United States"}, ""),
				new County(new String[]{"Marion County", "South Carolina", "United States"}, ""),
				new County(new String[]{"Marlboro County", "South Carolina", "United States"}, ""),
				new County(new String[]{"McCormick County", "South Carolina", "United States"}, ""),
				new County(new String[]{"Newberry County", "South Carolina", "United States"}, ""),
				new County(new String[]{"Oconee County", "South Carolina", "United States"}, ""),
				new County(new String[]{"Orangeburg County", "South Carolina", "United States"}, ""),
				new County(new String[]{"Pickens County", "South Carolina", "United States"}, ""),
				new County(new String[]{"Richland County", "South Carolina", "United States"}, ""),
				new County(new String[]{"Saluda County", "South Carolina", "United States"}, ""),
				new County(new String[]{"Spartanburg County", "South Carolina", "United States"}, ""),
				new County(new String[]{"Sumter County", "South Carolina", "United States"}, ""),
				new County(new String[]{"Union County", "South Carolina", "United States"}, ""),
				new County(new String[]{"Williamsburg County", "South Carolina", "United States"}, ""),
				new County(new String[]{"York County", "South Carolina", "United States"}, "")
			});
		
		ArrayList<PlaceStructure> southDakota = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Aurora County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Beadle County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Bennett County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Bon Homme County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Brookings County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Brown County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Brule County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Buffalo County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Butte County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Campbell County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Charles Mix County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Clark County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Clay County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Codington County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Corson County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Custer County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Davison County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Day County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Deuel County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Dewey County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Douglas County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Edmunds County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Fall River County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Faulk County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Grant County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Gregory County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Haakon County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Hamlin County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Hand County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Hanson County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Harding County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Hughes County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Hutchinson County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Hyde County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Jackson County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Jerauld County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Jones County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Kingsbury County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Lake County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Lawrence County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Lincoln County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Lyman County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Marshall County", "South Dakota", "United States"}, ""),
				new County(new String[]{"McCook County", "South Dakota", "United States"}, ""),
				new County(new String[]{"McPherson County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Meade County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Mellette County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Miner County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Minnehaha County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Moody County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Pennington County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Perkins County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Potter County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Roberts County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Sanborn County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Shannon County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Spink County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Stanley County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Sully County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Todd County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Tripp County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Turner County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Union County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Walworth County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Yankton County", "South Dakota", "United States"}, ""),
				new County(new String[]{"Ziebach County", "South Dakota", "United States"}, "")
			});
		
		ArrayList<PlaceStructure> tennessee = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Anderson County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Bedford County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Benton County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Bledsoe County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Blount County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Bradley County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Campbell County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Cannon County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Carroll County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Carter County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Cheatham County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Chester County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Claiborne County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Clay County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Cocke County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Coffee County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Crockett County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Cumberland County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Davidson County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Decatur County", "Tennessee", "United States"}, ""),
				new County(new String[]{"DeKalb County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Dickson County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Dyer County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Fayette County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Fentress County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Franklin County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Gibson County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Giles County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Grainger County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Greene County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Grundy County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Hamblen County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Hamilton County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Hancock County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Hardeman County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Hardin County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Hawkins County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Haywood County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Henderson County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Henry County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Hickman County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Houston County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Humphreys County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Jackson County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Jefferson County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Johnson County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Knox County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Lake County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Lauderdale County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Lawrence County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Lewis County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Lincoln County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Loudon County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Macon County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Madison County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Marion County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Marshall County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Maury County", "Tennessee", "United States"}, ""),
				new County(new String[]{"McMinn County", "Tennessee", "United States"}, ""),
				new County(new String[]{"McNairy County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Meigs County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Monroe County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Montgomery County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Moore County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Morgan County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Obion County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Overton County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Perry County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Pickett County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Polk County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Putnam County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Rhea County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Roane County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Robertson County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Rutherford County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Scott County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Sequatchie County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Sevier County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Shelby County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Smith County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Stewart County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Sullivan County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Sumner County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Tipton County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Trousdale County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Unicoi County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Union County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Van Buren County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Warren County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Washington County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Wayne County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Weakley County", "Tennessee", "United States"}, ""),
				new County(new String[]{"White County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Williamson County", "Tennessee", "United States"}, ""),
				new County(new String[]{"Wilson County", "Tennessee", "United States"}, "")
			});
		
		ArrayList<PlaceStructure> texas = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Anderson County", "Texas", "United States"}, ""),
				new County(new String[]{"Andrews County", "Texas", "United States"}, ""),
				new County(new String[]{"Angelina County", "Texas", "United States"}, ""),
				new County(new String[]{"Aransas County", "Texas", "United States"}, ""),
				new County(new String[]{"Archer County", "Texas", "United States"}, ""),
				new County(new String[]{"Armstrong County", "Texas", "United States"}, ""),
				new County(new String[]{"Atascosa County", "Texas", "United States"}, ""),
				new County(new String[]{"Austin County", "Texas", "United States"}, ""),
				new County(new String[]{"Bailey County", "Texas", "United States"}, ""),
				new County(new String[]{"Bandera County", "Texas", "United States"}, ""),
				new County(new String[]{"Bastrop County", "Texas", "United States"}, ""),
				new County(new String[]{"Baylor County", "Texas", "United States"}, ""),
				new County(new String[]{"Bee County", "Texas", "United States"}, ""),
				new County(new String[]{"Bell County", "Texas", "United States"}, ""),
				new County(new String[]{"Bexar County", "Texas", "United States"}, ""),
				new County(new String[]{"Blanco County", "Texas", "United States"}, ""),
				new County(new String[]{"Borden County", "Texas", "United States"}, ""),
				new County(new String[]{"Bosque County", "Texas", "United States"}, ""),
				new County(new String[]{"Bowie County", "Texas", "United States"}, ""),
				new County(new String[]{"Brazoria County", "Texas", "United States"}, ""),
				new County(new String[]{"Brazos County", "Texas", "United States"}, ""),
				new County(new String[]{"Brewster County", "Texas", "United States"}, ""),
				new County(new String[]{"Briscoe County", "Texas", "United States"}, ""),
				new County(new String[]{"Brooks County", "Texas", "United States"}, ""),
				new County(new String[]{"Brown County", "Texas", "United States"}, ""),
				new County(new String[]{"Burleson County", "Texas", "United States"}, ""),
				new County(new String[]{"Burnet County", "Texas", "United States"}, ""),
				new County(new String[]{"Caldwell County", "Texas", "United States"}, ""),
				new County(new String[]{"Calhoun County", "Texas", "United States"}, ""),
				new County(new String[]{"Callahan County", "Texas", "United States"}, ""),
				new County(new String[]{"Cameron County", "Texas", "United States"}, ""),
				new County(new String[]{"Camp County", "Texas", "United States"}, ""),
				new County(new String[]{"Carson County", "Texas", "United States"}, ""),
				new County(new String[]{"Cass County", "Texas", "United States"}, ""),
				new County(new String[]{"Castro County", "Texas", "United States"}, ""),
				new County(new String[]{"Chambers County", "Texas", "United States"}, ""),
				new County(new String[]{"Cherokee County", "Texas", "United States"}, ""),
				new County(new String[]{"Childress County", "Texas", "United States"}, ""),
				new County(new String[]{"Clay County", "Texas", "United States"}, ""),
				new County(new String[]{"Cochran County", "Texas", "United States"}, ""),
				new County(new String[]{"Coke County", "Texas", "United States"}, ""),
				new County(new String[]{"Coleman County", "Texas", "United States"}, ""),
				new County(new String[]{"Collin County", "Texas", "United States"}, ""),
				new County(new String[]{"Collingsworth County", "Texas", "United States"}, ""),
				new County(new String[]{"Colorado County", "Texas", "United States"}, ""),
				new County(new String[]{"Comal County", "Texas", "United States"}, ""),
				new County(new String[]{"Comanche County", "Texas", "United States"}, ""),
				new County(new String[]{"Concho County", "Texas", "United States"}, ""),
				new County(new String[]{"Cooke County", "Texas", "United States"}, ""),
				new County(new String[]{"Coryell County", "Texas", "United States"}, ""),
				new County(new String[]{"Cottle County", "Texas", "United States"}, ""),
				new County(new String[]{"Crane County", "Texas", "United States"}, ""),
				new County(new String[]{"Crockett County", "Texas", "United States"}, ""),
				new County(new String[]{"Crosby County", "Texas", "United States"}, ""),
				new County(new String[]{"Culberson County", "Texas", "United States"}, ""),
				new County(new String[]{"Dallam County", "Texas", "United States"}, ""),
				new County(new String[]{"Dallas County", "Texas", "United States"}, ""),
				new County(new String[]{"Dawson County", "Texas", "United States"}, ""),
				new County(new String[]{"Deaf Smith County", "Texas", "United States"}, ""),
				new County(new String[]{"Delta County", "Texas", "United States"}, ""),
				new County(new String[]{"Denton County", "Texas", "United States"}, ""),
				new County(new String[]{"DeWitt County", "Texas", "United States"}, ""),
				new County(new String[]{"Dickens County", "Texas", "United States"}, ""),
				new County(new String[]{"Dimmit County", "Texas", "United States"}, ""),
				new County(new String[]{"Donley County", "Texas", "United States"}, ""),
				new County(new String[]{"Duval County", "Texas", "United States"}, ""),
				new County(new String[]{"Eastland County", "Texas", "United States"}, ""),
				new County(new String[]{"Ector County", "Texas", "United States"}, ""),
				new County(new String[]{"Edwards County", "Texas", "United States"}, ""),
				new County(new String[]{"Ellis County", "Texas", "United States"}, ""),
				new County(new String[]{"El Paso County", "Texas", "United States"}, ""),
				new County(new String[]{"Erath County", "Texas", "United States"}, ""),
				new County(new String[]{"Falls County", "Texas", "United States"}, ""),
				new County(new String[]{"Fannin County", "Texas", "United States"}, ""),
				new County(new String[]{"Fayette County", "Texas", "United States"}, ""),
				new County(new String[]{"Fisher County", "Texas", "United States"}, ""),
				new County(new String[]{"Floyd County", "Texas", "United States"}, ""),
				new County(new String[]{"Foard County", "Texas", "United States"}, ""),
				new County(new String[]{"Fort Bend County", "Texas", "United States"}, ""),
				new County(new String[]{"Franklin County", "Texas", "United States"}, ""),
				new County(new String[]{"Freestone County", "Texas", "United States"}, ""),
				new County(new String[]{"Frio County", "Texas", "United States"}, ""),
				new County(new String[]{"Gaines County", "Texas", "United States"}, ""),
				new County(new String[]{"Galveston County", "Texas", "United States"}, ""),
				new County(new String[]{"Garza County", "Texas", "United States"}, ""),
				new County(new String[]{"Gillespie County", "Texas", "United States"}, ""),
				new County(new String[]{"Glasscock County", "Texas", "United States"}, ""),
				new County(new String[]{"Goliad County", "Texas", "United States"}, ""),
				new County(new String[]{"Gonzales County", "Texas", "United States"}, ""),
				new County(new String[]{"Gray County", "Texas", "United States"}, ""),
				new County(new String[]{"Grayson County", "Texas", "United States"}, ""),
				new County(new String[]{"Gregg County", "Texas", "United States"}, ""),
				new County(new String[]{"Grimes County", "Texas", "United States"}, ""),
				new County(new String[]{"Guadalupe County", "Texas", "United States"}, ""),
				new County(new String[]{"Hale County", "Texas", "United States"}, ""),
				new County(new String[]{"Hall County", "Texas", "United States"}, ""),
				new County(new String[]{"Hamilton County", "Texas", "United States"}, ""),
				new County(new String[]{"Hansford County", "Texas", "United States"}, ""),
				new County(new String[]{"Hardeman County", "Texas", "United States"}, ""),
				new County(new String[]{"Hardin County", "Texas", "United States"}, ""),
				new County(new String[]{"Harris County", "Texas", "United States"}, ""),
				new County(new String[]{"Harrison County", "Texas", "United States"}, ""),
				new County(new String[]{"Hartley County", "Texas", "United States"}, ""),
				new County(new String[]{"Haskell County", "Texas", "United States"}, ""),
				new County(new String[]{"Hays County", "Texas", "United States"}, ""),
				new County(new String[]{"Hemphill County", "Texas", "United States"}, ""),
				new County(new String[]{"Henderson County", "Texas", "United States"}, ""),
				new County(new String[]{"Hidalgo County", "Texas", "United States"}, ""),
				new County(new String[]{"Hill County", "Texas", "United States"}, ""),
				new County(new String[]{"Hockley County", "Texas", "United States"}, ""),
				new County(new String[]{"Hood County", "Texas", "United States"}, ""),
				new County(new String[]{"Hopkins County", "Texas", "United States"}, ""),
				new County(new String[]{"Houston County", "Texas", "United States"}, ""),
				new County(new String[]{"Howard County", "Texas", "United States"}, ""),
				new County(new String[]{"Hudspeth County", "Texas", "United States"}, ""),
				new County(new String[]{"Hunt County", "Texas", "United States"}, ""),
				new County(new String[]{"Hutchinson County", "Texas", "United States"}, ""),
				new County(new String[]{"Irion County", "Texas", "United States"}, ""),
				new County(new String[]{"Jack County", "Texas", "United States"}, ""),
				new County(new String[]{"Jackson County", "Texas", "United States"}, ""),
				new County(new String[]{"Jasper County", "Texas", "United States"}, ""),
				new County(new String[]{"Jeff Davis County", "Texas", "United States"}, ""),
				new County(new String[]{"Jefferson County", "Texas", "United States"}, ""),
				new County(new String[]{"Jim Hogg County", "Texas", "United States"}, ""),
				new County(new String[]{"Jim Wells County", "Texas", "United States"}, ""),
				new County(new String[]{"Johnson County", "Texas", "United States"}, ""),
				new County(new String[]{"Jones County", "Texas", "United States"}, ""),
				new County(new String[]{"Karnes County", "Texas", "United States"}, ""),
				new County(new String[]{"Kaufman County", "Texas", "United States"}, ""),
				new County(new String[]{"Kendall County", "Texas", "United States"}, ""),
				new County(new String[]{"Kenedy County", "Texas", "United States"}, ""),
				new County(new String[]{"Kent County", "Texas", "United States"}, ""),
				new County(new String[]{"Kerr County", "Texas", "United States"}, ""),
				new County(new String[]{"Kimble County", "Texas", "United States"}, ""),
				new County(new String[]{"King County", "Texas", "United States"}, ""),
				new County(new String[]{"Kinney County", "Texas", "United States"}, ""),
				new County(new String[]{"Kleberg County", "Texas", "United States"}, ""),
				new County(new String[]{"Knox County", "Texas", "United States"}, ""),
				new County(new String[]{"Lamar County", "Texas", "United States"}, ""),
				new County(new String[]{"Lamb County", "Texas", "United States"}, ""),
				new County(new String[]{"Lampasas County", "Texas", "United States"}, ""),
				new County(new String[]{"La Salle County", "Texas", "United States"}, ""),
				new County(new String[]{"Lavaca County", "Texas", "United States"}, ""),
				new County(new String[]{"Lee County", "Texas", "United States"}, ""),
				new County(new String[]{"Leon County", "Texas", "United States"}, ""),
				new County(new String[]{"Liberty County", "Texas", "United States"}, ""),
				new County(new String[]{"Limestone County", "Texas", "United States"}, ""),
				new County(new String[]{"Lipscomb County", "Texas", "United States"}, ""),
				new County(new String[]{"Live Oak County", "Texas", "United States"}, ""),
				new County(new String[]{"Llano County", "Texas", "United States"}, ""),
				new County(new String[]{"Loving County", "Texas", "United States"}, ""),
				new County(new String[]{"Lubbock County", "Texas", "United States"}, ""),
				new County(new String[]{"Lynn County", "Texas", "United States"}, ""),
				new County(new String[]{"McCulloch County", "Texas", "United States"}, ""),
				new County(new String[]{"McLennan County", "Texas", "United States"}, ""),
				new County(new String[]{"McMullen County", "Texas", "United States"}, ""),
				new County(new String[]{"Madison County", "Texas", "United States"}, ""),
				new County(new String[]{"Marion County", "Texas", "United States"}, ""),
				new County(new String[]{"Martin County", "Texas", "United States"}, ""),
				new County(new String[]{"Mason County", "Texas", "United States"}, ""),
				new County(new String[]{"Matagorda County", "Texas", "United States"}, ""),
				new County(new String[]{"Maverick County", "Texas", "United States"}, ""),
				new County(new String[]{"Medina County", "Texas", "United States"}, ""),
				new County(new String[]{"Menard County", "Texas", "United States"}, ""),
				new County(new String[]{"Midland County", "Texas", "United States"}, ""),
				new County(new String[]{"Milam County", "Texas", "United States"}, ""),
				new County(new String[]{"Mills County", "Texas", "United States"}, ""),
				new County(new String[]{"Mitchell County", "Texas", "United States"}, ""),
				new County(new String[]{"Montague County", "Texas", "United States"}, ""),
				new County(new String[]{"Montgomery County", "Texas", "United States"}, ""),
				new County(new String[]{"Moore County", "Texas", "United States"}, ""),
				new County(new String[]{"Morris County", "Texas", "United States"}, ""),
				new County(new String[]{"Motley County", "Texas", "United States"}, ""),
				new County(new String[]{"Nacogdoches County", "Texas", "United States"}, ""),
				new County(new String[]{"Navarro County", "Texas", "United States"}, ""),
				new County(new String[]{"Newton County", "Texas", "United States"}, ""),
				new County(new String[]{"Nolan County", "Texas", "United States"}, ""),
				new County(new String[]{"Nueces County", "Texas", "United States"}, ""),
				new County(new String[]{"Ochiltree County", "Texas", "United States"}, ""),
				new County(new String[]{"Oldham County", "Texas", "United States"}, ""),
				new County(new String[]{"Orange County", "Texas", "United States"}, ""),
				new County(new String[]{"Palo Pinto County", "Texas", "United States"}, ""),
				new County(new String[]{"Panola County", "Texas", "United States"}, ""),
				new County(new String[]{"Parker County", "Texas", "United States"}, ""),
				new County(new String[]{"Parmer County", "Texas", "United States"}, ""),
				new County(new String[]{"Pecos County", "Texas", "United States"}, ""),
				new County(new String[]{"Polk County", "Texas", "United States"}, ""),
				new County(new String[]{"Potter County", "Texas", "United States"}, ""),
				new County(new String[]{"Presidio County", "Texas", "United States"}, ""),
				new County(new String[]{"Rains County", "Texas", "United States"}, ""),
				new County(new String[]{"Randall County", "Texas", "United States"}, ""),
				new County(new String[]{"Reagan County", "Texas", "United States"}, ""),
				new County(new String[]{"Real County", "Texas", "United States"}, ""),
				new County(new String[]{"Red River County", "Texas", "United States"}, ""),
				new County(new String[]{"Reeves County", "Texas", "United States"}, ""),
				new County(new String[]{"Refugio County", "Texas", "United States"}, ""),
				new County(new String[]{"Roberts County", "Texas", "United States"}, ""),
				new County(new String[]{"Robertson County", "Texas", "United States"}, ""),
				new County(new String[]{"Rockwall County", "Texas", "United States"}, ""),
				new County(new String[]{"Runnels County", "Texas", "United States"}, ""),
				new County(new String[]{"Rusk County", "Texas", "United States"}, ""),
				new County(new String[]{"Sabine County", "Texas", "United States"}, ""),
				new County(new String[]{"San Augustine County", "Texas", "United States"}, ""),
				new County(new String[]{"San Jacinto County", "Texas", "United States"}, ""),
				new County(new String[]{"San Patricio County", "Texas", "United States"}, ""),
				new County(new String[]{"San Saba County", "Texas", "United States"}, ""),
				new County(new String[]{"Schleicher County", "Texas", "United States"}, ""),
				new County(new String[]{"Scurry County", "Texas", "United States"}, ""),
				new County(new String[]{"Shackelford County", "Texas", "United States"}, ""),
				new County(new String[]{"Shelby County", "Texas", "United States"}, ""),
				new County(new String[]{"Sherman County", "Texas", "United States"}, ""),
				new County(new String[]{"Smith County", "Texas", "United States"}, ""),
				new County(new String[]{"Somervell County", "Texas", "United States"}, ""),
				new County(new String[]{"Starr County", "Texas", "United States"}, ""),
				new County(new String[]{"Stephens County", "Texas", "United States"}, ""),
				new County(new String[]{"Sterling County", "Texas", "United States"}, ""),
				new County(new String[]{"Stonewall County", "Texas", "United States"}, ""),
				new County(new String[]{"Sutton County", "Texas", "United States"}, ""),
				new County(new String[]{"Swisher County", "Texas", "United States"}, ""),
				new County(new String[]{"Tarrant County", "Texas", "United States"}, ""),
				new County(new String[]{"Taylor County", "Texas", "United States"}, ""),
				new County(new String[]{"Terrell County", "Texas", "United States"}, ""),
				new County(new String[]{"Terry County", "Texas", "United States"}, ""),
				new County(new String[]{"Throckmorton County", "Texas", "United States"}, ""),
				new County(new String[]{"Titus County", "Texas", "United States"}, ""),
				new County(new String[]{"Tom Green County", "Texas", "United States"}, ""),
				new County(new String[]{"Travis County", "Texas", "United States"}, ""),
				new County(new String[]{"Trinity County", "Texas", "United States"}, ""),
				new County(new String[]{"Tyler County", "Texas", "United States"}, ""),
				new County(new String[]{"Upshur County", "Texas", "United States"}, ""),
				new County(new String[]{"Upton County", "Texas", "United States"}, ""),
				new County(new String[]{"Uvalde County", "Texas", "United States"}, ""),
				new County(new String[]{"Val Verde County", "Texas", "United States"}, ""),
				new County(new String[]{"Van Zandt County", "Texas", "United States"}, ""),
				new County(new String[]{"Victoria County", "Texas", "United States"}, ""),
				new County(new String[]{"Walker County", "Texas", "United States"}, ""),
				new County(new String[]{"Waller County", "Texas", "United States"}, ""),
				new County(new String[]{"Ward County", "Texas", "United States"}, ""),
				new County(new String[]{"Washington County", "Texas", "United States"}, ""),
				new County(new String[]{"Webb County", "Texas", "United States"}, ""),
				new County(new String[]{"Wharton County", "Texas", "United States"}, ""),
				new County(new String[]{"Wheeler County", "Texas", "United States"}, ""),
				new County(new String[]{"Wichita County", "Texas", "United States"}, ""),
				new County(new String[]{"Wilbarger County", "Texas", "United States"}, ""),
				new County(new String[]{"Willacy County", "Texas", "United States"}, ""),
				new County(new String[]{"Williamson County", "Texas", "United States"}, ""),
				new County(new String[]{"Wilson County", "Texas", "United States"}, ""),
				new County(new String[]{"Winkler County", "Texas", "United States"}, ""),
				new County(new String[]{"Wise County", "Texas", "United States"}, ""),
				new County(new String[]{"Wood County", "Texas", "United States"}, ""),
				new County(new String[]{"Yoakum County", "Texas", "United States"}, ""),
				new County(new String[]{"Young County", "Texas", "United States"}, ""),
				new County(new String[]{"Zapata County", "Texas", "United States"}, ""),
				new County(new String[]{"Zavala County", "Texas", "United States"}, "")
			});
		
		ArrayList<PlaceStructure> utah = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Beaver County", "Utah", "United States"}, ""),
				new County(new String[]{"Box Elder County", "Utah", "United States"}, ""),
				new County(new String[]{"Cache County", "Utah", "United States"}, ""),
				new County(new String[]{"Carbon County", "Utah", "United States"}, ""),
				new County(new String[]{"Daggett County", "Utah", "United States"}, ""),
				new County(new String[]{"Davis County", "Utah", "United States"}, ""),
				new County(new String[]{"Duchesne County", "Utah", "United States"}, ""),
				new County(new String[]{"Emery County", "Utah", "United States"}, ""),
				new County(new String[]{"Garfield County", "Utah", "United States"}, ""),
				new County(new String[]{"Grand County", "Utah", "United States"}, ""),
				new County(new String[]{"Iron County", "Utah", "United States"}, ""),
				new County(new String[]{"Juab County", "Utah", "United States"}, ""),
				new County(new String[]{"Kane County", "Utah", "United States"}, ""),
				new County(new String[]{"Millard County", "Utah", "United States"}, ""),
				new County(new String[]{"Morgan County", "Utah", "United States"}, ""),
				new County(new String[]{"Piute County", "Utah", "United States"}, ""),
				new County(new String[]{"Rich County", "Utah", "United States"}, ""),
				new County(new String[]{"Salt Lake County", "Utah", "United States"}, ""),
				new County(new String[]{"San Juan County", "Utah", "United States"}, ""),
				new County(new String[]{"Sanpete County", "Utah", "United States"}, ""),
				new County(new String[]{"Sevier County", "Utah", "United States"}, ""),
				new County(new String[]{"Summit County", "Utah", "United States"}, ""),
				new County(new String[]{"Tooele County", "Utah", "United States"}, ""),
				new County(new String[]{"Uintah County", "Utah", "United States"}, ""),
				new County(new String[]{"Utah County", "Utah", "United States"}, ""),
				new County(new String[]{"Wasatch County", "Utah", "United States"}, ""),
				new County(new String[]{"Washington County", "Utah", "United States"}, ""),
				new County(new String[]{"Wayne County", "Utah", "United States"}, ""),
				new County(new String[]{"Weber County", "Utah", "United States"}, "")
			});
		
		ArrayList<PlaceStructure> vermont = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Addison County", "Vermont", "United States"}, ""),
				new County(new String[]{"Bennington County", "Vermont", "United States"}, ""),
				new County(new String[]{"Caledonia County", "Vermont", "United States"}, ""),
				new County(new String[]{"Chittenden County", "Vermont", "United States"}, ""),
				new County(new String[]{"Essex County", "Vermont", "United States"}, ""),
				new County(new String[]{"Franklin County", "Vermont", "United States"}, ""),
				new County(new String[]{"Grand Isle County", "Vermont", "United States"}, ""),
				new County(new String[]{"Lamoille County", "Vermont", "United States"}, ""),
				new County(new String[]{"Orange County", "Vermont", "United States"}, ""),
				new County(new String[]{"Orleans County", "Vermont", "United States"}, ""),
				new County(new String[]{"Rutland County", "Vermont", "United States"}, ""),
				new County(new String[]{"Washington County", "Vermont", "United States"}, ""),
				new County(new String[]{"Windham County", "Vermont", "United States"}, ""),
				new County(new String[]{"Windsor County", "Vermont", "United States"}, "")
			});
		
		ArrayList<PlaceStructure> virginia = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Accomack County", "Virginia", "United States"}, ""),
				new County(new String[]{"Albemarle County", "Virginia", "United States"}, ""),
				new County(new String[]{"Alleghany County", "Virginia", "United States"}, ""),
				new County(new String[]{"Amelia County", "Virginia", "United States"}, ""),
				new County(new String[]{"Amherst County", "Virginia", "United States"}, ""),
				new County(new String[]{"Appomattox County", "Virginia", "United States"}, ""),
				new County(new String[]{"Arlington County", "Virginia", "United States"}, ""),
				new County(new String[]{"Augusta County", "Virginia", "United States"}, ""),
				new County(new String[]{"Bath County", "Virginia", "United States"}, ""),
				new County(new String[]{"Bedford County", "Virginia", "United States"}, ""),
				new County(new String[]{"Bland County", "Virginia", "United States"}, ""),
				new County(new String[]{"Botetourt County", "Virginia", "United States"}, ""),
				new County(new String[]{"Brunswick County", "Virginia", "United States"}, ""),
				new County(new String[]{"Buchanan County", "Virginia", "United States"}, ""),
				new County(new String[]{"Buckingham County", "Virginia", "United States"}, ""),
				new County(new String[]{"Campbell County", "Virginia", "United States"}, ""),
				new County(new String[]{"Caroline County", "Virginia", "United States"}, ""),
				new County(new String[]{"Carroll County", "Virginia", "United States"}, ""),
				new County(new String[]{"Charles City County", "Virginia", "United States"}, ""),
				new County(new String[]{"Charlotte County", "Virginia", "United States"}, ""),
				new County(new String[]{"Chesterfield County", "Virginia", "United States"}, ""),
				new County(new String[]{"Clarke County", "Virginia", "United States"}, ""),
				new County(new String[]{"Craig County", "Virginia", "United States"}, ""),
				new County(new String[]{"Culpeper County", "Virginia", "United States"}, ""),
				new County(new String[]{"Cumberland County", "Virginia", "United States"}, ""),
				new County(new String[]{"Dickenson County", "Virginia", "United States"}, ""),
				new County(new String[]{"Dinwiddie County", "Virginia", "United States"}, ""),
				new County(new String[]{"Essex County", "Virginia", "United States"}, ""),
				new County(new String[]{"Fairfax County", "Virginia", "United States"}, ""),
				new County(new String[]{"Fauquier County", "Virginia", "United States"}, ""),
				new County(new String[]{"Floyd County", "Virginia", "United States"}, ""),
				new County(new String[]{"Fluvanna County", "Virginia", "United States"}, ""),
				new County(new String[]{"Franklin County", "Virginia", "United States"}, ""),
				new County(new String[]{"Frederick County", "Virginia", "United States"}, ""),
				new County(new String[]{"Giles County", "Virginia", "United States"}, ""),
				new County(new String[]{"Gloucester County", "Virginia", "United States"}, ""),
				new County(new String[]{"Goochland County", "Virginia", "United States"}, ""),
				new County(new String[]{"Grayson County", "Virginia", "United States"}, ""),
				new County(new String[]{"Greene County", "Virginia", "United States"}, ""),
				new County(new String[]{"Greensville County", "Virginia", "United States"}, ""),
				new County(new String[]{"Halifax County", "Virginia", "United States"}, ""),
				new County(new String[]{"Hanover County", "Virginia", "United States"}, ""),
				new County(new String[]{"Henrico County", "Virginia", "United States"}, ""),
				new County(new String[]{"Henry County", "Virginia", "United States"}, ""),
				new County(new String[]{"Highland County", "Virginia", "United States"}, ""),
				new County(new String[]{"Isle of Wight County", "Virginia", "United States"}, ""),
				new County(new String[]{"James City County", "Virginia", "United States"}, ""),
				new County(new String[]{"King and Queen County", "Virginia", "United States"}, ""),
				new County(new String[]{"King George County", "Virginia", "United States"}, ""),
				new County(new String[]{"King William County", "Virginia", "United States"}, ""),
				new County(new String[]{"Lancaster County", "Virginia", "United States"}, ""),
				new County(new String[]{"Lee County", "Virginia", "United States"}, ""),
				new County(new String[]{"Loudoun County", "Virginia", "United States"}, ""),
				new County(new String[]{"Louisa County", "Virginia", "United States"}, ""),
				new County(new String[]{"Lunenburg County", "Virginia", "United States"}, ""),
				new County(new String[]{"Madison County", "Virginia", "United States"}, ""),
				new County(new String[]{"Mathews County", "Virginia", "United States"}, ""),
				new County(new String[]{"Mecklenburg County", "Virginia", "United States"}, ""),
				new County(new String[]{"Middlesex County", "Virginia", "United States"}, ""),
				new County(new String[]{"Montgomery County", "Virginia", "United States"}, ""),
				new County(new String[]{"Nelson County", "Virginia", "United States"}, ""),
				new County(new String[]{"New Kent County", "Virginia", "United States"}, ""),
				new County(new String[]{"Northampton County", "Virginia", "United States"}, ""),
				new County(new String[]{"Northumberland County", "Virginia", "United States"}, ""),
				new County(new String[]{"Nottoway County", "Virginia", "United States"}, ""),
				new County(new String[]{"Orange County", "Virginia", "United States"}, ""),
				new County(new String[]{"Page County", "Virginia", "United States"}, ""),
				new County(new String[]{"Patrick County", "Virginia", "United States"}, ""),
				new County(new String[]{"Pittsylvania County", "Virginia", "United States"}, ""),
				new County(new String[]{"Powhatan County", "Virginia", "United States"}, ""),
				new County(new String[]{"Prince Edward County", "Virginia", "United States"}, ""),
				new County(new String[]{"Prince George County", "Virginia", "United States"}, ""),
				new County(new String[]{"Prince William County", "Virginia", "United States"}, ""),
				new County(new String[]{"Pulaski County", "Virginia", "United States"}, ""),
				new County(new String[]{"Rappahannock County", "Virginia", "United States"}, ""),
				new County(new String[]{"Richmond County", "Virginia", "United States"}, ""),
				new County(new String[]{"Roanoke County", "Virginia", "United States"}, ""),
				new County(new String[]{"Rockbridge County", "Virginia", "United States"}, ""),
				new County(new String[]{"Rockingham County", "Virginia", "United States"}, ""),
				new County(new String[]{"Russell County", "Virginia", "United States"}, ""),
				new County(new String[]{"Scott County", "Virginia", "United States"}, ""),
				new County(new String[]{"Shenandoah County", "Virginia", "United States"}, ""),
				new County(new String[]{"Smyth County", "Virginia", "United States"}, ""),
				new County(new String[]{"Southampton County", "Virginia", "United States"}, ""),
				new County(new String[]{"Spotsylvania County", "Virginia", "United States"}, ""),
				new County(new String[]{"Chesapeake", "Virginia", "United States"}, ""),
				new County(new String[]{"Hampton", "Virginia", "United States"}, ""),
				new County(new String[]{"Newport", "Virginia", "United States"}, ""),
				new County(new String[]{"Norfolk", "Virginia", "United States"}, ""),
				new County(new String[]{"Portsmouth", "Virginia", "United States"}, ""),
				new County(new String[]{"Suffolk", "Virginia", "United States"}, ""),
				new County(new String[]{"Virginia Beach", "Virginia", "United States"}, ""),
			});
		
		ArrayList<PlaceStructure> washington = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Adams County", "Washington", "United States"}, ""),
				new County(new String[]{"Asotin County", "Washington", "United States"}, ""),
				new County(new String[]{"Benton County", "Washington", "United States"}, ""),
				new County(new String[]{"Chelan County", "Washington", "United States"}, ""),
				new County(new String[]{"Clallam County", "Washington", "United States"}, ""),
				new County(new String[]{"Clark County", "Washington", "United States"}, ""),
				new County(new String[]{"Columbia County", "Washington", "United States"}, ""),
				new County(new String[]{"Cowlitz County", "Washington", "United States"}, ""),
				new County(new String[]{"Douglas County", "Washington", "United States"}, ""),
				new County(new String[]{"Ferry County", "Washington", "United States"}, ""),
				new County(new String[]{"Franklin County", "Washington", "United States"}, ""),
				new County(new String[]{"Garfield County", "Washington", "United States"}, ""),
				new County(new String[]{"Grant County", "Washington", "United States"}, ""),
				new County(new String[]{"Grays Harbor County", "Washington", "United States"}, ""),
				new County(new String[]{"Island County", "Washington", "United States"}, ""),
				new County(new String[]{"Jefferson County", "Washington", "United States"}, ""),
				new County(new String[]{"King County", "Washington", "United States"}, ""),
				new County(new String[]{"Kitsap County", "Washington", "United States"}, ""),
				new County(new String[]{"Kittitas County", "Washington", "United States"}, ""),
				new County(new String[]{"Klickitat County", "Washington", "United States"}, ""),
				new County(new String[]{"Lewis County", "Washington", "United States"}, ""),
				new County(new String[]{"Lincoln County", "Washington", "United States"}, ""),
				new County(new String[]{"Mason County", "Washington", "United States"}, ""),
				new County(new String[]{"Okanogan County", "Washington", "United States"}, ""),
				new County(new String[]{"Pacific County", "Washington", "United States"}, ""),
				new County(new String[]{"Pend Oreille County", "Washington", "United States"}, ""),
				new County(new String[]{"Pierce County", "Washington", "United States"}, ""),
				new County(new String[]{"San Juan County", "Washington", "United States"}, ""),
				new County(new String[]{"Skagit County", "Washington", "United States"}, ""),
				new County(new String[]{"Skamania County", "Washington", "United States"}, ""),
				new County(new String[]{"Snohomish County", "Washington", "United States"}, ""),
				new County(new String[]{"Spokane County", "Washington", "United States"}, ""),
				new County(new String[]{"Stevens County", "Washington", "United States"}, ""),
				new County(new String[]{"Thurston County", "Washington", "United States"}, ""),
				new County(new String[]{"Wahkiakum County", "Washington", "United States"}, ""),
				new County(new String[]{"Walla Walla County", "Washington", "United States"}, ""),
				new County(new String[]{"Whatcom County", "Washington", "United States"}, ""),
				new County(new String[]{"Whitman County", "Washington", "United States"}, ""),
				new County(new String[]{"Yakima County", "Washington", "United States"}, "")
			});
		
		ArrayList<PlaceStructure> westVirginia = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Barbour County", "West Virginia", "United States"}, ""),
				new County(new String[]{"Berkeley County", "West Virginia", "United States"}, ""),
				new County(new String[]{"Boone County", "West Virginia", "United States"}, ""),
				new County(new String[]{"Braxton County", "West Virginia", "United States"}, ""),
				new County(new String[]{"Brooke County", "West Virginia", "United States"}, ""),
				new County(new String[]{"Cabell County", "West Virginia", "United States"}, ""),
				new County(new String[]{"Calhoun County", "West Virginia", "United States"}, ""),
				new County(new String[]{"Clay County", "West Virginia", "United States"}, ""),
				new County(new String[]{"Doddridge County", "West Virginia", "United States"}, ""),
				new County(new String[]{"Fayette County", "West Virginia", "United States"}, ""),
				new County(new String[]{"Gilmer County", "West Virginia", "United States"}, ""),
				new County(new String[]{"Grant County", "West Virginia", "United States"}, ""),
				new County(new String[]{"Greenbrier County", "West Virginia", "United States"}, ""),
				new County(new String[]{"Hampshire County", "West Virginia", "United States"}, ""),
				new County(new String[]{"Hancock County", "West Virginia", "United States"}, ""),
				new County(new String[]{"Hardy County", "West Virginia", "United States"}, ""),
				new County(new String[]{"Harrison County", "West Virginia", "United States"}, ""),
				new County(new String[]{"Jackson County", "West Virginia", "United States"}, ""),
				new County(new String[]{"Jefferson County", "West Virginia", "United States"}, ""),
				new County(new String[]{"Kanawha County", "West Virginia", "United States"}, ""),
				new County(new String[]{"Lewis County", "West Virginia", "United States"}, ""),
				new County(new String[]{"Lincoln County", "West Virginia", "United States"}, ""),
				new County(new String[]{"Logan County", "West Virginia", "United States"}, ""),
				new County(new String[]{"Marion County", "West Virginia", "United States"}, ""),
				new County(new String[]{"Marshall County", "West Virginia", "United States"}, ""),
				new County(new String[]{"Mason County", "West Virginia", "United States"}, ""),
				new County(new String[]{"McDowell County", "West Virginia", "United States"}, ""),
				new County(new String[]{"Mercer County", "West Virginia", "United States"}, ""),
				new County(new String[]{"Mineral County", "West Virginia", "United States"}, ""),
				new County(new String[]{"Mingo County", "West Virginia", "United States"}, ""),
				new County(new String[]{"Monongalia County", "West Virginia", "United States"}, ""),
				new County(new String[]{"Monroe County", "West Virginia", "United States"}, ""),
				new County(new String[]{"Morgan County", "West Virginia", "United States"}, ""),
				new County(new String[]{"Nicholas County", "West Virginia", "United States"}, ""),
				new County(new String[]{"Ohio County", "West Virginia", "United States"}, ""),
				new County(new String[]{"Pendleton County", "West Virginia", "United States"}, ""),
				new County(new String[]{"Pleasants County", "West Virginia", "United States"}, ""),
				new County(new String[]{"Pocahontas County", "West Virginia", "United States"}, ""),
				new County(new String[]{"Preston County", "West Virginia", "United States"}, ""),
				new County(new String[]{"Putnam County", "West Virginia", "United States"}, ""),
				new County(new String[]{"Raleigh County", "West Virginia", "United States"}, ""),
				new County(new String[]{"Randolph County", "West Virginia", "United States"}, ""),
				new County(new String[]{"Ritchie County", "West Virginia", "United States"}, ""),
				new County(new String[]{"Roane County", "West Virginia", "United States"}, ""),
				new County(new String[]{"Summers County", "West Virginia", "United States"}, ""),
				new County(new String[]{"Taylor County", "West Virginia", "United States"}, ""),
				new County(new String[]{"Tucker County", "West Virginia", "United States"}, ""),
				new County(new String[]{"Tyler County", "West Virginia", "United States"}, ""),
				new County(new String[]{"Upshur County", "West Virginia", "United States"}, ""),
				new County(new String[]{"Wayne County", "West Virginia", "United States"}, ""),
				new County(new String[]{"Webster County", "West Virginia", "United States"}, ""),
				new County(new String[]{"Wetzel County", "West Virginia", "United States"}, ""),
				new County(new String[]{"Wirt County", "West Virginia", "United States"}, ""),
				new County(new String[]{"Wood County", "West Virginia", "United States"}, ""),
				new County(new String[]{"Wyoming County", "West Virginia", "United States"}, "")
			});
		
		ArrayList<PlaceStructure> wisconsin = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Adams County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Ashland County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Barron County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Bayfield County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Brown County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Buffalo County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Burnett County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Calumet County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Chippewa County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Clark County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Columbia County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Crawford County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Dane County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Dodge County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Door County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Douglas County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Dunn County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Eau Claire County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Florence County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Fond du Lac County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Forest County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Grant County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Green County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Green Lake County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Iowa County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Iron County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Jackson County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Jefferson County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Juneau County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Kenosha County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Kewaunee County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"La Crosse County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Lafayette County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Langlade County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Lincoln County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Manitowoc County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Marathon County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Marinette County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Marquette County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Menominee County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Milwaukee County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Monroe County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Oconto County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Oneida County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Outagamie County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Ozaukee County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Pepin County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Pierce County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Polk County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Portage County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Price County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Racine County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Richland County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Rock County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Rusk County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Sauk County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Sawyer County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Shawano County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Sheboygan County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Saint Croix County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Taylor County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Trempealeau County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Vernon County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Vilas County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Walworth County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Washburn County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Washington County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Waukesha County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Waupaca County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Waushara County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Winnebago County", "Wisconsin", "United States"}, ""),
				new County(new String[]{"Wood County", "Wisconsin", "United States"}, "")
			});
		
		ArrayList<PlaceStructure> wyoming = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Albany County", "Wyoming", "United States"}, ""),
				new County(new String[]{"Big Horn County", "Wyoming", "United States"}, ""),
				new County(new String[]{"Campbell County", "Wyoming", "United States"}, ""),
				new County(new String[]{"Carbon County", "Wyoming", "United States"}, ""),
				new County(new String[]{"Converse County", "Wyoming", "United States"}, ""),
				new County(new String[]{"Crook County", "Wyoming", "United States"}, ""),
				new County(new String[]{"Fremont County", "Wyoming", "United States"}, ""),
				new County(new String[]{"Goshen County", "Wyoming", "United States"}, ""),
				new County(new String[]{"Hot Springs County", "Wyoming", "United States"}, ""),
				new County(new String[]{"Johnson County", "Wyoming", "United States"}, ""),
				new County(new String[]{"Laramie County", "Wyoming", "United States"}, ""),
				new County(new String[]{"Lincoln County", "Wyoming", "United States"}, ""),
				new County(new String[]{"Natrona County", "Wyoming", "United States"}, ""),
				new County(new String[]{"Niobrara County", "Wyoming", "United States"}, ""),
				new County(new String[]{"Park County", "Wyoming", "United States"}, ""),
				new County(new String[]{"Platte County", "Wyoming", "United States"}, ""),
				new County(new String[]{"Sheridan County", "Wyoming", "United States"}, ""),
				new County(new String[]{"Sublette County", "Wyoming", "United States"}, ""),
				new County(new String[]{"Sweetwater County", "Wyoming", "United States"}, ""),
				new County(new String[]{"Teton County", "Wyoming", "United States"}, ""),
				new County(new String[]{"Uinta County", "Wyoming", "United States"}, ""),
				new County(new String[]{"Washakie County", "Wyoming", "United States"}, ""),
				new County(new String[]{"Weston County", "Wyoming", "United States"}, "")
			});
		
		ArrayList<PlaceStructure> usArmedForces = Util.arrayList(new PlaceStructure[]{
//				new County(new String[]{"Armed Forces Africa", "United States"}, ""),
//				new County(new String[]{"Armed Forces Americas", "United States"}, ""),
//				new County(new String[]{"Armed Forces Canada", "United States"}, ""),
//				new County(new String[]{"Armed Forces Europe", "United States"}, ""),
//				new County(new String[]{"Armed Forces Middle East", "United States"}, ""),
//				new County(new String[]{"Armed Forces Pacific", "United States"}, "")
			});
		
		ArrayList<PlaceStructure> usVirginIslands = Util.arrayList(new PlaceStructure[]{
//				new County(new String[]{"VIRGIN ISLANDS", "United States"}, "")
			});
		
		ArrayList<PlaceStructure> washingtonDC = Util.arrayList(new PlaceStructure[]{
//				new County(new String[]{"Washington, DISTRICT OF COLUMBIA, United States"}, "")
			});

		//		em.persist(new XlsState(new String[]{"Palau", "United States"}, ""));
//		em.persist(new XlsState(new String[]{"Puerto Rico", "United States"}, ""));
		
		ArrayList<PlaceStructure> list = new ArrayList<PlaceStructure>();
		list = Util.arrayList(list, ohio);
		list = Util.arrayList(list, oklahoma);
		list = Util.arrayList(list, oregon);
		list = Util.arrayList(list, pennsylvania);
		list = Util.arrayList(list, rhodeIsland);
		list = Util.arrayList(list, southCarolina);
		list = Util.arrayList(list, southDakota);
		list = Util.arrayList(list, tennessee);
		list = Util.arrayList(list, texas);
		list = Util.arrayList(list, utah);
		list = Util.arrayList(list, vermont);
		list = Util.arrayList(list, usVirginIslands);
		list = Util.arrayList(list, virginia);
		list = Util.arrayList(list, washington);
		list = Util.arrayList(list, washingtonDC);
		list = Util.arrayList(list, westVirginia);
		list = Util.arrayList(list, wisconsin);
		list = Util.arrayList(list, wyoming);
		list = Util.arrayList(list, usArmedForces);
		return list;
	}
}
