package ws.daley.genealogy.db.places;

import java.util.ArrayList;

import ws.daley.genealogy.db.places.abstrct.PlaceStructure;
import ws.daley.genealogy.util.Util;

public class CountyUSAToK
{
	public static ArrayList<PlaceStructure> us()
	{
		ArrayList<PlaceStructure> alabama = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Autauga County", "Alabama", "United States"}, ""),
				new County(new String[]{"Baldwin County", "Alabama", "United States"}, ""),
				new County(new String[]{"Barbour County", "Alabama", "United States"}, ""),
				new County(new String[]{"Bibb County", "Alabama", "United States"}, ""),
				new County(new String[]{"Blount County", "Alabama", "United States"}, ""),
				new County(new String[]{"Bullock County", "Alabama", "United States"}, ""),
				new County(new String[]{"Butler County", "Alabama", "United States"}, ""),
				new County(new String[]{"Calhoun County", "Alabama", "United States"}, ""),
				new County(new String[]{"Chambers County", "Alabama", "United States"}, ""),
				new County(new String[]{"Cherokee County", "Alabama", "United States"}, ""),
				new County(new String[]{"Chilton County", "Alabama", "United States"}, ""),
				new County(new String[]{"Choctaw County", "Alabama", "United States"}, ""),
				new County(new String[]{"Clarke County", "Alabama", "United States"}, ""),
				new County(new String[]{"Clay County", "Alabama", "United States"}, ""),
				new County(new String[]{"Cleburne County", "Alabama", "United States"}, ""),
				new County(new String[]{"Coffee County", "Alabama", "United States"}, ""),
				new County(new String[]{"Colbert County", "Alabama", "United States"}, ""),
				new County(new String[]{"Conecuh County", "Alabama", "United States"}, ""),
				new County(new String[]{"Coosa County", "Alabama", "United States"}, ""),
				new County(new String[]{"Covington County", "Alabama", "United States"}, ""),
				new County(new String[]{"Crenshaw County", "Alabama", "United States"}, ""),
				new County(new String[]{"Cullman County", "Alabama", "United States"}, ""),
				new County(new String[]{"Dale County", "Alabama", "United States"}, ""),
				new County(new String[]{"Dallas County", "Alabama", "United States"}, ""),
				new County(new String[]{"DeKalb County", "Alabama", "United States"}, ""),
				new County(new String[]{"Elmore County", "Alabama", "United States"}, ""),
				new County(new String[]{"Escambia County", "Alabama", "United States"}, ""),
				new County(new String[]{"Etowah County", "Alabama", "United States"}, ""),
				new County(new String[]{"Fayette County", "Alabama", "United States"}, ""),
				new County(new String[]{"Franklin County", "Alabama", "United States"}, ""),
				new County(new String[]{"Geneva County", "Alabama", "United States"}, ""),
				new County(new String[]{"Greene County", "Alabama", "United States"}, ""),
				new County(new String[]{"Hale County", "Alabama", "United States"}, ""),
				new County(new String[]{"Henry County", "Alabama", "United States"}, ""),
				new County(new String[]{"Houston County", "Alabama", "United States"}, ""),
				new County(new String[]{"Jackson County", "Alabama", "United States"}, ""),
				new County(new String[]{"Jefferson County", "Alabama", "United States"}, ""),
				new County(new String[]{"Lamar County", "Alabama", "United States"}, ""),
				new County(new String[]{"Lauderdale County", "Alabama", "United States"}, ""),
				new County(new String[]{"Lawrence County", "Alabama", "United States"}, ""),
				new County(new String[]{"Lee County", "Alabama", "United States"}, ""),
				new County(new String[]{"Limestone County", "Alabama", "United States"}, ""),
				new County(new String[]{"Lowndes County", "Alabama", "United States"}, ""),
				new County(new String[]{"Macon County", "Alabama", "United States"}, ""),
				new County(new String[]{"Madison County", "Alabama", "United States"}, ""),
				new County(new String[]{"Marengo County", "Alabama", "United States"}, ""),
				new County(new String[]{"Marion County", "Alabama", "United States"}, ""),
				new County(new String[]{"Marshall County", "Alabama", "United States"}, ""),
				new County(new String[]{"Mobile County", "Alabama", "United States"}, ""),
				new County(new String[]{"Monroe County", "Alabama", "United States"}, ""),
				new County(new String[]{"Montgomery County", "Alabama", "United States"}, ""),
				new County(new String[]{"Morgan County", "Alabama", "United States"}, ""),
				new County(new String[]{"Perry County", "Alabama", "United States"}, ""),
				new County(new String[]{"Pickens County", "Alabama", "United States"}, ""),
				new County(new String[]{"Pike County", "Alabama", "United States"}, ""),
				new County(new String[]{"Randolph County", "Alabama", "United States"}, ""),
				new County(new String[]{"Russell County", "Alabama", "United States"}, ""),
				new County(new String[]{"St. Clair County", "Alabama", "United States"}, ""),
				new County(new String[]{"Shelby County", "Alabama", "United States"}, ""),
				new County(new String[]{"Sumter County", "Alabama", "United States"}, ""),
				new County(new String[]{"Talladega County", "Alabama", "United States"}, ""),
				new County(new String[]{"Tallapoosa County", "Alabama", "United States"}, ""),
				new County(new String[]{"Tuscaloosa County", "Alabama", "United States"}, ""),
				new County(new String[]{"Walker County", "Alabama", "United States"}, ""),
				new County(new String[]{"Washington County", "Alabama", "United States"}, ""),
				new County(new String[]{"Wilcox County", "Alabama", "United States"}, ""),
				new County(new String[]{"Winston County", "Alabama", "United States"}, "")
			});
		
		ArrayList<PlaceStructure> alaska = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Aleutians East Borough", "Alaska", "United States"}, ""),
				new County(new String[]{"Municipality of Anchorage", "Alaska", "United States"}, ""),
				new County(new String[]{"Bristol Bay Borough", "Alaska", "United States"}, ""),
				new County(new String[]{"Denali Borough", "Alaska", "United States"}, ""),
				new County(new String[]{"Fairbanks North Star Borough", "Alaska", "United States"}, ""),
				new County(new String[]{"Haines Borough", "Alaska", "United States"}, ""),
				new County(new String[]{"Borough of Juneau", "Alaska", "United States"}, ""),
				new County(new String[]{"Kenai Peninsula Borough", "Alaska", "United States"}, ""),
				new County(new String[]{"Ketchikan Gateway Borough", "Alaska", "United States"}, ""),
				new County(new String[]{"Kodiak Island Borough", "Alaska", "United States"}, ""),
				new County(new String[]{"Lake and Peninsula Borough", "Alaska", "United States"}, ""),
				new County(new String[]{"Matanuska-Susitna Borough", "Alaska", "United States"}, ""),
				new County(new String[]{"North Slope Borough", "Alaska", "United States"}, ""),
				new County(new String[]{"Northwest Arctic Borough", "Alaska", "United States"}, ""),
				new County(new String[]{"Borough of Sitka", "Alaska", "United States"}, ""),
				new County(new String[]{"Municipality of Skagway Borough", "Alaska", "United States"}, ""),
				new County(new String[]{"Borough of Wrangell", "Alaska", "United States"}, ""),
				new County(new String[]{"Borough of Yakutat", "Alaska", "United States"}, "")
			});
		
		ArrayList<PlaceStructure> americanSamoa = Util.arrayList(new PlaceStructure[]{
//				new County(new String[]{"AMERICAN SAMOA", "United States"}, "")
			});
		
		ArrayList<PlaceStructure> arizona = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Apache County", "Arizona", "United States"}, ""),
				new County(new String[]{"Cochise County", "Arizona", "United States"}, ""),
				new County(new String[]{"Coconino County", "Arizona", "United States"}, ""),
				new County(new String[]{"Gila County", "Arizona", "United States"}, ""),
				new County(new String[]{"Graham County", "Arizona", "United States"}, ""),
				new County(new String[]{"Greenlee County", "Arizona", "United States"}, ""),
				new County(new String[]{"La Paz County", "Arizona", "United States"}, ""),
				new County(new String[]{"Maricopa County", "Arizona", "United States"}, ""),
				new County(new String[]{"Mohave County", "Arizona", "United States"}, ""),
				new County(new String[]{"Navajo County", "Arizona", "United States"}, ""),
				new County(new String[]{"Pima County", "Arizona", "United States"}, ""),
				new County(new String[]{"Pinal County", "Arizona", "United States"}, ""),
				new County(new String[]{"Santa Cruz County", "Arizona", "United States"}, ""),
				new County(new String[]{"Yavapai County", "Arizona", "United States"}, ""),
				new County(new String[]{"Yuma County", "Arizona", "United States"}, "")
			});
		
		ArrayList<PlaceStructure> arkansas = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Arkansas County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Ashley County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Baxter County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Benton County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Boone County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Bradley County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Calhoun County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Carroll County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Chicot County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Clark County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Clay County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Cleburne County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Cleveland County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Columbia County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Conway County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Craighead County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Crawford County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Crittenden County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Cross County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Dallas County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Desha County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Drew County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Faulkner County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Franklin County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Fulton County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Garland County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Grant County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Greene County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Hempstead County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Hot Spring County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Howard County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Independence County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Izard County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Jackson County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Jefferson County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Johnson County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Lafayette County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Lawrence County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Lee County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Lincoln County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Little River County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Logan County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Lonoke County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Madison County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Marion County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Miller County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Mississippi County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Monroe County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Montgomery County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Nevada County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Newton County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Ouachita County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Perry County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Phillips County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Pike County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Poinsett County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Polk County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Pope County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Prairie County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Pulaski County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Randolph County", "Arkansas", "United States"}, ""),
				new County(new String[]{"St. Francis County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Saline County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Scott County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Searcy County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Sebastian County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Sevier County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Sharp County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Stone County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Union County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Van Buren County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Washington County", "Arkansas", "United States"}, ""),
				new County(new String[]{"White County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Woodruff County", "Arkansas", "United States"}, ""),
				new County(new String[]{"Yell County", "Arkansas", "United States"}, "")
			});
		
		ArrayList<PlaceStructure> california = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Alameda County", "California", "United States"}, ""),
				new County(new String[]{"Alpine County", "California", "United States"}, ""),
				new County(new String[]{"Amador County", "California", "United States"}, ""),
				new County(new String[]{"Butte County", "California", "United States"}, ""),
				new County(new String[]{"Calaveras County", "California", "United States"}, ""),
				new County(new String[]{"Colusa County", "California", "United States"}, ""),
				new County(new String[]{"Contra Costa County", "California", "United States"}, ""),
				new County(new String[]{"Del Norte County", "California", "United States"}, ""),
				new County(new String[]{"El Dorado County", "California", "United States"}, ""),
				new County(new String[]{"Fresno County", "California", "United States"}, ""),
				new County(new String[]{"Glenn County", "California", "United States"}, ""),
				new County(new String[]{"Humboldt County", "California", "United States"}, ""),
				new County(new String[]{"Imperial County", "California", "United States"}, ""),
				new County(new String[]{"Inyo County", "California", "United States"}, ""),
				new County(new String[]{"Kern County", "California", "United States"}, ""),
				new County(new String[]{"Kings County", "California", "United States"}, ""),
				new County(new String[]{"Lake County", "California", "United States"}, ""),
				new County(new String[]{"Lassen County", "California", "United States"}, ""),
				new County(new String[]{"Los Angeles County", "California", "United States"}, ""),
				new County(new String[]{"Madera County", "California", "United States"}, ""),
				new County(new String[]{"Marin County", "California", "United States"}, ""),
				new County(new String[]{"Mariposa County", "California", "United States"}, ""),
				new County(new String[]{"Mendocino County", "California", "United States"}, ""),
				new County(new String[]{"Merced County", "California", "United States"}, ""),
				new County(new String[]{"Modoc County", "California", "United States"}, ""),
				new County(new String[]{"Mono County", "California", "United States"}, ""),
				new County(new String[]{"Monterey County", "California", "United States"}, ""),
				new County(new String[]{"Napa County", "California", "United States"}, ""),
				new County(new String[]{"Nevada County", "California", "United States"}, ""),
				new County(new String[]{"Orange County", "California", "United States"}, ""),
				new County(new String[]{"Placer County", "California", "United States"}, ""),
				new County(new String[]{"Plumas County", "California", "United States"}, ""),
				new County(new String[]{"Riverside County", "California", "United States"}, ""),
				new County(new String[]{"Sacramento County", "California", "United States"}, ""),
				new County(new String[]{"San Benito County", "California", "United States"}, ""),
				new County(new String[]{"San Bernardino County", "California", "United States"}, ""),
				new County(new String[]{"San Diego County", "California", "United States"}, ""),
				new County(new String[]{"San Francisco County", "California", "United States"}, ""),
				new County(new String[]{"San Joaquin County", "California", "United States"}, ""),
				new County(new String[]{"San Luis Obispo County", "California", "United States"}, ""),
				new County(new String[]{"San Mateo County", "California", "United States"}, ""),
				new County(new String[]{"Santa Barbara County", "California", "United States"}, ""),
				new County(new String[]{"Santa Clara County", "California", "United States"}, ""),
				new County(new String[]{"Santa Cruz County", "California", "United States"}, ""),
				new County(new String[]{"Shasta County", "California", "United States"}, ""),
				new County(new String[]{"Sierra County", "California", "United States"}, ""),
				new County(new String[]{"Siskiyou County", "California", "United States"}, ""),
				new County(new String[]{"Solano County", "California", "United States"}, ""),
				new County(new String[]{"Sonoma County", "California", "United States"}, ""),
				new County(new String[]{"Stanislaus County", "California", "United States"}, ""),
				new County(new String[]{"Sutter County", "California", "United States"}, ""),
				new County(new String[]{"Tehama County", "California", "United States"}, ""),
				new County(new String[]{"Trinity County", "California", "United States"}, ""),
				new County(new String[]{"Tulare County", "California", "United States"}, ""),
				new County(new String[]{"Tuolumne County", "California", "United States"}, ""),
				new County(new String[]{"Ventura County", "California", "United States"}, ""),
				new County(new String[]{"Yolo County", "California", "United States"}, ""),
				new County(new String[]{"Yuba ", "California", "United States"}, "")
			});
		
		ArrayList<PlaceStructure> colorado = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Adams County", "Colorado", "United States"}, ""),
				new County(new String[]{"Alamosa County", "Colorado", "United States"}, ""),
				new County(new String[]{"Arapahoe County", "Colorado", "United States"}, ""),
				new County(new String[]{"Archuleta County", "Colorado", "United States"}, ""),
				new County(new String[]{"Baca County", "Colorado", "United States"}, ""),
				new County(new String[]{"Bent County", "Colorado", "United States"}, ""),
				new County(new String[]{"Boulder County", "Colorado", "United States"}, ""),
				new County(new String[]{"Broomfield County", "Colorado", "United States"}, ""),
				new County(new String[]{"Chaffee County", "Colorado", "United States"}, ""),
				new County(new String[]{"Cheyenne County", "Colorado", "United States"}, ""),
				new County(new String[]{"Clear Creek County", "Colorado", "United States"}, ""),
				new County(new String[]{"Conejos County", "Colorado", "United States"}, ""),
				new County(new String[]{"Costilla County", "Colorado", "United States"}, ""),
				new County(new String[]{"Crowley County", "Colorado", "United States"}, ""),
				new County(new String[]{"Custer County", "Colorado", "United States"}, ""),
				new County(new String[]{"Delta County", "Colorado", "United States"}, ""),
				new County(new String[]{"Denver County", "Colorado", "United States"}, ""),
				new County(new String[]{"Dolores County", "Colorado", "United States"}, ""),
				new County(new String[]{"Douglas County", "Colorado", "United States"}, ""),
				new County(new String[]{"Eagle County", "Colorado", "United States"}, ""),
				new County(new String[]{"Elbert County", "Colorado", "United States"}, ""),
				new County(new String[]{"El Paso County", "Colorado", "United States"}, ""),
				new County(new String[]{"Fremont County", "Colorado", "United States"}, ""),
				new County(new String[]{"Garfield County", "Colorado", "United States"}, ""),
				new County(new String[]{"Gilpin County", "Colorado", "United States"}, ""),
				new County(new String[]{"Grand County", "Colorado", "United States"}, ""),
				new County(new String[]{"Gunnison County", "Colorado", "United States"}, ""),
				new County(new String[]{"Hinsdale County", "Colorado", "United States"}, ""),
				new County(new String[]{"Huerfano County", "Colorado", "United States"}, ""),
				new County(new String[]{"Jackson County", "Colorado", "United States"}, ""),
				new County(new String[]{"Jefferson County", "Colorado", "United States"}, ""),
				new County(new String[]{"Kiowa County", "Colorado", "United States"}, ""),
				new County(new String[]{"Kit Carson County", "Colorado", "United States"}, ""),
				new County(new String[]{"Lake County", "Colorado", "United States"}, ""),
				new County(new String[]{"La Plata County", "Colorado", "United States"}, ""),
				new County(new String[]{"Larimer County", "Colorado", "United States"}, ""),
				new County(new String[]{"Las Animas County", "Colorado", "United States"}, ""),
				new County(new String[]{"Lincoln County", "Colorado", "United States"}, ""),
				new County(new String[]{"Logan County", "Colorado", "United States"}, ""),
				new County(new String[]{"Mesa County", "Colorado", "United States"}, ""),
				new County(new String[]{"Mineral County", "Colorado", "United States"}, ""),
				new County(new String[]{"Moffat County", "Colorado", "United States"}, ""),
				new County(new String[]{"Montezuma County", "Colorado", "United States"}, ""),
				new County(new String[]{"Montrose County", "Colorado", "United States"}, ""),
				new County(new String[]{"Morgan County", "Colorado", "United States"}, ""),
				new County(new String[]{"Otero County", "Colorado", "United States"}, ""),
				new County(new String[]{"Ouray County", "Colorado", "United States"}, ""),
				new County(new String[]{"Park County", "Colorado", "United States"}, ""),
				new County(new String[]{"Phillips County", "Colorado", "United States"}, ""),
				new County(new String[]{"Pitkin County", "Colorado", "United States"}, ""),
				new County(new String[]{"Prowers County", "Colorado", "United States"}, ""),
				new County(new String[]{"Pueblo County", "Colorado", "United States"}, ""),
				new County(new String[]{"Rio Blanco County", "Colorado", "United States"}, ""),
				new County(new String[]{"Rio Grande County", "Colorado", "United States"}, ""),
				new County(new String[]{"Routt County", "Colorado", "United States"}, ""),
				new County(new String[]{"Saguache County", "Colorado", "United States"}, ""),
				new County(new String[]{"San Juan County", "Colorado", "United States"}, ""),
				new County(new String[]{"San Miguel County", "Colorado", "United States"}, ""),
				new County(new String[]{"Sedgwick County", "Colorado", "United States"}, ""),
				new County(new String[]{"Summit County", "Colorado", "United States"}, ""),
				new County(new String[]{"Teller County", "Colorado", "United States"}, ""),
				new County(new String[]{"Washington County", "Colorado", "United States"}, ""),
				new County(new String[]{"Weld County", "Colorado", "United States"}, ""),
				new County(new String[]{"Yuma County", "Colorado", "United States"}, "")
			});
		
		ArrayList<PlaceStructure> connecticut = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Bridgeport County", "Connecticut", "United States"}, ""),
				new County(new String[]{"Fairfield County", "Connecticut", "United States"}, ""),
				new County(new String[]{"Hartford County", "Connecticut", "United States"}, ""),
				new County(new String[]{"Litchfield County", "Connecticut", "United States"}, ""),
				new County(new String[]{"Middlesex County", "Connecticut", "United States"}, ""),
				new County(new String[]{"New Haven County", "Connecticut", "United States"}, ""),
				new County(new String[]{"New London County", "Connecticut", "United States"}, ""),
				new County(new String[]{"Tolland County", "Connecticut", "United States"}, ""),
				new County(new String[]{"Rockville County", "Connecticut", "United States"}, ""),
				new County(new String[]{"Windham County", "Connecticut", "United States"}, ""),
				new County(new String[]{"Brooklyn County", "Connecticut", "United States"}, ""),
				new County(new String[]{"Willimantic and Putnam County", "Connecticut", "United States"}, "")
			});
		
		ArrayList<PlaceStructure> delaware = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Kent County", "Delaware", "United States"}, ""),
				new County(new String[]{"New Castle County", "Delaware", "United States"}, ""),
				new County(new String[]{"Sussex County", "Delaware", "United States"}, "")
			});
		
		ArrayList<PlaceStructure> florida = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Alachua County", "Florida", "United States"}, ""),
				new County(new String[]{"Baker County", "Florida", "United States"}, ""),
				new County(new String[]{"Bay County", "Florida", "United States"}, ""),
				new County(new String[]{"Bradford County", "Florida", "United States"}, ""),
				new County(new String[]{"Brevard County", "Florida", "United States"}, ""),
				new County(new String[]{"Broward County", "Florida", "United States"}, ""),
				new County(new String[]{"Calhoun County", "Florida", "United States"}, ""),
				new County(new String[]{"Charlotte County", "Florida", "United States"}, ""),
				new County(new String[]{"Citrus County", "Florida", "United States"}, ""),
				new County(new String[]{"Clay County", "Florida", "United States"}, ""),
				new County(new String[]{"Collier County", "Florida", "United States"}, ""),
				new County(new String[]{"Columbia County", "Florida", "United States"}, ""),
				new County(new String[]{"DeSoto County", "Florida", "United States"}, ""),
				new County(new String[]{"Dixie County", "Florida", "United States"}, ""),
				new County(new String[]{"Duval County", "Florida", "United States"}, ""),
				new County(new String[]{"Escambia County", "Florida", "United States"}, ""),
				new County(new String[]{"Flagler County", "Florida", "United States"}, ""),
				new County(new String[]{"Franklin County", "Florida", "United States"}, ""),
				new County(new String[]{"Gadsden County", "Florida", "United States"}, ""),
				new County(new String[]{"Gilchrist County", "Florida", "United States"}, ""),
				new County(new String[]{"Glades County", "Florida", "United States"}, ""),
				new County(new String[]{"Gulf County", "Florida", "United States"}, ""),
				new County(new String[]{"Hamilton County", "Florida", "United States"}, ""),
				new County(new String[]{"Hardee County", "Florida", "United States"}, ""),
				new County(new String[]{"Hendry County", "Florida", "United States"}, ""),
				new County(new String[]{"Hernando County", "Florida", "United States"}, ""),
				new County(new String[]{"Highlands County", "Florida", "United States"}, ""),
				new County(new String[]{"Hillsborough County", "Florida", "United States"}, ""),
				new County(new String[]{"Holmes County", "Florida", "United States"}, ""),
				new County(new String[]{"Indian River County", "Florida", "United States"}, ""),
				new County(new String[]{"Jackson County", "Florida", "United States"}, ""),
				new County(new String[]{"Jefferson County", "Florida", "United States"}, ""),
				new County(new String[]{"Lafayette County", "Florida", "United States"}, ""),
				new County(new String[]{"Lake County", "Florida", "United States"}, ""),
				new County(new String[]{"Lee County", "Florida", "United States"}, ""),
				new County(new String[]{"Leon County", "Florida", "United States"}, ""),
				new County(new String[]{"Levy County", "Florida", "United States"}, ""),
				new County(new String[]{"Liberty County", "Florida", "United States"}, ""),
				new County(new String[]{"Madison County", "Florida", "United States"}, ""),
				new County(new String[]{"Manatee County", "Florida", "United States"}, ""),
				new County(new String[]{"Marion County", "Florida", "United States"}, ""),
				new County(new String[]{"Martin County", "Florida", "United States"}, ""),
				new County(new String[]{"Miami-Dade County", "Florida", "United States"}, ""),
				new County(new String[]{"Monroe County", "Florida", "United States"}, ""),
				new County(new String[]{"Nassau County", "Florida", "United States"}, ""),
				new County(new String[]{"Okaloosa County", "Florida", "United States"}, ""),
				new County(new String[]{"Okeechobee County", "Florida", "United States"}, ""),
				new County(new String[]{"Orange County", "Florida", "United States"}, ""),
				new County(new String[]{"Osceola County", "Florida", "United States"}, ""),
				new County(new String[]{"Palm Beach County", "Florida", "United States"}, ""),
				new County(new String[]{"Pasco County", "Florida", "United States"}, ""),
				new County(new String[]{"Pinellas County", "Florida", "United States"}, ""),
				new County(new String[]{"Polk County", "Florida", "United States"}, ""),
				new County(new String[]{"Putnam County", "Florida", "United States"}, ""),
				new County(new String[]{"Saint Johns County", "Florida", "United States"}, ""),
				new County(new String[]{"Saint Lucie County", "Florida", "United States"}, ""),
				new County(new String[]{"Santa Rosa County", "Florida", "United States"}, ""),
				new County(new String[]{"Sarasota County", "Florida", "United States"}, ""),
				new County(new String[]{"Seminole County", "Florida", "United States"}, ""),
				new County(new String[]{"Sumter County", "Florida", "United States"}, ""),
				new County(new String[]{"Suwannee County", "Florida", "United States"}, ""),
				new County(new String[]{"Taylor County", "Florida", "United States"}, ""),
				new County(new String[]{"Union County", "Florida", "United States"}, ""),
				new County(new String[]{"Volusia County", "Florida", "United States"}, ""),
				new County(new String[]{"Wakulla County", "Florida", "United States"}, ""),
				new County(new String[]{"Walton County", "Florida", "United States"}, ""),
				new County(new String[]{"Washington County", "Florida", "United States"}, "")
			});
		
		ArrayList<PlaceStructure> georgia = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Appling County", "Georgia", "United States"}, ""),
				new County(new String[]{"Atkinson County", "Georgia", "United States"}, ""),
				new County(new String[]{"Bacon County", "Georgia", "United States"}, ""),
				new County(new String[]{"Baker County", "Georgia", "United States"}, ""),
				new County(new String[]{"Baldwin County", "Georgia", "United States"}, ""),
				new County(new String[]{"Banks County", "Georgia", "United States"}, ""),
				new County(new String[]{"Barrow County", "Georgia", "United States"}, ""),
				new County(new String[]{"Bartow County", "Georgia", "United States"}, ""),
				new County(new String[]{"Ben Hill County", "Georgia", "United States"}, ""),
				new County(new String[]{"Berrien County", "Georgia", "United States"}, ""),
				new County(new String[]{"Bibb County", "Georgia", "United States"}, ""),
				new County(new String[]{"Bleckley County", "Georgia", "United States"}, ""),
				new County(new String[]{"Brantley County", "Georgia", "United States"}, ""),
				new County(new String[]{"Brooks County", "Georgia", "United States"}, ""),
				new County(new String[]{"Bryan County", "Georgia", "United States"}, ""),
				new County(new String[]{"Bulloch County", "Georgia", "United States"}, ""),
				new County(new String[]{"Burke County", "Georgia", "United States"}, ""),
				new County(new String[]{"Butts County", "Georgia", "United States"}, ""),
				new County(new String[]{"Calhoun County", "Georgia", "United States"}, ""),
				new County(new String[]{"Camden County", "Georgia", "United States"}, ""),
				new County(new String[]{"Candler County", "Georgia", "United States"}, ""),
				new County(new String[]{"Carroll County", "Georgia", "United States"}, ""),
				new County(new String[]{"Catoosa County", "Georgia", "United States"}, ""),
				new County(new String[]{"Charlton County", "Georgia", "United States"}, ""),
				new County(new String[]{"Chatham County", "Georgia", "United States"}, ""),
				new County(new String[]{"Chattahoochee County", "Georgia", "United States"}, ""),
				new County(new String[]{"Chattooga County", "Georgia", "United States"}, ""),
				new County(new String[]{"Cherokee County", "Georgia", "United States"}, ""),
				new County(new String[]{"Clarke County", "Georgia", "United States"}, ""),
				new County(new String[]{"Clay County", "Georgia", "United States"}, ""),
				new County(new String[]{"Clayton County", "Georgia", "United States"}, ""),
				new County(new String[]{"Clinch County", "Georgia", "United States"}, ""),
				new County(new String[]{"Cobb County", "Georgia", "United States"}, ""),
				new County(new String[]{"Coffee County", "Georgia", "United States"}, ""),
				new County(new String[]{"Colquitt County", "Georgia", "United States"}, ""),
				new County(new String[]{"Columbia County", "Georgia", "United States"}, ""),
				new County(new String[]{"Cook County", "Georgia", "United States"}, ""),
				new County(new String[]{"Coweta County", "Georgia", "United States"}, ""),
				new County(new String[]{"Crawford County", "Georgia", "United States"}, ""),
				new County(new String[]{"Crisp County", "Georgia", "United States"}, ""),
				new County(new String[]{"Dade County", "Georgia", "United States"}, ""),
				new County(new String[]{"Dawson County", "Georgia", "United States"}, ""),
				new County(new String[]{"Decatur County", "Georgia", "United States"}, ""),
				new County(new String[]{"DeKalb County", "Georgia", "United States"}, ""),
				new County(new String[]{"Dodge County", "Georgia", "United States"}, ""),
				new County(new String[]{"Dooly County", "Georgia", "United States"}, ""),
				new County(new String[]{"Dougherty County", "Georgia", "United States"}, ""),
				new County(new String[]{"Douglas County", "Georgia", "United States"}, ""),
				new County(new String[]{"Early County", "Georgia", "United States"}, ""),
				new County(new String[]{"Echols County", "Georgia", "United States"}, ""),
				new County(new String[]{"Effingham County", "Georgia", "United States"}, ""),
				new County(new String[]{"Elbert County", "Georgia", "United States"}, ""),
				new County(new String[]{"Emanuel County", "Georgia", "United States"}, ""),
				new County(new String[]{"Evans County", "Georgia", "United States"}, ""),
				new County(new String[]{"Fannin County", "Georgia", "United States"}, ""),
				new County(new String[]{"Fayette County", "Georgia", "United States"}, ""),
				new County(new String[]{"Floyd County", "Georgia", "United States"}, ""),
				new County(new String[]{"Forsyth County", "Georgia", "United States"}, ""),
				new County(new String[]{"Franklin County", "Georgia", "United States"}, ""),
				new County(new String[]{"Fulton County", "Georgia", "United States"}, ""),
				new County(new String[]{"Gilmer County", "Georgia", "United States"}, ""),
				new County(new String[]{"Glascock County", "Georgia", "United States"}, ""),
				new County(new String[]{"Glynn County", "Georgia", "United States"}, ""),
				new County(new String[]{"Gordon County", "Georgia", "United States"}, ""),
				new County(new String[]{"Grady County", "Georgia", "United States"}, ""),
				new County(new String[]{"Greene County", "Georgia", "United States"}, ""),
				new County(new String[]{"Gwinnett County", "Georgia", "United States"}, ""),
				new County(new String[]{"Habersham County", "Georgia", "United States"}, ""),
				new County(new String[]{"Hall County", "Georgia", "United States"}, ""),
				new County(new String[]{"Hancock County", "Georgia", "United States"}, ""),
				new County(new String[]{"Haralson County", "Georgia", "United States"}, ""),
				new County(new String[]{"Harris County", "Georgia", "United States"}, ""),
				new County(new String[]{"Hart County", "Georgia", "United States"}, ""),
				new County(new String[]{"Heard County", "Georgia", "United States"}, ""),
				new County(new String[]{"Henry County", "Georgia", "United States"}, ""),
				new County(new String[]{"Houston County", "Georgia", "United States"}, ""),
				new County(new String[]{"Irwin County", "Georgia", "United States"}, ""),
				new County(new String[]{"Jackson County", "Georgia", "United States"}, ""),
				new County(new String[]{"Jasper County", "Georgia", "United States"}, ""),
				new County(new String[]{"Jeff Davis County", "Georgia", "United States"}, ""),
				new County(new String[]{"Jefferson County", "Georgia", "United States"}, ""),
				new County(new String[]{"Jenkins County", "Georgia", "United States"}, ""),
				new County(new String[]{"Johnson County", "Georgia", "United States"}, ""),
				new County(new String[]{"Jones County", "Georgia", "United States"}, ""),
				new County(new String[]{"Lamar County", "Georgia", "United States"}, ""),
				new County(new String[]{"Lanier County", "Georgia", "United States"}, ""),
				new County(new String[]{"Laurens County", "Georgia", "United States"}, ""),
				new County(new String[]{"Lee County", "Georgia", "United States"}, ""),
				new County(new String[]{"Liberty County", "Georgia", "United States"}, ""),
				new County(new String[]{"Lincoln County", "Georgia", "United States"}, ""),
				new County(new String[]{"Long County", "Georgia", "United States"}, ""),
				new County(new String[]{"Lowndes County", "Georgia", "United States"}, ""),
				new County(new String[]{"Lumpkin County", "Georgia", "United States"}, ""),
				new County(new String[]{"Macon County", "Georgia", "United States"}, ""),
				new County(new String[]{"Madison County", "Georgia", "United States"}, ""),
				new County(new String[]{"Marion County", "Georgia", "United States"}, ""),
				new County(new String[]{"McDuffie County", "Georgia", "United States"}, ""),
				new County(new String[]{"McIntosh County", "Georgia", "United States"}, ""),
				new County(new String[]{"Meriwether County", "Georgia", "United States"}, ""),
				new County(new String[]{"Miller County", "Georgia", "United States"}, ""),
				new County(new String[]{"Mitchell County", "Georgia", "United States"}, ""),
				new County(new String[]{"Monroe County", "Georgia", "United States"}, ""),
				new County(new String[]{"Montgomery County", "Georgia", "United States"}, ""),
				new County(new String[]{"Morgan County", "Georgia", "United States"}, ""),
				new County(new String[]{"Murray County", "Georgia", "United States"}, ""),
				new County(new String[]{"Muscogee County", "Georgia", "United States"}, ""),
				new County(new String[]{"Newton County", "Georgia", "United States"}, ""),
				new County(new String[]{"Oconee County", "Georgia", "United States"}, ""),
				new County(new String[]{"Oglethorpe County", "Georgia", "United States"}, ""),
				new County(new String[]{"Paulding County", "Georgia", "United States"}, ""),
				new County(new String[]{"Peach County", "Georgia", "United States"}, ""),
				new County(new String[]{"Pickens County", "Georgia", "United States"}, ""),
				new County(new String[]{"Pierce County", "Georgia", "United States"}, ""),
				new County(new String[]{"Pike County", "Georgia", "United States"}, ""),
				new County(new String[]{"Polk County", "Georgia", "United States"}, ""),
				new County(new String[]{"Pulaski County", "Georgia", "United States"}, ""),
				new County(new String[]{"Putnam County", "Georgia", "United States"}, ""),
				new County(new String[]{"Quitman County", "Georgia", "United States"}, ""),
				new County(new String[]{"Rabun County", "Georgia", "United States"}, ""),
				new County(new String[]{"Randolph County", "Georgia", "United States"}, ""),
				new County(new String[]{"Richmond County", "Georgia", "United States"}, ""),
				new County(new String[]{"Rockdale County", "Georgia", "United States"}, ""),
				new County(new String[]{"Schley County", "Georgia", "United States"}, ""),
				new County(new String[]{"Screven County", "Georgia", "United States"}, ""),
				new County(new String[]{"Seminole County", "Georgia", "United States"}, ""),
				new County(new String[]{"Spalding County", "Georgia", "United States"}, ""),
				new County(new String[]{"Stephens County", "Georgia", "United States"}, ""),
				new County(new String[]{"Stewart County", "Georgia", "United States"}, ""),
				new County(new String[]{"Sumter County", "Georgia", "United States"}, ""),
				new County(new String[]{"Talbot County", "Georgia", "United States"}, ""),
				new County(new String[]{"Taliaferro County", "Georgia", "United States"}, ""),
				new County(new String[]{"Tattnall County", "Georgia", "United States"}, ""),
				new County(new String[]{"Taylor County", "Georgia", "United States"}, ""),
				new County(new String[]{"Telfair County", "Georgia", "United States"}, ""),
				new County(new String[]{"Terrell County", "Georgia", "United States"}, ""),
				new County(new String[]{"Thomas County", "Georgia", "United States"}, ""),
				new County(new String[]{"Tift County", "Georgia", "United States"}, ""),
				new County(new String[]{"Toombs County", "Georgia", "United States"}, ""),
				new County(new String[]{"Towns County", "Georgia", "United States"}, ""),
				new County(new String[]{"Treutlen County", "Georgia", "United States"}, ""),
				new County(new String[]{"Troup County", "Georgia", "United States"}, ""),
				new County(new String[]{"Turner County", "Georgia", "United States"}, ""),
				new County(new String[]{"Twiggs County", "Georgia", "United States"}, ""),
				new County(new String[]{"Union County", "Georgia", "United States"}, ""),
				new County(new String[]{"Upson County", "Georgia", "United States"}, ""),
				new County(new String[]{"Walker County", "Georgia", "United States"}, ""),
				new County(new String[]{"Walton County", "Georgia", "United States"}, ""),
				new County(new String[]{"Ware County", "Georgia", "United States"}, ""),
				new County(new String[]{"Warren County", "Georgia", "United States"}, ""),
				new County(new String[]{"Washington County", "Georgia", "United States"}, ""),
				new County(new String[]{"Wayne County", "Georgia", "United States"}, ""),
				new County(new String[]{"Webster County", "Georgia", "United States"}, ""),
				new County(new String[]{"Wheeler County", "Georgia", "United States"}, ""),
				new County(new String[]{"White County", "Georgia", "United States"}, ""),
				new County(new String[]{"Whitfield County", "Georgia", "United States"}, ""),
				new County(new String[]{"Wilcox County", "Georgia", "United States"}, ""),
				new County(new String[]{"Wilkes County", "Georgia", "United States"}, ""),
				new County(new String[]{"Wilkinson County", "Georgia", "United States"}, ""),
				new County(new String[]{"Worth County", "Georgia", "United States"}, "")
			});
		
		ArrayList<PlaceStructure> guam = Util.arrayList(new PlaceStructure[]{
//				new County(new String[]{"GUAM", "United States"}, "")
			});
		
		ArrayList<PlaceStructure> hawaii = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Hawaii County", "Hawaii", "United States"}, ""),
				new County(new String[]{"Honolulu County", "Hawaii", "United States"}, ""),
				new County(new String[]{"Kalawao County", "Hawaii", "United States"}, ""),
				new County(new String[]{"Kauai County", "Hawaii", "United States"}, ""),
				new County(new String[]{"Maui County", "Hawaii", "United States"}, "")
			});
		
		ArrayList<PlaceStructure> idaho = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Ada County", "Idaho", "United States"}, ""),
				new County(new String[]{"Adams County", "Idaho", "United States"}, ""),
				new County(new String[]{"Bannock County", "Idaho", "United States"}, ""),
				new County(new String[]{"Bear Lake County", "Idaho", "United States"}, ""),
				new County(new String[]{"Benewah County", "Idaho", "United States"}, ""),
				new County(new String[]{"Bingham County", "Idaho", "United States"}, ""),
				new County(new String[]{"Blaine County", "Idaho", "United States"}, ""),
				new County(new String[]{"Boise County", "Idaho", "United States"}, ""),
				new County(new String[]{"Bonner County", "Idaho", "United States"}, ""),
				new County(new String[]{"Bonneville County", "Idaho", "United States"}, ""),
				new County(new String[]{"Boundary County", "Idaho", "United States"}, ""),
				new County(new String[]{"Butte County", "Idaho", "United States"}, ""),
				new County(new String[]{"Camas County", "Idaho", "United States"}, ""),
				new County(new String[]{"Canyon County", "Idaho", "United States"}, ""),
				new County(new String[]{"Caribou County", "Idaho", "United States"}, ""),
				new County(new String[]{"Cassia County", "Idaho", "United States"}, ""),
				new County(new String[]{"Clark County", "Idaho", "United States"}, ""),
				new County(new String[]{"Clearwater County", "Idaho", "United States"}, ""),
				new County(new String[]{"Custer County", "Idaho", "United States"}, ""),
				new County(new String[]{"Elmore County", "Idaho", "United States"}, ""),
				new County(new String[]{"Franklin County", "Idaho", "United States"}, ""),
				new County(new String[]{"Fremont County", "Idaho", "United States"}, ""),
				new County(new String[]{"Gem County", "Idaho", "United States"}, ""),
				new County(new String[]{"Gooding County", "Idaho", "United States"}, ""),
				new County(new String[]{"Idaho County", "Idaho", "United States"}, ""),
				new County(new String[]{"Jefferson County", "Idaho", "United States"}, ""),
				new County(new String[]{"Jerome County", "Idaho", "United States"}, ""),
				new County(new String[]{"Kootenai County", "Idaho", "United States"}, ""),
				new County(new String[]{"Latah County", "Idaho", "United States"}, ""),
				new County(new String[]{"Lemhi County", "Idaho", "United States"}, ""),
				new County(new String[]{"Lewis County", "Idaho", "United States"}, ""),
				new County(new String[]{"Lincoln County", "Idaho", "United States"}, ""),
				new County(new String[]{"Madison County", "Idaho", "United States"}, ""),
				new County(new String[]{"Minidoka County", "Idaho", "United States"}, ""),
				new County(new String[]{"Nez Perce County", "Idaho", "United States"}, ""),
				new County(new String[]{"Oneida County", "Idaho", "United States"}, ""),
				new County(new String[]{"Owyhee County", "Idaho", "United States"}, ""),
				new County(new String[]{"Payette County", "Idaho", "United States"}, ""),
				new County(new String[]{"Power County", "Idaho", "United States"}, ""),
				new County(new String[]{"Shoshone County", "Idaho", "United States"}, ""),
				new County(new String[]{"Teton County", "Idaho", "United States"}, ""),
				new County(new String[]{"Twin Falls County", "Idaho", "United States"}, ""),
				new County(new String[]{"Valley County", "Idaho", "United States"}, ""),
				new County(new String[]{"Washington County", "Idaho", "United States"}, "")
			});
		
		ArrayList<PlaceStructure> illinois = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Adams County", "Illinois", "United States"}, ""),
				new County(new String[]{"Alexander County", "Illinois", "United States"}, ""),
				new County(new String[]{"Bond County", "Illinois", "United States"}, ""),
				new County(new String[]{"Boone County", "Illinois", "United States"}, ""),
				new County(new String[]{"Brown County", "Illinois", "United States"}, ""),
				new County(new String[]{"Bureau County", "Illinois", "United States"}, ""),
				new County(new String[]{"Calhoun County", "Illinois", "United States"}, ""),
				new County(new String[]{"Carroll County", "Illinois", "United States"}, ""),
				new County(new String[]{"Cass County", "Illinois", "United States"}, ""),
				new County(new String[]{"Champaign County", "Illinois", "United States"}, ""),
				new County(new String[]{"Christian County", "Illinois", "United States"}, ""),
				new County(new String[]{"Clark County", "Illinois", "United States"}, ""),
				new County(new String[]{"Clay County", "Illinois", "United States"}, ""),
				new County(new String[]{"Clinton County", "Illinois", "United States"}, ""),
				new County(new String[]{"Coles County", "Illinois", "United States"}, ""),
				new County(new String[]{"Cook County", "Illinois", "United States"}, ""),
				new County(new String[]{"Crawford County", "Illinois", "United States"}, ""),
				new County(new String[]{"Cumberland County", "Illinois", "United States"}, ""),
				new County(new String[]{"De Witt County", "Illinois", "United States"}, ""),
				new County(new String[]{"DeKalb County", "Illinois", "United States"}, ""),
				new County(new String[]{"Douglas County", "Illinois", "United States"}, ""),
				new County(new String[]{"DuPage County", "Illinois", "United States"}, ""),
				new County(new String[]{"Edgar County", "Illinois", "United States"}, ""),
				new County(new String[]{"Edwards County", "Illinois", "United States"}, ""),
				new County(new String[]{"Effingham County", "Illinois", "United States"}, ""),
				new County(new String[]{"Fayette County", "Illinois", "United States"}, ""),
				new County(new String[]{"Ford County", "Illinois", "United States"}, ""),
				new County(new String[]{"Franklin County", "Illinois", "United States"}, ""),
				new County(new String[]{"Fulton County", "Illinois", "United States"}, ""),
				new County(new String[]{"Gallatin County", "Illinois", "United States"}, ""),
				new County(new String[]{"Greene County", "Illinois", "United States"}, ""),
				new County(new String[]{"Grundy County", "Illinois", "United States"}, ""),
				new County(new String[]{"Hamilton County", "Illinois", "United States"}, ""),
				new County(new String[]{"Hancock County", "Illinois", "United States"}, ""),
				new County(new String[]{"Hardin County", "Illinois", "United States"}, ""),
				new County(new String[]{"Henderson County", "Illinois", "United States"}, ""),
				new County(new String[]{"Henry County", "Illinois", "United States"}, ""),
				new County(new String[]{"Iroquois County", "Illinois", "United States"}, ""),
				new County(new String[]{"Jackson County", "Illinois", "United States"}, ""),
				new County(new String[]{"Jasper County", "Illinois", "United States"}, ""),
				new County(new String[]{"Jefferson County", "Illinois", "United States"}, ""),
				new County(new String[]{"Jersey County", "Illinois", "United States"}, ""),
				new County(new String[]{"Jo Daviess County", "Illinois", "United States"}, ""),
				new County(new String[]{"Johnson County", "Illinois", "United States"}, ""),
				new County(new String[]{"Kane County", "Illinois", "United States"}, ""),
				new County(new String[]{"Kankakee County", "Illinois", "United States"}, ""),
				new County(new String[]{"Kendall County", "Illinois", "United States"}, ""),
				new County(new String[]{"Knox County", "Illinois", "United States"}, ""),
				new County(new String[]{"Lake County", "Illinois", "United States"}, ""),
				new County(new String[]{"LaSalle County", "Illinois", "United States"}, ""),
				new County(new String[]{"Lawrence County", "Illinois", "United States"}, ""),
				new County(new String[]{"Lee County", "Illinois", "United States"}, ""),
				new County(new String[]{"Livingston County", "Illinois", "United States"}, ""),
				new County(new String[]{"Logan County", "Illinois", "United States"}, ""),
				new County(new String[]{"Macon County", "Illinois", "United States"}, ""),
				new County(new String[]{"Macoupin County", "Illinois", "United States"}, ""),
				new County(new String[]{"Madison County", "Illinois", "United States"}, ""),
				new County(new String[]{"Marion County", "Illinois", "United States"}, ""),
				new County(new String[]{"Marshall County", "Illinois", "United States"}, ""),
				new County(new String[]{"Mason County", "Illinois", "United States"}, ""),
				new County(new String[]{"Massac County", "Illinois", "United States"}, ""),
				new County(new String[]{"McDonough County", "Illinois", "United States"}, ""),
				new County(new String[]{"McHenry County", "Illinois", "United States"}, ""),
				new County(new String[]{"McLean County", "Illinois", "United States"}, ""),
				new County(new String[]{"Menard County", "Illinois", "United States"}, ""),
				new County(new String[]{"Mercer County", "Illinois", "United States"}, ""),
				new County(new String[]{"Monroe County", "Illinois", "United States"}, ""),
				new County(new String[]{"Montgomery County", "Illinois", "United States"}, ""),
				new County(new String[]{"Morgan County", "Illinois", "United States"}, ""),
				new County(new String[]{"Moultrie County", "Illinois", "United States"}, ""),
				new County(new String[]{"Ogle County", "Illinois", "United States"}, ""),
				new County(new String[]{"Peoria County", "Illinois", "United States"}, ""),
				new County(new String[]{"Perry County", "Illinois", "United States"}, ""),
				new County(new String[]{"Piatt County", "Illinois", "United States"}, ""),
				new County(new String[]{"Pike County", "Illinois", "United States"}, ""),
				new County(new String[]{"Pope County", "Illinois", "United States"}, ""),
				new County(new String[]{"Pulaski County", "Illinois", "United States"}, ""),
				new County(new String[]{"Putnam County", "Illinois", "United States"}, ""),
				new County(new String[]{"Randolph County", "Illinois", "United States"}, ""),
				new County(new String[]{"Richland County", "Illinois", "United States"}, ""),
				new County(new String[]{"Rock Island County", "Illinois", "United States"}, ""),
				new County(new String[]{"Saline County", "Illinois", "United States"}, ""),
				new County(new String[]{"Sangamon County", "Illinois", "United States"}, ""),
				new County(new String[]{"Schuyler County", "Illinois", "United States"}, ""),
				new County(new String[]{"Scott County", "Illinois", "United States"}, ""),
				new County(new String[]{"Shelby County", "Illinois", "United States"}, ""),
				new County(new String[]{"St. Clair County", "Illinois", "United States"}, ""),
				new County(new String[]{"Stark County", "Illinois", "United States"}, ""),
				new County(new String[]{"Stephenson County", "Illinois", "United States"}, ""),
				new County(new String[]{"Tazewell County", "Illinois", "United States"}, ""),
				new County(new String[]{"Union County", "Illinois", "United States"}, ""),
				new County(new String[]{"Vermilion County", "Illinois", "United States"}, ""),
				new County(new String[]{"Wabash County", "Illinois", "United States"}, ""),
				new County(new String[]{"Warren County", "Illinois", "United States"}, ""),
				new County(new String[]{"Washington County", "Illinois", "United States"}, ""),
				new County(new String[]{"Wayne County", "Illinois", "United States"}, ""),
				new County(new String[]{"White County", "Illinois", "United States"}, ""),
				new County(new String[]{"Whiteside County", "Illinois", "United States"}, ""),
				new County(new String[]{"Will County", "Illinois", "United States"}, ""),
				new County(new String[]{"Williamson County", "Illinois", "United States"}, ""),
				new County(new String[]{"Winnebago County", "Illinois", "United States"}, ""),
				new County(new String[]{"Woodford County", "Illinois", "United States"}, "")
			});
		
		ArrayList<PlaceStructure> indiana = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Adams County", "Indiana", "United States"}, ""),
				new County(new String[]{"Allen County", "Indiana", "United States"}, ""),
				new County(new String[]{"Bartholomew County", "Indiana", "United States"}, ""),
				new County(new String[]{"Benton County", "Indiana", "United States"}, ""),
				new County(new String[]{"Blackford County", "Indiana", "United States"}, ""),
				new County(new String[]{"Boone County", "Indiana", "United States"}, ""),
				new County(new String[]{"Brown County", "Indiana", "United States"}, ""),
				new County(new String[]{"Carroll County", "Indiana", "United States"}, ""),
				new County(new String[]{"Cass County", "Indiana", "United States"}, ""),
				new County(new String[]{"Clark County", "Indiana", "United States"}, ""),
				new County(new String[]{"Clay County", "Indiana", "United States"}, ""),
				new County(new String[]{"Clinton County", "Indiana", "United States"}, ""),
				new County(new String[]{"Crawford County", "Indiana", "United States"}, ""),
				new County(new String[]{"Daviess County", "Indiana", "United States"}, ""),
				new County(new String[]{"Dearborn County", "Indiana", "United States"}, ""),
				new County(new String[]{"Decatur County", "Indiana", "United States"}, ""),
				new County(new String[]{"DeKalb County", "Indiana", "United States"}, ""),
				new County(new String[]{"Delaware County", "Indiana", "United States"}, ""),
				new County(new String[]{"Dubois County", "Indiana", "United States"}, ""),
				new County(new String[]{"Elkhart County", "Indiana", "United States"}, ""),
				new County(new String[]{"Fayette County", "Indiana", "United States"}, ""),
				new County(new String[]{"Floyd County", "Indiana", "United States"}, ""),
				new County(new String[]{"Fountain County", "Indiana", "United States"}, ""),
				new County(new String[]{"Franklin County", "Indiana", "United States"}, ""),
				new County(new String[]{"Fulton County", "Indiana", "United States"}, ""),
				new County(new String[]{"Gibson County", "Indiana", "United States"}, ""),
				new County(new String[]{"Grant County", "Indiana", "United States"}, ""),
				new County(new String[]{"Greene County", "Indiana", "United States"}, ""),
				new County(new String[]{"Hamilton County", "Indiana", "United States"}, ""),
				new County(new String[]{"Hancock County", "Indiana", "United States"}, ""),
				new County(new String[]{"Harrison County", "Indiana", "United States"}, ""),
				new County(new String[]{"Hendricks County", "Indiana", "United States"}, ""),
				new County(new String[]{"Henry County", "Indiana", "United States"}, ""),
				new County(new String[]{"Howard County", "Indiana", "United States"}, ""),
				new County(new String[]{"Huntington County", "Indiana", "United States"}, ""),
				new County(new String[]{"Jackson County", "Indiana", "United States"}, ""),
				new County(new String[]{"Jasper County", "Indiana", "United States"}, ""),
				new County(new String[]{"Jay County", "Indiana", "United States"}, ""),
				new County(new String[]{"Jefferson County", "Indiana", "United States"}, ""),
				new County(new String[]{"Jennings County", "Indiana", "United States"}, ""),
				new County(new String[]{"Johnson County", "Indiana", "United States"}, ""),
				new County(new String[]{"Knox County", "Indiana", "United States"}, ""),
				new County(new String[]{"Kosciusko County", "Indiana", "United States"}, ""),
				new County(new String[]{"LaGrange County", "Indiana", "United States"}, ""),
				new County(new String[]{"Lake County", "Indiana", "United States"}, ""),
				new County(new String[]{"LaPorte County", "Indiana", "United States"}, ""),
				new County(new String[]{"Lawrence County", "Indiana", "United States"}, ""),
				new County(new String[]{"Madison County", "Indiana", "United States"}, ""),
				new County(new String[]{"Marion County", "Indiana", "United States"}, ""),
				new County(new String[]{"Marshall County", "Indiana", "United States"}, ""),
				new County(new String[]{"Martin County", "Indiana", "United States"}, ""),
				new County(new String[]{"Miami County", "Indiana", "United States"}, ""),
				new County(new String[]{"Monroe County", "Indiana", "United States"}, ""),
				new County(new String[]{"Montgomery County", "Indiana", "United States"}, ""),
				new County(new String[]{"Morgan County", "Indiana", "United States"}, ""),
				new County(new String[]{"Newton County", "Indiana", "United States"}, ""),
				new County(new String[]{"Noble County", "Indiana", "United States"}, ""),
				new County(new String[]{"Ohio County", "Indiana", "United States"}, ""),
				new County(new String[]{"Orange County", "Indiana", "United States"}, ""),
				new County(new String[]{"Owen County", "Indiana", "United States"}, ""),
				new County(new String[]{"Parke County", "Indiana", "United States"}, ""),
				new County(new String[]{"Perry County", "Indiana", "United States"}, ""),
				new County(new String[]{"Pike County", "Indiana", "United States"}, ""),
				new County(new String[]{"Porter County", "Indiana", "United States"}, ""),
				new County(new String[]{"Posey County", "Indiana", "United States"}, ""),
				new County(new String[]{"Pulaski County", "Indiana", "United States"}, ""),
				new County(new String[]{"Putnam County", "Indiana", "United States"}, ""),
				new County(new String[]{"Randolph County", "Indiana", "United States"}, ""),
				new County(new String[]{"Ripley County", "Indiana", "United States"}, ""),
				new County(new String[]{"Rush County", "Indiana", "United States"}, ""),
				new County(new String[]{"St. Joseph County", "Indiana", "United States"}, ""),
				new County(new String[]{"Scott County", "Indiana", "United States"}, ""),
				new County(new String[]{"Shelby County", "Indiana", "United States"}, ""),
				new County(new String[]{"Spencer County", "Indiana", "United States"}, ""),
				new County(new String[]{"Starke County", "Indiana", "United States"}, ""),
				new County(new String[]{"Steuben County", "Indiana", "United States"}, ""),
				new County(new String[]{"Sullivan County", "Indiana", "United States"}, ""),
				new County(new String[]{"Switzerland County", "Indiana", "United States"}, ""),
				new County(new String[]{"Tippecanoe County", "Indiana", "United States"}, ""),
				new County(new String[]{"Tipton County", "Indiana", "United States"}, ""),
				new County(new String[]{"Union County", "Indiana", "United States"}, ""),
				new County(new String[]{"Vanderburgh County", "Indiana", "United States"}, ""),
				new County(new String[]{"Vermillion County", "Indiana", "United States"}, ""),
				new County(new String[]{"Vigo County", "Indiana", "United States"}, ""),
				new County(new String[]{"Wabash County", "Indiana", "United States"}, ""),
				new County(new String[]{"Warren County", "Indiana", "United States"}, ""),
				new County(new String[]{"Warrick County", "Indiana", "United States"}, ""),
				new County(new String[]{"Washington County", "Indiana", "United States"}, ""),
				new County(new String[]{"Wayne County", "Indiana", "United States"}, ""),
				new County(new String[]{"Wells County", "Indiana", "United States"}, ""),
				new County(new String[]{"White County", "Indiana", "United States"}, ""),
				new County(new String[]{"Whitley County", "Indiana", "United States"}, "")
			});
		
		ArrayList<PlaceStructure> iowa = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Adair County", "Iowa", "United States"}, ""),
				new County(new String[]{"Adams County", "Iowa", "United States"}, ""),
				new County(new String[]{"Allamakee County", "Iowa", "United States"}, ""),
				new County(new String[]{"Appanoose County", "Iowa", "United States"}, ""),
				new County(new String[]{"Audubon County", "Iowa", "United States"}, ""),
				new County(new String[]{"Benton County", "Iowa", "United States"}, ""),
				new County(new String[]{"Black Hawk County", "Iowa", "United States"}, ""),
				new County(new String[]{"Boone County", "Iowa", "United States"}, ""),
				new County(new String[]{"Bremer County", "Iowa", "United States"}, ""),
				new County(new String[]{"Buchanan County", "Iowa", "United States"}, ""),
				new County(new String[]{"Buena Vista County", "Iowa", "United States"}, ""),
				new County(new String[]{"Butler County", "Iowa", "United States"}, ""),
				new County(new String[]{"Calhoun County", "Iowa", "United States"}, ""),
				new County(new String[]{"Carroll County", "Iowa", "United States"}, ""),
				new County(new String[]{"Cass County", "Iowa", "United States"}, ""),
				new County(new String[]{"Cedar County", "Iowa", "United States"}, ""),
				new County(new String[]{"Cerro Gordo County", "Iowa", "United States"}, ""),
				new County(new String[]{"Cherokee County", "Iowa", "United States"}, ""),
				new County(new String[]{"Chickasaw County", "Iowa", "United States"}, ""),
				new County(new String[]{"Clarke County", "Iowa", "United States"}, ""),
				new County(new String[]{"Clay County", "Iowa", "United States"}, ""),
				new County(new String[]{"Clayton County", "Iowa", "United States"}, ""),
				new County(new String[]{"Clinton County", "Iowa", "United States"}, ""),
				new County(new String[]{"Crawford County", "Iowa", "United States"}, ""),
				new County(new String[]{"Dallas County", "Iowa", "United States"}, ""),
				new County(new String[]{"Davis County", "Iowa", "United States"}, ""),
				new County(new String[]{"Decatur County", "Iowa", "United States"}, ""),
				new County(new String[]{"Delaware County", "Iowa", "United States"}, ""),
				new County(new String[]{"Des Moines County", "Iowa", "United States"}, ""),
				new County(new String[]{"Dickinson County", "Iowa", "United States"}, ""),
				new County(new String[]{"Dubuque County", "Iowa", "United States"}, ""),
				new County(new String[]{"Emmet County", "Iowa", "United States"}, ""),
				new County(new String[]{"Fayette County", "Iowa", "United States"}, ""),
				new County(new String[]{"Floyd County", "Iowa", "United States"}, ""),
				new County(new String[]{"Franklin County", "Iowa", "United States"}, ""),
				new County(new String[]{"Fremont County", "Iowa", "United States"}, ""),
				new County(new String[]{"Greene County", "Iowa", "United States"}, ""),
				new County(new String[]{"Grundy County", "Iowa", "United States"}, ""),
				new County(new String[]{"Guthrie County", "Iowa", "United States"}, ""),
				new County(new String[]{"Hamilton County", "Iowa", "United States"}, ""),
				new County(new String[]{"Hancock County", "Iowa", "United States"}, ""),
				new County(new String[]{"Hardin County", "Iowa", "United States"}, ""),
				new County(new String[]{"Harrison County", "Iowa", "United States"}, ""),
				new County(new String[]{"Henry County", "Iowa", "United States"}, ""),
				new County(new String[]{"Howard County", "Iowa", "United States"}, ""),
				new County(new String[]{"Humboldt County", "Iowa", "United States"}, ""),
				new County(new String[]{"Ida County", "Iowa", "United States"}, ""),
				new County(new String[]{"Iowa County", "Iowa", "United States"}, ""),
				new County(new String[]{"Jackson County", "Iowa", "United States"}, ""),
				new County(new String[]{"Jasper County", "Iowa", "United States"}, ""),
				new County(new String[]{"Jefferson County", "Iowa", "United States"}, ""),
				new County(new String[]{"Johnson County", "Iowa", "United States"}, ""),
				new County(new String[]{"Jones County", "Iowa", "United States"}, ""),
				new County(new String[]{"Keokuk County", "Iowa", "United States"}, ""),
				new County(new String[]{"Kossuth County", "Iowa", "United States"}, ""),
				new County(new String[]{"Lee County", "Iowa", "United States"}, ""),
				new County(new String[]{"Linn County", "Iowa", "United States"}, ""),
				new County(new String[]{"Louisa County", "Iowa", "United States"}, ""),
				new County(new String[]{"Lucas County", "Iowa", "United States"}, ""),
				new County(new String[]{"Lyon County", "Iowa", "United States"}, ""),
				new County(new String[]{"Madison County", "Iowa", "United States"}, ""),
				new County(new String[]{"Mahaska County", "Iowa", "United States"}, ""),
				new County(new String[]{"Marion County", "Iowa", "United States"}, ""),
				new County(new String[]{"Marshall County", "Iowa", "United States"}, ""),
				new County(new String[]{"Mills County", "Iowa", "United States"}, ""),
				new County(new String[]{"Mitchell County", "Iowa", "United States"}, ""),
				new County(new String[]{"Monona County", "Iowa", "United States"}, ""),
				new County(new String[]{"Monroe County", "Iowa", "United States"}, ""),
				new County(new String[]{"Montgomery County", "Iowa", "United States"}, ""),
				new County(new String[]{"Muscatine County", "Iowa", "United States"}, ""),
				new County(new String[]{"O''Brien County", "Iowa", "United States"}, ""),
				new County(new String[]{"Osceola County", "Iowa", "United States"}, ""),
				new County(new String[]{"Page County", "Iowa", "United States"}, ""),
				new County(new String[]{"Palo Alto County", "Iowa", "United States"}, ""),
				new County(new String[]{"Plymouth County", "Iowa", "United States"}, ""),
				new County(new String[]{"Pocahontas County", "Iowa", "United States"}, ""),
				new County(new String[]{"Polk County", "Iowa", "United States"}, ""),
				new County(new String[]{"Pottawattamie County", "Iowa", "United States"}, ""),
				new County(new String[]{"Poweshiek County", "Iowa", "United States"}, ""),
				new County(new String[]{"Ringgold County", "Iowa", "United States"}, ""),
				new County(new String[]{"Sac County", "Iowa", "United States"}, ""),
				new County(new String[]{"Scott County", "Iowa", "United States"}, ""),
				new County(new String[]{"Shelby County", "Iowa", "United States"}, ""),
				new County(new String[]{"Sioux County", "Iowa", "United States"}, ""),
				new County(new String[]{"Story County", "Iowa", "United States"}, ""),
				new County(new String[]{"Tama County", "Iowa", "United States"}, ""),
				new County(new String[]{"Taylor County", "Iowa", "United States"}, ""),
				new County(new String[]{"Union County", "Iowa", "United States"}, ""),
				new County(new String[]{"Van Buren County", "Iowa", "United States"}, ""),
				new County(new String[]{"Wapello County", "Iowa", "United States"}, ""),
				new County(new String[]{"Warren County", "Iowa", "United States"}, ""),
				new County(new String[]{"Washington County", "Iowa", "United States"}, ""),
				new County(new String[]{"Wayne County", "Iowa", "United States"}, ""),
				new County(new String[]{"Webster County", "Iowa", "United States"}, ""),
				new County(new String[]{"Winnebago County", "Iowa", "United States"}, ""),
				new County(new String[]{"Winneshiek County", "Iowa", "United States"}, ""),
				new County(new String[]{"Woodbury County", "Iowa", "United States"}, ""),
				new County(new String[]{"Worth County", "Iowa", "United States"}, ""),
				new County(new String[]{"Wright County", "Iowa", "United States"}, "")
			});
		
		ArrayList<PlaceStructure> kansas = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Allen County", "Kansas", "United States"}, ""),
				new County(new String[]{"Anderson County", "Kansas", "United States"}, ""),
				new County(new String[]{"Atchison County", "Kansas", "United States"}, ""),
				new County(new String[]{"Barber County", "Kansas", "United States"}, ""),
				new County(new String[]{"Barton County", "Kansas", "United States"}, ""),
				new County(new String[]{"Bourbon County", "Kansas", "United States"}, ""),
				new County(new String[]{"Brown County", "Kansas", "United States"}, ""),
				new County(new String[]{"Butler County", "Kansas", "United States"}, ""),
				new County(new String[]{"Chase County", "Kansas", "United States"}, ""),
				new County(new String[]{"Chautauqua County", "Kansas", "United States"}, ""),
				new County(new String[]{"Cherokee County", "Kansas", "United States"}, ""),
				new County(new String[]{"Cheyenne County", "Kansas", "United States"}, ""),
				new County(new String[]{"Clark County", "Kansas", "United States"}, ""),
				new County(new String[]{"Clay County", "Kansas", "United States"}, ""),
				new County(new String[]{"Cloud County", "Kansas", "United States"}, ""),
				new County(new String[]{"Coffey County", "Kansas", "United States"}, ""),
				new County(new String[]{"Comanche County", "Kansas", "United States"}, ""),
				new County(new String[]{"Cowley County", "Kansas", "United States"}, ""),
				new County(new String[]{"Crawford County", "Kansas", "United States"}, ""),
				new County(new String[]{"Decatur County", "Kansas", "United States"}, ""),
				new County(new String[]{"Dickinson County", "Kansas", "United States"}, ""),
				new County(new String[]{"Doniphan County", "Kansas", "United States"}, ""),
				new County(new String[]{"Douglas County", "Kansas", "United States"}, ""),
				new County(new String[]{"Edwards County", "Kansas", "United States"}, ""),
				new County(new String[]{"Elk County", "Kansas", "United States"}, ""),
				new County(new String[]{"Ellis County", "Kansas", "United States"}, ""),
				new County(new String[]{"Ellsworth County", "Kansas", "United States"}, ""),
				new County(new String[]{"Finney County", "Kansas", "United States"}, ""),
				new County(new String[]{"Ford County", "Kansas", "United States"}, ""),
				new County(new String[]{"Franklin County", "Kansas", "United States"}, ""),
				new County(new String[]{"Geary County", "Kansas", "United States"}, ""),
				new County(new String[]{"Gove County", "Kansas", "United States"}, ""),
				new County(new String[]{"Graham County", "Kansas", "United States"}, ""),
				new County(new String[]{"Grant County", "Kansas", "United States"}, ""),
				new County(new String[]{"Gray County", "Kansas", "United States"}, ""),
				new County(new String[]{"Greeley County", "Kansas", "United States"}, ""),
				new County(new String[]{"Greenwood County", "Kansas", "United States"}, ""),
				new County(new String[]{"Hamilton County", "Kansas", "United States"}, ""),
				new County(new String[]{"Harper County", "Kansas", "United States"}, ""),
				new County(new String[]{"Harvey County", "Kansas", "United States"}, ""),
				new County(new String[]{"Haskell County", "Kansas", "United States"}, ""),
				new County(new String[]{"Hodgeman County", "Kansas", "United States"}, ""),
				new County(new String[]{"Jackson County", "Kansas", "United States"}, ""),
				new County(new String[]{"Jefferson County", "Kansas", "United States"}, ""),
				new County(new String[]{"Jewell County", "Kansas", "United States"}, ""),
				new County(new String[]{"Johnson County", "Kansas", "United States"}, ""),
				new County(new String[]{"Kearny County", "Kansas", "United States"}, ""),
				new County(new String[]{"Kingman County", "Kansas", "United States"}, ""),
				new County(new String[]{"Kiowa County", "Kansas", "United States"}, ""),
				new County(new String[]{"Labette County", "Kansas", "United States"}, ""),
				new County(new String[]{"Lane County", "Kansas", "United States"}, ""),
				new County(new String[]{"Leavenworth County", "Kansas", "United States"}, ""),
				new County(new String[]{"Lincoln County", "Kansas", "United States"}, ""),
				new County(new String[]{"Linn County", "Kansas", "United States"}, ""),
				new County(new String[]{"Logan County", "Kansas", "United States"}, ""),
				new County(new String[]{"Lyon County", "Kansas", "United States"}, ""),
				new County(new String[]{"Marion County", "Kansas", "United States"}, ""),
				new County(new String[]{"Marshall County", "Kansas", "United States"}, ""),
				new County(new String[]{"McPherson County", "Kansas", "United States"}, ""),
				new County(new String[]{"Meade County", "Kansas", "United States"}, ""),
				new County(new String[]{"Miami County", "Kansas", "United States"}, ""),
				new County(new String[]{"Mitchell County", "Kansas", "United States"}, ""),
				new County(new String[]{"Montgomery County", "Kansas", "United States"}, ""),
				new County(new String[]{"Morris County", "Kansas", "United States"}, ""),
				new County(new String[]{"Morton County", "Kansas", "United States"}, ""),
				new County(new String[]{"Nemaha County", "Kansas", "United States"}, ""),
				new County(new String[]{"Neosho County", "Kansas", "United States"}, ""),
				new County(new String[]{"Ness County", "Kansas", "United States"}, ""),
				new County(new String[]{"Norton County", "Kansas", "United States"}, ""),
				new County(new String[]{"Osage County", "Kansas", "United States"}, ""),
				new County(new String[]{"Osborne County", "Kansas", "United States"}, ""),
				new County(new String[]{"Ottawa County", "Kansas", "United States"}, ""),
				new County(new String[]{"Pawnee County", "Kansas", "United States"}, ""),
				new County(new String[]{"Phillips County", "Kansas", "United States"}, ""),
				new County(new String[]{"Pottawatomie County", "Kansas", "United States"}, ""),
				new County(new String[]{"Pratt County", "Kansas", "United States"}, ""),
				new County(new String[]{"Rawlins County", "Kansas", "United States"}, ""),
				new County(new String[]{"Reno County", "Kansas", "United States"}, ""),
				new County(new String[]{"Republic County", "Kansas", "United States"}, ""),
				new County(new String[]{"Rice County", "Kansas", "United States"}, ""),
				new County(new String[]{"Riley County", "Kansas", "United States"}, ""),
				new County(new String[]{"Rooks County", "Kansas", "United States"}, ""),
				new County(new String[]{"Rush County", "Kansas", "United States"}, ""),
				new County(new String[]{"Russell County", "Kansas", "United States"}, ""),
				new County(new String[]{"Saline County", "Kansas", "United States"}, ""),
				new County(new String[]{"Scott County", "Kansas", "United States"}, ""),
				new County(new String[]{"Sedgwick County", "Kansas", "United States"}, ""),
				new County(new String[]{"Seward County", "Kansas", "United States"}, ""),
				new County(new String[]{"Shawnee County", "Kansas", "United States"}, ""),
				new County(new String[]{"Sheridan County", "Kansas", "United States"}, ""),
				new County(new String[]{"Sherman County", "Kansas", "United States"}, ""),
				new County(new String[]{"Smith County", "Kansas", "United States"}, ""),
				new County(new String[]{"Stafford County", "Kansas", "United States"}, ""),
				new County(new String[]{"Stanton County", "Kansas", "United States"}, ""),
				new County(new String[]{"Stevens County", "Kansas", "United States"}, ""),
				new County(new String[]{"Sumner County", "Kansas", "United States"}, ""),
				new County(new String[]{"Thomas County", "Kansas", "United States"}, ""),
				new County(new String[]{"Trego County", "Kansas", "United States"}, ""),
				new County(new String[]{"Wabaunsee County", "Kansas", "United States"}, ""),
				new County(new String[]{"Wallace County", "Kansas", "United States"}, ""),
				new County(new String[]{"Washington County", "Kansas", "United States"}, ""),
				new County(new String[]{"Wichita County", "Kansas", "United States"}, ""),
				new County(new String[]{"Wilson County", "Kansas", "United States"}, ""),
				new County(new String[]{"Woodson County", "Kansas", "United States"}, ""),
				new County(new String[]{"Wyandotte County", "Kansas", "United States"}, "")
			});
		
		ArrayList<PlaceStructure> kentucky = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Adair County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Allen County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Anderson County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Ballard County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Barren County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Bath County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Bell County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Boone County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Bourbon County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Boyd County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Boyle County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Bracken County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Breathitt County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Breckinridge County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Bullitt County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Butler County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Caldwell County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Calloway County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Campbell County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Carlisle County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Carroll County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Carter County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Casey County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Christian County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Clark County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Clay County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Clinton County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Crittenden County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Cumberland County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Daviess County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Edmonson County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Elliott County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Estill County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Fayette County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Fleming County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Floyd County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Franklin County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Fulton County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Gallatin County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Garrard County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Grant County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Graves County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Grayson County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Green County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Greenup County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Hancock County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Hardin County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Harlan County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Harrison County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Hart County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Henderson County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Henry County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Hickman County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Hopkins County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Jackson County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Jefferson County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Jessamine County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Johnson County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Kenton County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Knott County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Knox County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Larue County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Laurel County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Lawrence County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Lee County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Leslie County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Letcher County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Lewis County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Lincoln County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Livingston County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Logan County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Lyon County", "Kentucky", "United States"}, ""),
				new County(new String[]{"McCracken County", "Kentucky", "United States"}, ""),
				new County(new String[]{"McCreary County", "Kentucky", "United States"}, ""),
				new County(new String[]{"McLean County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Madison County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Magoffin County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Marion County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Marshall County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Martin County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Mason County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Meade County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Menifee County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Mercer County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Metcalfe County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Monroe County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Montgomery County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Morgan County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Muhlenberg County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Nelson County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Nicholas County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Ohio County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Oldham County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Owen County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Owsley County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Pendleton County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Perry County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Pike County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Powell County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Pulaski County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Robertson County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Rockcastle County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Rowan County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Russell County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Scott County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Shelby County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Simpson County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Spencer County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Taylor County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Todd County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Trigg County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Trimble County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Union County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Warren County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Washington County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Wayne County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Webster County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Whitley County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Wolfe County", "Kentucky", "United States"}, ""),
				new County(new String[]{"Woodford County", "Kentucky", "United States"}, "")
			});
		
		ArrayList<PlaceStructure> list = new ArrayList<PlaceStructure>();
		list = Util.arrayList(list, alabama);
		list = Util.arrayList(list, alaska);
		list = Util.arrayList(list, arizona);
		list = Util.arrayList(list, americanSamoa);
		list = Util.arrayList(list, arkansas);
		list = Util.arrayList(list, california);
		list = Util.arrayList(list, colorado);
		list = Util.arrayList(list, connecticut);
		list = Util.arrayList(list, delaware);
		list = Util.arrayList(list, florida);
		list = Util.arrayList(list, georgia);
		list = Util.arrayList(list, guam);
		list = Util.arrayList(list, hawaii);
		list = Util.arrayList(list, idaho);
		list = Util.arrayList(list, illinois);
		list = Util.arrayList(list, indiana);
		list = Util.arrayList(list, iowa);
		list = Util.arrayList(list, kansas);
		list = Util.arrayList(list, kentucky);
		return list;
	}
}
