package ws.daley.genealogy.db.places;

import java.util.ArrayList;

import ws.daley.genealogy.db.places.abstrct.PlaceStructure;
import ws.daley.genealogy.util.Util;

public class CountyCanada
{
	public static ArrayList<PlaceStructure> canada()
	{
		ArrayList<PlaceStructure> alberta = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Acadia", "Alberta", "Canada"}, ""),
				new County(new String[]{"Athabasca", "Alberta", "Canada"}, ""),
				new County(new String[]{"Banff", "Alberta", "Canada"}, ""),
				new County(new String[]{"Barrhead", "Alberta", "Canada"}, ""),
				new County(new String[]{"Beaver", "Alberta", "Canada"}, ""),
				new County(new String[]{"Big Lakes", "Alberta", "Canada"}, ""),
				new County(new String[]{"Bighorn", "Alberta", "Canada"}, ""),
				new County(new String[]{"Birch Hills", "Alberta", "Canada"}, ""),
				new County(new String[]{"Bonnyville", "Alberta", "Canada"}, ""),
				new County(new String[]{"Brazeau", "Alberta", "Canada"}, ""),
				new County(new String[]{"Calgary", "Alberta", "Canada"}, ""),
				new County(new String[]{"Camrose", "Alberta", "Canada"}, ""),
				new County(new String[]{"Cardston", "Alberta", "Canada"}, ""),
				new County(new String[]{"Clear Hills", "Alberta", "Canada"}, ""),
				new County(new String[]{"Clearwater", "Alberta", "Canada"}, ""),
				new County(new String[]{"Crowsnest Pass", "Alberta", "Canada"}, ""),
				new County(new String[]{"Cypress", "Alberta", "Canada"}, ""),
				new County(new String[]{"Edmonton", "Alberta", "Canada"}, ""),
				new County(new String[]{"Elk Island", "Alberta", "Canada"}, ""),
				new County(new String[]{"Fairview", "Alberta", "Canada"}, ""),
				new County(new String[]{"Flagstaff", "Alberta", "Canada"}, ""),
				new County(new String[]{"Foothills", "Alberta", "Canada"}, ""),
				new County(new String[]{"Forty Mile", "Alberta", "Canada"}, ""),
				new County(new String[]{"Grande Prairie", "Alberta", "Canada"}, ""),
				new County(new String[]{"Greenview", "Alberta", "Canada"}, ""),
				new County(new String[]{"Jasper", "Alberta", "Canada"}, ""),
				new County(new String[]{"Kananaskis", "Alberta", "Canada"}, ""),
				new County(new String[]{"Kneehill", "Alberta", "Canada"}, ""),
				new County(new String[]{"Lac La Biche", "Alberta", "Canada"}, ""),
				new County(new String[]{"Lac Ste. Anne", "Alberta", "Canada"}, ""),
				new County(new String[]{"Lacombe", "Alberta", "Canada"}, ""),
				new County(new String[]{"Lamont", "Alberta", "Canada"}, ""),
				new County(new String[]{"Leduc", "Alberta", "Canada"}, ""),
				new County(new String[]{"Lesser Slave River", "Alberta", "Canada"}, ""),
				new County(new String[]{"Lethbridge", "Alberta", "Canada"}, ""),
				new County(new String[]{"Mackenzie", "Alberta", "Canada"}, ""),
				new County(new String[]{"Minburn", "Alberta", "Canada"}, ""),
				new County(new String[]{"Mountain View", "Alberta", "Canada"}, ""),
				new County(new String[]{"Newell", "Alberta", "Canada"}, ""),
				new County(new String[]{"Northern Lights", "Alberta", "Canada"}, ""),
				new County(new String[]{"Northern Sunrise", "Alberta", "Canada"}, ""),
				new County(new String[]{"Opportunity", "Alberta", "Canada"}, ""),
				new County(new String[]{"Paintearth", "Alberta", "Canada"}, ""),
				new County(new String[]{"Parkland", "Alberta", "Canada"}, ""),
				new County(new String[]{"Peace", "Alberta", "Canada"}, ""),
				new County(new String[]{"Pincher Creek", "Alberta", "Canada"}, ""),
				new County(new String[]{"Ponoka", "Alberta", "Canada"}, ""),
				new County(new String[]{"Provost", "Alberta", "Canada"}, ""),
				new County(new String[]{"Ranchland", "Alberta", "Canada"}, ""),
				new County(new String[]{"Red Deer", "Alberta", "Canada"}, ""),
				new County(new String[]{"Rocky View", "Alberta", "Canada"}, ""),
				new County(new String[]{"Saddle Hills", "Alberta", "Canada"}, ""),
				new County(new String[]{"Smoky Lake", "Alberta", "Canada"}, ""),
				new County(new String[]{"Special Areas", "Alberta", "Canada"}, ""),
				new County(new String[]{"Spirit River", "Alberta", "Canada"}, ""),
				new County(new String[]{"St. Paul", "Alberta", "Canada"}, ""),
				new County(new String[]{"Starland", "Alberta", "Canada"}, ""),
				new County(new String[]{"Stettler", "Alberta", "Canada"}, ""),
				new County(new String[]{"Strathcona", "Alberta", "Canada"}, ""),
				new County(new String[]{"Sturgeon", "Alberta", "Canada"}, ""),
				new County(new String[]{"Taber", "Alberta", "Canada"}, ""),
				new County(new String[]{"Thorhild", "Alberta", "Canada"}, ""),
				new County(new String[]{"Two Hills", "Alberta", "Canada"}, ""),
				new County(new String[]{"Vermilion River", "Alberta", "Canada"}, ""),
				new County(new String[]{"Vulcan", "Alberta", "Canada"}, ""),
				new County(new String[]{"Wainwright", "Alberta", "Canada"}, ""),
				new County(new String[]{"Warner", "Alberta", "Canada"}, ""),
				new County(new String[]{"Waterton Lakes", "Alberta", "Canada"}, ""),
				new County(new String[]{"Westlock", "Alberta", "Canada"}, ""),
				new County(new String[]{"Wetaskiwin", "Alberta", "Canada"}, ""),
				new County(new String[]{"Willmore Wilderness", "Alberta", "Canada"}, ""),
				new County(new String[]{"Willow Creek", "Alberta", "Canada"}, ""),
				new County(new String[]{"Wood Buffalo", "Alberta", "Canada"}, ""),
				new County(new String[]{"Woodlands", "Alberta", "Canada"}, ""),
				new County(new String[]{"Yellowhead", "Alberta", "Canada"}, "")
			});
		
		ArrayList<PlaceStructure> britishColumbia = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Abbotsford", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Alert Bay", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Anmore", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Armstrong", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Ashcroft", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Barriere", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Belcarra", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Bowen Island", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Burnaby", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Burns Lake", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Cache Creek", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Campbell River", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Canal Flats", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Cariboo", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Castlegar", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Central Saanich", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Chase", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Chetwynd", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Chilliwack", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Clearwater", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Clinton", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Coldstream", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Colwood", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Comox", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Coquitlam", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Courtenay", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Cranbrook", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Creston", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Cumberland", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Dawson Creek", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Delta", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Duncan", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Elkford", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Enderby", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Esquimalt", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Fernie", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Fort Nelson", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Fort St. James", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Fort St. John", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Fraser Lake", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Fruitvale", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Gibsons", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Gold River", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Golden", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Grand Forks", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Granisle", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Greenwood", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Harrison Hot Springs", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Hazelton", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Highlands", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Hope", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Houston", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Hudson''s Hope", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Invermere", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Kamloops", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Kaslo", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Kelowna", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Kent", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Keremeos", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Kimberley", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Kitimat", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Kootenay", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Ladysmith", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Lake XlsCountry", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Lake Cowichan", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Langford", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Langley", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Lantzville", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Lillooet", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Lions Bay", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Logan Lake", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Lumby", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Lytton", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Mackenzie", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Maple Ridge", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Masset", "British Columbia", "Canada"}, ""),
				new County(new String[]{"McBride", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Merritt", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Metchosin", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Midway", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Mission", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Montrose", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Nakusp", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Nanaimo", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Nelson", "British Columbia", "Canada"}, ""),
				new County(new String[]{"New Denver", "British Columbia", "Canada"}, ""),
				new County(new String[]{"New Hazelton", "British Columbia", "Canada"}, ""),
				new County(new String[]{"New Westminster", "British Columbia", "Canada"}, ""),
				new County(new String[]{"North Cowichan", "British Columbia", "Canada"}, ""),
				new County(new String[]{"North Saanich", "British Columbia", "Canada"}, ""),
				new County(new String[]{"North Vancouver", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Oak Bay", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Oliver", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Osoyoos", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Parksville", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Peachland", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Pemberton", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Penticton", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Pitt Meadows", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Port Alberni", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Port Alice", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Port Clements", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Port Coquitlam", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Port Edward", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Port Hardy", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Port McNeill", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Port Moody", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Pouce Coupe", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Powell River", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Prince George", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Prince Rupert", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Princeton", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Qualicum Beach", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Queen Charlotte", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Quesnel", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Radium Hot Springs", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Revelstoke", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Richmond", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Rossland", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Saanich", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Salmo", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Salmon Arm", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Sayward", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Sechelt", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Sicamous", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Sidney", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Silverton", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Slocan", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Smithers", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Sooke", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Spallumcheen", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Sparwood", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Squamish", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Stewart", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Summerland", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Surrey", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Tahsis", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Taylor", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Telkwa", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Terrace", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Tofino", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Trail", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Tumbler Ridge", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Ucluelet", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Valemount", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Vancouver", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Vanderhoof", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Vernon", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Victoria", "British Columbia", "Canada"}, ""),
				new County(new String[]{"View Royal", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Warfield", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Wells", "British Columbia", "Canada"}, ""),
				new County(new String[]{"West Vancouver", "British Columbia", "Canada"}, ""),
				new County(new String[]{"West Kelowna", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Westminster", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Whistler", "British Columbia", "Canada"}, ""),
				new County(new String[]{"White Rock", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Williams Lake", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Yale", "British Columbia", "Canada"}, ""),
				new County(new String[]{"Zeballos", "British Columbia", "Canada"}, ""),
				new County(new String[]{"100 Mile House", "British Columbia", "Canada"}, "")
			});
		
		ArrayList<PlaceStructure> manitoba = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Albert", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Alexander", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Alonsa", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Archie", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Argyle", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Armstrong", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Arthur", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Beausejour Area", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Bifrost", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Binscarth", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Birtle", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Blanshard", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Brandon Area", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Brenda", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Brokenhead", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Cameron", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Cartier", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Central Plains Region", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Central Manitoba", "Manitoba", "Canada"}, ""),
				new County(new String[]{"City of Winnipeg", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Churchill/Northern Manitoba", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Clanwilliam", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Coldwell", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Cornwallis", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Dauphin", "Manitoba", "Canada"}, ""),
				new County(new String[]{"DeSalaberry", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Dufferin", "Manitoba", "Canada"}, ""),
				new County(new String[]{"East St. Paul", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Eastern Manitoba", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Eastman", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Eastman Region", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Edward", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Ellice", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Eriksdale", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Ethelbert", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Fisher", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Flin Flon/North West", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Franklin", "Manitoba", "Canada"}, ""),
				new County(new String[]{"GilbertPlains", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Gimli", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Glenella", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Glenwood", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Grahamdale", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Grandview", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Grey", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Hamiota", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Hanover", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Harrison", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Headingley", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Hillsburg", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Interlake", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Interlake Region", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Kelsey", "Manitoba", "Canada"}, ""),
				new County(new String[]{"La Broquerie", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Lac du Bonnet", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Lakeview", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Langford", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Lansdowne", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Lawrence", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Lorne", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Louise", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Macdonald", "Manitoba", "Canada"}, ""),
				new County(new String[]{"McCreary", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Miniota", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Minitonas", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Minto", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Montcalm", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Morris", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Morton", "Manitoba", "Canada"}, ""),
				new County(new String[]{"MosseyRiver", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Mountain", "Manitoba", "Canada"}, ""),
				new County(new String[]{"North East Man", "Manitoba", "Canada"}, ""),
				new County(new String[]{"North Interlake", "Manitoba", "Canada"}, ""),
				new County(new String[]{"North Cypress", "Manitoba", "Canada"}, ""),
				new County(new String[]{"North Norfolk", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Northern", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Oakland", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Ochre River", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Odanah", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Park", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Parkland", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Pembina Valley", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Pilot Mound Area", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Piney", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Pipestone", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Portage la Prairie Area", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Reynolds", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Rhineland", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Ritchot", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Riverside", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Roblin", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Rockwood", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Roland", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Rosedale", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Rossburn", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Rosser", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Russell", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Saskatchewan", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Selkirk Area", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Shell River", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Shelmouth-Boulton", "Manitoba", "Canada"}, ""),
				new County(new String[]{"ShoalLake", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Sifton", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Siglunes", "Manitoba", "Canada"}, ""),
				new County(new String[]{"SilverCreek", "Manitoba", "Canada"}, ""),
				new County(new String[]{"South Cypress", "Manitoba", "Canada"}, ""),
				new County(new String[]{"South Interlake", "Manitoba", "Canada"}, ""),
				new County(new String[]{"South Norfolk", "Manitoba", "Canada"}, ""),
				new County(new String[]{"South West", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Springfield", "Manitoba", "Canada"}, ""),
				new County(new String[]{"St. Andrews", "Manitoba", "Canada"}, ""),
				new County(new String[]{"St. Clements", "Manitoba", "Canada"}, ""),
				new County(new String[]{"St. François Xavier", "Manitoba", "Canada"}, ""),
				new County(new String[]{"St. Laurent", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Ste. Anne", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Ste. Rose", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Stanley", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Steinbach Area", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Stonewall", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Strathclair", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Strathcona", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Stuartburn", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Swan River", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Swan Valley", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Taché", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Thompson/North Central", "Manitoba", "Canada"}, ""),
				new County(new String[]{"TurtleMountain", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Victoria", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Victoria Beach", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Virden Area", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Wallace", "Manitoba", "Canada"}, ""),
				new County(new String[]{"West St. Paul", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Westbourne", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Western Manitoba", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Westman", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Whitehead", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Whitehorse Plains", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Whitemouth", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Whitewater", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Winchester", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Winnipeg Capital Region", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Winnipeg census division", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Woodlands", "Manitoba", "Canada"}, ""),
				new County(new String[]{"Woodworth", "Manitoba", "Canada"}, ""),
			});
		
		ArrayList<PlaceStructure> newBrunswick = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Alma", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Aroostook", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Atholville", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Baker-Brook", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Balmoral", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Bas-Caraquet", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Bath", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Bathurst", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Beaubassin-Est", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Belledune", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Beresford", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Bertrand", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Blacks Harbour", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Blackville", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Bouctouche", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Cambridge-Narrows", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Campbellton", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Canterbury", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Cap-Pele", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Caraquet", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Centreville", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Charlo", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Chipman", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Clair", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Dalhousie", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Dieppe", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Doaktown", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Dorchester", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Drummond", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Edmundston", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Eel River Crossing", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Florenceville-Bristol", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Fredericton Junction", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Gagetown", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Grand Manan", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Grand Bay-Westfield", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Grand Falls/Grand-Sault", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Grande-Anse", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Hampton", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Hartland", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Harvey Station (York)", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Hillsborough", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Kedgwick", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Lac-Baker", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Lameque", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"LeGoulet", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Maisonette", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"McAdam", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Meductic", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Memramcook", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Millville", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Minto", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Miramichi", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Moncton", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Nackawic", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Neguac", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"New Maryland", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Nigadoo", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Norton", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Oromocto", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Paquetville", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Perth-Andover", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Petitcodiac", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Petit-Rocher", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Plaster Rock", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Pointe-Verte", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Port Elgin", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Quispamsis", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Rexton", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Richibucto", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Riverside-Albert", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Riverview", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Riviere-Verte", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Rogersville", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Rothesay", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Sackville", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Saint John", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Saint Martins", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Saint-Leonard", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Salisbury", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Shediac", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Shippagan", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"St. Andrews", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"St. George", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"St. uentin", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"St. Stephen", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"St-Andre", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"St-Antoine", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"St-Francois-de-Madawaska", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"St-Hilaire", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"St-Isidore", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"St-Leolin", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"St-Louis-de-Kent", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Stanley", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Ste-Anne-de-Madawaska", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Ste-Marie-St-Raphael", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Stonehaven", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Sussex Corner", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Sussex", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Tide Head", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Tracadie-Sheila", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Tracy", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Upper Miramichi", "New Brunswick", "Canada"}, ""),
				new County(new String[]{"Woodstock", "New Brunswick", "Canada"}, "")
			});
		
		ArrayList<PlaceStructure> newfoundland = Util.arrayList(new PlaceStructure[]{
//				new County(new String[]{"Newfoundland and Labrador", "Canada"}, ""),
			});
		
		ArrayList<PlaceStructure> northwestTerritories = Util.arrayList(new PlaceStructure[]{
//				new County(new String[]{"Northwest Territories", "Canada"}, ""),
			});
		
		ArrayList<PlaceStructure> novaScotia = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Annapolis County", "Nova Scotia", "Canada"}, ""),
				new County(new String[]{"Antigonish County", "Nova Scotia", "Canada"}, ""),
				new County(new String[]{"Cape Breton County", "Nova Scotia", "Canada"}, ""),
				new County(new String[]{"Colchester County", "Nova Scotia", "Canada"}, ""),
				new County(new String[]{"Cumberland County", "Nova Scotia", "Canada"}, ""),
				new County(new String[]{"Digby County", "Nova Scotia", "Canada"}, ""),
				new County(new String[]{"Guysborough County", "Nova Scotia", "Canada"}, ""),
				new County(new String[]{"Halifax County", "Nova Scotia", "Canada"}, ""),
				new County(new String[]{"Hants County", "Nova Scotia", "Canada"}, ""),
				new County(new String[]{"Inverness County", "Nova Scotia", "Canada"}, ""),
				new County(new String[]{"Kings County", "Nova Scotia", "Canada"}, ""),
				new County(new String[]{"Lunenburg County", "Nova Scotia", "Canada"}, ""),
				new County(new String[]{"Pictou County", "Nova Scotia", "Canada"}, ""),
				new County(new String[]{"Queens County", "Nova Scotia", "Canada"}, ""),
				new County(new String[]{"Richmond County", "Nova Scotia", "Canada"}, ""),
				new County(new String[]{"Shelburne County", "Nova Scotia", "Canada"}, ""),
				new County(new String[]{"Victoria County", "Nova Scotia", "Canada"}, ""),
				new County(new String[]{"Yarmouth County", "Nova Scotia", "Canada"}, ""),
			});
		
		ArrayList<PlaceStructure> nunavut = Util.arrayList(new PlaceStructure[]{
//				new County(new String[]{"NUNAVUT", "CANADA"}, ""),
			});
		
		ArrayList<PlaceStructure> ontario = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Algoma", "Ontario", "Canada"}, ""),
				new County(new String[]{"Brant", "Ontario", "Canada"}, ""),
				new County(new String[]{"Bruce", "Ontario", "Canada"}, ""),
				new County(new String[]{"Chatham-Kent", "Ontario", "Canada"}, ""),
				new County(new String[]{"Cochrane", "Ontario", "Canada"}, ""),
				new County(new String[]{"Dufferin", "Ontario", "Canada"}, ""),
				new County(new String[]{"Durham", "Ontario", "Canada"}, ""),
				new County(new String[]{"Elgin", "Ontario", "Canada"}, ""),
				new County(new String[]{"Essex", "Ontario", "Canada"}, ""),
				new County(new String[]{"Frontenac", "Ontario", "Canada"}, ""),
				new County(new String[]{"Greater Sudbury", "Ontario", "Canada"}, ""),
				new County(new String[]{"Grey", "Ontario", "Canada"}, ""),
				new County(new String[]{"Haldimand", "Ontario", "Canada"}, ""),
				new County(new String[]{"Haliburton", "Ontario", "Canada"}, ""),
				new County(new String[]{"Halton", "Ontario", "Canada"}, ""),
				new County(new String[]{"Hamilton", "Ontario", "Canada"}, ""),
				new County(new String[]{"Hastings", "Ontario", "Canada"}, ""),
				new County(new String[]{"Huron", "Ontario", "Canada"}, ""),
				new County(new String[]{"Kawartha Lakes", "Ontario", "Canada"}, ""),
				new County(new String[]{"Kenora", "Ontario", "Canada"}, ""),
				new County(new String[]{"Lambton", "Ontario", "Canada"}, ""),
				new County(new String[]{"Lanark", "Ontario", "Canada"}, ""),
				new County(new String[]{"Leeds and Grenville", "Ontario", "Canada"}, ""),
				new County(new String[]{"Lennox and Addington", "Ontario", "Canada"}, ""),
				new County(new String[]{"Manitoulin", "Ontario", "Canada"}, ""),
				new County(new String[]{"Middlesex", "Ontario", "Canada"}, ""),
				new County(new String[]{"Muskoka", "Ontario", "Canada"}, ""),
				new County(new String[]{"Niagara", "Ontario", "Canada"}, ""),
				new County(new String[]{"Nipissing", "Ontario", "Canada"}, ""),
				new County(new String[]{"Norfolk", "Ontario", "Canada"}, ""),
				new County(new String[]{"Northumberland", "Ontario", "Canada"}, ""),
				new County(new String[]{"Ottawa", "Ontario", "Canada"}, ""),
				new County(new String[]{"Oxford", "Ontario", "Canada"}, ""),
				new County(new String[]{"Parry Sound", "Ontario", "Canada"}, ""),
				new County(new String[]{"Peel", "Ontario", "Canada"}, ""),
				new County(new String[]{"Perth", "Ontario", "Canada"}, ""),
				new County(new String[]{"Peterborough", "Ontario", "Canada"}, ""),
				new County(new String[]{"Prescott and Russell", "Ontario", "Canada"}, ""),
				new County(new String[]{"Prince Edward", "Ontario", "Canada"}, ""),
				new County(new String[]{"Rainy River", "Ontario", "Canada"}, ""),
				new County(new String[]{"Renfrew", "Ontario", "Canada"}, ""),
				new County(new String[]{"Simcoe", "Ontario", "Canada"}, ""),
				new County(new String[]{"Stormont", "Dundas and Glengarry", "Ontario", "Canada"}, ""),
				new County(new String[]{"Sudbury", "Ontario", "Canada"}, ""),
				new County(new String[]{"Thunder Bay", "Ontario", "Canada"}, ""),
				new County(new String[]{"Timiskaming", "Ontario", "Canada"}, ""),
				new County(new String[]{"Toronto", "Ontario", "Canada"}, ""),
				new County(new String[]{"Waterloo", "Ontario", "Canada"}, ""),
				new County(new String[]{"Wellington", "Ontario", "Canada"}, ""),
				new County(new String[]{"York", "Ontario", "Canada"}, ""),
			});
		
		ArrayList<PlaceStructure> princeEdwardIsland = Util.arrayList(new PlaceStructure[]{
//				new County(new String[]{"Prince Edward Island", "CANADA"}, ""),
			});
		
		ArrayList<PlaceStructure> quebec = Util.arrayList(new PlaceStructure[]{
				new County(new String[]{"Abitibi Territory", "Quebec", "Canada"}, ""),
				new County(new String[]{"Argenteuil County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Arthabaska County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Bagot County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Beauce County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Beauharnois County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Bellechasse County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Berthier County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Bonaventure County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Brome County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Chambly County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Champlain County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Charlevoix-Est County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Charlevoix-Ouest County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Châteauguay County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Chicoutimi County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Compton County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Deux-Montagnes County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Dorchester County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Drummond County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Frontenac County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Gaspé-Est County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Gaspé-Ouest County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Gatineau County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Hull County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Huntingdon County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Iberville County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Ile-de-Montréal County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Ile-Jésus County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Iles-de-la-Madeleine County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Joliette County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Kamouraska County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Labelle County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Laprairie County", "Quebec", "Canada"}, ""),
				new County(new String[]{"L''Assomption County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Lévis County", "Quebec", "Canada"}, ""),
				new County(new String[]{"L''Islet County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Lotbinière County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Lac-Saint-Jean-Est County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Lac-Saint-Jean-Ouest County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Maskinongé County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Matane County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Matapédia County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Mégantic County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Missisquoi County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Mistassini Territory", "Quebec", "Canada"}, ""),
				new County(new String[]{"Montcalm County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Montmorency No. 1 County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Montmorency No. 2 County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Montmagny County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Napierville County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Nicolet County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Nouveau-Quebec Territory", "Quebec", "Canada"}, ""),
				new County(new String[]{"Papineau County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Pontiac County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Portneuf County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Québec County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Richelieu County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Richmond County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Rimouski County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Rivière-du-Loup County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Rouville County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Saint-Hyacinthe County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Saint-Jean County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Saint-Maurice County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Saguenay County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Shefford County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Sherbrooke County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Soulanges County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Stanstead County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Témiscouata County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Témiscamingue County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Terrebonne County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Vaudreuil County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Verchères County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Wolfe County", "Quebec", "Canada"}, ""),
				new County(new String[]{"Yamaska County", "Quebec", "Canada"}, ""),
			});
		
		ArrayList<PlaceStructure> saskatchewan = Util.arrayList(new PlaceStructure[]{
//				new County(new String[]{"Saskatchewan", "Canada"}, ""),
			});
		
		ArrayList<PlaceStructure> yukon = Util.arrayList(new PlaceStructure[]{
//				new County(new String[]{"Yukon", "Canada"}, ""),
			});

		ArrayList<PlaceStructure> list = new ArrayList<PlaceStructure>();
		list = Util.arrayList(list, alberta);
		list = Util.arrayList(list, britishColumbia);
		list = Util.arrayList(list, manitoba);
		list = Util.arrayList(list, newBrunswick);
		list = Util.arrayList(list, newfoundland);
		list = Util.arrayList(list, northwestTerritories);
		list = Util.arrayList(list, novaScotia);
		list = Util.arrayList(list, nunavut);
		list = Util.arrayList(list, ontario);
		list = Util.arrayList(list, princeEdwardIsland);
		list = Util.arrayList(list, quebec);
		list = Util.arrayList(list, saskatchewan);
		list = Util.arrayList(list, yukon);
		return list;
	}
	
}
