package ws.daley.genealogy.db.xls;

import java.util.ArrayList;
import java.util.TreeMap;

public class XlsCountry
{
	private static TreeMap<String, ArrayList<String>> countryMap = new TreeMap<String, ArrayList<String>>();
	public static TreeMap<String, ArrayList<String>> getCountryMap() {return countryMap;}
	
    public static void addPlaceLists()
    {
		String[][][] elements = new String[][][]{
			{{"Afghanistan"}, {"AF"}},
			{{"Albania"}, {"AL"}},
			{{"Algeria"}, {"DZ"}},
			{{"American Samoa"}, {"AS"}},
			{{"Andorra"}, {"AD"}},
			{{"Angola"}, {"AO"}},
			{{"Anguilla"}, {"AI"}},
			{{"Antarctia"}, {"AQ"}},
			{{"Antigua BBarbuda"}, {"AG"}},
			{{"Argentina"}, {"AR"}},
			{{"Armenia"}, {"AM"}},
			{{"Aruba"}, {"AW"}},
			{{"Australia"}, {"AU"}},
			{{"Austria"}, {"AT"}},
			{{"Azerbaijan"}, {"AZ"}},
			{{"Bahamas"}, {"BS"}},
			{{"Bahrain"}, {"BH"}},
			{{"Bangladesh"}, {"BD"}},
			{{"Barbados"}, {"BB"}},
			{{"Belarus"}, {"BY"}},
			{{"Belgium"}, {"BE"}},
			{{"Belize"}, {"BZ"}},
			{{"Benin"}, {"BJ"}},
			{{"Bermuda"}, {"BM"}},
			{{"Bhutan"}, {"BT"}},
			{{"Bolivia"}, {"BO"}},
			{{"Bosnia Herzegovina"}, {"BA"}},
			{{"Botswana"}, {"BW"}},
			{{"Bouvet Island"}, {"BV"}},
			{{"Brazil"}, {"BR"}},
			{{"British Indian Ocean Territory"}, {"IO"}},
			{{"Brunei Darussalam"}, {"BN"}},
			{{"Bulgaria"}, {"BG"}},
			{{"Burkina Faso"}, {"BF"}},
			{{"Burundi"}, {"BI"}},
			{{"Cambodia"}, {"KH"}},
			{{"Cameroon"}, {"CM"}},
			{{"Canada"}, {"CA"}},
			{{"Cape Verde"}, {"CV"}},
			{{"Cayman Islands"}, {"KY"}},
			{{"Central African Republic"}, {"CF"}},
			{{"Chad"}, {"TD"}},
			{{"Chile"}, {"CL"}},
			{{"China"}, {"CN"}},
			{{"Christmas Island"}, {"CX"}},
			{{"Cocos (Keeling) Islands"}, {"CC"}},
			{{"Colombia"}, {"CO"}},
			{{"Comoros"}, {"KM"}},
			{{"Congo"}, {"CG"}},
			{{"Congo, The Democratic Republic Of"}, {"CD"}},
			{{"Cook Islands"}, {"CK"}},
			{{"Costa Rica"}, {"CR"}},
			{{"CÔte D''Ivoire"}, {"CI"}},
			{{"Croatia"}, {"HR"}},
			{{"Cuba"}, {"CU"}},
			{{"Cyprus"}, {"CY"}},
			{{"Czech Republic"}, {"CZ"}},
			{{"Denmark"}, {"DK"}},
			{{"Djibouti"}, {"DJ"}},
			{{"Dominica"}, {"DM"}},
			{{"Dominican Republic"}, {"DO"}},
			{{"Ecuador"}, {"EC"}},
			{{"Egyot"}, {"EG"}},
			{{"El Salvador"}, {"SV"}},
			{{"Equatorial Guinea"}, {"GQ"}},
			{{"Eritrea"}, {"ER"}},
			{{"Estonia"}, {"EE"}},
			{{"Ethiopia"}, {"ET"}},
			{{"Falkland Islands (Malvinas)"}, {"FK"}},
			{{"Faroe Islands"}, {"FO"}},
			{{"Fiji"}, {"FJ"}},
			{{"Finland"}, {"FI"}},
			{{"France"}, {"FR"}},
			{{"French Guiana"}, {"GF"}},
			{{"French Polynesia"}, {"PF"}},
			{{"French Southern Territories"}, {"TF"}},
			{{"Gabon"}, {"GA"}},
			{{"Gambia"}, {"GM"}},
			{{"Georgia"}, {"GE"}},
			{{"Germany"}, {"DE", "Bavaria"}},
			{{"Ghana"}, {"GH"}},
			{{"Gibraltar"}, {"GI"}},
			{{"Greece"}, {"GR"}},
			{{"Greenland"}, {"GL"}},
			{{"Grenada"}, {"GD"}},
			{{"Guadaloupe"}, {"GP"}},
			{{"Guam"}, {"GU"}},
			{{"Guatemala"}, {"GT"}},
			{{"Guinea"}, {"GN"}},
			{{"Guinea-Bissau"}, {"GW"}},
			{{"Guyana"}, {"GY"}},
			{{"Haiti"}, {"HT"}},
			{{"Heard Island McDonald Islands"}, {"HM"}},
			{{"Holy See (Vatican City State)"}, {"VA"}},
			{{"Honduras"}, {"HN"}},
			{{"Hong Kong"}, {"HK"}},
			{{"Hungary"}, {"HU"}},
			{{"Iceland"}, {"IS"}},
			{{"India"}, {"IN"}},
			{{"Indonesia"}, {"ID"}},
			{{"Iran, Islamic Republic Of"}, {"IR"}},
			{{"Iraq"}, {"IQ"}},
			{{"Ireland"}, {"IE"}},
			{{"Israel"}, {"IL"}},
			{{"Italy"}, {"IT"}},
			{{"Jamaica"}, {"JM"}},
			{{"Japan"}, {"JP"}},
			{{"Jordan"}, {"JO"}},
			{{"Kazakhstan"}, {"KZ"}},
			{{"Kenya"}, {"KE"}},
			{{"Kiribati"}, {"KI"}},
			{{"Korea, Democratic People''s Republic Of"}, {"KP"}},
			{{"Korea, Republic Of"}, {"KR"}},
			{{"Kuwait"}, {"KW"}},
			{{"Kyrgyzstan"}, {"KG"}},
			{{"Lao People''s Democratic Republic"}, {"LA"}},
			{{"Latvia"}, {"LV"}},
			{{"Lebanon"}, {"LB"}},
			{{"Lesotho"}, {"LS"}},
			{{"Liberia"}, {"LR"}},
			{{"Libyan arab jamahiriya"}, {"LY"}},
			{{"Liechtenstein"}, {"LI"}},
			{{"Lithuania"}, {"LT"}},
			{{"Luxembourg"}, {"LU"}},
			{{"Macao"}, {"MO"}},
			{{"Macedonia, The Former Yugoslav Republic Of"}, {"MK"}},
			{{"Madagascar"}, {"MG"}},
			{{"Malawi"}, {"MW"}},
			{{"Malaysia"}, {"MY"}},
			{{"Maldives"}, {"MV"}},
			{{"Mali"}, {"ML"}},
			{{"Malta"}, {"MT"}},
			{{"Marshall Islands"}, {"MH"}},
			{{"Martinique"}, {"MQ"}},
			{{"Mauritania"}, {"MR"}},
			{{"Mauritius"}, {"MU"}},
			{{"Mayotte"}, {"YT"}},
			{{"Mexico"}, {"MX"}},
			{{"Micronisia, Federated States Of"}, {"FM"}},
			{{"Moldova, Republic Of"}, {"MD"}},
			{{"Monaco"}, {"MC"}},
			{{"Mongolia"}, {"MN"}},
			{{"Montserrat"}, {"MS"}},
			{{"Morocco"}, {"MA"}},
			{{"Mozambique"}, {"MZ"}},
			{{"Myanmar"}, {"MM"}},
			{{"Namibia"}, {"NA"}},
			{{"Nauru"}, {"NR"}},
			{{"Nepal"}, {"NP"}},
			{{"Netherlands"}, {"NL", "Holland"}},
			{{"Netherlands Antilles"}, {"AN"}},
			{{"New Caledonia"}, {"NC"}},
			{{"New Zealand"}, {"NZ"}},
			{{"Nicaragua"}, {"NI"}},
			{{"Niger"}, {"NE"}},
			{{"Nigeria"}, {"NG"}},
			{{"Niue"}, {"NU"}},
			{{"Norfolk Island"}, {"NF"}},
			{{"Northern Mariana Islands"}, {"MP"}},
			{{"Norway"}, {"NO"}},
			{{"Oman"}, {"OM"}},
			{{"Pakistan"}, {"PK"}},
			{{"Palau"}, {"PW"}},
			{{"Palestinian Territory, Occupied"}, {"PS"}},
			{{"Panama"}, {"PA"}},
			{{"Papua New Guinea"}, {"PG"}},
			{{"Paraguay"}, {"PY"}},
			{{"Peru"}, {"PE"}},
			{{"Philippines"}, {"PH"}},
			{{"Pitcairn"}, {"PN"}},
			{{"Poland"}, {"PL"}},
			{{"Portugal"}, {"PT"}},
			{{"Puerto Rico"}, {"PR"}},
			{{"Qatar"}, {"QA"}},
			{{"RÉunion"}, {"RE"}},
			{{"Romania"}, {"RO"}},
			{{"Russian Federation"}, {"RU", "Russia"}},
			{{"Rwanda"}, {"RW"}},
			{{"Saint Helena"}, {"SH"}},
			{{"Saint Kitts Nevis"}, {"KN"}},
			{{"Saint Lucia"}, {"LC"}},
			{{"Saint Pierre Miquelon"}, {"PM"}},
			{{"Saint Vincent The Grenadines"}, {"VC"}},
			{{"Samoa"}, {"WS"}},
			{{"San Marino"}, {"SM"}},
			{{"Sao Tome Principe"}, {"ST"}},
			{{"Saudi Arabia"}, {"SA"}},
			{{"Senegal"}, {"SN"}},
			{{"Serbia Montenegro"}, {"CS"}},
			{{"Seychelles"}, {"SC"}},
			{{"Sierra Leone"}, {"SL"}},
			{{"Singapore"}, {"SG"}},
			{{"Slovakia"}, {"SK"}},
			{{"Slovenai"}, {"SI"}},
			{{"Solomon Islands"}, {"SB"}},
			{{"Somalia"}, {"SO"}},
			{{"South Africa"}, {"ZA"}},
			{{"South Georgia South Sandwich Islands"}, {"GS"}},
			{{"Spain"}, {"ES"}},
			{{"Sri Lanka"}, {"LK"}},
			{{"Sudan"}, {"SD"}},
			{{"Suriname"}, {"SR"}},
			{{"Svalbard Jan Mayen"}, {"SJ"}},
			{{"Swaziland"}, {"SZ"}},
			{{"Sweden"}, {"SE"}},
			{{"Switzerland"}, {"CH"}},
			{{"Syrian Arab Republic"}, {"SY"}},
			{{"Taiwan, Province Of China"}, {"TW"}},
			{{"Tajikistan"}, {"TJ"}},
			{{"Tanzania, United Republic Of"}, {"TZ"}},
			{{"Thailand"}, {"TH"}},
			{{"Timor-Leste"}, {"TL"}},
			{{"Togo"}, {"TG"}},
			{{"Tokelau"}, {"TK"}},
			{{"Tonga"}, {"TO"}},
			{{"Trinidad Tobago"}, {"TT"}},
			{{"Tunisia"}, {"TN"}},
			{{"Turkey"}, {"TR"}},
			{{"Turkmenistan"}, {"TM"}},
			{{"Turks Caicos Islands"}, {"TC"}},
			{{"Tuvalu"}, {"TV"}},
			{{"Uganda"}, {"UG"}},
			{{"Ukraine"}, {"UA"}},
			{{"United Arab Emirates"}, {"AE"}},
			{{"United Kingdom"}, {"GB", "England", "Great Britain", "Northern Ireland", "Wales"}},
			{{"United States"}, {"US", "USA"}},
			{{"United States Minor Outlying Islands"}, {"UM"}},
			{{"Uruguay"}, {"UY"}},
			{{"Uzbekistan"}, {"UZ"}},
			{{"Vanuatu"}, {"VU"}},
			{{"Venezuela"}, {"VE"}},
			{{"Viet Nam"}, {"VN"}},
			{{"Virgin Islands, British"}, {"VG"}},
			{{"Virgin Islands, U.S."}, {"VI"}},
			{{"Wallis Futuna"}, {"WF"}},
			{{"Western Sahara"}, {"EH"}},
			{{"Yemen"}, {"YE"}},
			{{"Zambia"}, {"ZM"}},
			{{"Zimbabwe"}, {"ZW"}}};
			/**
			 * Vatican City XlsState see HOLY SEE
			 * Zaire see CONGO, DEMOCRATIC REPUBLIC OF
			 */
		addNameList(elements);
    }
    
    public static void addNameList(String[][][] elements)
    {
    	for(String[][] element: elements)
    	{
    		ArrayList<String> list = new ArrayList<String>();
    		for(String alias:element[1])
    			list.add(alias);
    		countryMap.put(element[0][0], list);
    	}
		XlsPlaceName.addNameList(elements);
    }
}
