package ws.daley.genealogy.db.xls;

public class XlsCountyCanada
{
	public static String[][][] getNames()
	{
		return new String[][][]{
			{{"Acadia", "Alberta", "Canada"}, {}},
			{{"Athabasca", "Alberta", "Canada"}, {}},
			{{"Banff", "Alberta", "Canada"}, {}},
			{{"Barrhead", "Alberta", "Canada"}, {}},
			{{"Beaver", "Alberta", "Canada"}, {}},
			{{"Big Lakes", "Alberta", "Canada"}, {}},
			{{"Bighorn", "Alberta", "Canada"}, {}},
			{{"Birch Hills", "Alberta", "Canada"}, {}},
			{{"Bonnyville", "Alberta", "Canada"}, {}},
			{{"Brazeau", "Alberta", "Canada"}, {}},
			{{"Calgary", "Alberta", "Canada"}, {}},
			{{"Camrose", "Alberta", "Canada"}, {}},
			{{"Cardston", "Alberta", "Canada"}, {}},
			{{"Clear Hills", "Alberta", "Canada"}, {}},
			{{"Clearwater", "Alberta", "Canada"}, {}},
			{{"Crowsnest Pass", "Alberta", "Canada"}, {}},
			{{"Cypress", "Alberta", "Canada"}, {}},
			{{"Edmonton", "Alberta", "Canada"}, {}},
			{{"Elk Island", "Alberta", "Canada"}, {}},
			{{"Fairview", "Alberta", "Canada"}, {}},
			{{"Flagstaff", "Alberta", "Canada"}, {}},
			{{"Foothills", "Alberta", "Canada"}, {}},
			{{"Forty Mile", "Alberta", "Canada"}, {}},
			{{"Grande Prairie", "Alberta", "Canada"}, {}},
			{{"Greenview", "Alberta", "Canada"}, {}},
			{{"Jasper", "Alberta", "Canada"}, {}},
			{{"Kananaskis", "Alberta", "Canada"}, {}},
			{{"Kneehill", "Alberta", "Canada"}, {}},
			{{"Lac La Biche", "Alberta", "Canada"}, {}},
			{{"Lac Ste. Anne", "Alberta", "Canada"}, {}},
			{{"Lacombe", "Alberta", "Canada"}, {}},
			{{"Lamont", "Alberta", "Canada"}, {}},
			{{"Leduc", "Alberta", "Canada"}, {}},
			{{"Lesser Slave River", "Alberta", "Canada"}, {}},
			{{"Lethbridge", "Alberta", "Canada"}, {}},
			{{"Mackenzie", "Alberta", "Canada"}, {}},
			{{"Minburn", "Alberta", "Canada"}, {}},
			{{"Mountain View", "Alberta", "Canada"}, {}},
			{{"Newell", "Alberta", "Canada"}, {}},
			{{"Northern Lights", "Alberta", "Canada"}, {}},
			{{"Northern Sunrise", "Alberta", "Canada"}, {}},
			{{"Opportunity", "Alberta", "Canada"}, {}},
			{{"Paintearth", "Alberta", "Canada"}, {}},
			{{"Parkland", "Alberta", "Canada"}, {}},
			{{"Peace", "Alberta", "Canada"}, {}},
			{{"Pincher Creek", "Alberta", "Canada"}, {}},
			{{"Ponoka", "Alberta", "Canada"}, {}},
			{{"Provost", "Alberta", "Canada"}, {}},
			{{"Ranchland", "Alberta", "Canada"}, {}},
			{{"Red Deer", "Alberta", "Canada"}, {}},
			{{"Rocky View", "Alberta", "Canada"}, {}},
			{{"Saddle Hills", "Alberta", "Canada"}, {}},
			{{"Smoky Lake", "Alberta", "Canada"}, {}},
			{{"Special Areas", "Alberta", "Canada"}, {}},
			{{"Spirit River", "Alberta", "Canada"}, {}},
			{{"St. Paul", "Alberta", "Canada"}, {}},
			{{"Starland", "Alberta", "Canada"}, {}},
			{{"Stettler", "Alberta", "Canada"}, {}},
			{{"Strathcona", "Alberta", "Canada"}, {}},
			{{"Sturgeon", "Alberta", "Canada"}, {}},
			{{"Taber", "Alberta", "Canada"}, {}},
			{{"Thorhild", "Alberta", "Canada"}, {}},
			{{"Two Hills", "Alberta", "Canada"}, {}},
			{{"Vermilion River", "Alberta", "Canada"}, {}},
			{{"Vulcan", "Alberta", "Canada"}, {}},
			{{"Wainwright", "Alberta", "Canada"}, {}},
			{{"Warner", "Alberta", "Canada"}, {}},
			{{"Waterton Lakes", "Alberta", "Canada"}, {}},
			{{"Westlock", "Alberta", "Canada"}, {}},
			{{"Wetaskiwin", "Alberta", "Canada"}, {}},
			{{"Willmore Wilderness", "Alberta", "Canada"}, {}},
			{{"Willow Creek", "Alberta", "Canada"}, {}},
			{{"Wood Buffalo", "Alberta", "Canada"}, {}},
			{{"Woodlands", "Alberta", "Canada"}, {}},
			{{"Yellowhead", "Alberta", "Canada"}, {}},

			{{"Abbotsford", "British Columbia", "Canada"}, {}},
			{{"Alert Bay", "British Columbia", "Canada"}, {}},
			{{"Anmore", "British Columbia", "Canada"}, {}},
			{{"Armstrong", "British Columbia", "Canada"}, {}},
			{{"Ashcroft", "British Columbia", "Canada"}, {}},
			{{"Barriere", "British Columbia", "Canada"}, {}},
			{{"Belcarra", "British Columbia", "Canada"}, {}},
			{{"Bowen Island", "British Columbia", "Canada"}, {}},
			{{"Burnaby", "British Columbia", "Canada"}, {}},
			{{"Burns Lake", "British Columbia", "Canada"}, {}},
			{{"Cache Creek", "British Columbia", "Canada"}, {}},
			{{"Campbell River", "British Columbia", "Canada"}, {}},
			{{"Canal Flats", "British Columbia", "Canada"}, {}},
			{{"Cariboo", "British Columbia", "Canada"}, {}},
			{{"Castlegar", "British Columbia", "Canada"}, {}},
			{{"Central Saanich", "British Columbia", "Canada"}, {}},
			{{"Chase", "British Columbia", "Canada"}, {}},
			{{"Chetwynd", "British Columbia", "Canada"}, {}},
			{{"Chilliwack", "British Columbia", "Canada"}, {}},
			{{"Clearwater", "British Columbia", "Canada"}, {}},
			{{"Clinton", "British Columbia", "Canada"}, {}},
			{{"Coldstream", "British Columbia", "Canada"}, {}},
			{{"Colwood", "British Columbia", "Canada"}, {}},
			{{"Comox", "British Columbia", "Canada"}, {}},
			{{"Coquitlam", "British Columbia", "Canada"}, {}},
			{{"Courtenay", "British Columbia", "Canada"}, {}},
			{{"Cranbrook", "British Columbia", "Canada"}, {}},
			{{"Creston", "British Columbia", "Canada"}, {}},
			{{"Cumberland", "British Columbia", "Canada"}, {}},
			{{"Dawson Creek", "British Columbia", "Canada"}, {}},
			{{"Delta", "British Columbia", "Canada"}, {}},
			{{"Duncan", "British Columbia", "Canada"}, {}},
			{{"Elkford", "British Columbia", "Canada"}, {}},
			{{"Enderby", "British Columbia", "Canada"}, {}},
			{{"Esquimalt", "British Columbia", "Canada"}, {}},
			{{"Fernie", "British Columbia", "Canada"}, {}},
			{{"Fort Nelson", "British Columbia", "Canada"}, {}},
			{{"Fort St. James", "British Columbia", "Canada"}, {}},
			{{"Fort St. John", "British Columbia", "Canada"}, {}},
			{{"Fraser Lake", "British Columbia", "Canada"}, {}},
			{{"Fruitvale", "British Columbia", "Canada"}, {}},
			{{"Gibsons", "British Columbia", "Canada"}, {}},
			{{"Gold River", "British Columbia", "Canada"}, {}},
			{{"Golden", "British Columbia", "Canada"}, {}},
			{{"Grand Forks", "British Columbia", "Canada"}, {}},
			{{"Granisle", "British Columbia", "Canada"}, {}},
			{{"Greenwood", "British Columbia", "Canada"}, {}},
			{{"Harrison Hot Springs", "British Columbia", "Canada"}, {}},
			{{"Hazelton", "British Columbia", "Canada"}, {}},
			{{"Highlands", "British Columbia", "Canada"}, {}},
			{{"Hope", "British Columbia", "Canada"}, {}},
			{{"Houston", "British Columbia", "Canada"}, {}},
			{{"Hudson''s Hope", "British Columbia", "Canada"}, {}},
			{{"Invermere", "British Columbia", "Canada"}, {}},
			{{"Kamloops", "British Columbia", "Canada"}, {}},
			{{"Kaslo", "British Columbia", "Canada"}, {}},
			{{"Kelowna", "British Columbia", "Canada"}, {}},
			{{"Kent", "British Columbia", "Canada"}, {}},
			{{"Keremeos", "British Columbia", "Canada"}, {}},
			{{"Kimberley", "British Columbia", "Canada"}, {}},
			{{"Kitimat", "British Columbia", "Canada"}, {}},
			{{"Kootenay", "British Columbia", "Canada"}, {}},
			{{"Ladysmith", "British Columbia", "Canada"}, {}},
			{{"Lake XlsCountry", "British Columbia", "Canada"}, {}},
			{{"Lake Cowichan", "British Columbia", "Canada"}, {}},
			{{"Langford", "British Columbia", "Canada"}, {}},
			{{"Langley", "British Columbia", "Canada"}, {}},
			{{"Lantzville", "British Columbia", "Canada"}, {}},
			{{"Lillooet", "British Columbia", "Canada"}, {}},
			{{"Lions Bay", "British Columbia", "Canada"}, {}},
			{{"Logan Lake", "British Columbia", "Canada"}, {}},
			{{"Lumby", "British Columbia", "Canada"}, {}},
			{{"Lytton", "British Columbia", "Canada"}, {}},
			{{"Mackenzie", "British Columbia", "Canada"}, {}},
			{{"Maple Ridge", "British Columbia", "Canada"}, {}},
			{{"Masset", "British Columbia", "Canada"}, {}},
			{{"McBride", "British Columbia", "Canada"}, {}},
			{{"Merritt", "British Columbia", "Canada"}, {}},
			{{"Metchosin", "British Columbia", "Canada"}, {}},
			{{"Midway", "British Columbia", "Canada"}, {}},
			{{"Mission", "British Columbia", "Canada"}, {}},
			{{"Montrose", "British Columbia", "Canada"}, {}},
			{{"Nakusp", "British Columbia", "Canada"}, {}},
			{{"Nanaimo", "British Columbia", "Canada"}, {}},
			{{"Nelson", "British Columbia", "Canada"}, {}},
			{{"New Denver", "British Columbia", "Canada"}, {}},
			{{"New Hazelton", "British Columbia", "Canada"}, {}},
			{{"New Westminster", "British Columbia", "Canada"}, {}},
			{{"North Cowichan", "British Columbia", "Canada"}, {}},
			{{"North Saanich", "British Columbia", "Canada"}, {}},
			{{"North Vancouver", "British Columbia", "Canada"}, {}},
			{{"Oak Bay", "British Columbia", "Canada"}, {}},
			{{"Oliver", "British Columbia", "Canada"}, {}},
			{{"Osoyoos", "British Columbia", "Canada"}, {}},
			{{"Parksville", "British Columbia", "Canada"}, {}},
			{{"Peachland", "British Columbia", "Canada"}, {}},
			{{"Pemberton", "British Columbia", "Canada"}, {}},
			{{"Penticton", "British Columbia", "Canada"}, {}},
			{{"Pitt Meadows", "British Columbia", "Canada"}, {}},
			{{"Port Alberni", "British Columbia", "Canada"}, {}},
			{{"Port Alice", "British Columbia", "Canada"}, {}},
			{{"Port Clements", "British Columbia", "Canada"}, {}},
			{{"Port Coquitlam", "British Columbia", "Canada"}, {}},
			{{"Port Edward", "British Columbia", "Canada"}, {}},
			{{"Port Hardy", "British Columbia", "Canada"}, {}},
			{{"Port McNeill", "British Columbia", "Canada"}, {}},
			{{"Port Moody", "British Columbia", "Canada"}, {}},
			{{"Pouce Coupe", "British Columbia", "Canada"}, {}},
			{{"Powell River", "British Columbia", "Canada"}, {}},
			{{"Prince George", "British Columbia", "Canada"}, {}},
			{{"Prince Rupert", "British Columbia", "Canada"}, {}},
			{{"Princeton", "British Columbia", "Canada"}, {}},
			{{"Qualicum Beach", "British Columbia", "Canada"}, {}},
			{{"Queen Charlotte", "British Columbia", "Canada"}, {}},
			{{"Quesnel", "British Columbia", "Canada"}, {}},
			{{"Radium Hot Springs", "British Columbia", "Canada"}, {}},
			{{"Revelstoke", "British Columbia", "Canada"}, {}},
			{{"Richmond", "British Columbia", "Canada"}, {}},
			{{"Rossland", "British Columbia", "Canada"}, {}},
			{{"Saanich", "British Columbia", "Canada"}, {}},
			{{"Salmo", "British Columbia", "Canada"}, {}},
			{{"Salmon Arm", "British Columbia", "Canada"}, {}},
			{{"Sayward", "British Columbia", "Canada"}, {}},
			{{"Sechelt", "British Columbia", "Canada"}, {}},
			{{"Sicamous", "British Columbia", "Canada"}, {}},
			{{"Sidney", "British Columbia", "Canada"}, {}},
			{{"Silverton", "British Columbia", "Canada"}, {}},
			{{"Slocan", "British Columbia", "Canada"}, {}},
			{{"Smithers", "British Columbia", "Canada"}, {}},
			{{"Sooke", "British Columbia", "Canada"}, {}},
			{{"Spallumcheen", "British Columbia", "Canada"}, {}},
			{{"Sparwood", "British Columbia", "Canada"}, {}},
			{{"Squamish", "British Columbia", "Canada"}, {}},
			{{"Stewart", "British Columbia", "Canada"}, {}},
			{{"Summerland", "British Columbia", "Canada"}, {}},
			{{"Surrey", "British Columbia", "Canada"}, {}},
			{{"Tahsis", "British Columbia", "Canada"}, {}},
			{{"Taylor", "British Columbia", "Canada"}, {}},
			{{"Telkwa", "British Columbia", "Canada"}, {}},
			{{"Terrace", "British Columbia", "Canada"}, {}},
			{{"Tofino", "British Columbia", "Canada"}, {}},
			{{"Trail", "British Columbia", "Canada"}, {}},
			{{"Tumbler Ridge", "British Columbia", "Canada"}, {}},
			{{"Ucluelet", "British Columbia", "Canada"}, {}},
			{{"Valemount", "British Columbia", "Canada"}, {}},
			{{"Vancouver", "British Columbia", "Canada"}, {}},
			{{"Vanderhoof", "British Columbia", "Canada"}, {}},
			{{"Vernon", "British Columbia", "Canada"}, {}},
			{{"Victoria", "British Columbia", "Canada"}, {}},
			{{"View Royal", "British Columbia", "Canada"}, {}},
			{{"Warfield", "British Columbia", "Canada"}, {}},
			{{"Wells", "British Columbia", "Canada"}, {}},
			{{"West Vancouver", "British Columbia", "Canada"}, {}},
			{{"West Kelowna", "British Columbia", "Canada"}, {}},
			{{"Westminster", "British Columbia", "Canada"}, {}},
			{{"Whistler", "British Columbia", "Canada"}, {}},
			{{"White Rock", "British Columbia", "Canada"}, {}},
			{{"Williams Lake", "British Columbia", "Canada"}, {}},
			{{"Yale", "British Columbia", "Canada"}, {}},
			{{"Zeballos", "British Columbia", "Canada"}, {}},
			{{"100 Mile House", "British Columbia", "Canada"}, {}},

			{{"Albert", "Manitoba", "Canada"}, {}},
			{{"Alexander", "Manitoba", "Canada"}, {}},
			{{"Alonsa", "Manitoba", "Canada"}, {}},
			{{"Archie", "Manitoba", "Canada"}, {}},
			{{"Argyle", "Manitoba", "Canada"}, {}},
			{{"Armstrong", "Manitoba", "Canada"}, {}},
			{{"Arthur", "Manitoba", "Canada"}, {}},
			{{"Beausejour Area", "Manitoba", "Canada"}, {}},
			{{"Bifrost", "Manitoba", "Canada"}, {}},
			{{"Binscarth", "Manitoba", "Canada"}, {}},
			{{"Birtle", "Manitoba", "Canada"}, {}},
			{{"Blanshard", "Manitoba", "Canada"}, {}},
			{{"Brandon Area", "Manitoba", "Canada"}, {}},
			{{"Brenda", "Manitoba", "Canada"}, {}},
			{{"Brokenhead", "Manitoba", "Canada"}, {}},
			{{"Cameron", "Manitoba", "Canada"}, {}},
			{{"Cartier", "Manitoba", "Canada"}, {}},
			{{"Central Plains Region", "Manitoba", "Canada"}, {}},
			{{"Central Manitoba", "Manitoba", "Canada"}, {}},
			{{"City of Winnipeg", "Manitoba", "Canada"}, {}},
			{{"Churchill/Northern Manitoba", "Manitoba", "Canada"}, {}},
			{{"Clanwilliam", "Manitoba", "Canada"}, {}},
			{{"Coldwell", "Manitoba", "Canada"}, {}},
			{{"Cornwallis", "Manitoba", "Canada"}, {}},
			{{"Dauphin", "Manitoba", "Canada"}, {}},
			{{"DeSalaberry", "Manitoba", "Canada"}, {}},
			{{"Dufferin", "Manitoba", "Canada"}, {}},
			{{"East St. Paul", "Manitoba", "Canada"}, {}},
			{{"Eastern Manitoba", "Manitoba", "Canada"}, {}},
			{{"Eastman", "Manitoba", "Canada"}, {}},
			{{"Eastman Region", "Manitoba", "Canada"}, {}},
			{{"Edward", "Manitoba", "Canada"}, {}},
			{{"Ellice", "Manitoba", "Canada"}, {}},
			{{"Eriksdale", "Manitoba", "Canada"}, {}},
			{{"Ethelbert", "Manitoba", "Canada"}, {}},
			{{"Fisher", "Manitoba", "Canada"}, {}},
			{{"Flin Flon/North West", "Manitoba", "Canada"}, {}},
			{{"Franklin", "Manitoba", "Canada"}, {}},
			{{"GilbertPlains", "Manitoba", "Canada"}, {}},
			{{"Gimli", "Manitoba", "Canada"}, {}},
			{{"Glenella", "Manitoba", "Canada"}, {}},
			{{"Glenwood", "Manitoba", "Canada"}, {}},
			{{"Grahamdale", "Manitoba", "Canada"}, {}},
			{{"Grandview", "Manitoba", "Canada"}, {}},
			{{"Grey", "Manitoba", "Canada"}, {}},
			{{"Hamiota", "Manitoba", "Canada"}, {}},
			{{"Hanover", "Manitoba", "Canada"}, {}},
			{{"Harrison", "Manitoba", "Canada"}, {}},
			{{"Headingley", "Manitoba", "Canada"}, {}},
			{{"Hillsburg", "Manitoba", "Canada"}, {}},
			{{"Interlake", "Manitoba", "Canada"}, {}},
			{{"Interlake Region", "Manitoba", "Canada"}, {}},
			{{"Kelsey", "Manitoba", "Canada"}, {}},
			{{"La Broquerie", "Manitoba", "Canada"}, {}},
			{{"Lac du Bonnet", "Manitoba", "Canada"}, {}},
			{{"Lakeview", "Manitoba", "Canada"}, {}},
			{{"Langford", "Manitoba", "Canada"}, {}},
			{{"Lansdowne", "Manitoba", "Canada"}, {}},
			{{"Lawrence", "Manitoba", "Canada"}, {}},
			{{"Lorne", "Manitoba", "Canada"}, {}},
			{{"Louise", "Manitoba", "Canada"}, {}},
			{{"Macdonald", "Manitoba", "Canada"}, {}},
			{{"McCreary", "Manitoba", "Canada"}, {}},
			{{"Miniota", "Manitoba", "Canada"}, {}},
			{{"Minitonas", "Manitoba", "Canada"}, {}},
			{{"Minto", "Manitoba", "Canada"}, {}},
			{{"Montcalm", "Manitoba", "Canada"}, {}},
			{{"Morris", "Manitoba", "Canada"}, {}},
			{{"Morton", "Manitoba", "Canada"}, {}},
			{{"MosseyRiver", "Manitoba", "Canada"}, {}},
			{{"Mountain", "Manitoba", "Canada"}, {}},
			{{"North East Man", "Manitoba", "Canada"}, {}},
			{{"North Interlake", "Manitoba", "Canada"}, {}},
			{{"North Cypress", "Manitoba", "Canada"}, {}},
			{{"North Norfolk", "Manitoba", "Canada"}, {}},
			{{"Northern", "Manitoba", "Canada"}, {}},
			{{"Oakland", "Manitoba", "Canada"}, {}},
			{{"Ochre River", "Manitoba", "Canada"}, {}},
			{{"Odanah", "Manitoba", "Canada"}, {}},
			{{"Park", "Manitoba", "Canada"}, {}},
			{{"Parkland", "Manitoba", "Canada"}, {}},
			{{"Pembina Valley", "Manitoba", "Canada"}, {}},
			{{"Pilot Mound Area", "Manitoba", "Canada"}, {}},
			{{"Piney", "Manitoba", "Canada"}, {}},
			{{"Pipestone", "Manitoba", "Canada"}, {}},
			{{"Portage la Prairie Area", "Manitoba", "Canada"}, {}},
			{{"Reynolds", "Manitoba", "Canada"}, {}},
			{{"Rhineland", "Manitoba", "Canada"}, {}},
			{{"Ritchot", "Manitoba", "Canada"}, {}},
			{{"Riverside", "Manitoba", "Canada"}, {}},
			{{"Roblin", "Manitoba", "Canada"}, {}},
			{{"Rockwood", "Manitoba", "Canada"}, {}},
			{{"Roland", "Manitoba", "Canada"}, {}},
			{{"Rosedale", "Manitoba", "Canada"}, {}},
			{{"Rossburn", "Manitoba", "Canada"}, {}},
			{{"Rosser", "Manitoba", "Canada"}, {}},
			{{"Russell", "Manitoba", "Canada"}, {}},
			{{"Saskatchewan", "Manitoba", "Canada"}, {}},
			{{"Selkirk Area", "Manitoba", "Canada"}, {}},
			{{"Shell River", "Manitoba", "Canada"}, {}},
			{{"Shelmouth-Boulton", "Manitoba", "Canada"}, {}},
			{{"ShoalLake", "Manitoba", "Canada"}, {}},
			{{"Sifton", "Manitoba", "Canada"}, {}},
			{{"Siglunes", "Manitoba", "Canada"}, {}},
			{{"SilverCreek", "Manitoba", "Canada"}, {}},
			{{"South Cypress", "Manitoba", "Canada"}, {}},
			{{"South Interlake", "Manitoba", "Canada"}, {}},
			{{"South Norfolk", "Manitoba", "Canada"}, {}},
			{{"South West", "Manitoba", "Canada"}, {}},
			{{"Springfield", "Manitoba", "Canada"}, {}},
			{{"St. Andrews", "Manitoba", "Canada"}, {}},
			{{"St. Clements", "Manitoba", "Canada"}, {}},
			{{"St. François Xavier", "Manitoba", "Canada"}, {}},
			{{"St. Laurent", "Manitoba", "Canada"}, {}},
			{{"Ste. Anne", "Manitoba", "Canada"}, {}},
			{{"Ste. Rose", "Manitoba", "Canada"}, {}},
			{{"Stanley", "Manitoba", "Canada"}, {}},
			{{"Steinbach Area", "Manitoba", "Canada"}, {}},
			{{"Stonewall", "Manitoba", "Canada"}, {}},
			{{"Strathclair", "Manitoba", "Canada"}, {}},
			{{"Strathcona", "Manitoba", "Canada"}, {}},
			{{"Stuartburn", "Manitoba", "Canada"}, {}},
			{{"Swan River", "Manitoba", "Canada"}, {}},
			{{"Swan Valley", "Manitoba", "Canada"}, {}},
			{{"Taché", "Manitoba", "Canada"}, {}},
			{{"Thompson/North Central", "Manitoba", "Canada"}, {}},
			{{"TurtleMountain", "Manitoba", "Canada"}, {}},
			{{"Victoria", "Manitoba", "Canada"}, {}},
			{{"Victoria Beach", "Manitoba", "Canada"}, {}},
			{{"Virden Area", "Manitoba", "Canada"}, {}},
			{{"Wallace", "Manitoba", "Canada"}, {}},
			{{"West St. Paul", "Manitoba", "Canada"}, {}},
			{{"Westbourne", "Manitoba", "Canada"}, {}},
			{{"Western Manitoba", "Manitoba", "Canada"}, {}},
			{{"Westman", "Manitoba", "Canada"}, {}},
			{{"Whitehead", "Manitoba", "Canada"}, {}},
			{{"Whitehorse Plains", "Manitoba", "Canada"}, {}},
			{{"Whitemouth", "Manitoba", "Canada"}, {}},
			{{"Whitewater", "Manitoba", "Canada"}, {}},
			{{"Winchester", "Manitoba", "Canada"}, {}},
			{{"Winnipeg Capital Region", "Manitoba", "Canada"}, {}},
			{{"Winnipeg census division", "Manitoba", "Canada"}, {}},
			{{"Woodlands", "Manitoba", "Canada"}, {}},
			{{"Woodworth", "Manitoba", "Canada"}, {}},

			{{"Alma", "New Brunswick", "Canada"}, {}},
			{{"Aroostook", "New Brunswick", "Canada"}, {}},
			{{"Atholville", "New Brunswick", "Canada"}, {}},
			{{"Baker-Brook", "New Brunswick", "Canada"}, {}},
			{{"Balmoral", "New Brunswick", "Canada"}, {}},
			{{"Bas-Caraquet", "New Brunswick", "Canada"}, {}},
			{{"Bath", "New Brunswick", "Canada"}, {}},
			{{"Bathurst", "New Brunswick", "Canada"}, {}},
			{{"Beaubassin-Est", "New Brunswick", "Canada"}, {}},
			{{"Belledune", "New Brunswick", "Canada"}, {}},
			{{"Beresford", "New Brunswick", "Canada"}, {}},
			{{"Bertrand", "New Brunswick", "Canada"}, {}},
			{{"Blacks Harbour", "New Brunswick", "Canada"}, {}},
			{{"Blackville", "New Brunswick", "Canada"}, {}},
			{{"Bouctouche", "New Brunswick", "Canada"}, {}},
			{{"Cambridge-Narrows", "New Brunswick", "Canada"}, {}},
			{{"Campbellton", "New Brunswick", "Canada"}, {}},
			{{"Canterbury", "New Brunswick", "Canada"}, {}},
			{{"Cap-Pele", "New Brunswick", "Canada"}, {}},
			{{"Caraquet", "New Brunswick", "Canada"}, {}},
			{{"Centreville", "New Brunswick", "Canada"}, {}},
			{{"Charlo", "New Brunswick", "Canada"}, {}},
			{{"Chipman", "New Brunswick", "Canada"}, {}},
			{{"Clair", "New Brunswick", "Canada"}, {}},
			{{"Dalhousie", "New Brunswick", "Canada"}, {}},
			{{"Dieppe", "New Brunswick", "Canada"}, {}},
			{{"Doaktown", "New Brunswick", "Canada"}, {}},
			{{"Dorchester", "New Brunswick", "Canada"}, {}},
			{{"Drummond", "New Brunswick", "Canada"}, {}},
			{{"Edmundston", "New Brunswick", "Canada"}, {}},
			{{"Eel River Crossing", "New Brunswick", "Canada"}, {}},
			{{"Florenceville-Bristol", "New Brunswick", "Canada"}, {}},
			{{"Fredericton Junction", "New Brunswick", "Canada"}, {}},
			{{"Gagetown", "New Brunswick", "Canada"}, {}},
			{{"Grand Manan", "New Brunswick", "Canada"}, {}},
			{{"Grand Bay-Westfield", "New Brunswick", "Canada"}, {}},
			{{"Grand Falls/Grand-Sault", "New Brunswick", "Canada"}, {}},
			{{"Grande-Anse", "New Brunswick", "Canada"}, {}},
			{{"Hampton", "New Brunswick", "Canada"}, {}},
			{{"Hartland", "New Brunswick", "Canada"}, {}},
			{{"Harvey Station (York)", "New Brunswick", "Canada"}, {}},
			{{"Hillsborough", "New Brunswick", "Canada"}, {}},
			{{"Kedgwick", "New Brunswick", "Canada"}, {}},
			{{"Lac-Baker", "New Brunswick", "Canada"}, {}},
			{{"Lameque", "New Brunswick", "Canada"}, {}},
			{{"LeGoulet", "New Brunswick", "Canada"}, {}},
			{{"Maisonette", "New Brunswick", "Canada"}, {}},
			{{"McAdam", "New Brunswick", "Canada"}, {}},
			{{"Meductic", "New Brunswick", "Canada"}, {}},
			{{"Memramcook", "New Brunswick", "Canada"}, {}},
			{{"Millville", "New Brunswick", "Canada"}, {}},
			{{"Minto", "New Brunswick", "Canada"}, {}},
			{{"Miramichi", "New Brunswick", "Canada"}, {}},
			{{"Moncton", "New Brunswick", "Canada"}, {}},
			{{"Nackawic", "New Brunswick", "Canada"}, {}},
			{{"Neguac", "New Brunswick", "Canada"}, {}},
			{{"New Maryland", "New Brunswick", "Canada"}, {}},
			{{"Nigadoo", "New Brunswick", "Canada"}, {}},
			{{"Norton", "New Brunswick", "Canada"}, {}},
			{{"Oromocto", "New Brunswick", "Canada"}, {}},
			{{"Paquetville", "New Brunswick", "Canada"}, {}},
			{{"Perth-Andover", "New Brunswick", "Canada"}, {}},
			{{"Petitcodiac", "New Brunswick", "Canada"}, {}},
			{{"Petit-Rocher", "New Brunswick", "Canada"}, {}},
			{{"Plaster Rock", "New Brunswick", "Canada"}, {}},
			{{"Pointe-Verte", "New Brunswick", "Canada"}, {}},
			{{"Port Elgin", "New Brunswick", "Canada"}, {}},
			{{"Quispamsis", "New Brunswick", "Canada"}, {}},
			{{"Rexton", "New Brunswick", "Canada"}, {}},
			{{"Richibucto", "New Brunswick", "Canada"}, {}},
			{{"Riverside-Albert", "New Brunswick", "Canada"}, {}},
			{{"Riverview", "New Brunswick", "Canada"}, {}},
			{{"Riviere-Verte", "New Brunswick", "Canada"}, {}},
			{{"Rogersville", "New Brunswick", "Canada"}, {}},
			{{"Rothesay", "New Brunswick", "Canada"}, {}},
			{{"Sackville", "New Brunswick", "Canada"}, {}},
			{{"Saint John", "New Brunswick", "Canada"}, {}},
			{{"Saint Martins", "New Brunswick", "Canada"}, {}},
			{{"Saint-Leonard", "New Brunswick", "Canada"}, {}},
			{{"Salisbury", "New Brunswick", "Canada"}, {}},
			{{"Shediac", "New Brunswick", "Canada"}, {}},
			{{"Shippagan", "New Brunswick", "Canada"}, {}},
			{{"St. Andrews", "New Brunswick", "Canada"}, {}},
			{{"St. George", "New Brunswick", "Canada"}, {}},
			{{"St. uentin", "New Brunswick", "Canada"}, {}},
			{{"St. Stephen", "New Brunswick", "Canada"}, {}},
			{{"St-Andre", "New Brunswick", "Canada"}, {}},
			{{"St-Antoine", "New Brunswick", "Canada"}, {}},
			{{"St-Francois-de-Madawaska", "New Brunswick", "Canada"}, {}},
			{{"St-Hilaire", "New Brunswick", "Canada"}, {}},
			{{"St-Isidore", "New Brunswick", "Canada"}, {}},
			{{"St-Leolin", "New Brunswick", "Canada"}, {}},
			{{"St-Louis-de-Kent", "New Brunswick", "Canada"}, {}},
			{{"Stanley", "New Brunswick", "Canada"}, {}},
			{{"Ste-Anne-de-Madawaska", "New Brunswick", "Canada"}, {}},
			{{"Ste-Marie-St-Raphael", "New Brunswick", "Canada"}, {}},
			{{"Stonehaven", "New Brunswick", "Canada"}, {}},
			{{"Sussex Corner", "New Brunswick", "Canada"}, {}},
			{{"Sussex", "New Brunswick", "Canada"}, {}},
			{{"Tide Head", "New Brunswick", "Canada"}, {}},
			{{"Tracadie-Sheila", "New Brunswick", "Canada"}, {}},
			{{"Tracy", "New Brunswick", "Canada"}, {}},
			{{"Upper Miramichi", "New Brunswick", "Canada"}, {}},
			{{"Woodstock", "New Brunswick", "Canada"}, {}},

			{{"Annapolis County", "Nova Scotia", "Canada"}, {}},
			{{"Antigonish County", "Nova Scotia", "Canada"}, {}},
			{{"Cape Breton County", "Nova Scotia", "Canada"}, {}},
			{{"Colchester County", "Nova Scotia", "Canada"}, {}},
			{{"Cumberland County", "Nova Scotia", "Canada"}, {}},
			{{"Digby County", "Nova Scotia", "Canada"}, {}},
			{{"Guysborough County", "Nova Scotia", "Canada"}, {}},
			{{"Halifax County", "Nova Scotia", "Canada"}, {}},
			{{"Hants County", "Nova Scotia", "Canada"}, {}},
			{{"Inverness County", "Nova Scotia", "Canada"}, {}},
			{{"Kings County", "Nova Scotia", "Canada"}, {}},
			{{"Lunenburg County", "Nova Scotia", "Canada"}, {}},
			{{"Pictou County", "Nova Scotia", "Canada"}, {}},
			{{"Queens County", "Nova Scotia", "Canada"}, {}},
			{{"Richmond County", "Nova Scotia", "Canada"}, {}},
			{{"Shelburne County", "Nova Scotia", "Canada"}, {}},
			{{"Victoria County", "Nova Scotia", "Canada"}, {}},
			{{"Yarmouth County", "Nova Scotia", "Canada"}, {}},

			{{"Algoma", "Ontario", "Canada"}, {}},
			{{"Brant", "Ontario", "Canada"}, {}},
			{{"Bruce", "Ontario", "Canada"}, {}},
			{{"Chatham-Kent", "Ontario", "Canada"}, {}},
			{{"Cochrane", "Ontario", "Canada"}, {}},
			{{"Dufferin", "Ontario", "Canada"}, {}},
			{{"Durham", "Ontario", "Canada"}, {}},
			{{"Elgin", "Ontario", "Canada"}, {}},
			{{"Essex", "Ontario", "Canada"}, {}},
			{{"Frontenac", "Ontario", "Canada"}, {}},
			{{"Greater Sudbury", "Ontario", "Canada"}, {}},
			{{"Grey", "Ontario", "Canada"}, {}},
			{{"Haldimand", "Ontario", "Canada"}, {}},
			{{"Haliburton", "Ontario", "Canada"}, {}},
			{{"Halton", "Ontario", "Canada"}, {}},
			{{"Hamilton", "Ontario", "Canada"}, {}},
			{{"Hastings", "Ontario", "Canada"}, {}},
			{{"Huron", "Ontario", "Canada"}, {}},
			{{"Kawartha Lakes", "Ontario", "Canada"}, {}},
			{{"Kenora", "Ontario", "Canada"}, {}},
			{{"Lambton", "Ontario", "Canada"}, {}},
			{{"Lanark", "Ontario", "Canada"}, {}},
			{{"Leeds and Grenville", "Ontario", "Canada"}, {}},
			{{"Lennox and Addington", "Ontario", "Canada"}, {}},
			{{"Manitoulin", "Ontario", "Canada"}, {}},
			{{"Middlesex", "Ontario", "Canada"}, {}},
			{{"Muskoka", "Ontario", "Canada"}, {}},
			{{"Niagara", "Ontario", "Canada"}, {}},
			{{"Nipissing", "Ontario", "Canada"}, {}},
			{{"Norfolk", "Ontario", "Canada"}, {}},
			{{"Northumberland", "Ontario", "Canada"}, {}},
			{{"Ottawa", "Ontario", "Canada"}, {}},
			{{"Oxford", "Ontario", "Canada"}, {}},
			{{"Parry Sound", "Ontario", "Canada"}, {}},
			{{"Peel", "Ontario", "Canada"}, {}},
			{{"Perth", "Ontario", "Canada"}, {}},
			{{"Peterborough", "Ontario", "Canada"}, {}},
			{{"Prescott and Russell", "Ontario", "Canada"}, {}},
			{{"Prince Edward", "Ontario", "Canada"}, {}},
			{{"Rainy River", "Ontario", "Canada"}, {}},
			{{"Renfrew", "Ontario", "Canada"}, {}},
			{{"Simcoe", "Ontario", "Canada"}, {}},
			{{"Stormont", "Dundas and Glengarry", "Ontario", "Canada"}, {}},
			{{"Sudbury", "Ontario", "Canada"}, {}},
			{{"Thunder Bay", "Ontario", "Canada"}, {}},
			{{"Timiskaming", "Ontario", "Canada"}, {}},
			{{"Toronto", "Ontario", "Canada"}, {}},
			{{"Waterloo", "Ontario", "Canada"}, {}},
			{{"Wellington", "Ontario", "Canada"}, {}},
			{{"York", "Ontario", "Canada"}, {}},

			{{"Abitibi Territory", "Quebec", "Canada"}, {}},
			{{"Argenteuil County", "Quebec", "Canada"}, {}},
			{{"Arthabaska County", "Quebec", "Canada"}, {}},
			{{"Bagot County", "Quebec", "Canada"}, {}},
			{{"Beauce County", "Quebec", "Canada"}, {}},
			{{"Beauharnois County", "Quebec", "Canada"}, {}},
			{{"Bellechasse County", "Quebec", "Canada"}, {}},
			{{"Berthier County", "Quebec", "Canada"}, {}},
			{{"Bonaventure County", "Quebec", "Canada"}, {}},
			{{"Brome County", "Quebec", "Canada"}, {}},
			{{"Chambly County", "Quebec", "Canada"}, {}},
			{{"Champlain County", "Quebec", "Canada"}, {}},
			{{"Charlevoix-Est County", "Quebec", "Canada"}, {}},
			{{"Charlevoix-Ouest County", "Quebec", "Canada"}, {}},
			{{"Châteauguay County", "Quebec", "Canada"}, {}},
			{{"Chicoutimi County", "Quebec", "Canada"}, {}},
			{{"Compton County", "Quebec", "Canada"}, {}},
			{{"Deux-Montagnes County", "Quebec", "Canada"}, {}},
			{{"Dorchester County", "Quebec", "Canada"}, {}},
			{{"Drummond County", "Quebec", "Canada"}, {}},
			{{"Frontenac County", "Quebec", "Canada"}, {}},
			{{"Gaspé-Est County", "Quebec", "Canada"}, {}},
			{{"Gaspé-Ouest County", "Quebec", "Canada"}, {}},
			{{"Gatineau County", "Quebec", "Canada"}, {}},
			{{"Hull County", "Quebec", "Canada"}, {}},
			{{"Huntingdon County", "Quebec", "Canada"}, {}},
			{{"Iberville County", "Quebec", "Canada"}, {}},
			{{"Ile-de-Montréal County", "Quebec", "Canada"}, {}},
			{{"Ile-Jésus County", "Quebec", "Canada"}, {}},
			{{"Iles-de-la-Madeleine County", "Quebec", "Canada"}, {}},
			{{"Joliette County", "Quebec", "Canada"}, {}},
			{{"Kamouraska County", "Quebec", "Canada"}, {}},
			{{"Labelle County", "Quebec", "Canada"}, {}},
			{{"Laprairie County", "Quebec", "Canada"}, {}},
			{{"L''Assomption County", "Quebec", "Canada"}, {}},
			{{"Lévis County", "Quebec", "Canada"}, {}},
			{{"L''Islet County", "Quebec", "Canada"}, {}},
			{{"Lotbinière County", "Quebec", "Canada"}, {}},
			{{"Lac-Saint-Jean-Est County", "Quebec", "Canada"}, {}},
			{{"Lac-Saint-Jean-Ouest County", "Quebec", "Canada"}, {}},
			{{"Maskinongé County", "Quebec", "Canada"}, {}},
			{{"Matane County", "Quebec", "Canada"}, {}},
			{{"Matapédia County", "Quebec", "Canada"}, {}},
			{{"Mégantic County", "Quebec", "Canada"}, {}},
			{{"Missisquoi County", "Quebec", "Canada"}, {}},
			{{"Mistassini Territory", "Quebec", "Canada"}, {}},
			{{"Montcalm County", "Quebec", "Canada"}, {}},
			{{"Montmorency No. 1 County", "Quebec", "Canada"}, {}},
			{{"Montmorency No. 2 County", "Quebec", "Canada"}, {}},
			{{"Montmagny County", "Quebec", "Canada"}, {}},
			{{"Napierville County", "Quebec", "Canada"}, {}},
			{{"Nicolet County", "Quebec", "Canada"}, {}},
			{{"Nouveau-Quebec Territory", "Quebec", "Canada"}, {}},
			{{"Papineau County", "Quebec", "Canada"}, {}},
			{{"Pontiac County", "Quebec", "Canada"}, {}},
			{{"Portneuf County", "Quebec", "Canada"}, {}},
			{{"Québec County", "Quebec", "Canada"}, {}},
			{{"Richelieu County", "Quebec", "Canada"}, {}},
			{{"Richmond County", "Quebec", "Canada"}, {}},
			{{"Rimouski County", "Quebec", "Canada"}, {}},
			{{"Rivière-du-Loup County", "Quebec", "Canada"}, {}},
			{{"Rouville County", "Quebec", "Canada"}, {}},
			{{"Saint-Hyacinthe County", "Quebec", "Canada"}, {}},
			{{"Saint-Jean County", "Quebec", "Canada"}, {}},
			{{"Saint-Maurice County", "Quebec", "Canada"}, {}},
			{{"Saguenay County", "Quebec", "Canada"}, {}},
			{{"Shefford County", "Quebec", "Canada"}, {}},
			{{"Sherbrooke County", "Quebec", "Canada"}, {}},
			{{"Soulanges County", "Quebec", "Canada"}, {}},
			{{"Stanstead County", "Quebec", "Canada"}, {}},
			{{"Témiscouata County", "Quebec", "Canada"}, {}},
			{{"Témiscamingue County", "Quebec", "Canada"}, {}},
			{{"Terrebonne County", "Quebec", "Canada"}, {}},
			{{"Vaudreuil County", "Quebec", "Canada"}, {}},
			{{"Verchères County", "Quebec", "Canada"}, {}},
			{{"Wolfe County", "Quebec", "Canada"}, {}},
			{{"Yamaska County", "Quebec", "Canada"}, {}}};
	}
}
