package ws.daley.genealogy.db.xls;

public class XlsCountyUSOToZ
{
	public static String[][][] getNames()
	{
		return new String[][][]{
			{{"Adams County", "Ohio", "United States"}, {}},
			{{"Allen County", "Ohio", "United States"}, {}},
			{{"Ashland County", "Ohio", "United States"}, {}},
			{{"Ashtabula County", "Ohio", "United States"}, {}},
			{{"Athens County", "Ohio", "United States"}, {}},
			{{"Auglaize County", "Ohio", "United States"}, {}},
			{{"Belmont County", "Ohio", "United States"}, {}},
			{{"Brown County", "Ohio", "United States"}, {}},
			{{"Butler County", "Ohio", "United States"}, {}},
			{{"Carroll County", "Ohio", "United States"}, {}},
			{{"Champaign County", "Ohio", "United States"}, {}},
			{{"Clark County", "Ohio", "United States"}, {}},
			{{"Clermont County", "Ohio", "United States"}, {}},
			{{"Clinton County", "Ohio", "United States"}, {}},
			{{"Columbiana County", "Ohio", "United States"}, {}},
			{{"Coshocton County", "Ohio", "United States"}, {}},
			{{"Crawford County", "Ohio", "United States"}, {}},
			{{"Cuyahoga County", "Ohio", "United States"}, {}},
			{{"Darke County", "Ohio", "United States"}, {}},
			{{"Defiance County", "Ohio", "United States"}, {}},
			{{"Delaware County", "Ohio", "United States"}, {}},
			{{"Erie County", "Ohio", "United States"}, {}},
			{{"Fairfield County", "Ohio", "United States"}, {}},
			{{"Fayette County", "Ohio", "United States"}, {}},
			{{"Franklin County", "Ohio", "United States"}, {}},
			{{"Fulton County", "Ohio", "United States"}, {}},
			{{"Gallia County", "Ohio", "United States"}, {}},
			{{"Geauga County", "Ohio", "United States"}, {}},
			{{"Greene County", "Ohio", "United States"}, {}},
			{{"Guernsey County", "Ohio", "United States"}, {"Guernsey"}},
			{{"Hamilton County", "Ohio", "United States"}, {}},
			{{"Hancock County", "Ohio", "United States"}, {}},
			{{"Hardin County", "Ohio", "United States"}, {}},
			{{"Harrison County", "Ohio", "United States"}, {}},
			{{"Henry County", "Ohio", "United States"}, {}},
			{{"Highland County", "Ohio", "United States"}, {}},
			{{"Hocking County", "Ohio", "United States"}, {}},
			{{"Holmes County", "Ohio", "United States"}, {}},
			{{"Huron County", "Ohio", "United States"}, {}},
			{{"Jackson County", "Ohio", "United States"}, {}},
			{{"Jefferson County", "Ohio", "United States"}, {}},
			{{"Knox County", "Ohio", "United States"}, {}},
			{{"Lake County", "Ohio", "United States"}, {}},
			{{"Lawrence County", "Ohio", "United States"}, {}},
			{{"Licking County", "Ohio", "United States"}, {}},
			{{"Logan County", "Ohio", "United States"}, {}},
			{{"Lorain County", "Ohio", "United States"}, {}},
			{{"Lucas County", "Ohio", "United States"}, {}},
			{{"Madison County", "Ohio", "United States"}, {}},
			{{"Mahoning County", "Ohio", "United States"}, {}},
			{{"Marion County", "Ohio", "United States"}, {}},
			{{"Medina County", "Ohio", "United States"}, {}},
			{{"Meigs County", "Ohio", "United States"}, {}},
			{{"Mercer County", "Ohio", "United States"}, {}},
			{{"Miami County", "Ohio", "United States"}, {}},
			{{"Monroe County", "Ohio", "United States"}, {}},
			{{"Montgomery County", "Ohio", "United States"}, {}},
			{{"Morgan County", "Ohio", "United States"}, {}},
			{{"Morrow County", "Ohio", "United States"}, {}},
			{{"Muskingum County", "Ohio", "United States"}, {}},
			{{"Noble County", "Ohio", "United States"}, {}},
			{{"Ottawa County", "Ohio", "United States"}, {}},
			{{"Paulding County", "Ohio", "United States"}, {}},
			{{"Perry County", "Ohio", "United States"}, {}},
			{{"Pickaway County", "Ohio", "United States"}, {}},
			{{"Pike County", "Ohio", "United States"}, {}},
			{{"Portage County", "Ohio", "United States"}, {}},
			{{"Preble County", "Ohio", "United States"}, {}},
			{{"Putnam County", "Ohio", "United States"}, {}},
			{{"Richland County", "Ohio", "United States"}, {}},
			{{"Ross County", "Ohio", "United States"}, {}},
			{{"Sandusky County", "Ohio", "United States"}, {}},
			{{"Scioto County", "Ohio", "United States"}, {}},
			{{"Seneca County", "Ohio", "United States"}, {}},
			{{"Shelby County", "Ohio", "United States"}, {}},
			{{"Stark County", "Ohio", "United States"}, {}},
			{{"Summit County", "Ohio", "United States"}, {}},
			{{"Trumbull County", "Ohio", "United States"}, {}},
			{{"Tuscarawas County", "Ohio", "United States"}, {}},
			{{"Union County", "Ohio", "United States"}, {}},
			{{"Van Wert County", "Ohio", "United States"}, {}},
			{{"Vinton County", "Ohio", "United States"}, {}},
			{{"Warren County", "Ohio", "United States"}, {}},
			{{"Washington County", "Ohio", "United States"}, {}},
			{{"Wayne County", "Ohio", "United States"}, {}},
			{{"Williams County", "Ohio", "United States"}, {}},
			{{"Wood County", "Ohio", "United States"}, {}},
			{{"Wyandot County", "Ohio", "United States"}, {}},

			{{"Adair County", "Oklahoma", "United States"}, {}},
			{{"Alfalfa County", "Oklahoma", "United States"}, {}},
			{{"Atoka County", "Oklahoma", "United States"}, {}},
			{{"Beaver County", "Oklahoma", "United States"}, {}},
			{{"Beckham County", "Oklahoma", "United States"}, {}},
			{{"Blaine County", "Oklahoma", "United States"}, {}},
			{{"Bryan County", "Oklahoma", "United States"}, {}},
			{{"Caddo County", "Oklahoma", "United States"}, {}},
			{{"Canadian County", "Oklahoma", "United States"}, {}},
			{{"Carter County", "Oklahoma", "United States"}, {}},
			{{"Cherokee County", "Oklahoma", "United States"}, {}},
			{{"Choctaw County", "Oklahoma", "United States"}, {}},
			{{"Cimarron County", "Oklahoma", "United States"}, {}},
			{{"Cleveland County", "Oklahoma", "United States"}, {}},
			{{"Coal County", "Oklahoma", "United States"}, {}},
			{{"Comanche County", "Oklahoma", "United States"}, {}},
			{{"Cotton County", "Oklahoma", "United States"}, {}},
			{{"Craig County", "Oklahoma", "United States"}, {}},
			{{"Creek County", "Oklahoma", "United States"}, {}},
			{{"Custer County", "Oklahoma", "United States"}, {}},
			{{"Delaware County", "Oklahoma", "United States"}, {}},
			{{"Dewey County", "Oklahoma", "United States"}, {}},
			{{"Ellis County", "Oklahoma", "United States"}, {}},
			{{"Garfield County", "Oklahoma", "United States"}, {}},
			{{"Garvin County", "Oklahoma", "United States"}, {}},
			{{"Grady County", "Oklahoma", "United States"}, {}},
			{{"Grant County", "Oklahoma", "United States"}, {}},
			{{"Greer County", "Oklahoma", "United States"}, {}},
			{{"Harmon County", "Oklahoma", "United States"}, {}},
			{{"Harper County", "Oklahoma", "United States"}, {}},
			{{"Haskell County", "Oklahoma", "United States"}, {}},
			{{"Hughes County", "Oklahoma", "United States"}, {}},
			{{"Jackson County", "Oklahoma", "United States"}, {}},
			{{"Jefferson County", "Oklahoma", "United States"}, {}},
			{{"Johnston County", "Oklahoma", "United States"}, {}},
			{{"Kay County", "Oklahoma", "United States"}, {}},
			{{"Kingfisher County", "Oklahoma", "United States"}, {}},
			{{"Kiowa County", "Oklahoma", "United States"}, {}},
			{{"Latimer County", "Oklahoma", "United States"}, {}},
			{{"Le Flore County", "Oklahoma", "United States"}, {}},
			{{"Lincoln County", "Oklahoma", "United States"}, {}},
			{{"Logan County", "Oklahoma", "United States"}, {}},
			{{"Love County", "Oklahoma", "United States"}, {}},
			{{"Major County", "Oklahoma", "United States"}, {}},
			{{"Marshall County", "Oklahoma", "United States"}, {}},
			{{"Mayes County", "Oklahoma", "United States"}, {}},
			{{"McClain County", "Oklahoma", "United States"}, {}},
			{{"McCurtain County", "Oklahoma", "United States"}, {}},
			{{"McIntosh County", "Oklahoma", "United States"}, {"McIntosh", "Mcintosh"}},
			{{"Murray County", "Oklahoma", "United States"}, {}},
			{{"Muskogee County", "Oklahoma", "United States"}, {"Muskogee"}},
			{{"Noble County", "Oklahoma", "United States"}, {}},
			{{"Nowata County", "Oklahoma", "United States"}, {}},
			{{"Okfuskee County", "Oklahoma", "United States"}, {}},
			{{"Oklahoma County", "Oklahoma", "United States"}, {}},
			{{"Okmulgee County", "Oklahoma", "United States"}, {}},
			{{"Osage County", "Oklahoma", "United States"}, {}},
			{{"Ottawa County", "Oklahoma", "United States"}, {}},
			{{"Pawnee County", "Oklahoma", "United States"}, {}},
			{{"Payne County", "Oklahoma", "United States"}, {}},
			{{"Pittsburg County", "Oklahoma", "United States"}, {}},
			{{"Pontotoc County", "Oklahoma", "United States"}, {}},
			{{"Pottawatomie County", "Oklahoma", "United States"}, {}},
			{{"Pushmataha County", "Oklahoma", "United States"}, {}},
			{{"Roger Mills County", "Oklahoma", "United States"}, {}},
			{{"Rogers County", "Oklahoma", "United States"}, {}},
			{{"Seminole County", "Oklahoma", "United States"}, {}},
			{{"Sequoyah County", "Oklahoma", "United States"}, {}},
			{{"Stephens County", "Oklahoma", "United States"}, {}},
			{{"Texas County", "Oklahoma", "United States"}, {}},
			{{"Tillman County", "Oklahoma", "United States"}, {}},
			{{"Tulsa County", "Oklahoma", "United States"}, {"Tulsa"}},
			{{"Wagoner County", "Oklahoma", "United States"}, {}},
			{{"Washington County", "Oklahoma", "United States"}, {}},
			{{"Washita County", "Oklahoma", "United States"}, {}},
			{{"Woods County", "Oklahoma", "United States"}, {}},
			{{"Woodward County", "Oklahoma", "United States"}, {}},

			{{"Baker County", "Oregon", "United States"}, {}},
			{{"Benton County", "Oregon", "United States"}, {}},
			{{"Clackamas County", "Oregon", "United States"}, {}},
			{{"Clatsop County", "Oregon", "United States"}, {}},
			{{"Columbia County", "Oregon", "United States"}, {}},
			{{"Coos County", "Oregon", "United States"}, {}},
			{{"Crook County", "Oregon", "United States"}, {}},
			{{"Curry County", "Oregon", "United States"}, {}},
			{{"Deschutes County", "Oregon", "United States"}, {}},
			{{"Douglas County", "Oregon", "United States"}, {}},
			{{"Gilliam County", "Oregon", "United States"}, {}},
			{{"Grant County", "Oregon", "United States"}, {}},
			{{"Harney County", "Oregon", "United States"}, {}},
			{{"Hood River County", "Oregon", "United States"}, {}},
			{{"Jackson County", "Oregon", "United States"}, {}},
			{{"Jefferson County", "Oregon", "United States"}, {}},
			{{"Josephine County", "Oregon", "United States"}, {}},
			{{"Klamath County", "Oregon", "United States"}, {}},
			{{"Lake County", "Oregon", "United States"}, {}},
			{{"Lane County", "Oregon", "United States"}, {}},
			{{"Lincoln County", "Oregon", "United States"}, {}},
			{{"Linn County", "Oregon", "United States"}, {}},
			{{"Malheur County", "Oregon", "United States"}, {}},
			{{"Marion County", "Oregon", "United States"}, {}},
			{{"Morrow County", "Oregon", "United States"}, {}},
			{{"Multnomah County", "Oregon", "United States"}, {}},
			{{"Polk County", "Oregon", "United States"}, {}},
			{{"Sherman County", "Oregon", "United States"}, {}},
			{{"Tillamook County", "Oregon", "United States"}, {}},
			{{"Umatilla County", "Oregon", "United States"}, {}},
			{{"Union County", "Oregon", "United States"}, {}},
			{{"Wallowa County", "Oregon", "United States"}, {}},
			{{"Wasco County", "Oregon", "United States"}, {}},
			{{"Washington County", "Oregon", "United States"}, {}},
			{{"Wheeler County", "Oregon", "United States"}, {}},
			{{"Yamhill County", "Oregon", "United States"}, {}},

			{{"Adams County", "Pennsylvania", "United States"}, {}},
			{{"Allegheny County", "Pennsylvania", "United States"}, {}},
			{{"Armstrong County", "Pennsylvania", "United States"}, {}},
			{{"Beaver County", "Pennsylvania", "United States"}, {}},
			{{"Bedford County", "Pennsylvania", "United States"}, {}},
			{{"Berks County", "Pennsylvania", "United States"}, {}},
			{{"Blair County", "Pennsylvania", "United States"}, {}},
			{{"Bradford County", "Pennsylvania", "United States"}, {}},
			{{"Bucks County", "Pennsylvania", "United States"}, {}},
			{{"Butler County", "Pennsylvania", "United States"}, {}},
			{{"Cambria County", "Pennsylvania", "United States"}, {}},
			{{"Cameron County", "Pennsylvania", "United States"}, {}},
			{{"Carbon County", "Pennsylvania", "United States"}, {}},
			{{"Centre County", "Pennsylvania", "United States"}, {}},
			{{"Chester County", "Pennsylvania", "United States"}, {}},
			{{"Clarion County", "Pennsylvania", "United States"}, {}},
			{{"Clearfield County", "Pennsylvania", "United States"}, {}},
			{{"Clinton County", "Pennsylvania", "United States"}, {}},
			{{"Columbia County", "Pennsylvania", "United States"}, {}},
			{{"Crawford County", "Pennsylvania", "United States"}, {}},
			{{"Cumberland County", "Pennsylvania", "United States"}, {}},
			{{"Dauphin County", "Pennsylvania", "United States"}, {}},
			{{"Delaware County", "Pennsylvania", "United States"}, {}},
			{{"Elk County", "Pennsylvania", "United States"}, {}},
			{{"Erie County", "Pennsylvania", "United States"}, {}},
			{{"Fayette County", "Pennsylvania", "United States"}, {}},
			{{"Forest County", "Pennsylvania", "United States"}, {}},
			{{"Franklin County", "Pennsylvania", "United States"}, {}},
			{{"Fulton County", "Pennsylvania", "United States"}, {}},
			{{"Greene County", "Pennsylvania", "United States"}, {}},
			{{"Huntingdon County", "Pennsylvania", "United States"}, {}},
			{{"Indiana County", "Pennsylvania", "United States"}, {}},
			{{"Jefferson County", "Pennsylvania", "United States"}, {}},
			{{"Juniata County", "Pennsylvania", "United States"}, {}},
			{{"Lackawanna County", "Pennsylvania", "United States"}, {}},
			{{"Lancaster County", "Pennsylvania", "United States"}, {}},
			{{"Lawrence County", "Pennsylvania", "United States"}, {}},
			{{"Lebanon County", "Pennsylvania", "United States"}, {}},
			{{"Lehigh County", "Pennsylvania", "United States"}, {}},
			{{"Luzerne County", "Pennsylvania", "United States"}, {}},
			{{"Lycoming County", "Pennsylvania", "United States"}, {}},
			{{"McKean County", "Pennsylvania", "United States"}, {}},
			{{"Mercer County", "Pennsylvania", "United States"}, {}},
			{{"Mifflin County", "Pennsylvania", "United States"}, {}},
			{{"Monroe County", "Pennsylvania", "United States"}, {}},
			{{"Montgomery County", "Pennsylvania", "United States"}, {}},
			{{"Montour County", "Pennsylvania", "United States"}, {}},
			{{"Northampton County", "Pennsylvania", "United States"}, {}},
			{{"Northumberland County", "Pennsylvania", "United States"}, {}},
			{{"Perry County", "Pennsylvania", "United States"}, {}},
			{{"Philadelphia County", "Pennsylvania", "United States"}, {}},
			{{"Pike County", "Pennsylvania", "United States"}, {}},
			{{"Potter County", "Pennsylvania", "United States"}, {}},
			{{"Schuylkill County", "Pennsylvania", "United States"}, {}},
			{{"Snyder County", "Pennsylvania", "United States"}, {}},
			{{"Somerset County", "Pennsylvania", "United States"}, {}},
			{{"Sullivan County", "Pennsylvania", "United States"}, {}},
			{{"Susquehanna County", "Pennsylvania", "United States"}, {}},
			{{"Tioga County", "Pennsylvania", "United States"}, {}},
			{{"Union County", "Pennsylvania", "United States"}, {}},
			{{"Venango County", "Pennsylvania", "United States"}, {}},
			{{"Warren County", "Pennsylvania", "United States"}, {}},
			{{"Washington County", "Pennsylvania", "United States"}, {}},
			{{"Wayne County", "Pennsylvania", "United States"}, {}},
			{{"Westmoreland County", "Pennsylvania", "United States"}, {}},
			{{"Wyoming County", "Pennsylvania", "United States"}, {}},
			{{"York County", "Pennsylvania", "United States"}, {}},

			{{"Bristol County", "Rhode Island", "United States"}, {}},
			{{"Kent County", "Rhode Island", "United States"}, {}},
			{{"Newport County", "Rhode Island", "United States"}, {}},
			{{"Providence County", "Rhode Island", "United States"}, {}},
			{{"Washington County", "Rhode Island", "United States"}, {}},

			{{"Abbeville County", "South Carolina", "United States"}, {}},
			{{"Aiken County", "South Carolina", "United States"}, {}},
			{{"Allendale County", "South Carolina", "United States"}, {}},
			{{"Anderson County", "South Carolina", "United States"}, {}},
			{{"Bamberg County", "South Carolina", "United States"}, {}},
			{{"Barnwell County", "South Carolina", "United States"}, {}},
			{{"Beaufort County", "South Carolina", "United States"}, {}},
			{{"Berkeley County", "South Carolina", "United States"}, {}},
			{{"Calhoun County", "South Carolina", "United States"}, {}},
			{{"Charleston County", "South Carolina", "United States"}, {}},
			{{"Cherokee County", "South Carolina", "United States"}, {}},
			{{"Chester County", "South Carolina", "United States"}, {}},
			{{"Chesterfield County", "South Carolina", "United States"}, {}},
			{{"Clarendon County", "South Carolina", "United States"}, {}},
			{{"Colleton County", "South Carolina", "United States"}, {}},
			{{"Darlington County", "South Carolina", "United States"}, {}},
			{{"Dillon County", "South Carolina", "United States"}, {}},
			{{"Dorchester County", "South Carolina", "United States"}, {}},
			{{"Edgefield County", "South Carolina", "United States"}, {}},
			{{"Fairfield County", "South Carolina", "United States"}, {}},
			{{"Florence County", "South Carolina", "United States"}, {}},
			{{"Georgetown County", "South Carolina", "United States"}, {}},
			{{"Greenville County", "South Carolina", "United States"}, {}},
			{{"Greenwood County", "South Carolina", "United States"}, {}},
			{{"Hampton County", "South Carolina", "United States"}, {}},
			{{"Horry County", "South Carolina", "United States"}, {}},
			{{"Jasper County", "South Carolina", "United States"}, {}},
			{{"Kershaw County", "South Carolina", "United States"}, {}},
			{{"Lancaster County", "South Carolina", "United States"}, {}},
			{{"Laurens County", "South Carolina", "United States"}, {}},
			{{"Lee County", "South Carolina", "United States"}, {}},
			{{"Lexington County", "South Carolina", "United States"}, {}},
			{{"Marion County", "South Carolina", "United States"}, {}},
			{{"Marlboro County", "South Carolina", "United States"}, {}},
			{{"McCormick County", "South Carolina", "United States"}, {}},
			{{"Newberry County", "South Carolina", "United States"}, {}},
			{{"Oconee County", "South Carolina", "United States"}, {}},
			{{"Orangeburg County", "South Carolina", "United States"}, {}},
			{{"Pickens County", "South Carolina", "United States"}, {}},
			{{"Richland County", "South Carolina", "United States"}, {}},
			{{"Saluda County", "South Carolina", "United States"}, {}},
			{{"Spartanburg County", "South Carolina", "United States"}, {}},
			{{"Sumter County", "South Carolina", "United States"}, {}},
			{{"Union County", "South Carolina", "United States"}, {}},
			{{"Williamsburg County", "South Carolina", "United States"}, {}},
			{{"York County", "South Carolina", "United States"}, {}},

			{{"Aurora County", "South Dakota", "United States"}, {}},
			{{"Beadle County", "South Dakota", "United States"}, {}},
			{{"Bennett County", "South Dakota", "United States"}, {}},
			{{"Bon Homme County", "South Dakota", "United States"}, {}},
			{{"Brookings County", "South Dakota", "United States"}, {}},
			{{"Brown County", "South Dakota", "United States"}, {}},
			{{"Brule County", "South Dakota", "United States"}, {}},
			{{"Buffalo County", "South Dakota", "United States"}, {}},
			{{"Butte County", "South Dakota", "United States"}, {}},
			{{"Campbell County", "South Dakota", "United States"}, {}},
			{{"Charles Mix County", "South Dakota", "United States"}, {}},
			{{"Clark County", "South Dakota", "United States"}, {}},
			{{"Clay County", "South Dakota", "United States"}, {}},
			{{"Codington County", "South Dakota", "United States"}, {}},
			{{"Corson County", "South Dakota", "United States"}, {}},
			{{"Custer County", "South Dakota", "United States"}, {}},
			{{"Davison County", "South Dakota", "United States"}, {}},
			{{"Day County", "South Dakota", "United States"}, {}},
			{{"Deuel County", "South Dakota", "United States"}, {}},
			{{"Dewey County", "South Dakota", "United States"}, {}},
			{{"Douglas County", "South Dakota", "United States"}, {}},
			{{"Edmunds County", "South Dakota", "United States"}, {}},
			{{"Fall River County", "South Dakota", "United States"}, {}},
			{{"Faulk County", "South Dakota", "United States"}, {}},
			{{"Grant County", "South Dakota", "United States"}, {}},
			{{"Gregory County", "South Dakota", "United States"}, {}},
			{{"Haakon County", "South Dakota", "United States"}, {}},
			{{"Hamlin County", "South Dakota", "United States"}, {}},
			{{"Hand County", "South Dakota", "United States"}, {}},
			{{"Hanson County", "South Dakota", "United States"}, {}},
			{{"Harding County", "South Dakota", "United States"}, {}},
			{{"Hughes County", "South Dakota", "United States"}, {}},
			{{"Hutchinson County", "South Dakota", "United States"}, {}},
			{{"Hyde County", "South Dakota", "United States"}, {}},
			{{"Jackson County", "South Dakota", "United States"}, {}},
			{{"Jerauld County", "South Dakota", "United States"}, {}},
			{{"Jones County", "South Dakota", "United States"}, {}},
			{{"Kingsbury County", "South Dakota", "United States"}, {}},
			{{"Lake County", "South Dakota", "United States"}, {}},
			{{"Lawrence County", "South Dakota", "United States"}, {}},
			{{"Lincoln County", "South Dakota", "United States"}, {}},
			{{"Lyman County", "South Dakota", "United States"}, {}},
			{{"Marshall County", "South Dakota", "United States"}, {}},
			{{"McCook County", "South Dakota", "United States"}, {}},
			{{"McPherson County", "South Dakota", "United States"}, {}},
			{{"Meade County", "South Dakota", "United States"}, {}},
			{{"Mellette County", "South Dakota", "United States"}, {}},
			{{"Miner County", "South Dakota", "United States"}, {}},
			{{"Minnehaha County", "South Dakota", "United States"}, {}},
			{{"Moody County", "South Dakota", "United States"}, {}},
			{{"Pennington County", "South Dakota", "United States"}, {}},
			{{"Perkins County", "South Dakota", "United States"}, {}},
			{{"Potter County", "South Dakota", "United States"}, {}},
			{{"Roberts County", "South Dakota", "United States"}, {}},
			{{"Sanborn County", "South Dakota", "United States"}, {}},
			{{"Shannon County", "South Dakota", "United States"}, {}},
			{{"Spink County", "South Dakota", "United States"}, {}},
			{{"Stanley County", "South Dakota", "United States"}, {}},
			{{"Sully County", "South Dakota", "United States"}, {}},
			{{"Todd County", "South Dakota", "United States"}, {}},
			{{"Tripp County", "South Dakota", "United States"}, {}},
			{{"Turner County", "South Dakota", "United States"}, {}},
			{{"Union County", "South Dakota", "United States"}, {}},
			{{"Walworth County", "South Dakota", "United States"}, {}},
			{{"Yankton County", "South Dakota", "United States"}, {}},
			{{"Ziebach County", "South Dakota", "United States"}, {}},

			{{"Anderson County", "Tennessee", "United States"}, {}},
			{{"Bedford County", "Tennessee", "United States"}, {}},
			{{"Benton County", "Tennessee", "United States"}, {}},
			{{"Bledsoe County", "Tennessee", "United States"}, {}},
			{{"Blount County", "Tennessee", "United States"}, {}},
			{{"Bradley County", "Tennessee", "United States"}, {}},
			{{"Campbell County", "Tennessee", "United States"}, {}},
			{{"Cannon County", "Tennessee", "United States"}, {}},
			{{"Carroll County", "Tennessee", "United States"}, {}},
			{{"Carter County", "Tennessee", "United States"}, {}},
			{{"Cheatham County", "Tennessee", "United States"}, {}},
			{{"Chester County", "Tennessee", "United States"}, {}},
			{{"Claiborne County", "Tennessee", "United States"}, {}},
			{{"Clay County", "Tennessee", "United States"}, {}},
			{{"Cocke County", "Tennessee", "United States"}, {}},
			{{"Coffee County", "Tennessee", "United States"}, {}},
			{{"Crockett County", "Tennessee", "United States"}, {}},
			{{"Cumberland County", "Tennessee", "United States"}, {}},
			{{"Davidson County", "Tennessee", "United States"}, {}},
			{{"Decatur County", "Tennessee", "United States"}, {}},
			{{"DeKalb County", "Tennessee", "United States"}, {}},
			{{"Dickson County", "Tennessee", "United States"}, {}},
			{{"Dyer County", "Tennessee", "United States"}, {}},
			{{"Fayette County", "Tennessee", "United States"}, {}},
			{{"Fentress County", "Tennessee", "United States"}, {}},
			{{"Franklin County", "Tennessee", "United States"}, {}},
			{{"Gibson County", "Tennessee", "United States"}, {}},
			{{"Giles County", "Tennessee", "United States"}, {}},
			{{"Grainger County", "Tennessee", "United States"}, {}},
			{{"Greene County", "Tennessee", "United States"}, {}},
			{{"Grundy County", "Tennessee", "United States"}, {}},
			{{"Hamblen County", "Tennessee", "United States"}, {}},
			{{"Hamilton County", "Tennessee", "United States"}, {}},
			{{"Hancock County", "Tennessee", "United States"}, {}},
			{{"Hardeman County", "Tennessee", "United States"}, {}},
			{{"Hardin County", "Tennessee", "United States"}, {}},
			{{"Hawkins County", "Tennessee", "United States"}, {}},
			{{"Haywood County", "Tennessee", "United States"}, {}},
			{{"Henderson County", "Tennessee", "United States"}, {}},
			{{"Henry County", "Tennessee", "United States"}, {"Henry"}},
			{{"Hickman County", "Tennessee", "United States"}, {}},
			{{"Houston County", "Tennessee", "United States"}, {}},
			{{"Humphreys County", "Tennessee", "United States"}, {}},
			{{"Jackson County", "Tennessee", "United States"}, {}},
			{{"Jefferson County", "Tennessee", "United States"}, {}},
			{{"Johnson County", "Tennessee", "United States"}, {}},
			{{"Knox County", "Tennessee", "United States"}, {}},
			{{"Lake County", "Tennessee", "United States"}, {}},
			{{"Lauderdale County", "Tennessee", "United States"}, {}},
			{{"Lawrence County", "Tennessee", "United States"}, {}},
			{{"Lewis County", "Tennessee", "United States"}, {}},
			{{"Lincoln County", "Tennessee", "United States"}, {}},
			{{"Loudon County", "Tennessee", "United States"}, {}},
			{{"Macon County", "Tennessee", "United States"}, {}},
			{{"Madison County", "Tennessee", "United States"}, {}},
			{{"Marion County", "Tennessee", "United States"}, {}},
			{{"Marshall County", "Tennessee", "United States"}, {}},
			{{"Maury County", "Tennessee", "United States"}, {}},
			{{"McMinn County", "Tennessee", "United States"}, {}},
			{{"McNairy County", "Tennessee", "United States"}, {}},
			{{"Meigs County", "Tennessee", "United States"}, {}},
			{{"Monroe County", "Tennessee", "United States"}, {}},
			{{"Montgomery County", "Tennessee", "United States"}, {}},
			{{"Moore County", "Tennessee", "United States"}, {}},
			{{"Morgan County", "Tennessee", "United States"}, {}},
			{{"Obion County", "Tennessee", "United States"}, {}},
			{{"Overton County", "Tennessee", "United States"}, {}},
			{{"Perry County", "Tennessee", "United States"}, {}},
			{{"Pickett County", "Tennessee", "United States"}, {}},
			{{"Polk County", "Tennessee", "United States"}, {}},
			{{"Putnam County", "Tennessee", "United States"}, {}},
			{{"Rhea County", "Tennessee", "United States"}, {}},
			{{"Roane County", "Tennessee", "United States"}, {}},
			{{"Robertson County", "Tennessee", "United States"}, {}},
			{{"Rutherford County", "Tennessee", "United States"}, {}},
			{{"Scott County", "Tennessee", "United States"}, {}},
			{{"Sequatchie County", "Tennessee", "United States"}, {}},
			{{"Sevier County", "Tennessee", "United States"}, {}},
			{{"Shelby County", "Tennessee", "United States"}, {}},
			{{"Smith County", "Tennessee", "United States"}, {}},
			{{"Stewart County", "Tennessee", "United States"}, {}},
			{{"Sullivan County", "Tennessee", "United States"}, {}},
			{{"Sumner County", "Tennessee", "United States"}, {}},
			{{"Tipton County", "Tennessee", "United States"}, {}},
			{{"Trousdale County", "Tennessee", "United States"}, {}},
			{{"Unicoi County", "Tennessee", "United States"}, {}},
			{{"Union County", "Tennessee", "United States"}, {}},
			{{"Van Buren County", "Tennessee", "United States"}, {}},
			{{"Warren County", "Tennessee", "United States"}, {}},
			{{"Washington County", "Tennessee", "United States"}, {}},
			{{"Wayne County", "Tennessee", "United States"}, {}},
			{{"Weakley County", "Tennessee", "United States"}, {}},
			{{"White County", "Tennessee", "United States"}, {}},
			{{"Williamson County", "Tennessee", "United States"}, {}},
			{{"Wilson County", "Tennessee", "United States"}, {}},

			{{"Anderson County", "Texas", "United States"}, {}},
			{{"Andrews County", "Texas", "United States"}, {}},
			{{"Angelina County", "Texas", "United States"}, {}},
			{{"Aransas County", "Texas", "United States"}, {}},
			{{"Archer County", "Texas", "United States"}, {}},
			{{"Armstrong County", "Texas", "United States"}, {}},
			{{"Atascosa County", "Texas", "United States"}, {}},
			{{"Austin County", "Texas", "United States"}, {}},
			{{"Bailey County", "Texas", "United States"}, {}},
			{{"Bandera County", "Texas", "United States"}, {}},
			{{"Bastrop County", "Texas", "United States"}, {}},
			{{"Baylor County", "Texas", "United States"}, {}},
			{{"Bee County", "Texas", "United States"}, {}},
			{{"Bell County", "Texas", "United States"}, {}},
			{{"Bexar County", "Texas", "United States"}, {}},
			{{"Blanco County", "Texas", "United States"}, {}},
			{{"Borden County", "Texas", "United States"}, {}},
			{{"Bosque County", "Texas", "United States"}, {}},
			{{"Bowie County", "Texas", "United States"}, {}},
			{{"Brazoria County", "Texas", "United States"}, {}},
			{{"Brazos County", "Texas", "United States"}, {}},
			{{"Brewster County", "Texas", "United States"}, {}},
			{{"Briscoe County", "Texas", "United States"}, {}},
			{{"Brooks County", "Texas", "United States"}, {}},
			{{"Brown County", "Texas", "United States"}, {}},
			{{"Burleson County", "Texas", "United States"}, {}},
			{{"Burnet County", "Texas", "United States"}, {}},
			{{"Caldwell County", "Texas", "United States"}, {}},
			{{"Calhoun County", "Texas", "United States"}, {}},
			{{"Callahan County", "Texas", "United States"}, {}},
			{{"Cameron County", "Texas", "United States"}, {}},
			{{"Camp County", "Texas", "United States"}, {}},
			{{"Carson County", "Texas", "United States"}, {}},
			{{"Cass County", "Texas", "United States"}, {}},
			{{"Castro County", "Texas", "United States"}, {}},
			{{"Chambers County", "Texas", "United States"}, {}},
			{{"Cherokee County", "Texas", "United States"}, {}},
			{{"Childress County", "Texas", "United States"}, {}},
			{{"Clay County", "Texas", "United States"}, {}},
			{{"Cochran County", "Texas", "United States"}, {}},
			{{"Coke County", "Texas", "United States"}, {}},
			{{"Coleman County", "Texas", "United States"}, {}},
			{{"Collin County", "Texas", "United States"}, {}},
			{{"Collingsworth County", "Texas", "United States"}, {}},
			{{"Colorado County", "Texas", "United States"}, {}},
			{{"Comal County", "Texas", "United States"}, {}},
			{{"Comanche County", "Texas", "United States"}, {}},
			{{"Concho County", "Texas", "United States"}, {}},
			{{"Cooke County", "Texas", "United States"}, {}},
			{{"Coryell County", "Texas", "United States"}, {}},
			{{"Cottle County", "Texas", "United States"}, {}},
			{{"Crane County", "Texas", "United States"}, {}},
			{{"Crockett County", "Texas", "United States"}, {}},
			{{"Crosby County", "Texas", "United States"}, {}},
			{{"Culberson County", "Texas", "United States"}, {}},
			{{"Dallam County", "Texas", "United States"}, {}},
			{{"Dallas County", "Texas", "United States"}, {}},
			{{"Dawson County", "Texas", "United States"}, {}},
			{{"Deaf Smith County", "Texas", "United States"}, {}},
			{{"Delta County", "Texas", "United States"}, {}},
			{{"Denton County", "Texas", "United States"}, {}},
			{{"DeWitt County", "Texas", "United States"}, {}},
			{{"Dickens County", "Texas", "United States"}, {}},
			{{"Dimmit County", "Texas", "United States"}, {}},
			{{"Donley County", "Texas", "United States"}, {}},
			{{"Duval County", "Texas", "United States"}, {}},
			{{"Eastland County", "Texas", "United States"}, {}},
			{{"Ector County", "Texas", "United States"}, {}},
			{{"Edwards County", "Texas", "United States"}, {}},
			{{"Ellis County", "Texas", "United States"}, {}},
			{{"El Paso County", "Texas", "United States"}, {}},
			{{"Erath County", "Texas", "United States"}, {}},
			{{"Falls County", "Texas", "United States"}, {}},
			{{"Fannin County", "Texas", "United States"}, {}},
			{{"Fayette County", "Texas", "United States"}, {}},
			{{"Fisher County", "Texas", "United States"}, {}},
			{{"Floyd County", "Texas", "United States"}, {}},
			{{"Foard County", "Texas", "United States"}, {}},
			{{"Fort Bend County", "Texas", "United States"}, {}},
			{{"Franklin County", "Texas", "United States"}, {}},
			{{"Freestone County", "Texas", "United States"}, {}},
			{{"Frio County", "Texas", "United States"}, {}},
			{{"Gaines County", "Texas", "United States"}, {}},
			{{"Galveston County", "Texas", "United States"}, {}},
			{{"Garza County", "Texas", "United States"}, {}},
			{{"Gillespie County", "Texas", "United States"}, {}},
			{{"Glasscock County", "Texas", "United States"}, {}},
			{{"Goliad County", "Texas", "United States"}, {}},
			{{"Gonzales County", "Texas", "United States"}, {}},
			{{"Gray County", "Texas", "United States"}, {}},
			{{"Grayson County", "Texas", "United States"}, {}},
			{{"Gregg County", "Texas", "United States"}, {}},
			{{"Grimes County", "Texas", "United States"}, {}},
			{{"Guadalupe County", "Texas", "United States"}, {}},
			{{"Hale County", "Texas", "United States"}, {}},
			{{"Hall County", "Texas", "United States"}, {}},
			{{"Hamilton County", "Texas", "United States"}, {}},
			{{"Hansford County", "Texas", "United States"}, {}},
			{{"Hardeman County", "Texas", "United States"}, {}},
			{{"Hardin County", "Texas", "United States"}, {}},
			{{"Harris County", "Texas", "United States"}, {}},
			{{"Harrison County", "Texas", "United States"}, {}},
			{{"Hartley County", "Texas", "United States"}, {}},
			{{"Haskell County", "Texas", "United States"}, {}},
			{{"Hays County", "Texas", "United States"}, {}},
			{{"Hemphill County", "Texas", "United States"}, {}},
			{{"Henderson County", "Texas", "United States"}, {}},
			{{"Hidalgo County", "Texas", "United States"}, {}},
			{{"Hill County", "Texas", "United States"}, {}},
			{{"Hockley County", "Texas", "United States"}, {}},
			{{"Hood County", "Texas", "United States"}, {}},
			{{"Hopkins County", "Texas", "United States"}, {}},
			{{"Houston County", "Texas", "United States"}, {}},
			{{"Howard County", "Texas", "United States"}, {}},
			{{"Hudspeth County", "Texas", "United States"}, {}},
			{{"Hunt County", "Texas", "United States"}, {}},
			{{"Hutchinson County", "Texas", "United States"}, {}},
			{{"Irion County", "Texas", "United States"}, {}},
			{{"Jack County", "Texas", "United States"}, {}},
			{{"Jackson County", "Texas", "United States"}, {}},
			{{"Jasper County", "Texas", "United States"}, {}},
			{{"Jeff Davis County", "Texas", "United States"}, {}},
			{{"Jefferson County", "Texas", "United States"}, {}},
			{{"Jim Hogg County", "Texas", "United States"}, {}},
			{{"Jim Wells County", "Texas", "United States"}, {}},
			{{"Johnson County", "Texas", "United States"}, {}},
			{{"Jones County", "Texas", "United States"}, {}},
			{{"Karnes County", "Texas", "United States"}, {}},
			{{"Kaufman County", "Texas", "United States"}, {}},
			{{"Kendall County", "Texas", "United States"}, {}},
			{{"Kenedy County", "Texas", "United States"}, {}},
			{{"Kent County", "Texas", "United States"}, {}},
			{{"Kerr County", "Texas", "United States"}, {}},
			{{"Kimble County", "Texas", "United States"}, {}},
			{{"King County", "Texas", "United States"}, {}},
			{{"Kinney County", "Texas", "United States"}, {}},
			{{"Kleberg County", "Texas", "United States"}, {}},
			{{"Knox County", "Texas", "United States"}, {}},
			{{"Lamar County", "Texas", "United States"}, {}},
			{{"Lamb County", "Texas", "United States"}, {}},
			{{"Lampasas County", "Texas", "United States"}, {}},
			{{"La Salle County", "Texas", "United States"}, {}},
			{{"Lavaca County", "Texas", "United States"}, {"Lavaca"}},
			{{"Lee County", "Texas", "United States"}, {}},
			{{"Leon County", "Texas", "United States"}, {}},
			{{"Liberty County", "Texas", "United States"}, {}},
			{{"Limestone County", "Texas", "United States"}, {}},
			{{"Lipscomb County", "Texas", "United States"}, {}},
			{{"Live Oak County", "Texas", "United States"}, {}},
			{{"Llano County", "Texas", "United States"}, {}},
			{{"Loving County", "Texas", "United States"}, {}},
			{{"Lubbock County", "Texas", "United States"}, {}},
			{{"Lynn County", "Texas", "United States"}, {}},
			{{"McCulloch County", "Texas", "United States"}, {}},
			{{"McLennan County", "Texas", "United States"}, {}},
			{{"McMullen County", "Texas", "United States"}, {}},
			{{"Madison County", "Texas", "United States"}, {}},
			{{"Marion County", "Texas", "United States"}, {}},
			{{"Martin County", "Texas", "United States"}, {}},
			{{"Mason County", "Texas", "United States"}, {}},
			{{"Matagorda County", "Texas", "United States"}, {}},
			{{"Maverick County", "Texas", "United States"}, {}},
			{{"Medina County", "Texas", "United States"}, {}},
			{{"Menard County", "Texas", "United States"}, {}},
			{{"Midland County", "Texas", "United States"}, {}},
			{{"Milam County", "Texas", "United States"}, {}},
			{{"Mills County", "Texas", "United States"}, {}},
			{{"Mitchell County", "Texas", "United States"}, {}},
			{{"Montague County", "Texas", "United States"}, {}},
			{{"Montgomery County", "Texas", "United States"}, {}},
			{{"Moore County", "Texas", "United States"}, {}},
			{{"Morris County", "Texas", "United States"}, {}},
			{{"Motley County", "Texas", "United States"}, {}},
			{{"Nacogdoches County", "Texas", "United States"}, {}},
			{{"Navarro County", "Texas", "United States"}, {}},
			{{"Newton County", "Texas", "United States"}, {}},
			{{"Nolan County", "Texas", "United States"}, {}},
			{{"Nueces County", "Texas", "United States"}, {"Nueces"}},
			{{"Ochiltree County", "Texas", "United States"}, {}},
			{{"Oldham County", "Texas", "United States"}, {}},
			{{"Orange County", "Texas", "United States"}, {}},
			{{"Palo Pinto County", "Texas", "United States"}, {}},
			{{"Panola County", "Texas", "United States"}, {}},
			{{"Parker County", "Texas", "United States"}, {}},
			{{"Parmer County", "Texas", "United States"}, {}},
			{{"Pecos County", "Texas", "United States"}, {}},
			{{"Polk County", "Texas", "United States"}, {}},
			{{"Potter County", "Texas", "United States"}, {}},
			{{"Presidio County", "Texas", "United States"}, {}},
			{{"Rains County", "Texas", "United States"}, {}},
			{{"Randall County", "Texas", "United States"}, {}},
			{{"Reagan County", "Texas", "United States"}, {}},
			{{"Real County", "Texas", "United States"}, {}},
			{{"Red River County", "Texas", "United States"}, {}},
			{{"Reeves County", "Texas", "United States"}, {}},
			{{"Refugio County", "Texas", "United States"}, {}},
			{{"Roberts County", "Texas", "United States"}, {}},
			{{"Robertson County", "Texas", "United States"}, {}},
			{{"Rockwall County", "Texas", "United States"}, {}},
			{{"Runnels County", "Texas", "United States"}, {}},
			{{"Rusk County", "Texas", "United States"}, {}},
			{{"Sabine County", "Texas", "United States"}, {}},
			{{"San Augustine County", "Texas", "United States"}, {}},
			{{"San Jacinto County", "Texas", "United States"}, {}},
			{{"San Patricio County", "Texas", "United States"}, {}},
			{{"San Saba County", "Texas", "United States"}, {}},
			{{"Schleicher County", "Texas", "United States"}, {}},
			{{"Scurry County", "Texas", "United States"}, {}},
			{{"Shackelford County", "Texas", "United States"}, {}},
			{{"Shelby County", "Texas", "United States"}, {}},
			{{"Sherman County", "Texas", "United States"}, {}},
			{{"Smith County", "Texas", "United States"}, {}},
			{{"Somervell County", "Texas", "United States"}, {}},
			{{"Starr County", "Texas", "United States"}, {}},
			{{"Stephens County", "Texas", "United States"}, {}},
			{{"Sterling County", "Texas", "United States"}, {}},
			{{"Stonewall County", "Texas", "United States"}, {}},
			{{"Sutton County", "Texas", "United States"}, {}},
			{{"Swisher County", "Texas", "United States"}, {}},
			{{"Tarrant County", "Texas", "United States"}, {}},
			{{"Taylor County", "Texas", "United States"}, {}},
			{{"Terrell County", "Texas", "United States"}, {}},
			{{"Terry County", "Texas", "United States"}, {}},
			{{"Throckmorton County", "Texas", "United States"}, {}},
			{{"Titus County", "Texas", "United States"}, {}},
			{{"Tom Green County", "Texas", "United States"}, {}},
			{{"Travis County", "Texas", "United States"}, {}},
			{{"Trinity County", "Texas", "United States"}, {}},
			{{"Tyler County", "Texas", "United States"}, {}},
			{{"Upshur County", "Texas", "United States"}, {}},
			{{"Upton County", "Texas", "United States"}, {}},
			{{"Uvalde County", "Texas", "United States"}, {}},
			{{"Val Verde County", "Texas", "United States"}, {}},
			{{"Van Zandt County", "Texas", "United States"}, {}},
			{{"Victoria County", "Texas", "United States"}, {}},
			{{"Walker County", "Texas", "United States"}, {}},
			{{"Waller County", "Texas", "United States"}, {}},
			{{"Ward County", "Texas", "United States"}, {}},
			{{"Washington County", "Texas", "United States"}, {}},
			{{"Webb County", "Texas", "United States"}, {}},
			{{"Wharton County", "Texas", "United States"}, {}},
			{{"Wheeler County", "Texas", "United States"}, {}},
			{{"Wichita County", "Texas", "United States"}, {}},
			{{"Wilbarger County", "Texas", "United States"}, {}},
			{{"Willacy County", "Texas", "United States"}, {}},
			{{"Williamson County", "Texas", "United States"}, {}},
			{{"Wilson County", "Texas", "United States"}, {}},
			{{"Winkler County", "Texas", "United States"}, {}},
			{{"Wise County", "Texas", "United States"}, {}},
			{{"Wood County", "Texas", "United States"}, {}},
			{{"Yoakum County", "Texas", "United States"}, {}},
			{{"Young County", "Texas", "United States"}, {}},
			{{"Zapata County", "Texas", "United States"}, {}},
			{{"Zavala County", "Texas", "United States"}, {}},

			{{"Beaver County", "Utah", "United States"}, {}},
			{{"Box Elder County", "Utah", "United States"}, {}},
			{{"Cache County", "Utah", "United States"}, {}},
			{{"Carbon County", "Utah", "United States"}, {}},
			{{"Daggett County", "Utah", "United States"}, {}},
			{{"Davis County", "Utah", "United States"}, {}},
			{{"Duchesne County", "Utah", "United States"}, {}},
			{{"Emery County", "Utah", "United States"}, {}},
			{{"Garfield County", "Utah", "United States"}, {}},
			{{"Grand County", "Utah", "United States"}, {}},
			{{"Iron County", "Utah", "United States"}, {}},
			{{"Juab County", "Utah", "United States"}, {}},
			{{"Kane County", "Utah", "United States"}, {}},
			{{"Millard County", "Utah", "United States"}, {}},
			{{"Morgan County", "Utah", "United States"}, {}},
			{{"Piute County", "Utah", "United States"}, {}},
			{{"Rich County", "Utah", "United States"}, {}},
			{{"Salt Lake County", "Utah", "United States"}, {}},
			{{"San Juan County", "Utah", "United States"}, {}},
			{{"Sanpete County", "Utah", "United States"}, {}},
			{{"Sevier County", "Utah", "United States"}, {}},
			{{"Summit County", "Utah", "United States"}, {}},
			{{"Tooele County", "Utah", "United States"}, {}},
			{{"Uintah County", "Utah", "United States"}, {}},
			{{"Utah County", "Utah", "United States"}, {}},
			{{"Wasatch County", "Utah", "United States"}, {}},
			{{"Washington County", "Utah", "United States"}, {}},
			{{"Wayne County", "Utah", "United States"}, {}},
			{{"Weber County", "Utah", "United States"}, {}},

			{{"Addison County", "Vermont", "United States"}, {}},
			{{"Bennington County", "Vermont", "United States"}, {}},
			{{"Caledonia County", "Vermont", "United States"}, {}},
			{{"Chittenden County", "Vermont", "United States"}, {}},
			{{"Essex County", "Vermont", "United States"}, {}},
			{{"Franklin County", "Vermont", "United States"}, {}},
			{{"Grand Isle County", "Vermont", "United States"}, {}},
			{{"Lamoille County", "Vermont", "United States"}, {}},
			{{"Orange County", "Vermont", "United States"}, {}},
			{{"Orleans County", "Vermont", "United States"}, {}},
			{{"Rutland County", "Vermont", "United States"}, {}},
			{{"Washington County", "Vermont", "United States"}, {}},
			{{"Windham County", "Vermont", "United States"}, {}},
			{{"Windsor County", "Vermont", "United States"}, {}},

			{{"Accomack County", "Virginia", "United States"}, {}},
			{{"Albemarle County", "Virginia", "United States"}, {}},
			{{"Alleghany County", "Virginia", "United States"}, {}},
			{{"Amelia County", "Virginia", "United States"}, {}},
			{{"Amherst County", "Virginia", "United States"}, {}},
			{{"Appomattox County", "Virginia", "United States"}, {}},
			{{"Arlington County", "Virginia", "United States"}, {}},
			{{"Augusta County", "Virginia", "United States"}, {}},
			{{"Bath County", "Virginia", "United States"}, {}},
			{{"Bedford County", "Virginia", "United States"}, {}},
			{{"Bland County", "Virginia", "United States"}, {}},
			{{"Botetourt County", "Virginia", "United States"}, {}},
			{{"Brunswick County", "Virginia", "United States"}, {}},
			{{"Buchanan County", "Virginia", "United States"}, {}},
			{{"Buckingham County", "Virginia", "United States"}, {}},
			{{"Campbell County", "Virginia", "United States"}, {}},
			{{"Caroline County", "Virginia", "United States"}, {}},
			{{"Carroll County", "Virginia", "United States"}, {}},
			{{"Charles City County", "Virginia", "United States"}, {}},
			{{"Charlotte County", "Virginia", "United States"}, {}},
			{{"Chesterfield County", "Virginia", "United States"}, {}},
			{{"Clarke County", "Virginia", "United States"}, {}},
			{{"Craig County", "Virginia", "United States"}, {}},
			{{"Culpeper County", "Virginia", "United States"}, {}},
			{{"Cumberland County", "Virginia", "United States"}, {}},
			{{"Dickenson County", "Virginia", "United States"}, {}},
			{{"Dinwiddie County", "Virginia", "United States"}, {}},
			{{"Essex County", "Virginia", "United States"}, {}},
			{{"Fairfax County", "Virginia", "United States"}, {}},
			{{"Fauquier County", "Virginia", "United States"}, {}},
			{{"Floyd County", "Virginia", "United States"}, {}},
			{{"Fluvanna County", "Virginia", "United States"}, {}},
			{{"Franklin County", "Virginia", "United States"}, {}},
			{{"Frederick County", "Virginia", "United States"}, {}},
			{{"Giles County", "Virginia", "United States"}, {}},
			{{"Gloucester County", "Virginia", "United States"}, {}},
			{{"Goochland County", "Virginia", "United States"}, {}},
			{{"Grayson County", "Virginia", "United States"}, {}},
			{{"Greene County", "Virginia", "United States"}, {}},
			{{"Greensville County", "Virginia", "United States"}, {}},
			{{"Halifax County", "Virginia", "United States"}, {}},
			{{"Hanover County", "Virginia", "United States"}, {}},
			{{"Henrico County", "Virginia", "United States"}, {}},
			{{"Henry County", "Virginia", "United States"}, {}},
			{{"Highland County", "Virginia", "United States"}, {}},
			{{"Isle of Wight County", "Virginia", "United States"}, {}},
			{{"James City County", "Virginia", "United States"}, {}},
			{{"King and Queen County", "Virginia", "United States"}, {}},
			{{"King George County", "Virginia", "United States"}, {}},
			{{"King William County", "Virginia", "United States"}, {}},
			{{"Lancaster County", "Virginia", "United States"}, {}},
			{{"Lee County", "Virginia", "United States"}, {}},
			{{"Loudoun County", "Virginia", "United States"}, {}},
			{{"Louisa County", "Virginia", "United States"}, {}},
			{{"Lunenburg County", "Virginia", "United States"}, {}},
			{{"Madison County", "Virginia", "United States"}, {}},
			{{"Mathews County", "Virginia", "United States"}, {}},
			{{"Mecklenburg County", "Virginia", "United States"}, {}},
			{{"Middlesex County", "Virginia", "United States"}, {}},
			{{"Montgomery County", "Virginia", "United States"}, {}},
			{{"Nelson County", "Virginia", "United States"}, {}},
			{{"New Kent County", "Virginia", "United States"}, {}},
			{{"Northampton County", "Virginia", "United States"}, {}},
			{{"Northumberland County", "Virginia", "United States"}, {}},
			{{"Nottoway County", "Virginia", "United States"}, {}},
			{{"Orange County", "Virginia", "United States"}, {}},
			{{"Page County", "Virginia", "United States"}, {}},
			{{"Patrick County", "Virginia", "United States"}, {}},
			{{"Pittsylvania County", "Virginia", "United States"}, {}},
			{{"Powhatan County", "Virginia", "United States"}, {}},
			{{"Prince Edward County", "Virginia", "United States"}, {}},
			{{"Prince George County", "Virginia", "United States"}, {}},
			{{"Prince William County", "Virginia", "United States"}, {}},
			{{"Pulaski County", "Virginia", "United States"}, {}},
			{{"Rappahannock County", "Virginia", "United States"}, {}},
			{{"Richmond County", "Virginia", "United States"}, {}},
			{{"Roanoke County", "Virginia", "United States"}, {}},
			{{"Rockbridge County", "Virginia", "United States"}, {}},
			{{"Rockingham County", "Virginia", "United States"}, {}},
			{{"Russell County", "Virginia", "United States"}, {}},
			{{"Scott County", "Virginia", "United States"}, {}},
			{{"Shenandoah County", "Virginia", "United States"}, {}},
			{{"Smyth County", "Virginia", "United States"}, {}},
			{{"Southampton County", "Virginia", "United States"}, {}},
			{{"Spotsylvania County", "Virginia", "United States"}, {}},
			{{"Chesapeake", "Virginia", "United States"}, {}},
			{{"Hampton", "Virginia", "United States"}, {}},
			{{"Newport", "Virginia", "United States"}, {}},
			{{"Norfolk", "Virginia", "United States"}, {}},
			{{"Portsmouth", "Virginia", "United States"}, {}},
			{{"Suffolk", "Virginia", "United States"}, {"Suffolk"}},
			{{"Virginia Beach", "Virginia", "United States"}, {}},

			{{"Adams County", "Washington", "United States"}, {}},
			{{"Asotin County", "Washington", "United States"}, {}},
			{{"Benton County", "Washington", "United States"}, {}},
			{{"Chelan County", "Washington", "United States"}, {}},
			{{"Clallam County", "Washington", "United States"}, {}},
			{{"Clark County", "Washington", "United States"}, {}},
			{{"Columbia County", "Washington", "United States"}, {}},
			{{"Cowlitz County", "Washington", "United States"}, {}},
			{{"Douglas County", "Washington", "United States"}, {}},
			{{"Ferry County", "Washington", "United States"}, {}},
			{{"Franklin County", "Washington", "United States"}, {}},
			{{"Garfield County", "Washington", "United States"}, {}},
			{{"Grant County", "Washington", "United States"}, {}},
			{{"Grays Harbor County", "Washington", "United States"}, {}},
			{{"Island County", "Washington", "United States"}, {}},
			{{"Jefferson County", "Washington", "United States"}, {}},
			{{"King County", "Washington", "United States"}, {}},
			{{"Kitsap County", "Washington", "United States"}, {}},
			{{"Kittitas County", "Washington", "United States"}, {}},
			{{"Klickitat County", "Washington", "United States"}, {}},
			{{"Lewis County", "Washington", "United States"}, {}},
			{{"Lincoln County", "Washington", "United States"}, {}},
			{{"Mason County", "Washington", "United States"}, {}},
			{{"Okanogan County", "Washington", "United States"}, {}},
			{{"Pacific County", "Washington", "United States"}, {}},
			{{"Pend Oreille County", "Washington", "United States"}, {}},
			{{"Pierce County", "Washington", "United States"}, {}},
			{{"San Juan County", "Washington", "United States"}, {}},
			{{"Skagit County", "Washington", "United States"}, {}},
			{{"Skamania County", "Washington", "United States"}, {}},
			{{"Snohomish County", "Washington", "United States"}, {}},
			{{"Spokane County", "Washington", "United States"}, {}},
			{{"Stevens County", "Washington", "United States"}, {}},
			{{"Thurston County", "Washington", "United States"}, {}},
			{{"Wahkiakum County", "Washington", "United States"}, {}},
			{{"Walla Walla County", "Washington", "United States"}, {}},
			{{"Whatcom County", "Washington", "United States"}, {}},
			{{"Whitman County", "Washington", "United States"}, {}},
			{{"Yakima County", "Washington", "United States"}, {}},

			{{"Barbour County", "West Virginia", "United States"}, {}},
			{{"Berkeley County", "West Virginia", "United States"}, {}},
			{{"Boone County", "West Virginia", "United States"}, {}},
			{{"Braxton County", "West Virginia", "United States"}, {}},
			{{"Brooke County", "West Virginia", "United States"}, {}},
			{{"Cabell County", "West Virginia", "United States"}, {}},
			{{"Calhoun County", "West Virginia", "United States"}, {}},
			{{"Clay County", "West Virginia", "United States"}, {}},
			{{"Doddridge County", "West Virginia", "United States"}, {}},
			{{"Fayette County", "West Virginia", "United States"}, {}},
			{{"Gilmer County", "West Virginia", "United States"}, {}},
			{{"Grant County", "West Virginia", "United States"}, {}},
			{{"Greenbrier County", "West Virginia", "United States"}, {}},
			{{"Hampshire County", "West Virginia", "United States"}, {}},
			{{"Hancock County", "West Virginia", "United States"}, {}},
			{{"Hardy County", "West Virginia", "United States"}, {}},
			{{"Harrison County", "West Virginia", "United States"}, {}},
			{{"Jackson County", "West Virginia", "United States"}, {}},
			{{"Jefferson County", "West Virginia", "United States"}, {}},
			{{"Kanawha County", "West Virginia", "United States"}, {}},
			{{"Lewis County", "West Virginia", "United States"}, {}},
			{{"Lincoln County", "West Virginia", "United States"}, {}},
			{{"Logan County", "West Virginia", "United States"}, {}},
			{{"Marion County", "West Virginia", "United States"}, {}},
			{{"Marshall County", "West Virginia", "United States"}, {}},
			{{"Mason County", "West Virginia", "United States"}, {}},
			{{"McDowell County", "West Virginia", "United States"}, {}},
			{{"Mercer County", "West Virginia", "United States"}, {}},
			{{"Mineral County", "West Virginia", "United States"}, {}},
			{{"Mingo County", "West Virginia", "United States"}, {}},
			{{"Monongalia County", "West Virginia", "United States"}, {}},
			{{"Monroe County", "West Virginia", "United States"}, {}},
			{{"Morgan County", "West Virginia", "United States"}, {}},
			{{"Nicholas County", "West Virginia", "United States"}, {}},
			{{"Ohio County", "West Virginia", "United States"}, {}},
			{{"Pendleton County", "West Virginia", "United States"}, {}},
			{{"Pleasants County", "West Virginia", "United States"}, {}},
			{{"Pocahontas County", "West Virginia", "United States"}, {}},
			{{"Preston County", "West Virginia", "United States"}, {}},
			{{"Putnam County", "West Virginia", "United States"}, {}},
			{{"Raleigh County", "West Virginia", "United States"}, {}},
			{{"Randolph County", "West Virginia", "United States"}, {}},
			{{"Ritchie County", "West Virginia", "United States"}, {}},
			{{"Roane County", "West Virginia", "United States"}, {}},
			{{"Summers County", "West Virginia", "United States"}, {}},
			{{"Taylor County", "West Virginia", "United States"}, {}},
			{{"Tucker County", "West Virginia", "United States"}, {}},
			{{"Tyler County", "West Virginia", "United States"}, {}},
			{{"Upshur County", "West Virginia", "United States"}, {}},
			{{"Wayne County", "West Virginia", "United States"}, {}},
			{{"Webster County", "West Virginia", "United States"}, {}},
			{{"Wetzel County", "West Virginia", "United States"}, {}},
			{{"Wirt County", "West Virginia", "United States"}, {}},
			{{"Wood County", "West Virginia", "United States"}, {}},
			{{"Wyoming County", "West Virginia", "United States"}, {}},

			{{"Adams County", "Wisconsin", "United States"}, {}},
			{{"Ashland County", "Wisconsin", "United States"}, {}},
			{{"Barron County", "Wisconsin", "United States"}, {}},
			{{"Bayfield County", "Wisconsin", "United States"}, {}},
			{{"Brown County", "Wisconsin", "United States"}, {}},
			{{"Buffalo County", "Wisconsin", "United States"}, {}},
			{{"Burnett County", "Wisconsin", "United States"}, {}},
			{{"Calumet County", "Wisconsin", "United States"}, {}},
			{{"Chippewa County", "Wisconsin", "United States"}, {}},
			{{"Clark County", "Wisconsin", "United States"}, {}},
			{{"Columbia County", "Wisconsin", "United States"}, {}},
			{{"Crawford County", "Wisconsin", "United States"}, {}},
			{{"Dane County", "Wisconsin", "United States"}, {}},
			{{"Dodge County", "Wisconsin", "United States"}, {}},
			{{"Door County", "Wisconsin", "United States"}, {}},
			{{"Douglas County", "Wisconsin", "United States"}, {}},
			{{"Dunn County", "Wisconsin", "United States"}, {}},
			{{"Eau Claire County", "Wisconsin", "United States"}, {}},
			{{"Florence County", "Wisconsin", "United States"}, {}},
			{{"Fond du Lac County", "Wisconsin", "United States"}, {}},
			{{"Forest County", "Wisconsin", "United States"}, {}},
			{{"Grant County", "Wisconsin", "United States"}, {}},
			{{"Green County", "Wisconsin", "United States"}, {}},
			{{"Green Lake County", "Wisconsin", "United States"}, {}},
			{{"Iowa County", "Wisconsin", "United States"}, {}},
			{{"Iron County", "Wisconsin", "United States"}, {}},
			{{"Jackson County", "Wisconsin", "United States"}, {}},
			{{"Jefferson County", "Wisconsin", "United States"}, {}},
			{{"Juneau County", "Wisconsin", "United States"}, {}},
			{{"Kenosha County", "Wisconsin", "United States"}, {}},
			{{"Kewaunee County", "Wisconsin", "United States"}, {}},
			{{"La Crosse County", "Wisconsin", "United States"}, {}},
			{{"Lafayette County", "Wisconsin", "United States"}, {}},
			{{"Langlade County", "Wisconsin", "United States"}, {}},
			{{"Lincoln County", "Wisconsin", "United States"}, {}},
			{{"Manitowoc County", "Wisconsin", "United States"}, {}},
			{{"Marathon County", "Wisconsin", "United States"}, {}},
			{{"Marinette County", "Wisconsin", "United States"}, {}},
			{{"Marquette County", "Wisconsin", "United States"}, {}},
			{{"Menominee County", "Wisconsin", "United States"}, {}},
			{{"Milwaukee County", "Wisconsin", "United States"}, {}},
			{{"Monroe County", "Wisconsin", "United States"}, {}},
			{{"Oconto County", "Wisconsin", "United States"}, {}},
			{{"Oneida County", "Wisconsin", "United States"}, {}},
			{{"Outagamie County", "Wisconsin", "United States"}, {}},
			{{"Ozaukee County", "Wisconsin", "United States"}, {}},
			{{"Pepin County", "Wisconsin", "United States"}, {}},
			{{"Pierce County", "Wisconsin", "United States"}, {}},
			{{"Polk County", "Wisconsin", "United States"}, {}},
			{{"Portage County", "Wisconsin", "United States"}, {}},
			{{"Price County", "Wisconsin", "United States"}, {}},
			{{"Racine County", "Wisconsin", "United States"}, {}},
			{{"Richland County", "Wisconsin", "United States"}, {}},
			{{"Rock County", "Wisconsin", "United States"}, {}},
			{{"Rusk County", "Wisconsin", "United States"}, {}},
			{{"Sauk County", "Wisconsin", "United States"}, {}},
			{{"Sawyer County", "Wisconsin", "United States"}, {}},
			{{"Shawano County", "Wisconsin", "United States"}, {}},
			{{"Sheboygan County", "Wisconsin", "United States"}, {}},
			{{"Saint Croix County", "Wisconsin", "United States"}, {}},
			{{"Taylor County", "Wisconsin", "United States"}, {}},
			{{"Trempealeau County", "Wisconsin", "United States"}, {}},
			{{"Vernon County", "Wisconsin", "United States"}, {}},
			{{"Vilas County", "Wisconsin", "United States"}, {}},
			{{"Walworth County", "Wisconsin", "United States"}, {}},
			{{"Washburn County", "Wisconsin", "United States"}, {}},
			{{"Washington County", "Wisconsin", "United States"}, {}},
			{{"Waukesha County", "Wisconsin", "United States"}, {}},
			{{"Waupaca County", "Wisconsin", "United States"}, {}},
			{{"Waushara County", "Wisconsin", "United States"}, {}},
			{{"Winnebago County", "Wisconsin", "United States"}, {}},
			{{"Wood County", "Wisconsin", "United States"}, {}},

			{{"Albany County", "Wyoming", "United States"}, {}},
			{{"Big Horn County", "Wyoming", "United States"}, {}},
			{{"Campbell County", "Wyoming", "United States"}, {}},
			{{"Carbon County", "Wyoming", "United States"}, {}},
			{{"Converse County", "Wyoming", "United States"}, {}},
			{{"Crook County", "Wyoming", "United States"}, {}},
			{{"Fremont County", "Wyoming", "United States"}, {}},
			{{"Goshen County", "Wyoming", "United States"}, {}},
			{{"Hot Springs County", "Wyoming", "United States"}, {}},
			{{"Johnson County", "Wyoming", "United States"}, {}},
			{{"Laramie County", "Wyoming", "United States"}, {}},
			{{"Lincoln County", "Wyoming", "United States"}, {}},
			{{"Natrona County", "Wyoming", "United States"}, {}},
			{{"Niobrara County", "Wyoming", "United States"}, {}},
			{{"Park County", "Wyoming", "United States"}, {}},
			{{"Platte County", "Wyoming", "United States"}, {}},
			{{"Sheridan County", "Wyoming", "United States"}, {}},
			{{"Sublette County", "Wyoming", "United States"}, {}},
			{{"Sweetwater County", "Wyoming", "United States"}, {}},
			{{"Teton County", "Wyoming", "United States"}, {}},
			{{"Uinta County", "Wyoming", "United States"}, {}},
			{{"Washakie County", "Wyoming", "United States"}, {}},
			{{"Weston County", "Wyoming", "United States"}, {}},
			{{"Armed Forces Africa", "United States"}, {}},
			{{"Armed Forces Americas", "United States"}, {}},
			{{"Armed Forces Canada", "United States"}, {}},
			{{"Armed Forces Europe", "United States"}, {}},
			{{"Armed Forces Middle East", "United States"}, {}},
			{{"Armed Forces Pacific", "United States"}, {}},

			{{"VIRGIN ISLANDS", "United States"}, {}},

			{{"Washington, DISTRICT OF COLUMBIA, United States"}, {}}
		};
	}
}
