package ws.daley.genealogy.db.xls;


public class XlsCountyUK
{
	public static String[][][] getNames()
	{
		return new String[][][]{
			{{"Bedfordshire", "England", "United Kingdom"}, {}},
			{{"Berkshire", "England", "United Kingdom"}, {}},
			{{"Buckinghamshire", "England", "United Kingdom"}, {}},
			{{"Cambridgeshire", "England", "United Kingdom"}, {}},
			{{"Cheshire", "England", "United Kingdom"}, {}},
			{{"Cornwall", "England", "United Kingdom"}, {}},
			{{"Cumberland", "England", "United Kingdom"}, {}},
			{{"Derbyshire", "England", "United Kingdom"}, {}},
			{{"Devon", "England", "United Kingdom"}, {}},
			{{"Dorset", "England", "United Kingdom"}, {}},
			{{"Durham", "England", "United Kingdom"}, {}},
			{{"Essex", "England", "United Kingdom"}, {}},
			{{"Gloucestershire", "England", "United Kingdom"}, {}},
			{{"Hampshire", "England", "United Kingdom"}, {}},
			{{"Herefordshire", "England", "United Kingdom"}, {}},
			{{"Hertfordshire", "England", "United Kingdom"}, {}},
			{{"Huntingdonshire", "England", "United Kingdom"}, {}},
			{{"Kent", "England", "United Kingdom"}, {}},
			{{"Lancashire", "England", "United Kingdom"}, {}},
			{{"Leicestershire", "England", "United Kingdom"}, {}},
			{{"Lincolnshire", "England", "United Kingdom"}, {}},
			{{"Middlesex", "England", "United Kingdom"}, {}},
			{{"Norfolk", "England", "United Kingdom"}, {}},
			{{"Northamptonshire", "England", "United Kingdom"}, {}},
			{{"Northumberland", "England", "United Kingdom"}, {}},
			{{"Nottinghamshire", "England", "United Kingdom"}, {}},
			{{"Oxfordshire", "England", "United Kingdom"}, {}},
			{{"Rutland", "England", "United Kingdom"}, {}},
			{{"Shropshire", "England", "United Kingdom"}, {}},
			{{"Somerset", "England", "United Kingdom"}, {}},
			{{"Staffordshire", "England", "United Kingdom"}, {}},
			{{"Suffolk", "England", "United Kingdom"}, {}},
			{{"Surrey", "England", "United Kingdom"}, {}},
			{{"Sussex", "England", "United Kingdom"}, {}},
			{{"Warwickshire", "England", "United Kingdom"}, {}},
			{{"Westmorland", "England", "United Kingdom"}, {}},
			{{"Wiltshire", "England", "United Kingdom"}, {}},
			{{"Worcestershire", "England", "United Kingdom"}, {}},
			{{"Yorkshire", "England", "United Kingdom"}, {}},

			{{"Carlow", "Ireland", "United Kingdom"}, {}},
			{{"Cavan", "Ireland", "United Kingdom"}, {}},
			{{"Clare", "Ireland", "United Kingdom"}, {}},
			{{"Cork", "Ireland", "United Kingdom"}, {}},
			{{"Donegal", "Ireland", "United Kingdom"}, {}},
			{{"Dublin", "Ireland", "United Kingdom"}, {}},
			{{"Galway", "Ireland", "United Kingdom"}, {}},
			{{"Kerry", "Ireland", "United Kingdom"}, {}},
			{{"Kildare", "Ireland", "United Kingdom"}, {}},
			{{"Kilkenny", "Ireland", "United Kingdom"}, {}},
			{{"Laois", "Ireland", "United Kingdom"}, {}},
			{{"Leitrim", "Ireland", "United Kingdom"}, {}},
			{{"Limerick", "Ireland", "United Kingdom"}, {}},
			{{"Longford", "Ireland", "United Kingdom"}, {}},
			{{"Louth", "Ireland", "United Kingdom"}, {}},
			{{"Mayo", "Ireland", "United Kingdom"}, {}},
			{{"Meath", "Ireland", "United Kingdom"}, {}},
			{{"Monaghan", "Ireland", "United Kingdom"}, {}},
			{{"Offaly", "Ireland", "United Kingdom"}, {}},
			{{"Roscommon", "Ireland", "United Kingdom"}, {}},
			{{"Sligo", "Ireland", "United Kingdom"}, {}},
			{{"Tipperary", "Ireland", "United Kingdom"}, {}},
			{{"Waterford", "Ireland", "United Kingdom"}, {}},
			{{"Westmeath", "Ireland", "United Kingdom"}, {}},
			{{"Wexford", "Ireland", "United Kingdom"}, {}},
			{{"Wicklow", "Ireland", "United Kingdom"}, {}},

			{{"Fermanagh", "Northern Ireland", "United Kingdom"}, {}},
			{{"Tyrone", "Northern Ireland", "United Kingdom"}, {}},
			{{"Londonderry", "Northern Ireland", "United Kingdom"}, {}},
			{{"Antrim", "Northern Ireland", "United Kingdom"}, {}},
			{{"Down", "Northern Ireland", "United Kingdom"}, {}},
			{{"Armagh", "Northern Ireland", "United Kingdom"}, {}},

			{{"Aberdeenshire", "Scotland", "United Kingdom"}, {}},
			{{"Angus/Forfarshire", "Scotland", "United Kingdom"}, {}},
			{{"Argyllshire", "Scotland", "United Kingdom"}, {}},
			{{"Ayrshire", "Scotland", "United Kingdom"}, {}},
			{{"Banffshire", "Scotland", "United Kingdom"}, {}},
			{{"Berwickshire", "Scotland", "United Kingdom"}, {}},
			{{"Buteshire", "Scotland", "United Kingdom"}, {}},
			{{"Cromartyshire", "Scotland", "United Kingdom"}, {}},
			{{"Caithness", "Scotland", "United Kingdom"}, {}},
			{{"Clackmannanshire", "Scotland", "United Kingdom"}, {}},
			{{"Dumfriesshire", "Scotland", "United Kingdom"}, {}},
			{{"Dunbartonshire/Dumbartonshire", "Scotland", "United Kingdom"}, {}},
			{{"East Lothian/Haddingtonshire", "Scotland", "United Kingdom"}, {}},
			{{"Fife", "Scotland", "United Kingdom"}, {}},
			{{"Inverness-shire", "Scotland", "United Kingdom"}, {}},
			{{"Kincardineshire", "Scotland", "United Kingdom"}, {}},
			{{"Kinross-shire", "Scotland", "United Kingdom"}, {}},
			{{"Kirkcudbrightshire", "Scotland", "United Kingdom"}, {}},
			{{"Lanarkshire", "Scotland", "United Kingdom"}, {}},
			{{"Midlothian/Edinburghshire", "Scotland", "United Kingdom"}, {}},
			{{"Morayshire", "Scotland", "United Kingdom"}, {}},
			{{"Nairnshire", "Scotland", "United Kingdom"}, {}},
			{{"Orkney", "Scotland", "United Kingdom"}, {}},
			{{"Peeblesshire", "Scotland", "United Kingdom"}, {}},
			{{"Perthshire", "Scotland", "United Kingdom"}, {}},
			{{"Renfrewshire", "Scotland", "United Kingdom"}, {}},
			{{"Ross-shire", "Scotland", "United Kingdom"}, {}},
			{{"Roxburghshire", "Scotland", "United Kingdom"}, {}},
			{{"Selkirkshire", "Scotland", "United Kingdom"}, {}},
			{{"Shetland", "Scotland", "United Kingdom"}, {}},
			{{"Stirlingshire", "Scotland", "United Kingdom"}, {}},
			{{"Sutherland", "Scotland", "United Kingdom"}, {}},
			{{"West Lothian/Linlithgowshire", "Scotland", "United Kingdom"}, {}},
			{{"Wigtownshire", "Scotland", "United Kingdom"}, {}},

			{{"Anglesey", "Wales", "United Kingdom"}, {}},
			{{"Brecknockshire", "Wales", "United Kingdom"}, {}},
			{{"Caernarfonshire", "Wales", "United Kingdom"}, {}},
			{{"Carmarthenshire", "Wales", "United Kingdom"}, {}},
			{{"Cardiganshire", "Wales", "United Kingdom"}, {}},
			{{"Denbighshire", "Wales", "United Kingdom"}, {}},
			{{"Flintshire", "Wales", "United Kingdom"}, {}},
			{{"Glamorgan", "Wales", "United Kingdom"}, {}},
			{{"Merioneth", "Wales", "United Kingdom"}, {}},
			{{"Monmouthshire", "Wales", "United Kingdom"}, {}},
			{{"Montgomeryshire", "Wales", "United Kingdom"}, {}},
			{{"Pembrokeshire", "Wales", "United Kingdom"}, {}},
			{{"Radnorshire", "Wales", "United Kingdom"}, {}}};
	}
}
