package ws.daley.genealogy.db.xls;

public class XlsCountyUSLToN
{
	public static String[][][] getNames()
	{
		return new String[][][]{
				{{"Acadia Parish", "Louisiana", "United States"}, {}},
				{{"Allen Parish", "Louisiana", "United States"}, {}},
				{{"Ascension Parish", "Louisiana", "United States"}, {}},
				{{"Assumption Parish", "Louisiana", "United States"}, {}},
				{{"Avoyelles Parish", "Louisiana", "United States"}, {}},
				{{"Beauregard Parish", "Louisiana", "United States"}, {}},
				{{"Bienville Parish", "Louisiana", "United States"}, {}},
				{{"Bossier Parish", "Louisiana", "United States"}, {}},
				{{"Caddo Parish", "Louisiana", "United States"}, {}},
				{{"Calcasieu Parish", "Louisiana", "United States"}, {}},
				{{"Caldwell Parish", "Louisiana", "United States"}, {}},
				{{"Cameron Parish", "Louisiana", "United States"}, {}},
				{{"Catahoula Parish", "Louisiana", "United States"}, {}},
				{{"Claiborne Parish", "Louisiana", "United States"}, {}},
				{{"Concordia Parish", "Louisiana", "United States"}, {}},
				{{"De Soto Parish", "Louisiana", "United States"}, {}},
				{{"East Baton Rouge Parish", "Louisiana", "United States"}, {}},
				{{"East Carroll Parish", "Louisiana", "United States"}, {}},
				{{"East Feliciana Parish", "Louisiana", "United States"}, {}},
				{{"Evangeline Parish", "Louisiana", "United States"}, {}},
				{{"Franklin Parish", "Louisiana", "United States"}, {}},
				{{"Grant Parish", "Louisiana", "United States"}, {}},
				{{"Iberia Parish", "Louisiana", "United States"}, {}},
				{{"Iberville Parish", "Louisiana", "United States"}, {}},
				{{"Jackson Parish", "Louisiana", "United States"}, {}},
				{{"Jefferson Parish", "Louisiana", "United States"}, {}},
				{{"Jefferson Davis Parish", "Louisiana", "United States"}, {}},
				{{"Lafayette Parish", "Louisiana", "United States"}, {}},
				{{"Lafourche Parish", "Louisiana", "United States"}, {}},
				{{"La Salle Parish", "Louisiana", "United States"}, {}},
				{{"Lincoln Parish", "Louisiana", "United States"}, {}},
				{{"Livingston Parish", "Louisiana", "United States"}, {}},
				{{"Madison Parish", "Louisiana", "United States"}, {}},
				{{"Morehouse Parish", "Louisiana", "United States"}, {}},
				{{"Natchitoches Parish", "Louisiana", "United States"}, {}},
				{{"Orleans Parish", "Louisiana", "United States"}, {}},
				{{"Ouachita Parish", "Louisiana", "United States"}, {}},
				{{"Plaquemines Parish", "Louisiana", "United States"}, {}},
				{{"Pointe Coupee Parish", "Louisiana", "United States"}, {}},
				{{"Rapides Parish", "Louisiana", "United States"}, {}},
				{{"Red River Parish", "Louisiana", "United States"}, {}},
				{{"Richland Parish", "Louisiana", "United States"}, {}},
				{{"Sabine Parish", "Louisiana", "United States"}, {}},
				{{"Saint Bernard Parish", "Louisiana", "United States"}, {}},
				{{"Saint Charles Parish", "Louisiana", "United States"}, {}},
				{{"Saint Helena Parish", "Louisiana", "United States"}, {}},
				{{"Saint James Parish", "Louisiana", "United States"}, {}},
				{{"Saint John the Baptist Parish", "Louisiana", "United States"}, {}},
				{{"Saint Landry Parish", "Louisiana", "United States"}, {}},
				{{"Saint Martin Parish", "Louisiana", "United States"}, {}},
				{{"Saint Mary Parish", "Louisiana", "United States"}, {}},
				{{"Saint Tammany Parish", "Louisiana", "United States"}, {}},
				{{"Tangipahoa Parish", "Louisiana", "United States"}, {}},
				{{"Tensas Parish", "Louisiana", "United States"}, {}},
				{{"Terrebonne Parish", "Louisiana", "United States"}, {}},
				{{"Union Parish", "Louisiana", "United States"}, {}},
				{{"Vermilion Parish", "Louisiana", "United States"}, {}},
				{{"Vernon Parish", "Louisiana", "United States"}, {}},
				{{"Washington Parish", "Louisiana", "United States"}, {}},
				{{"Webster Parish", "Louisiana", "United States"}, {}},
				{{"West Baton Rouge Parish", "Louisiana", "United States"}, {}},
				{{"West Carroll Parish", "Louisiana", "United States"}, {}},
				{{"West Feliciana Parish", "Louisiana", "United States"}, {}},
				{{"Winn Parish", "Louisiana", "United States"}, {}},

				{{"Androscoggin County", "Maine", "United States"}, {}},
				{{"Aroostook County", "Maine", "United States"}, {}},
				{{"Cumberland County", "Maine", "United States"}, {}},
				{{"Franklin County", "Maine", "United States"}, {}},
				{{"Hancock County", "Maine", "United States"}, {}},
				{{"Kennebec County", "Maine", "United States"}, {}},
				{{"Knox County", "Maine", "United States"}, {}},
				{{"Lincoln County", "Maine", "United States"}, {}},
				{{"Oxford County", "Maine", "United States"}, {}},
				{{"Penobscot County", "Maine", "United States"}, {}},
				{{"Piscataquis County", "Maine", "United States"}, {}},
				{{"Sagadahoc County", "Maine", "United States"}, {}},
				{{"Somerset County", "Maine", "United States"}, {}},
				{{"Waldo County", "Maine", "United States"}, {}},
				{{"Washington County", "Maine", "United States"}, {}},
				{{"York County", "Maine", "United States"}, {}},
				{{"MARSHALL ISLANDS", "United States"}, {}},

				{{"Allegany County", "Maryland", "United States"}, {}},
				{{"Anne Arundel County", "Maryland", "United States"}, {}},
				{{"Baltimore County", "Maryland", "United States"}, {}},
				{{"Calvert County", "Maryland", "United States"}, {}},
				{{"Caroline County", "Maryland", "United States"}, {}},
				{{"Carroll County", "Maryland", "United States"}, {}},
				{{"Cecil County", "Maryland", "United States"}, {}},
				{{"Charles County", "Maryland", "United States"}, {}},
				{{"Dorchester County", "Maryland", "United States"}, {}},
				{{"Frederick County", "Maryland", "United States"}, {}},
				{{"Garrett County", "Maryland", "United States"}, {}},
				{{"Harford County", "Maryland", "United States"}, {}},
				{{"Howard County", "Maryland", "United States"}, {}},
				{{"Kent County", "Maryland", "United States"}, {}},
				{{"Montgomery County", "Maryland", "United States"}, {}},
				{{"Prince George''s County", "Maryland", "United States"}, {}},
				{{"Queen Anne''s County", "Maryland", "United States"}, {}},
				{{"Saint Mary''s County", "Maryland", "United States"}, {}},
				{{"Somerset County", "Maryland", "United States"}, {}},
				{{"Talbot County", "Maryland", "United States"}, {}},
				{{"Washington County", "Maryland", "United States"}, {}},
				{{"Wicomico County", "Maryland", "United States"}, {}},
				{{"Worcester County", "Maryland", "United States"}, {}},

				{{"Barnstable County", "Massachusetts", "United States"}, {}},
				{{"Berkshire County", "Massachusetts", "United States"}, {}},
				{{"Bristol County", "Massachusetts", "United States"}, {}},
				{{"Dukes County", "Massachusetts", "United States"}, {}},
				{{"Essex County", "Massachusetts", "United States"}, {}},
				{{"Franklin County", "Massachusetts", "United States"}, {}},
				{{"Hampden County", "Massachusetts", "United States"}, {}},
				{{"Hampshire County", "Massachusetts", "United States"}, {}},
				{{"Middlesex County", "Massachusetts", "United States"}, {}},
				{{"Nantucket County", "Massachusetts", "United States"}, {}},
				{{"Norfolk County", "Massachusetts", "United States"}, {}},
				{{"Plymouth County", "Massachusetts", "United States"}, {}},
				{{"Suffolk County", "Massachusetts", "United States"}, {}},
				{{"Worcester County", "Massachusetts", "United States"}, {}},

				{{"Alcona County", "Michigan", "United States"}, {}},
				{{"Alger County", "Michigan", "United States"}, {}},
				{{"Allegan County", "Michigan", "United States"}, {}},
				{{"Alpena County", "Michigan", "United States"}, {}},
				{{"Antrim County", "Michigan", "United States"}, {}},
				{{"Arenac County", "Michigan", "United States"}, {}},
				{{"Baraga County", "Michigan", "United States"}, {}},
				{{"Barry County", "Michigan", "United States"}, {}},
				{{"Bay County", "Michigan", "United States"}, {}},
				{{"Benzie County", "Michigan", "United States"}, {}},
				{{"Berrien County", "Michigan", "United States"}, {}},
				{{"Branch County", "Michigan", "United States"}, {}},
				{{"Calhoun County", "Michigan", "United States"}, {}},
				{{"Cass County", "Michigan", "United States"}, {}},
				{{"Charlevoix County", "Michigan", "United States"}, {}},
				{{"Cheboygan County", "Michigan", "United States"}, {}},
				{{"Chippewa County", "Michigan", "United States"}, {}},
				{{"Clare County", "Michigan", "United States"}, {}},
				{{"Clinton County", "Michigan", "United States"}, {}},
				{{"Crawford County", "Michigan", "United States"}, {}},
				{{"Delta County", "Michigan", "United States"}, {}},
				{{"Dickinson County", "Michigan", "United States"}, {}},
				{{"Eaton County", "Michigan", "United States"}, {}},
				{{"Emmet County", "Michigan", "United States"}, {}},
				{{"Genesee County", "Michigan", "United States"}, {}},
				{{"Gladwin County", "Michigan", "United States"}, {}},
				{{"Gogebic County", "Michigan", "United States"}, {}},
				{{"Grand Traverse County", "Michigan", "United States"}, {}},
				{{"Gratiot County", "Michigan", "United States"}, {}},
				{{"Hillsdale County", "Michigan", "United States"}, {}},
				{{"Houghton County", "Michigan", "United States"}, {}},
				{{"Huron County", "Michigan", "United States"}, {}},
				{{"Ingham County", "Michigan", "United States"}, {}},
				{{"Ionia County", "Michigan", "United States"}, {}},
				{{"Iosco County", "Michigan", "United States"}, {}},
				{{"Iron County", "Michigan", "United States"}, {}},
				{{"Isabella County", "Michigan", "United States"}, {}},
				{{"Jackson County", "Michigan", "United States"}, {}},
				{{"Kalamazoo County", "Michigan", "United States"}, {}},
				{{"Kalkaska County", "Michigan", "United States"}, {}},
				{{"Kent County", "Michigan", "United States"}, {}},
				{{"Keweenaw County", "Michigan", "United States"}, {}},
				{{"Lake County", "Michigan", "United States"}, {}},
				{{"Lapeer County", "Michigan", "United States"}, {}},
				{{"Leelanau County", "Michigan", "United States"}, {}},
				{{"Lenawee County", "Michigan", "United States"}, {}},
				{{"Livingston County", "Michigan", "United States"}, {}},
				{{"Luce County", "Michigan", "United States"}, {}},
				{{"Mackinac County", "Michigan", "United States"}, {}},
				{{"Macomb County", "Michigan", "United States"}, {}},
				{{"Manistee County", "Michigan", "United States"}, {}},
				{{"Marquette County", "Michigan", "United States"}, {}},
				{{"Mason County", "Michigan", "United States"}, {}},
				{{"Mecosta County", "Michigan", "United States"}, {}},
				{{"Menominee County", "Michigan", "United States"}, {}},
				{{"Midland County", "Michigan", "United States"}, {}},
				{{"Missaukee County", "Michigan", "United States"}, {}},
				{{"Monroe County", "Michigan", "United States"}, {}},
				{{"Montcalm County", "Michigan", "United States"}, {}},
				{{"Montmorency County", "Michigan", "United States"}, {}},
				{{"Muskegon County", "Michigan", "United States"}, {}},
				{{"Newaygo County", "Michigan", "United States"}, {}},
				{{"Oakland County", "Michigan", "United States"}, {}},
				{{"Oceana County", "Michigan", "United States"}, {}},
				{{"Ogemaw County", "Michigan", "United States"}, {}},
				{{"Ontonagon County", "Michigan", "United States"}, {}},
				{{"Osceola County", "Michigan", "United States"}, {}},
				{{"Oscoda County", "Michigan", "United States"}, {}},
				{{"Otsego County", "Michigan", "United States"}, {}},
				{{"Ottawa County", "Michigan", "United States"}, {}},
				{{"Presque Isle County", "Michigan", "United States"}, {}},
				{{"Roscommon County", "Michigan", "United States"}, {}},
				{{"Saginaw County", "Michigan", "United States"}, {}},
				{{"St. Clair County", "Michigan", "United States"}, {}},
				{{"St. Joseph County", "Michigan", "United States"}, {}},
				{{"Sanilac County", "Michigan", "United States"}, {}},
				{{"Schoolcraft County", "Michigan", "United States"}, {}},
				{{"Shiawassee County", "Michigan", "United States"}, {}},
				{{"Tuscola County", "Michigan", "United States"}, {}},
				{{"Van Buren County", "Michigan", "United States"}, {}},
				{{"Washtenaw County", "Michigan", "United States"}, {}},
				{{"Wayne County", "Michigan", "United States"}, {}},
				{{"Wexford County", "Michigan", "United States"}, {}},

				{{"FEDERATED STATES OF MICRONESIA", "United States"}, {}},

				{{"Aitkin County", "Minnesota", "United States"}, {}},
				{{"Anoka County", "Minnesota", "United States"}, {}},
				{{"Becker County", "Minnesota", "United States"}, {}},
				{{"Beltrami County", "Minnesota", "United States"}, {}},
				{{"Benton County", "Minnesota", "United States"}, {}},
				{{"Big Stone County", "Minnesota", "United States"}, {}},
				{{"Blue Earth County", "Minnesota", "United States"}, {}},
				{{"Brown County", "Minnesota", "United States"}, {}},
				{{"Carlton County", "Minnesota", "United States"}, {}},
				{{"Carver County", "Minnesota", "United States"}, {}},
				{{"Cass County", "Minnesota", "United States"}, {}},
				{{"Chippewa County", "Minnesota", "United States"}, {}},
				{{"Chisago County", "Minnesota", "United States"}, {}},
				{{"Clay County", "Minnesota", "United States"}, {}},
				{{"Clearwater County", "Minnesota", "United States"}, {}},
				{{"Cook County", "Minnesota", "United States"}, {}},
				{{"Cottonwood County", "Minnesota", "United States"}, {}},
				{{"Crow Wing County", "Minnesota", "United States"}, {}},
				{{"Dakota County", "Minnesota", "United States"}, {}},
				{{"Dodge County", "Minnesota", "United States"}, {}},
				{{"Douglas County", "Minnesota", "United States"}, {}},
				{{"Faribault County", "Minnesota", "United States"}, {}},
				{{"Fillmore County", "Minnesota", "United States"}, {}},
				{{"Freeborn County", "Minnesota", "United States"}, {}},
				{{"Goodhue County", "Minnesota", "United States"}, {}},
				{{"Grant County", "Minnesota", "United States"}, {}},
				{{"Hennepin County", "Minnesota", "United States"}, {}},
				{{"Houston County", "Minnesota", "United States"}, {}},
				{{"Hubbard County", "Minnesota", "United States"}, {}},
				{{"Isanti County", "Minnesota", "United States"}, {}},
				{{"Itasca County", "Minnesota", "United States"}, {}},
				{{"Jackson County", "Minnesota", "United States"}, {}},
				{{"Kanabec County", "Minnesota", "United States"}, {}},
				{{"Kandiyohi County", "Minnesota", "United States"}, {}},
				{{"Kittson County", "Minnesota", "United States"}, {}},
				{{"Koochiching County", "Minnesota", "United States"}, {}},
				{{"Lac qui Parle County", "Minnesota", "United States"}, {}},
				{{"Lake County", "Minnesota", "United States"}, {}},
				{{"Lake of the Woods County", "Minnesota", "United States"}, {}},
				{{"Le Sueur County", "Minnesota", "United States"}, {}},
				{{"Lincoln County", "Minnesota", "United States"}, {}},
				{{"Lyon County", "Minnesota", "United States"}, {}},
				{{"Mahnomen County", "Minnesota", "United States"}, {}},
				{{"Marshall County", "Minnesota", "United States"}, {}},
				{{"Martin County", "Minnesota", "United States"}, {}},
				{{"McLeod County", "Minnesota", "United States"}, {}},
				{{"Meeker County", "Minnesota", "United States"}, {}},
				{{"Mille Lacs County", "Minnesota", "United States"}, {}},
				{{"Morrison County", "Minnesota", "United States"}, {}},
				{{"Mower County", "Minnesota", "United States"}, {}},
				{{"Murray County", "Minnesota", "United States"}, {}},
				{{"Nicollet County", "Minnesota", "United States"}, {}},
				{{"Nobles County", "Minnesota", "United States"}, {}},
				{{"Norman County", "Minnesota", "United States"}, {}},
				{{"Olmsted County", "Minnesota", "United States"}, {}},
				{{"Otter Tail County", "Minnesota", "United States"}, {}},
				{{"Pennington County", "Minnesota", "United States"}, {}},
				{{"Pine County", "Minnesota", "United States"}, {}},
				{{"Pipestone County", "Minnesota", "United States"}, {}},
				{{"Polk County", "Minnesota", "United States"}, {}},
				{{"Pope County", "Minnesota", "United States"}, {}},
				{{"Ramsey County", "Minnesota", "United States"}, {}},
				{{"Red Lake County", "Minnesota", "United States"}, {}},
				{{"Redwood County", "Minnesota", "United States"}, {}},
				{{"Renville County", "Minnesota", "United States"}, {}},
				{{"Rice County", "Minnesota", "United States"}, {}},
				{{"Rock County", "Minnesota", "United States"}, {}},
				{{"Roseau County", "Minnesota", "United States"}, {}},
				{{"St. Louis County", "Minnesota", "United States"}, {}},
				{{"Scott County", "Minnesota", "United States"}, {}},
				{{"Sherburne County", "Minnesota", "United States"}, {}},
				{{"Sibley County", "Minnesota", "United States"}, {}},
				{{"Stearns County", "Minnesota", "United States"}, {}},
				{{"Steele County", "Minnesota", "United States"}, {}},
				{{"Stevens County", "Minnesota", "United States"}, {}},
				{{"Swift County", "Minnesota", "United States"}, {}},
				{{"Todd County", "Minnesota", "United States"}, {}},
				{{"Traverse County", "Minnesota", "United States"}, {}},
				{{"Wabasha County", "Minnesota", "United States"}, {}},
				{{"Wadena County", "Minnesota", "United States"}, {}},
				{{"Waseca County", "Minnesota", "United States"}, {}},
				{{"Washington County", "Minnesota", "United States"}, {}},
				{{"Watonwan County", "Minnesota", "United States"}, {}},
				{{"Wilkin County", "Minnesota", "United States"}, {}},
				{{"Winona County", "Minnesota", "United States"}, {}},
				{{"Wright County", "Minnesota", "United States"}, {}},
				{{"Yellow Medicine County", "Minnesota", "United States"}, {}},

				{{"Adams County", "Mississippi", "United States"}, {}},
				{{"Alcorn County", "Mississippi", "United States"}, {}},
				{{"Amite County", "Mississippi", "United States"}, {}},
				{{"Attala County", "Mississippi", "United States"}, {}},
				{{"Benton County", "Mississippi", "United States"}, {}},
				{{"Bolivar County", "Mississippi", "United States"}, {}},
				{{"Calhoun County", "Mississippi", "United States"}, {}},
				{{"Carroll County", "Mississippi", "United States"}, {}},
				{{"Chickasaw County", "Mississippi", "United States"}, {}},
				{{"Choctaw County", "Mississippi", "United States"}, {}},
				{{"Claiborne County", "Mississippi", "United States"}, {}},
				{{"Clarke County", "Mississippi", "United States"}, {}},
				{{"Clay County", "Mississippi", "United States"}, {}},
				{{"Coahoma County", "Mississippi", "United States"}, {}},
				{{"Copiah County", "Mississippi", "United States"}, {}},
				{{"Covington County", "Mississippi", "United States"}, {}},
				{{"DeSoto County", "Mississippi", "United States"}, {}},
				{{"Forrest County", "Mississippi", "United States"}, {}},
				{{"Franklin County", "Mississippi", "United States"}, {}},
				{{"George County", "Mississippi", "United States"}, {}},
				{{"Greene County", "Mississippi", "United States"}, {}},
				{{"Grenada County", "Mississippi", "United States"}, {}},
				{{"Hancock County", "Mississippi", "United States"}, {}},
				{{"Harrison County", "Mississippi", "United States"}, {}},
				{{"Hinds County", "Mississippi", "United States"}, {}},
				{{"Holmes County", "Mississippi", "United States"}, {}},
				{{"Humphreys County", "Mississippi", "United States"}, {}},
				{{"Issaquena County", "Mississippi", "United States"}, {}},
				{{"Itawamba County", "Mississippi", "United States"}, {}},
				{{"Jackson County", "Mississippi", "United States"}, {}},
				{{"Jasper County", "Mississippi", "United States"}, {}},
				{{"Jefferson County", "Mississippi", "United States"}, {}},
				{{"Jefferson Davis County", "Mississippi", "United States"}, {}},
				{{"Jones County", "Mississippi", "United States"}, {}},
				{{"Kemper County", "Mississippi", "United States"}, {}},
				{{"Lafayette County", "Mississippi", "United States"}, {}},
				{{"Lamar County", "Mississippi", "United States"}, {}},
				{{"Lauderdale County", "Mississippi", "United States"}, {}},
				{{"Lawrence County", "Mississippi", "United States"}, {}},
				{{"Leake County", "Mississippi", "United States"}, {}},
				{{"Lee County", "Mississippi", "United States"}, {}},
				{{"Leflore County", "Mississippi", "United States"}, {}},
				{{"Lincoln County", "Mississippi", "United States"}, {}},
				{{"Lowndes County", "Mississippi", "United States"}, {}},
				{{"Madison County", "Mississippi", "United States"}, {}},
				{{"Marion County", "Mississippi", "United States"}, {}},
				{{"Marshall County", "Mississippi", "United States"}, {}},
				{{"Monroe County", "Mississippi", "United States"}, {}},
				{{"Montgomery County", "Mississippi", "United States"}, {}},
				{{"Neshoba County", "Mississippi", "United States"}, {}},
				{{"Newton County", "Mississippi", "United States"}, {}},
				{{"Noxubee County", "Mississippi", "United States"}, {}},
				{{"Oktibbeha County", "Mississippi", "United States"}, {}},
				{{"Panola County", "Mississippi", "United States"}, {}},
				{{"Pearl River County", "Mississippi", "United States"}, {}},
				{{"Perry County", "Mississippi", "United States"}, {}},
				{{"Pike County", "Mississippi", "United States"}, {}},
				{{"Pontotoc County", "Mississippi", "United States"}, {}},
				{{"Prentiss County", "Mississippi", "United States"}, {}},
				{{"Quitman County", "Mississippi", "United States"}, {}},
				{{"Rankin County", "Mississippi", "United States"}, {}},
				{{"Scott County", "Mississippi", "United States"}, {}},
				{{"Sharkey County", "Mississippi", "United States"}, {}},
				{{"Simpson County", "Mississippi", "United States"}, {}},
				{{"Smith County", "Mississippi", "United States"}, {}},
				{{"Stone County", "Mississippi", "United States"}, {}},
				{{"Sunflower County", "Mississippi", "United States"}, {}},
				{{"Tallahatchie County", "Mississippi", "United States"}, {}},
				{{"Tate County", "Mississippi", "United States"}, {}},
				{{"Tippah County", "Mississippi", "United States"}, {}},
				{{"Tishomingo County", "Mississippi", "United States"}, {}},
				{{"Tunica County", "Mississippi", "United States"}, {}},
				{{"Union County", "Mississippi", "United States"}, {}},
				{{"Walthall County", "Mississippi", "United States"}, {}},
				{{"Warren County", "Mississippi", "United States"}, {}},
				{{"Washington County", "Mississippi", "United States"}, {}},
				{{"Wayne County", "Mississippi", "United States"}, {}},
				{{"Webster County", "Mississippi", "United States"}, {}},
				{{"Wilkinson County", "Mississippi", "United States"}, {}},
				{{"Winston County", "Mississippi", "United States"}, {}},
				{{"Yalobusha County", "Mississippi", "United States"}, {}},
				{{"Yazoo County", "Mississippi", "United States"}, {}},

				{{"Adair County", "Missouri", "United States"}, {}},
				{{"Andrew County", "Missouri", "United States"}, {}},
				{{"Atchison County", "Missouri", "United States"}, {}},
				{{"Audrain County", "Missouri", "United States"}, {}},
				{{"Barry County", "Missouri", "United States"}, {}},
				{{"Barton County", "Missouri", "United States"}, {}},
				{{"Bates County", "Missouri", "United States"}, {}},
				{{"Benton County", "Missouri", "United States"}, {}},
				{{"Bollinger County", "Missouri", "United States"}, {}},
				{{"Boone County", "Missouri", "United States"}, {}},
				{{"Buchanan County", "Missouri", "United States"}, {}},
				{{"Butler County", "Missouri", "United States"}, {}},
				{{"Caldwell County", "Missouri", "United States"}, {}},
				{{"Callaway County", "Missouri", "United States"}, {}},
				{{"Camden County", "Missouri", "United States"}, {}},
				{{"Cape Girardeau County", "Missouri", "United States"}, {}},
				{{"Carroll County", "Missouri", "United States"}, {}},
				{{"Carter County", "Missouri", "United States"}, {}},
				{{"Cass County", "Missouri", "United States"}, {}},
				{{"Cedar County", "Missouri", "United States"}, {}},
				{{"Chariton County", "Missouri", "United States"}, {}},
				{{"Christian County", "Missouri", "United States"}, {}},
				{{"Clark County", "Missouri", "United States"}, {}},
				{{"Clay County", "Missouri", "United States"}, {}},
				{{"Clinton County", "Missouri", "United States"}, {}},
				{{"Cole County", "Missouri", "United States"}, {}},
				{{"Cooper County", "Missouri", "United States"}, {}},
				{{"Crawford County", "Missouri", "United States"}, {}},
				{{"Dade County", "Missouri", "United States"}, {}},
				{{"Dallas County", "Missouri", "United States"}, {}},
				{{"Daviess County", "Missouri", "United States"}, {}},
				{{"DeKalb County", "Missouri", "United States"}, {}},
				{{"Dent County", "Missouri", "United States"}, {}},
				{{"Douglas County", "Missouri", "United States"}, {}},
				{{"Dunklin County", "Missouri", "United States"}, {}},
				{{"Franklin County", "Missouri", "United States"}, {}},
				{{"Gasconade County", "Missouri", "United States"}, {}},
				{{"Gentry County", "Missouri", "United States"}, {}},
				{{"Greene County", "Missouri", "United States"}, {}},
				{{"Grundy County", "Missouri", "United States"}, {}},
				{{"Harrison County", "Missouri", "United States"}, {}},
				{{"Henry County", "Missouri", "United States"}, {}},
				{{"Hickory County", "Missouri", "United States"}, {}},
				{{"Holt County", "Missouri", "United States"}, {}},
				{{"Howard County", "Missouri", "United States"}, {}},
				{{"Howell County", "Missouri", "United States"}, {}},
				{{"Iron County", "Missouri", "United States"}, {}},
				{{"Jackson County", "Missouri", "United States"}, {}},
				{{"Jasper County", "Missouri", "United States"}, {}},
				{{"Jefferson County", "Missouri", "United States"}, {}},
				{{"Johnson County", "Missouri", "United States"}, {}},
				{{"Knox County", "Missouri", "United States"}, {}},
				{{"Laclede County", "Missouri", "United States"}, {}},
				{{"Lafayette County", "Missouri", "United States"}, {}},
				{{"Lawrence County", "Missouri", "United States"}, {}},
				{{"Lewis County", "Missouri", "United States"}, {}},
				{{"Lincoln County", "Missouri", "United States"}, {}},
				{{"Linn County", "Missouri", "United States"}, {}},
				{{"Livingston County", "Missouri", "United States"}, {}},
				{{"Macon County", "Missouri", "United States"}, {}},
				{{"Madison County", "Missouri", "United States"}, {}},
				{{"Maries County", "Missouri", "United States"}, {}},
				{{"Marion County", "Missouri", "United States"}, {}},
				{{"McDonald County", "Missouri", "United States"}, {}},
				{{"Mercer County", "Missouri", "United States"}, {}},
				{{"Miller County", "Missouri", "United States"}, {}},
				{{"Mississippi County", "Missouri", "United States"}, {}},
				{{"Moniteau County", "Missouri", "United States"}, {}},
				{{"Monroe County", "Missouri", "United States"}, {}},
				{{"Montgomery County", "Missouri", "United States"}, {}},
				{{"Morgan County", "Missouri", "United States"}, {}},
				{{"New Madrid County", "Missouri", "United States"}, {}},
				{{"Newton County", "Missouri", "United States"}, {}},
				{{"Nodaway County", "Missouri", "United States"}, {}},
				{{"Oregon County", "Missouri", "United States"}, {}},
				{{"Osage County", "Missouri", "United States"}, {}},
				{{"Ozark County", "Missouri", "United States"}, {}},
				{{"Pemiscot County", "Missouri", "United States"}, {}},
				{{"Perry County", "Missouri", "United States"}, {}},
				{{"Pettis County", "Missouri", "United States"}, {}},
				{{"Phelps County", "Missouri", "United States"}, {}},
				{{"Pike County", "Missouri", "United States"}, {}},
				{{"Platte County", "Missouri", "United States"}, {}},
				{{"Polk County", "Missouri", "United States"}, {}},
				{{"Pulaski County", "Missouri", "United States"}, {}},
				{{"Putnam County", "Missouri", "United States"}, {}},
				{{"Ralls County", "Missouri", "United States"}, {}},
				{{"Randolph County", "Missouri", "United States"}, {}},
				{{"Ray County", "Missouri", "United States"}, {}},
				{{"Reynolds County", "Missouri", "United States"}, {}},
				{{"Ripley County", "Missouri", "United States"}, {}},
				{{"Saint Charles County", "Missouri", "United States"}, {}},
				{{"Saint Clair County", "Missouri", "United States"}, {}},
				{{"Saint Francois County", "Missouri", "United States"}, {}},
				{{"Saint Louis County", "Missouri", "United States"}, {"St Louis County", "St. Louis County", "St Louis", "St. Louis", "Saint Louis"}},
				{{"Sainte Genevieve County", "Missouri", "United States"}, {}},
				{{"Saline County", "Missouri", "United States"}, {}},
				{{"Schuyler County", "Missouri", "United States"}, {}},
				{{"Scotland County", "Missouri", "United States"}, {}},
				{{"Scott County", "Missouri", "United States"}, {}},
				{{"Shannon County", "Missouri", "United States"}, {}},
				{{"Shelby County", "Missouri", "United States"}, {}},
				{{"Stoddard County", "Missouri", "United States"}, {}},
				{{"Stone County", "Missouri", "United States"}, {}},
				{{"Sullivan County", "Missouri", "United States"}, {}},
				{{"Taney County", "Missouri", "United States"}, {}},
				{{"Texas County", "Missouri", "United States"}, {}},
				{{"Vernon County", "Missouri", "United States"}, {}},
				{{"Warren County", "Missouri", "United States"}, {}},
				{{"Washington County", "Missouri", "United States"}, {}},
				{{"Wayne County", "Missouri", "United States"}, {}},
				{{"Webster County", "Missouri", "United States"}, {}},
				{{"Worth County", "Missouri", "United States"}, {}},
				{{"Wright County", "Missouri", "United States"}, {}},

				{{"Beaverhead County", "Montana", "United States"}, {}},
				{{"Big Horn County", "Montana", "United States"}, {}},
				{{"Blaine County", "Montana", "United States"}, {}},
				{{"Broadwater County", "Montana", "United States"}, {}},
				{{"Carbon County", "Montana", "United States"}, {}},
				{{"Carter County", "Montana", "United States"}, {}},
				{{"Cascade County", "Montana", "United States"}, {}},
				{{"Chouteau County", "Montana", "United States"}, {}},
				{{"Custer County", "Montana", "United States"}, {}},
				{{"Daniels County", "Montana", "United States"}, {}},
				{{"Dawson County", "Montana", "United States"}, {}},
				{{"Deer Lodge County", "Montana", "United States"}, {}},
				{{"Fallon County", "Montana", "United States"}, {}},
				{{"Fergus County", "Montana", "United States"}, {}},
				{{"Flathead County", "Montana", "United States"}, {}},
				{{"Gallatin County", "Montana", "United States"}, {}},
				{{"Garfield County", "Montana", "United States"}, {}},
				{{"Glacier County", "Montana", "United States"}, {}},
				{{"Golden Valley County", "Montana", "United States"}, {}},
				{{"Granite County", "Montana", "United States"}, {}},
				{{"Hill County", "Montana", "United States"}, {}},
				{{"Jefferson County", "Montana", "United States"}, {}},
				{{"Judith Basin County", "Montana", "United States"}, {}},
				{{"Lake County", "Montana", "United States"}, {}},
				{{"Lewis and Clark County", "Montana", "United States"}, {}},
				{{"Liberty County", "Montana", "United States"}, {}},
				{{"Lincoln County", "Montana", "United States"}, {}},
				{{"Madison County", "Montana", "United States"}, {}},
				{{"McCone County", "Montana", "United States"}, {}},
				{{"Meagher County", "Montana", "United States"}, {}},
				{{"Mineral County", "Montana", "United States"}, {}},
				{{"Missoula County", "Montana", "United States"}, {}},
				{{"Musselshell County", "Montana", "United States"}, {}},
				{{"Park County", "Montana", "United States"}, {}},
				{{"Petroleum County", "Montana", "United States"}, {}},
				{{"Phillips County", "Montana", "United States"}, {}},
				{{"Pondera County", "Montana", "United States"}, {}},
				{{"Powder River County", "Montana", "United States"}, {}},
				{{"Powell County", "Montana", "United States"}, {}},
				{{"Prairie County", "Montana", "United States"}, {}},
				{{"Ravalli County", "Montana", "United States"}, {}},
				{{"Richland County", "Montana", "United States"}, {}},
				{{"Roosevelt County", "Montana", "United States"}, {}},
				{{"Rosebud County", "Montana", "United States"}, {}},
				{{"Sanders County", "Montana", "United States"}, {}},
				{{"Sheridan County", "Montana", "United States"}, {}},
				{{"Silver Bow County", "Montana", "United States"}, {}},
				{{"Stillwater County", "Montana", "United States"}, {}},
				{{"Sweet Grass County", "Montana", "United States"}, {}},
				{{"Teton County", "Montana", "United States"}, {}},
				{{"Toole County", "Montana", "United States"}, {}},
				{{"Treasure County", "Montana", "United States"}, {}},
				{{"Valley County", "Montana", "United States"}, {}},
				{{"Wheatland County", "Montana", "United States"}, {}},
				{{"Wibaux County", "Montana", "United States"}, {}},
				{{"Yellowstone County", "Montana", "United States"}, {}},

				{{"Adams County", "Nebraska", "Unite States"}, {}},
				{{"Antelope County", "Nebraska", "Unite States"}, {}},
				{{"Arthur County", "Nebraska", "Unite States"}, {}},
				{{"Banner County", "Nebraska", "Unite States"}, {}},
				{{"Blaine County", "Nebraska", "Unite States"}, {}},
				{{"Boone County", "Nebraska", "Unite States"}, {}},
				{{"Box Butte County", "Nebraska", "Unite States"}, {}},
				{{"Boyd County", "Nebraska", "Unite States"}, {}},
				{{"Brown County", "Nebraska", "Unite States"}, {}},
				{{"Buffalo County", "Nebraska", "Unite States"}, {}},
				{{"Burt County", "Nebraska", "Unite States"}, {}},
				{{"Butler County", "Nebraska", "Unite States"}, {}},
				{{"Cass County", "Nebraska", "Unite States"}, {}},
				{{"Cedar County", "Nebraska", "Unite States"}, {}},
				{{"Chase County", "Nebraska", "Unite States"}, {}},
				{{"Cherry County", "Nebraska", "Unite States"}, {}},
				{{"Cheyenne County", "Nebraska", "Unite States"}, {}},
				{{"Clay County", "Nebraska", "Unite States"}, {}},
				{{"Colfax County", "Nebraska", "Unite States"}, {}},
				{{"Cuming County", "Nebraska", "Unite States"}, {}},
				{{"Custer County", "Nebraska", "Unite States"}, {}},
				{{"Dakota County", "Nebraska", "Unite States"}, {}},
				{{"Dawes County", "Nebraska", "Unite States"}, {}},
				{{"Dawson County", "Nebraska", "Unite States"}, {}},
				{{"Deuel County", "Nebraska", "Unite States"}, {}},
				{{"Dixon County", "Nebraska", "Unite States"}, {}},
				{{"Dodge County", "Nebraska", "Unite States"}, {}},
				{{"Douglas County", "Nebraska", "Unite States"}, {}},
				{{"Dundy County", "Nebraska", "Unite States"}, {}},
				{{"Fillmore County", "Nebraska", "Unite States"}, {}},
				{{"Franklin County", "Nebraska", "Unite States"}, {}},
				{{"Frontier County", "Nebraska", "Unite States"}, {}},
				{{"Furnas County", "Nebraska", "Unite States"}, {}},
				{{"Gage County", "Nebraska", "Unite States"}, {}},
				{{"Garden County", "Nebraska", "Unite States"}, {}},
				{{"Garfield County", "Nebraska", "Unite States"}, {}},
				{{"Gosper County", "Nebraska", "Unite States"}, {}},
				{{"Grant County", "Nebraska", "Unite States"}, {}},
				{{"Greeley County", "Nebraska", "Unite States"}, {}},
				{{"Hall County", "Nebraska", "Unite States"}, {}},
				{{"Hamilton County", "Nebraska", "Unite States"}, {}},
				{{"Harlan County", "Nebraska", "Unite States"}, {}},
				{{"Hayes County", "Nebraska", "Unite States"}, {}},
				{{"Hitchcock County", "Nebraska", "Unite States"}, {}},
				{{"Holt County", "Nebraska", "Unite States"}, {}},
				{{"Hooker County", "Nebraska", "Unite States"}, {}},
				{{"Howard County", "Nebraska", "Unite States"}, {}},
				{{"Jefferson County", "Nebraska", "Unite States"}, {}},
				{{"Johnson County", "Nebraska", "Unite States"}, {}},
				{{"Kearney County", "Nebraska", "Unite States"}, {}},
				{{"Keith County", "Nebraska", "Unite States"}, {}},
				{{"Keya Paha County", "Nebraska", "Unite States"}, {}},
				{{"Kimball County", "Nebraska", "Unite States"}, {}},
				{{"Knox County", "Nebraska", "Unite States"}, {}},
				{{"Lancaster County", "Nebraska", "Unite States"}, {}},
				{{"Lincoln County", "Nebraska", "Unite States"}, {}},
				{{"Logan County", "Nebraska", "Unite States"}, {}},
				{{"Loup County", "Nebraska", "Unite States"}, {}},
				{{"Madison County", "Nebraska", "Unite States"}, {}},
				{{"McPherson County", "Nebraska", "Unite States"}, {}},
				{{"Merrick County", "Nebraska", "Unite States"}, {}},
				{{"Morrill County", "Nebraska", "Unite States"}, {}},
				{{"Nance County", "Nebraska", "Unite States"}, {}},
				{{"Nemaha County", "Nebraska", "Unite States"}, {}},
				{{"Nuckolls County", "Nebraska", "Unite States"}, {}},
				{{"Otoe County", "Nebraska", "Unite States"}, {}},
				{{"Pawnee County", "Nebraska", "Unite States"}, {}},
				{{"Perkins County", "Nebraska", "Unite States"}, {}},
				{{"Phelps County", "Nebraska", "Unite States"}, {}},
				{{"Pierce County", "Nebraska", "Unite States"}, {}},
				{{"Platte County", "Nebraska", "Unite States"}, {}},
				{{"Polk County", "Nebraska", "Unite States"}, {}},
				{{"Red Willow County", "Nebraska", "Unite States"}, {}},
				{{"Richardson County", "Nebraska", "Unite States"}, {}},
				{{"Rock County", "Nebraska", "Unite States"}, {}},
				{{"Saline County", "Nebraska", "Unite States"}, {}},
				{{"Sarpy County", "Nebraska", "Unite States"}, {}},
				{{"Saunders County", "Nebraska", "Unite States"}, {}},
				{{"Scotts Bluff County", "Nebraska", "Unite States"}, {}},
				{{"Seward County", "Nebraska", "Unite States"}, {}},
				{{"Sheridan County", "Nebraska", "Unite States"}, {}},
				{{"Sherman County", "Nebraska", "Unite States"}, {}},
				{{"Sioux County", "Nebraska", "Unite States"}, {}},
				{{"Stanton County", "Nebraska", "Unite States"}, {}},
				{{"Thayer County", "Nebraska", "Unite States"}, {}},
				{{"Thomas County", "Nebraska", "Unite States"}, {}},
				{{"Thurston County", "Nebraska", "Unite States"}, {}},
				{{"Valley County", "Nebraska", "Unite States"}, {}},
				{{"Washington County", "Nebraska", "Unite States"}, {}},
				{{"Wayne County", "Nebraska", "Unite States"}, {}},
				{{"Webster County", "Nebraska", "Unite States"}, {}},
				{{"Wheeler County", "Nebraska", "Unite States"}, {}},
				{{"York County", "Nebraska", "Unite States"}, {}},

				{{"Carson City", "Nevada", "United States"}, {}},
				{{"Churchill County", "Nevada", "United States"}, {}},
				{{"Clark County", "Nevada", "United States"}, {}},
				{{"Douglas County", "Nevada", "United States"}, {}},
				{{"Elko County", "Nevada", "United States"}, {}},
				{{"Esmeralda County", "Nevada", "United States"}, {}},
				{{"Eureka County", "Nevada", "United States"}, {}},
				{{"Humboldt County", "Nevada", "United States"}, {}},
				{{"Lander County", "Nevada", "United States"}, {}},
				{{"Lincoln County", "Nevada", "United States"}, {}},
				{{"Lyon County", "Nevada", "United States"}, {}},
				{{"Mineral County", "Nevada", "United States"}, {}},
				{{"Nye County", "Nevada", "United States"}, {}},
				{{"Pershing County", "Nevada", "United States"}, {}},
				{{"Storey County", "Nevada", "United States"}, {}},
				{{"Washoe County", "Nevada", "United States"}, {}},
				{{"White Pine County", "Nevada", "United States"}, {}},

				{{"Belknap County", "New Hampshire", "United States"}, {}},
				{{"Carroll County", "New Hampshire", "United States"}, {}},
				{{"Cheshire County", "New Hampshire", "United States"}, {}},
				{{"Coos County", "New Hampshire", "United States"}, {}},
				{{"Grafton County", "New Hampshire", "United States"}, {}},
				{{"Hillsborough County", "New Hampshire", "United States"}, {}},
				{{"Merrimack County", "New Hampshire", "United States"}, {}},
				{{"Rockingham County", "New Hampshire", "United States"}, {}},
				{{"Strafford County", "New Hampshire", "United States"}, {}},
				{{"Sullivan County", "New Hampshire", "United States"}, {}},

				{{"Atlantic County", "New Jersey", "United States"}, {}},
				{{"Bergen County", "New Jersey", "United States"}, {}},
				{{"Burlington County", "New Jersey", "United States"}, {}},
				{{"Camden County", "New Jersey", "United States"}, {}},
				{{"Cape May County", "New Jersey", "United States"}, {}},
				{{"Cumberland County", "New Jersey", "United States"}, {}},
				{{"Essex County", "New Jersey", "United States"}, {}},
				{{"Gloucester County", "New Jersey", "United States"}, {}},
				{{"Hudson County", "New Jersey", "United States"}, {}},
				{{"Hunterdon County", "New Jersey", "United States"}, {}},
				{{"Mercer County", "New Jersey", "United States"}, {}},
				{{"Middlesex County", "New Jersey", "United States"}, {}},
				{{"Monmouth County", "New Jersey", "United States"}, {}},
				{{"Morris County", "New Jersey", "United States"}, {}},
				{{"Ocean County", "New Jersey", "United States"}, {}},
				{{"Passaic County", "New Jersey", "United States"}, {}},
				{{"Salem County", "New Jersey", "United States"}, {}},
				{{"Somerset County", "New Jersey", "United States"}, {}},
				{{"Sussex County", "New Jersey", "United States"}, {}},
				{{"Union County", "New Jersey", "United States"}, {}},
				{{"Warren County", "New Jersey", "United States"}, {}},

				{{"Bernalillo County", "New Mexico", "United States"}, {}},
				{{"Catron County", "New Mexico", "United States"}, {}},
				{{"Chaves County", "New Mexico", "United States"}, {}},
				{{"Cibola County", "New Mexico", "United States"}, {}},
				{{"Colfax County", "New Mexico", "United States"}, {}},
				{{"Curry County", "New Mexico", "United States"}, {}},
				{{"De Baca County", "New Mexico", "United States"}, {}},
				{{"Doña Ana County", "New Mexico", "United States"}, {}},
				{{"Eddy County", "New Mexico", "United States"}, {}},
				{{"Grant County", "New Mexico", "United States"}, {}},
				{{"Guadalupe County", "New Mexico", "United States"}, {}},
				{{"Harding County", "New Mexico", "United States"}, {}},
				{{"Hidalgo County", "New Mexico", "United States"}, {}},
				{{"Lea County", "New Mexico", "United States"}, {}},
				{{"Lincoln County", "New Mexico", "United States"}, {}},
				{{"Los Alamos County", "New Mexico", "United States"}, {}},
				{{"Luna County", "New Mexico", "United States"}, {}},
				{{"McKinley County", "New Mexico", "United States"}, {}},
				{{"Mora County", "New Mexico", "United States"}, {}},
				{{"Otero County", "New Mexico", "United States"}, {}},
				{{"Quay County", "New Mexico", "United States"}, {}},
				{{"Rio Arriba County", "New Mexico", "United States"}, {}},
				{{"Roosevelt County", "New Mexico", "United States"}, {}},
				{{"Sandoval County", "New Mexico", "United States"}, {}},
				{{"San Juan County", "New Mexico", "United States"}, {}},
				{{"San Miguel County", "New Mexico", "United States"}, {}},
				{{"Santa Fe County", "New Mexico", "United States"}, {}},
				{{"Sierra County", "New Mexico", "United States"}, {}},
				{{"Socorro County", "New Mexico", "United States"}, {}},
				{{"Taos County", "New Mexico", "United States"}, {}},
				{{"Torrance County", "New Mexico", "United States"}, {}},
				{{"Union County", "New Mexico", "United States"}, {}},
				{{"Valencia County", "New Mexico", "United States"}, {}},

				{{"Albany County", "New York", "United States"}, {}},
				{{"Allegany County", "New York", "United States"}, {}},
				{{"Bronx County", "New York", "United States"}, {}},
				{{"Broome County", "New York", "United States"}, {}},
				{{"Cattaraugus County", "New York", "United States"}, {}},
				{{"Cayuga County", "New York", "United States"}, {}},
				{{"Chautauqua County", "New York", "United States"}, {}},
				{{"Chemung County", "New York", "United States"}, {}},
				{{"Chenango County", "New York", "United States"}, {}},
				{{"Clinton County", "New York", "United States"}, {}},
				{{"Columbia County", "New York", "United States"}, {}},
				{{"Cortland County", "New York", "United States"}, {}},
				{{"Delaware County", "New York", "United States"}, {}},
				{{"Dutchess County", "New York", "United States"}, {}},
				{{"Erie County", "New York", "United States"}, {}},
				{{"Essex County", "New York", "United States"}, {}},
				{{"Franklin County", "New York", "United States"}, {}},
				{{"Fulton County", "New York", "United States"}, {}},
				{{"Genesee County", "New York", "United States"}, {}},
				{{"Greene County", "New York", "United States"}, {}},
				{{"Hamilton County", "New York", "United States"}, {}},
				{{"Herkimer County", "New York", "United States"}, {}},
				{{"Jefferson County", "New York", "United States"}, {}},
				{{"Kings County", "New York", "United States"}, {"Kings"}},
				{{"Brooklyn", "New York", "United States"}, {}},
				{{"Lewis County", "New York", "United States"}, {}},
				{{"Livingston County", "New York", "United States"}, {}},
				{{"Madison County", "New York", "United States"}, {}},
				{{"Monroe County", "New York", "United States"}, {}},
				{{"Montgomery County", "New York", "United States"}, {}},
				{{"Nassau County", "New York", "United States"}, {}},
				{{"New York County", "New York", "United States"}, {}},
				{{"Manhattan", "New York", "United States"}, {}},
				{{"Niagara County", "New York", "United States"}, {}},
				{{"Oneida County", "New York", "United States"}, {}},
				{{"Onondaga County", "New York", "United States"}, {}},
				{{"Ontario County", "New York", "United States"}, {}},
				{{"Orange County", "New York", "United States"}, {}},
				{{"Orleans County", "New York", "United States"}, {}},
				{{"Oswego County", "New York", "United States"}, {}},
				{{"Otsego County", "New York", "United States"}, {}},
				{{"Putnam County", "New York", "United States"}, {}},
				{{"Queens County", "New York", "United States"}, {"Queens"}},
				{{"Rensselaer County", "New York", "United States"}, {}},
				{{"Richmond County", "New York", "United States"}, {}},
				{{"Staten Island", "New York", "United States"}, {}},
				{{"Rockland County", "New York", "United States"}, {}},
				{{"St. Lawrence County", "New York", "United States"}, {}},
				{{"Saratoga County", "New York", "United States"}, {}},
				{{"Schenectady County", "New York", "United States"}, {}},
				{{"Schoharie County", "New York", "United States"}, {}},
				{{"Schuyler County", "New York", "United States"}, {}},
				{{"Seneca County", "New York", "United States"}, {}},
				{{"Steuben County", "New York", "United States"}, {}},
				{{"Suffolk County", "New York", "United States"}, {}},
				{{"Sullivan County", "New York", "United States"}, {}},
				{{"Tioga County", "New York", "United States"}, {}},
				{{"Tompkins County", "New York", "United States"}, {}},
				{{"Ulster County", "New York", "United States"}, {}},
				{{"Warren County", "New York", "United States"}, {}},
				{{"Washington County", "New York", "United States"}, {}},
				{{"Wayne County", "New York", "United States"}, {}},
				{{"Westchester County", "New York", "United States"}, {}},
				{{"Wyoming County", "New York", "United States"}, {}},
				{{"Yates County", "New York", "United States"}, {}},

				{{"Alamance County", "North Carolina", "New York"}, {}},
				{{"Alexander County", "North Carolina", "New York"}, {}},
				{{"Alleghany County", "North Carolina", "New York"}, {}},
				{{"Anson County", "North Carolina", "New York"}, {}},
				{{"Ashe County", "North Carolina", "New York"}, {}},
				{{"Avery County", "North Carolina", "New York"}, {}},
				{{"Beaufort County", "North Carolina", "New York"}, {}},
				{{"Bertie County", "North Carolina", "New York"}, {}},
				{{"Bladen County", "North Carolina", "New York"}, {}},
				{{"Brunswick County", "North Carolina", "New York"}, {}},
				{{"Buncombe County", "North Carolina", "New York"}, {}},
				{{"Burke County", "North Carolina", "New York"}, {}},
				{{"Cabarrus County", "North Carolina", "New York"}, {}},
				{{"Caldwell County", "North Carolina", "New York"}, {}},
				{{"Camden County", "North Carolina", "New York"}, {}},
				{{"Carteret County", "North Carolina", "New York"}, {}},
				{{"Caswell County", "North Carolina", "New York"}, {}},
				{{"Catawba County", "North Carolina", "New York"}, {}},
				{{"Chatham County", "North Carolina", "New York"}, {}},
				{{"Cherokee County", "North Carolina", "New York"}, {}},
				{{"Chowan County", "North Carolina", "New York"}, {}},
				{{"Clay County", "North Carolina", "New York"}, {}},
				{{"Cleveland County", "North Carolina", "New York"}, {}},
				{{"Columbus County", "North Carolina", "New York"}, {}},
				{{"Craven County", "North Carolina", "New York"}, {}},
				{{"Cumberland County", "North Carolina", "New York"}, {}},
				{{"Currituck County", "North Carolina", "New York"}, {}},
				{{"Dare County", "North Carolina", "New York"}, {}},
				{{"Davidson County", "North Carolina", "New York"}, {}},
				{{"Davie County", "North Carolina", "New York"}, {}},
				{{"Duplin County", "North Carolina", "New York"}, {}},
				{{"Durham County", "North Carolina", "New York"}, {}},
				{{"Edgecombe County", "North Carolina", "New York"}, {}},
				{{"Forsyth County", "North Carolina", "New York"}, {}},
				{{"Franklin County", "North Carolina", "New York"}, {}},
				{{"Gaston County", "North Carolina", "New York"}, {}},
				{{"Gates County", "North Carolina", "New York"}, {}},
				{{"Graham County", "North Carolina", "New York"}, {}},
				{{"Granville County", "North Carolina", "New York"}, {}},
				{{"Greene County", "North Carolina", "New York"}, {}},
				{{"Guilford County", "North Carolina", "New York"}, {}},
				{{"Halifax County", "North Carolina", "New York"}, {}},
				{{"Harnett County", "North Carolina", "New York"}, {}},
				{{"Haywood County", "North Carolina", "New York"}, {}},
				{{"Henderson County", "North Carolina", "New York"}, {}},
				{{"Hertford County", "North Carolina", "New York"}, {}},
				{{"Hoke County", "North Carolina", "New York"}, {}},
				{{"Hyde County", "North Carolina", "New York"}, {}},
				{{"Iredell County", "North Carolina", "New York"}, {}},
				{{"Jackson County", "North Carolina", "New York"}, {}},
				{{"Johnston County", "North Carolina", "New York"}, {}},
				{{"Jones County", "North Carolina", "New York"}, {}},
				{{"Lee County", "North Carolina", "New York"}, {}},
				{{"Lenoir County", "North Carolina", "New York"}, {}},
				{{"Lincoln County", "North Carolina", "New York"}, {}},
				{{"McDowell County", "North Carolina", "New York"}, {}},
				{{"Macon County", "North Carolina", "New York"}, {}},
				{{"Madison County", "North Carolina", "New York"}, {}},
				{{"Martin County", "North Carolina", "New York"}, {}},
				{{"Mecklenburg County", "North Carolina", "New York"}, {}},
				{{"Mitchell County", "North Carolina", "New York"}, {}},
				{{"Montgomery County", "North Carolina", "New York"}, {}},
				{{"Moore County", "North Carolina", "New York"}, {}},
				{{"Nash County", "North Carolina", "New York"}, {}},
				{{"New Hanover County", "North Carolina", "New York"}, {}},
				{{"Northampton County", "North Carolina", "New York"}, {}},
				{{"Onslow County", "North Carolina", "New York"}, {}},
				{{"Orange County", "North Carolina", "New York"}, {}},
				{{"Pamlico County", "North Carolina", "New York"}, {}},
				{{"Pasquotank County", "North Carolina", "New York"}, {}},
				{{"Pender County", "North Carolina", "New York"}, {}},
				{{"Perquimans County", "North Carolina", "New York"}, {}},
				{{"Person County", "North Carolina", "New York"}, {}},
				{{"Pitt County", "North Carolina", "New York"}, {}},
				{{"Polk County", "North Carolina", "New York"}, {}},
				{{"Randolph County", "North Carolina", "New York"}, {}},
				{{"Richmond County", "North Carolina", "New York"}, {}},
				{{"Robeson County", "North Carolina", "New York"}, {}},
				{{"Rockingham County", "North Carolina", "New York"}, {}},
				{{"Rowan County", "North Carolina", "New York"}, {}},
				{{"Rutherford County", "North Carolina", "New York"}, {}},
				{{"Sampson County", "North Carolina", "New York"}, {}},
				{{"Scotland County", "North Carolina", "New York"}, {}},
				{{"Stanly County", "North Carolina", "New York"}, {}},
				{{"Stokes County", "North Carolina", "New York"}, {}},
				{{"Surry County", "North Carolina", "New York"}, {}},
				{{"Swain County", "North Carolina", "New York"}, {}},
				{{"Transylvania County", "North Carolina", "New York"}, {}},
				{{"Tyrrell County", "North Carolina", "New York"}, {}},
				{{"Union County", "North Carolina", "New York"}, {}},
				{{"Vance County", "North Carolina", "New York"}, {}},
				{{"Wake County", "North Carolina", "New York"}, {}},
				{{"Warren County", "North Carolina", "New York"}, {}},
				{{"Washington County", "North Carolina", "New York"}, {}},
				{{"Watauga County", "North Carolina", "New York"}, {}},
				{{"Wayne County", "North Carolina", "New York"}, {}},
				{{"Wilkes County", "North Carolina", "New York"}, {}},
				{{"Wilson County", "North Carolina", "New York"}, {}},
				{{"Yadkin County", "North Carolina", "New York"}, {}},
				{{"Yancey County", "North Carolina", "New York"}, {}},

				{{"Adams County", "North Dakota", "United States"}, {}},
				{{"Barnes County", "North Dakota", "United States"}, {}},
				{{"Benson County", "North Dakota", "United States"}, {}},
				{{"Billings County", "North Dakota", "United States"}, {}},
				{{"Bottineau County", "North Dakota", "United States"}, {}},
				{{"Bowman County", "North Dakota", "United States"}, {}},
				{{"Burke County", "North Dakota", "United States"}, {}},
				{{"Burleigh County", "North Dakota", "United States"}, {}},
				{{"Cass County", "North Dakota", "United States"}, {}},
				{{"Cavalier County", "North Dakota", "United States"}, {}},
				{{"Dickey County", "North Dakota", "United States"}, {}},
				{{"Divide County", "North Dakota", "United States"}, {}},
				{{"Dunn County", "North Dakota", "United States"}, {}},
				{{"Eddy County", "North Dakota", "United States"}, {}},
				{{"Emmons County", "North Dakota", "United States"}, {}},
				{{"Foster County", "North Dakota", "United States"}, {}},
				{{"Golden Valley County", "North Dakota", "United States"}, {}},
				{{"Grand Forks County", "North Dakota", "United States"}, {}},
				{{"Grant County", "North Dakota", "United States"}, {}},
				{{"Griggs County", "North Dakota", "United States"}, {}},
				{{"Hettinger County", "North Dakota", "United States"}, {}},
				{{"Kidder County", "North Dakota", "United States"}, {}},
				{{"LaMoure County", "North Dakota", "United States"}, {}},
				{{"Logan County", "North Dakota", "United States"}, {}},
				{{"McHenry County", "North Dakota", "United States"}, {}},
				{{"McIntosh County", "North Dakota", "United States"}, {}},
				{{"McKenzie County", "North Dakota", "United States"}, {}},
				{{"McLean County", "North Dakota", "United States"}, {}},
				{{"Mercer County", "North Dakota", "United States"}, {}},
				{{"Morton County", "North Dakota", "United States"}, {}},
				{{"Mountrail County", "North Dakota", "United States"}, {}},
				{{"Nelson County", "North Dakota", "United States"}, {}},
				{{"Oliver County", "North Dakota", "United States"}, {}},
				{{"Pembina County", "North Dakota", "United States"}, {}},
				{{"Pierce County", "North Dakota", "United States"}, {}},
				{{"Ramsey County", "North Dakota", "United States"}, {}},
				{{"Ransom County", "North Dakota", "United States"}, {}},
				{{"Renville County", "North Dakota", "United States"}, {}},
				{{"Richland County", "North Dakota", "United States"}, {}},
				{{"Rolette County", "North Dakota", "United States"}, {}},
				{{"Sargent County", "North Dakota", "United States"}, {}},
				{{"Sheridan County", "North Dakota", "United States"}, {}},
				{{"Sioux County", "North Dakota", "United States"}, {}},
				{{"Slope County", "North Dakota", "United States"}, {}},
				{{"Stark County", "North Dakota", "United States"}, {}},
				{{"Steele County", "North Dakota", "United States"}, {}},
				{{"Stutsman County", "North Dakota", "United States"}, {}},
				{{"Towner County", "North Dakota", "United States"}, {}},
				{{"Traill County", "North Dakota", "United States"}, {}},
				{{"Walsh County", "North Dakota", "United States"}, {}},
				{{"Ward County", "North Dakota", "United States"}, {}},
				{{"Wells County", "North Dakota", "United States"}, {}},
				{{"Williams County", "North Dakota", "United States"}, {}}
			};
	}
}
