package ws.daley.genealogy.db.places;

import org.apache.openjpa.persistence.OpenJPAEntityManager;

public class PlaceLoader
{
	private static OpenJPAEntityManager entityManager;
	
    public static void loadPlaces(OpenJPAEntityManager em)
    {
    	entityManager = em;
    	loadCountries();
    	loadCountryAliases();
    	loadStates();
    	loadStateAliases();
    	loadCountyAliases();
    	loadFixups();
    }

    public static void loadCountryAliases()
    {
		for(CountryAlias countryAlias: new CountryAlias[]{
				new CountryAlias("United States", "USA"),
				new CountryAlias("Germany", "Bavaria"),
//				new CountryAlias("United Kingdom", "England"),
//				new CountryAlias("United Kingdom", "Northern Ireland"),
				new CountryAlias("Netherlands", "Holland"),
				new CountryAlias("Russian Federation", "Russia")
//				new CountryAlias("United Kingdom", "Wales")
		})
			entityManager.persist(countryAlias);
    }

    public static void loadCountries()
    {
		for(Country country: new Country[]{
				Country.getCountry(null, "AFGHANISTAN", "AF", null),
				Country.getCountry(null, "ALBANIA", "AL", null),
				Country.getCountry(null, "ALGERIA", "DZ", null),
				Country.getCountry(null, "AMERICAN SAMOA", "AS", null),
				Country.getCountry(null, "ANDORRA", "AD", null),
				Country.getCountry(null, "ANGOLA", "AO", null),
				Country.getCountry(null, "ANGUILLA", "AI", null),
				Country.getCountry(null, "ANTARCTICA", "AQ", null),
				Country.getCountry(null, "ANTIGUA BARBUDA", "AG", null),
				Country.getCountry(null, "ARGENTINA", "AR", null),
				Country.getCountry(null, "ARMENIA", "AM", null),
				Country.getCountry(null, "ARUBA", "AW", null),
				Country.getCountry(null, "AUSTRALIA", "AU", null),
				Country.getCountry(null, "AUSTRIA", "AT", null),
				Country.getCountry(null, "AZERBAIJAN", "AZ", null),
				Country.getCountry(null, "BAHAMAS", "BS", null),
				Country.getCountry(null, "BAHRAIN", "BH", null),
				Country.getCountry(null, "BANGLADESH", "BD", null),
				Country.getCountry(null, "BARBADOS", "BB", null),
				Country.getCountry(null, "BELARUS", "BY", null),
				Country.getCountry(null, "BELGIUM", "BE", null),
				Country.getCountry(null, "BELIZE", "BZ", null),
				Country.getCountry(null, "BENIN", "BJ", null),
				Country.getCountry(null, "BERMUDA", "BM", null),
				Country.getCountry(null, "BHUTAN", "BT", null),
				Country.getCountry(null, "BOLIVIA", "BO", null),
				Country.getCountry(null, "BOSNIA HERZEGOVINA", "BA", null),
				Country.getCountry(null, "BOTSWANA", "BW", null),
				Country.getCountry(null, "BOUVET ISLAND", "BV", null),
				Country.getCountry(null, "BRAZIL", "BR", null),
				Country.getCountry(null, "BRITISH INDIAN OCEAN TERRITORY", "IO", null),
				Country.getCountry(null, "BRUNEI DARUSSALAM", "BN", null),
				Country.getCountry(null, "BULGARIA", "BG", null),
				Country.getCountry(null, "BURKINA FASO", "BF", null),
				Country.getCountry(null, "BURUNDI", "BI", null),
				Country.getCountry(null, "CAMBODIA", "KH", null),
				Country.getCountry(null, "CAMEROON", "CM", null),
				Country.getCountry(null, "CANADA", "CA", null),
				Country.getCountry(null, "CAPE VERDE", "CV", null),
				Country.getCountry(null, "CAYMAN ISLANDS", "KY", null),
				Country.getCountry(null, "CENTRAL AFRICAN REpublic static", "CF", null),
				Country.getCountry(null, "CHAD", "TD", null),
				Country.getCountry(null, "CHILE", "CL", null),
				Country.getCountry(null, "CHINA", "CN", null),
				Country.getCountry(null, "CHRISTMAS ISLAND", "CX", null),
				Country.getCountry(null, "COCOS (KEELING, null) ISLANDS", "CC", null),
				Country.getCountry(null, "COLOMBIA", "CO", null),
				Country.getCountry(null, "COMOROS", "KM", null),
				Country.getCountry(null, "CONGO", "CG", null),
				Country.getCountry(null, "CONGO, THE DEMOCRATIC REpublic static OF", "CD", null),
				Country.getCountry(null, "COOK ISLANDS", "CK", null),
				Country.getCountry(null, "COSTA RICA", "CR", null),
				Country.getCountry(null, "CÔTE D''IVOIRE", "CI", null),
				Country.getCountry(null, "CROATIA", "HR", null),
				Country.getCountry(null, "CUBA", "CU", null),
				Country.getCountry(null, "CYPRUS", "CY", null),
				Country.getCountry(null, "CZECH REpublic static", "CZ", null),
				Country.getCountry(null, "DENMARK", "DK", null),
				Country.getCountry(null, "DJIBOUTI", "DJ", null),
				Country.getCountry(null, "DOMINICA", "DM", null),
				Country.getCountry(null, "DOMINICAN REpublic static", "DO", null),
				Country.getCountry(null, "ECUADOR", "EC", null),
				Country.getCountry(null, "EGYPT", "EG", null),
				Country.getCountry(null, "EL SALVADOR", "SV", null),
				Country.getCountry(null, "EQUATORIAL GUINEA", "GQ", null),
				Country.getCountry(null, "ERITREA", "ER", null),
				Country.getCountry(null, "ESTONIA", "EE", null),
				Country.getCountry(null, "ETHIOPIA", "ET", null),
				Country.getCountry(null, "FALKLAND ISLANDS (MALVINAS, null)", "FK", null),
				Country.getCountry(null, "FAROE ISLANDS", "FO", null),
				Country.getCountry(null, "FIJI", "FJ", null),
				Country.getCountry(null, "FINLAND", "FI", null),
				Country.getCountry(null, "FRANCE", "FR", null),
				Country.getCountry(null, "FRENCH GUIANA", "GF", null),
				Country.getCountry(null, "FRENCH POLYNESIA", "PF", null),
				Country.getCountry(null, "FRENCH SOUTHERN TERRITORIES", "TF", null),
				Country.getCountry(null, "GABON", "GA", null),
				Country.getCountry(null, "GAMBIA", "GM", null),
				Country.getCountry(null, "GEORGIA", "GE", null),
				Country.getCountry(null, "GERMANY", "DE", null),
				Country.getCountry(null, "GHANA", "GH", null),
				Country.getCountry(null, "GIBRALTAR", "GI", null),
				Country.getCountry(null, "GREECE", "GR", null),
				Country.getCountry(null, "GREENLAND", "GL", null),
				Country.getCountry(null, "GRENADA", "GD", null),
				Country.getCountry(null, "GUADELOUPE", "GP", null),
				Country.getCountry(null, "GUAM", "GU", null),
				Country.getCountry(null, "GUATEMALA", "GT", null),
				Country.getCountry(null, "GUINEA", "GN", null),
				Country.getCountry(null, "GUINEA-BISSAU", "GW", null),
				Country.getCountry(null, "GUYANA", "GY", null),
				Country.getCountry(null, "HAITI", "HT", null),
				Country.getCountry(null, "HEARD ISLAND MCDONALD ISLANDS", "HM", null),
				Country.getCountry(null, "HOLY SEE (VATICAN CITY STATE, null)", "VA", null),
				Country.getCountry(null, "HONDURAS", "HN", null),
				Country.getCountry(null, "HONG KONG", "HK", null),
				Country.getCountry(null, "HUNGARY", "HU", null),
				Country.getCountry(null, "ICELAND", "IS", null),
				Country.getCountry(null, "INDIA", "IN", null),
				Country.getCountry(null, "INDONESIA", "ID", null),
				Country.getCountry(null, "IRAN, ISLAMIC REpublic static OF", "IR", null),
				Country.getCountry(null, "IRAQ", "IQ", null),
//				Country.getCountry(null, "IRELAND", "IE", null),
				Country.getCountry(null, "ISRAEL", "IL", null),
				Country.getCountry(null, "ITALY", "IT", null),
				Country.getCountry(null, "JAMAICA", "JM", null),
				Country.getCountry(null, "JAPAN", "JP", null),
				Country.getCountry(null, "JORDAN", "JO", null),
				Country.getCountry(null, "KAZAKHSTAN", "KZ", null),
				Country.getCountry(null, "KENYA", "KE", null),
				Country.getCountry(null, "KIRIBATI", "KI", null),
				Country.getCountry(null, "KOREA, DEMOCRATIC PEOPLE''S REpublic static OF", "KP", null),
				Country.getCountry(null, "KOREA, REpublic static OF", "KR", null),
				Country.getCountry(null, "KUWAIT", "KW", null),
				Country.getCountry(null, "KYRGYZSTAN", "KG", null),
				Country.getCountry(null, "LAO PEOPLE''S DEMOCRATIC REpublic static", "LA", null),
				Country.getCountry(null, "LATVIA", "LV", null),
				Country.getCountry(null, "LEBANON", "LB", null),
				Country.getCountry(null, "LESOTHO", "LS", null),
				Country.getCountry(null, "LIBERIA", "LR", null),
				Country.getCountry(null, "LIBYAN ARAB JAMAHIRIYA", "LY", null),
				Country.getCountry(null, "LIECHTENSTEIN", "LI", null),
				Country.getCountry(null, "LITHUANIA", "LT", null),
				Country.getCountry(null, "LUXEMBOURG", "LU", null),
				Country.getCountry(null, "MACAO", "MO", null),
				Country.getCountry(null, "MACEDONIA, THE FORMER YUGOSLAV REpublic static OF", "MK", null),
				Country.getCountry(null, "MADAGASCAR", "MG", null),
				Country.getCountry(null, "MALAWI", "MW", null),
				Country.getCountry(null, "MALAYSIA", "MY", null),
				Country.getCountry(null, "MALDIVES", "MV", null),
				Country.getCountry(null, "MALI", "ML", null),
				Country.getCountry(null, "MALTA", "MT", null),
				Country.getCountry(null, "MARSHALL ISLANDS", "MH", null),
				Country.getCountry(null, "MARTINIQUE", "MQ", null),
				Country.getCountry(null, "MAURITANIA", "MR", null),
				Country.getCountry(null, "MAURITIUS", "MU", null),
				Country.getCountry(null, "MAYOTTE", "YT", null),
				Country.getCountry(null, "MEXICO", "MX", null),
				Country.getCountry(null, "MICRONESIA, FEDERATED STATES OF", "FM", null),
				Country.getCountry(null, "MOLDOVA, REpublic static OF", "MD", null),
				Country.getCountry(null, "MONACO", "MC", null),
				Country.getCountry(null, "MONGOLIA", "MN", null),
				Country.getCountry(null, "MONTSERRAT", "MS", null),
				Country.getCountry(null, "MOROCCO", "MA", null),
				Country.getCountry(null, "MOZAMBIQUE", "MZ", null),
				Country.getCountry(null, "MYANMAR", "MM", null),
				Country.getCountry(null, "NAMIBIA", "NA", null),
				Country.getCountry(null, "NAURU", "NR", null),
				Country.getCountry(null, "NEPAL", "NP", null),
				Country.getCountry(null, "NETHERLANDS", "NL", null),
				Country.getCountry(null, "NETHERLANDS ANTILLES", "AN", null),
				Country.getCountry(null, "NEW CALEDONIA", "NC", null),
				Country.getCountry(null, "NEW ZEALAND", "NZ", null),
				Country.getCountry(null, "NICARAGUA", "NI", null),
				Country.getCountry(null, "NIGER", "NE", null),
				Country.getCountry(null, "NIGERIA", "NG", null),
				Country.getCountry(null, "NIUE", "NU", null),
				Country.getCountry(null, "NORFOLK ISLAND", "NF", null),
				Country.getCountry(null, "NORTHERN MARIANA ISLANDS", "MP", null),
				Country.getCountry(null, "NORWAY", "NO", null),
				Country.getCountry(null, "OMAN", "OM", null),
				Country.getCountry(null, "PAKISTAN", "PK", null),
				Country.getCountry(null, "PALAU", "PW", null),
				Country.getCountry(null, "PALESTINIAN TERRITORY, OCCUPIED", "PS", null),
				Country.getCountry(null, "PANAMA", "PA", null),
				Country.getCountry(null, "PAPUA NEW GUINEA", "PG", null),
				Country.getCountry(null, "PARAGUAY", "PY", null),
				Country.getCountry(null, "PERU", "PE", null),
				Country.getCountry(null, "PHILIPPINES", "PH", null),
				Country.getCountry(null, "PITCAIRN", "PN", null),
				Country.getCountry(null, "POLAND", "PL", null),
				Country.getCountry(null, "PORTUGAL", "PT", null),
				Country.getCountry(null, "PUERTO RICO", "PR", null),
				Country.getCountry(null, "QATAR", "QA", null),
				Country.getCountry(null, "RÉUNION", "RE", null),
				Country.getCountry(null, "ROMANIA", "RO", null),
				Country.getCountry(null, "RUSSIAN FEDERATION", "RU", null),
				Country.getCountry(null, "RWANDA", "RW", null),
				Country.getCountry(null, "SAINT HELENA", "SH", null),
				Country.getCountry(null, "SAINT KITTS NEVIS", "KN", null),
				Country.getCountry(null, "SAINT LUCIA", "LC", null),
				Country.getCountry(null, "SAINT PIERRE MIQUELON", "PM", null),
				Country.getCountry(null, "SAINT VINCENT THE GRENADINES", "VC", null),
				Country.getCountry(null, "SAMOA", "WS", null),
				Country.getCountry(null, "SAN MARINO", "SM", null),
				Country.getCountry(null, "SAO TOME PRINCIPE", "ST", null),
				Country.getCountry(null, "SAUDI ARABIA", "SA", null),
				Country.getCountry(null, "SENEGAL", "SN", null),
				Country.getCountry(null, "SERBIA MONTENEGRO", "CS", null),
				Country.getCountry(null, "SEYCHELLES", "SC", null),
				Country.getCountry(null, "SIERRA LEONE", "SL", null),
				Country.getCountry(null, "SINGAPORE", "SG", null),
				Country.getCountry(null, "SLOVAKIA", "SK", null),
				Country.getCountry(null, "SLOVENIA", "SI", null),
				Country.getCountry(null, "SOLOMON ISLANDS", "SB", null),
				Country.getCountry(null, "SOMALIA", "SO", null),
				Country.getCountry(null, "SOUTH AFRICA", "ZA", null),
				Country.getCountry(null, "SOUTH GEORGIA SOUTH SANDWICH ISLANDS", "GS", null),
				Country.getCountry(null, "SPAIN", "ES", null),
				Country.getCountry(null, "SRI LANKA", "LK", null),
				Country.getCountry(null, "SUDAN", "SD", null),
				Country.getCountry(null, "SURINAME", "SR", null),
				Country.getCountry(null, "SVALBARD JAN MAYEN", "SJ", null),
				Country.getCountry(null, "SWAZILAND", "SZ", null),
				Country.getCountry(null, "SWEDEN", "SE", null),
				Country.getCountry(null, "SWITZERLAND", "CH", null),
				Country.getCountry(null, "SYRIAN ARAB REpublic static", "SY", null),
				Country.getCountry(null, "TAIWAN, PROVINCE OF CHINA", "TW", null),
				Country.getCountry(null, "TAJIKISTAN", "TJ", null),
				Country.getCountry(null, "TANZANIA, UNITED REpublic static OF", "TZ", null),
				Country.getCountry(null, "THAILAND", "TH", null),
				Country.getCountry(null, "TIMOR-LESTE", "TL", null),
				Country.getCountry(null, "TOGO", "TG", null),
				Country.getCountry(null, "TOKELAU", "TK", null),
				Country.getCountry(null, "TONGA", "TO", null),
				Country.getCountry(null, "TRINIDAD TOBAGO", "TT", null),
				Country.getCountry(null, "TUNISIA", "TN", null),
				Country.getCountry(null, "TURKEY", "TR", null),
				Country.getCountry(null, "TURKMENISTAN", "TM", null),
				Country.getCountry(null, "TURKS CAICOS ISLANDS", "TC", null),
				Country.getCountry(null, "TUVALU", "TV", null),
				Country.getCountry(null, "UGANDA", "UG", null),
				Country.getCountry(null, "UKRAINE", "UA", null),
				Country.getCountry(null, "UNITED ARAB EMIRATES", "AE", null),
				Country.getCountry(null, "UNITED KINGDOM", "GB", null),
				Country.getCountry(null, "UNITED STATES", "US", null),
				Country.getCountry(null, "UNITED STATES MINOR OUTLYING ISLANDS", "UM", null),
				Country.getCountry(null, "URUGUAY", "UY", null),
				Country.getCountry(null, "UZBEKISTAN", "UZ", null),
				Country.getCountry(null, "VANUATU", "VU", null),
				Country.getCountry(null, "VENEZUELA", "VE", null),
				Country.getCountry(null, "VIET NAM", "VN", null),
				Country.getCountry(null, "VIRGIN ISLANDS, BRITISH", "VG", null),
				Country.getCountry(null, "VIRGIN ISLANDS, U.S.", "VI", null),
				Country.getCountry(null, "WALLIS FUTUNA", "WF", null),
				Country.getCountry(null, "WESTERN SAHARA", "EH", null),
				Country.getCountry(null, "YEMEN", "YE", null),
				Country.getCountry(null, "ZAMBIA", "ZM", null),
				Country.getCountry(null, "ZIMBABWE", "ZW", null)
				/**
				 * Vatican City State see HOLY SEE
				 * Zaire see CONGO, DEMOCRATIC REpublic static OF
				 */
		})
			entityManager.persist(country);
    }
    
    public static void loadStates()
    {
    	Country us = Country.getCountryMap().get("us");
    	Country ca = Country.getCountryMap().get("ca");
    	Country mx = Country.getCountryMap().get("mx");
    	Country fr = Country.getCountryMap().get("fr");
    	Country de = Country.getCountryMap().get("de");
    	Country gb = Country.getCountryMap().get("gb");
    	Country nl = Country.getCountryMap().get("nl");
    	for(State state:new State[]{
    			State.getState(us, "ALABAMA", "AL", null),
    			State.getState(us, "ALASKA", "AK", null),
    			State.getState(us, "AMERICAN SAMOA", "AS", null),
    			State.getState(us, "ARIZONA", "AZ", null),
    			State.getState(us, "ARKANSAS", "AR", null),
    			State.getState(us, "CALIFORNIA", "CA", null),
    			State.getState(us, "COLORADO", "CO", null),
    			State.getState(us, "CONNECTICUT", "CT", null),
    			State.getState(us, "DELAWARE", "DE", null),
    			State.getState(us, "DISTRICT OF COLUMBIA", "DC", null),
    			State.getState(us, "FEDERATED STATES OF MICRONESIA", "FM", null),
    			State.getState(us, "FLORIDA", "FL", null),
    			State.getState(us, "GEORGIA", "GA", null),
    			State.getState(us, "GUAM", "GU", null),
    			State.getState(us, "HAWAII", "HI", null),
    			State.getState(us, "IDAHO", "ID", null),
    			State.getState(us, "ILLINOIS", "IL", null),
    			State.getState(us, "INDIANA", "IN", null),
    			State.getState(us, "IOWA", "IA", null),
    			State.getState(us, "KANSAS", "KS", null),
    			State.getState(us, "KENTUCKY", "KY", null),
    			State.getState(us, "LOUISIANA", "LA", null),
    			State.getState(us, "MAINE", "ME", null),
    			State.getState(us, "MARSHALL ISLANDS", "MH", null),
    			State.getState(us, "MARYLAND", "MD", null),
    			State.getState(us, "MASSACHUSETTS", "MA", null),
    			State.getState(us, "MICHIGAN", "MI", null),
    			State.getState(us, "MINNESOTA", "MN", null),
    			State.getState(us, "MISSISSIPPI", "MS", null),
    			State.getState(us, "MISSOURI", "MO", null),
    			State.getState(us, "MONTANA", "MT", null),
    			State.getState(us, "NEBRASKA", "NE", null),
    			State.getState(us, "NEVADA", "NV", null),
    			State.getState(us, "NEW HAMPSHIRE", "NH", null),
    			State.getState(us, "NEW JERSEY", "NJ", null),
    			State.getState(us, "NEW MEXICO", "NM", null),
    			State.getState(us, "NEW YORK", "NY", null),
    			State.getState(us, "NORTH CAROLINA", "NC", null),
    			State.getState(us, "NORTH DAKOTA", "ND", null),
    			State.getState(us, "NORTHERN MARIANA ISLANDS", "MP", null),
    			State.getState(us, "OHIO", "OH", null),
    			State.getState(us, "OKLAHOMA", "OK", null),
    			State.getState(us, "OREGON", "OR", null),
    			State.getState(us, "PALAU", "PW", null),
    			State.getState(us, "PENNSYLVANIA", "PA", null),
    			State.getState(us, "PUERTO RICO", "PR", null),
    			State.getState(us, "RHODE ISLAND", "RI", null),
    			State.getState(us, "SOUTH CAROLINA", "SC", null),
    			State.getState(us, "SOUTH DAKOTA", "SD", null),
    			State.getState(us, "TENNESSEE", "TN", null),
    			State.getState(us, "TEXAS", "TX", null),
    			State.getState(us, "UTAH", "UT", null),
    			State.getState(us, "VERMONT", "VT", null),
    			State.getState(us, "VIRGIN ISLANDS", "VI", null),
    			State.getState(us, "VIRGINIA", "VA", null),
    			State.getState(us, "WASHINGTON", "WA", null),
    			State.getState(us, "WASHINGTON, DISTRICT OF COLUMBIA", "DC", null),
    			State.getState(us, "WEST VIRGINIA", "WV", null),
    			State.getState(us, "WISCONSIN", "WI", null),
    			State.getState(us, "WYOMING", "WY", null),
    			State.getState(us, "Armed Forces Africa", "AE", null),
    			State.getState(us, "Armed Forces Americas", "AA", null),
    			State.getState(us, "Armed Forces Canada", "AE", null),
    			State.getState(us, "Armed Forces Europe", "AE", null),
    			State.getState(us, "Armed Forces Middle East", "AE", null),
    			State.getState(us, "Armed Forces Pacific", "AP", null),
    			State.getState(ca, "Alberta", "AB", null),
    			State.getState(ca, "British Columbia", "BC", null),
    			State.getState(ca, "Manitoba", "MB", null),
    			State.getState(ca, "New Brunswick", "NB", null),
    			State.getState(ca, "Newfoundland and Labrador", "NL", null),
    			State.getState(ca, "Northwest Territories", "NT", null),
    			State.getState(ca, "Nova Scotia", "NS", null),
    			State.getState(ca, "Nunavut", "NU", null),
    			State.getState(ca, "Ontario", "ON", null),
    			State.getState(ca, "Prince Edward Island", "PE", null),
    			State.getState(ca, "Quebec", "QC", null),
    			State.getState(ca, "Saskatchewan", "SK", null),
    			State.getState(ca, "Yukon", "YT", null),
    			State.getState(mx, "Aguascalientes", "AG", null),
    			State.getState(mx, "Baja California", "BN", null),
    			State.getState(mx, "Baja California Sur", "BS", null),
    			State.getState(mx, "Campeche", "CM", null),
    			State.getState(mx, "Chiapas", "CP", null),
    			State.getState(mx, "Chihuahua", "CH", null),
    			State.getState(mx, "Coahuila", "CA", null),
    			State.getState(mx, "Colima", "CL", null),
    			State.getState(mx, "Distrito Federal", "DF", null),
    			State.getState(mx, "Durango", "DU", null),
    			State.getState(mx, "Guanajuato", "GJ", null),
    			State.getState(mx, "Guerrero", "GR", null),
    			State.getState(mx, "Hidalgo", "HI", null),
    			State.getState(mx, "Jalisco", "JA", null),
    			State.getState(mx, "México", "MX", null),
    			State.getState(mx, "Michoacán", "MC", null),
    			State.getState(mx, "Morelos", "MR", null),
    			State.getState(mx, "Nayarit", "NA", null),
    			State.getState(mx, "Nuevo León", "NL", null),
    			State.getState(mx, "Oaxaca", "OA", null),
    			State.getState(mx, "Puebla", "PU", null),
    			State.getState(mx, "Querétaro", "AE", null),
    			State.getState(mx, "Quintana Roo", "AR", null),
    			State.getState(mx, "San Luis Potosí", "SL", null),
    			State.getState(mx, "Sinaloa", "SI", null),
    			State.getState(mx, "Sonora", "SO", null),
    			State.getState(mx, "Tabasco", "TB", null),
    			State.getState(mx, "Tamaulipas", "TM", null),
    			State.getState(mx, "Tlaxcala", "TL", null),
    			State.getState(mx, "Veracruz", "VE", null),
    			State.getState(mx, "Yucatán", "YU", null),
    			State.getState(mx, "Zacatecas", "ZA", null),
    			State.getState(fr, "Alsace", "", null),
    			State.getState(fr, "Aquitane", "", null),
    			State.getState(fr, "Auvergne", "", null),
    			State.getState(fr, "Bourgogne", "", null),
    			State.getState(fr, "Brittany", "", null),
    			State.getState(fr, "Centre", "", null),
    			State.getState(fr, "Champagne-Ardenne", "", null),
    			State.getState(fr, "Corsica", "", null),
    			State.getState(fr, "Franche-Comté", "", null),
    			State.getState(fr, "Île-de-France", "", null),
    			State.getState(fr, "Languedoc-Roussillon", "", null),
    			State.getState(fr, "Limousin", "", null),
    			State.getState(fr, "Lorraine", "", null),
    			State.getState(fr, "Midi-Pyrénées", "", null),
    			State.getState(fr, "Nord-Pas-de-Calais", "", null),
    			State.getState(fr, "Basse-Normandie", "", null),
    			State.getState(fr, "Haute-Normandie", "", null),
    			State.getState(fr, "Pays de la Loire", "", null),
    			State.getState(fr, "Picardy", "", null),
    			State.getState(fr, "Poitou-Charentes", "", null),
    			State.getState(fr, "Provence-Alpes-Côte d''Azur", "", null),
    			State.getState(fr, "Rhône-Alpes", "", null),
    			State.getState(fr, "French Guiana", "", null),
    			State.getState(fr, "Guadeloupe", "", null),
    			State.getState(fr, "Martinique", "", null),
    			State.getState(fr, "Réunion", "", null),
    			State.getState(gb, "Channel Islands", "CHI", null),
    			State.getState(gb, "England", "ENG", null),
    			State.getState(gb, "Isle of Man", "IOM", null),
    			State.getState(gb, "Ireland", "IRL", null),
    			State.getState(gb, "Northern Ireland", "NIR", null),
    			State.getState(gb, "Scotland", "SCT", null),
    			State.getState(gb, "WALES", "WAL", null),
    			State.getState(de, "Baden-Württemberg", "", null),
    			State.getState(de, "Bavaria", "", null),
    			State.getState(de, "Berlin", "", null),
    			State.getState(de, "Brandenburg", "", null),
    			State.getState(de, "Bremen", "", null),
    			State.getState(de, "Hamburg", "", null),
    			State.getState(de, "Hesse", "", null),
    			State.getState(de, "Mecklenburg-Western Pomerania", "", null),
    			State.getState(de, "Lower Saxony", "", null),
    			State.getState(de, "North Rhine-Westphalia", "", null),
    			State.getState(de, "Rhineland-Palatinate", "", null),
    			State.getState(de, "Saarland", "", null),
    			State.getState(de, "Saxony", "", null),
    			State.getState(de, "Saxony-Anhalt", "", null),
    			State.getState(de, "Schleswig-Holstein", "", null),
    			State.getState(de, "Thuringia", "", null),
    			State.getState(nl, "Drenthe", "", null),
    			State.getState(nl, "Flevoland", "", null),
    			State.getState(nl, "Friesland", "", null),
    			State.getState(nl, "Gelderland", "", null),
    			State.getState(nl, "Groningen", "", null),
    			State.getState(nl, "Limburg", "", null),
    			State.getState(nl, "North Brabant", "", null),
    			State.getState(nl, "North Holland", "", null),
    			State.getState(nl, "Overijssel", "", null),
    			State.getState(nl, "Utrecht", "", null),
    			State.getState(nl, "Zealand", "", null),
    			State.getState(nl, "South Holland", "", null),
    	})
			entityManager.persist(state);
    }

    public static void loadStateAliases()
    {
    	Country us = Country.getCountry("US", null, null);
    	Country fr = Country.getCountry("FR", null, null);
    	Country de = Country.getCountry("DE", null, null);
    	Country nl = Country.getCountry("NL", null, null);
		for(StateAlias stateAlias: new StateAlias[]{
	    		new StateAlias("New York", "New York State", us),
	    		new StateAlias("Alsace", "Alsace-Lorraine", fr),
	    		new StateAlias("Bavaria", "Bayern", de),
	    		new StateAlias("Hesse", "Hessen", de),
	    		new StateAlias("Mecklenburg-Western Pomerania", "Mecklenburg-Vorpommern", de),
	    		new StateAlias("Lower Saxony", "Niedersachsen", de),
	    		new StateAlias("North Rhine-Westphalia", "Nordrhein-Westfalen", de),
	    		new StateAlias("Rhineland-Palatinate", "Rheinland-Pfalz", de),
	    		new StateAlias("Saxony", "Sachsen", de),
	    		new StateAlias("Saxony-Anhalt", "Sachsen-Anhalt", de),
	    		new StateAlias("Thuringia", "Thüringen", de),
	    		new StateAlias("North Brabant", "Noord Brabant", nl),
	    		new StateAlias("North Holland", "Noord Holland", nl),
	    		new StateAlias("Zealand", "Zeeland", nl),
	    		new StateAlias("South Holland", "Zuid Holland", nl),
	    		new StateAlias("South Holland", "Zuid-Holland", nl)
		})
			entityManager.persist(stateAlias);
    }

    public static void loadCountyAliases()
    {
    	Country us = Country.getCountry("United State", null, null);
    	Country gb = Country.getCountry("GreatBritain", null, null);
		for(CountyAlias countyAlias: new CountyAlias[]{
				new CountyAlias("Mohave County", "Mohave", us, State.getState(us, "ARIZONA", null, null)),
				new CountyAlias("Pope County", "Pope", us, State.getState(us, "ARKANSAS", null, null)),
				new CountyAlias("Alameda County", "Aameda", us, State.getState(us, "CALIFORNIA", null, null)),
				new CountyAlias("Calaveras County", "Calaveras", us, State.getState(us, "CALIFORNIA", null, null)),
				new CountyAlias("Calaveras County", "Calavaras County", us, State.getState(us, "CALIFORNIA", null, null)),
				new CountyAlias("Kern County", "Kern", us, State.getState(us, "CALIFORNIA", null, null)),
				new CountyAlias("Talbot County", "Talbot", us, State.getState(us, "GEORGIA", null, null)),
				new CountyAlias("Jo Daviess County", "Jo Davies County", us, State.getState(us, "ILLINOIS", null, null)),
				new CountyAlias("LaPorte County", "La Porte County", us, State.getState(us, "INDIANA", null, null)),
				new CountyAlias("Fayette County", "Fayette", us, State.getState(us, "IOWA", null, null)),
				new CountyAlias("Saint Louis County", "St Louis County", us, State.getState(us, "MISSOURI", null, null)),
				new CountyAlias("Kings County", "Kings", us, State.getState(us, "NEW YORK", null, null)),
				new CountyAlias("Queens County", "Queens", us, State.getState(us, "NEW YORK", null, null)),
				new CountyAlias("Guernsey County", "Guernsey", us, State.getState(us, "OHIO", null, null)),
				new CountyAlias("McIntosh County", "McIntosh", us, State.getState(us, "OKLAHOMA", null, null)),
				new CountyAlias("Muskogee County", "Muskogee", us, State.getState(us, "OKLAHOMA", null, null)),
				new CountyAlias("Tulsa County", "Tulsa", us, State.getState(us, "OKLAHOMA", null, null)),
				new CountyAlias("Henry County", "Henry", us, State.getState(us, "TENNESSEE", null, null)),
				new CountyAlias("Lavaca County", "Lavaca", us, State.getState(us, "TEXAS", null, null)),
				new CountyAlias("Nueces County", "Nueces", us, State.getState(us, "TEXAS", null, null)),
				new CountyAlias("Suffolk", "Nansemond County", us, State.getState(us, "VIRGINIA", null, null)),
				new CountyAlias("Devon", "Devonshire", gb, State.getState(gb, "ENGLAND", null, null)),
				new CountyAlias("Tyrone", "Tyrone County", gb, State.getState(gb, "NORTHERN IRELAND", null, null)),
				new CountyAlias("Yorkshire", "York", gb, State.getState(gb, "ENGLAND", null, null)),
				new CountyAlias("Roscommon", "County Roscommon", gb, State.getState(gb, "IRELAND", null, null))
		})
			entityManager.persist(countyAlias);
    }

    public static void loadFixups()
    {
		for(Fixup fix:new Fixup[]{
				new Fixup("Ireland, Tyrone", "Northern Ireland, Tyrone County"),
				new Fixup("Ireland, Tyrone County", "Northern Ireland, Tyrone County"),
				new Fixup("Russia, Odessa", "Ukraine, Odessa"),
				new Fixup("USA, California, Tulare County, Old Porterville Cemetery", "USA, California, Tulare County, Porterville, Old Porterville Cemetery"),
				new Fixup("USA, California, Tulare County, Porterville, Porterville Cem.", "USA, California, Tulare County, Porterville, Porterville Cemetery"),
				new Fixup("USA, California, Tulare County, Porterville, Porterville Cem., Hillcrest Memorial Park", "USA, California, Tulare County, Porterville, Porterville Cemetery, Hillcrest Memorial Park"),
				new Fixup("USA, California, Tulare County, Porterville, Porterville Hosp", "USA, California, Tulare County, Porterville, Porterville Hospital"),
				new Fixup("USA, Kentucky, Kentucky County, Hardin", "USA, Kentucky, Marshall County, Hardiny"),
				new Fixup("USA, Kentucky, Kentucky County", "USA, Kentucky, Marshall County"),
				new Fixup("USA, New York State, Clinton County, Ellenburghy", "USA, New York State, Clinton County, Ellenburg"),
				new Fixup("USA, Oklahoma, McIntosh", "USA, Oklahoma, McIntosh County"),
				new Fixup("USA, Oklahoma, Mcintosh County", "USA, Oklahoma, McIntosh County"),
				new Fixup("USA, Oklahoma, Mcintosh County, Boynton", "USA, Oklahoma, McIntosh County, Boynton"),
				new Fixup("USA, Wisconsin, Fond Du Lac County", "USA, Wisconsin, Fond du Lac County")
		})
			entityManager.persist(fix);
    }
}
