//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.02 at 10:07:12 PM EST 
//


package jaxb.gedcom;

import javax.xml.bind.annotation.AccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import jaxb.gedcom.ChildElement;
import jaxb.gedcom.LinkElement;


/**
 *  Date = D MMM YYYY, e.g., 3 MAR 1842 
 *  Time = H:MM[:SS[.F]], e.g., 5:42:03.8 
 * 
 * <p>Java class for Child element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="Child">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{}Link"/>
 *           &lt;element ref="{}ChildNbr" minOccurs="0"/>
 *           &lt;element ref="{}RelToFath" minOccurs="0"/>
 *           &lt;element ref="{}RelToMoth" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(AccessType.FIELD)
@XmlType(name = "", propOrder = {
    "link",
    "childNbr",
    "relToFath",
    "relToMoth"
})
@XmlRootElement(name = "Child")
public class ChildElement {

    @XmlElement(name = "Link")
    protected LinkElement link;
    @XmlElement(name = "ChildNbr")
    protected String childNbr;
    @XmlElement(name = "RelToFath")
    protected String relToFath;
    @XmlElement(name = "RelToMoth")
    protected String relToMoth;

    /**
     * Gets the value of the link property.
     * 
     * @return
     *     possible object is
     *     {@link LinkElement }
     *     
     */
    public LinkElement getLink() {
        return link;
    }

    /**
     * Sets the value of the link property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinkElement }
     *     
     */
    public void setLink(LinkElement value) {
        this.link = value;
    }

    /**
     * Gets the value of the childNbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChildNbr() {
        return childNbr;
    }

    /**
     * Sets the value of the childNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChildNbr(String value) {
        this.childNbr = value;
    }

    /**
     * Gets the value of the relToFath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelToFath() {
        return relToFath;
    }

    /**
     * Sets the value of the relToFath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelToFath(String value) {
        this.relToFath = value;
    }

    /**
     * Gets the value of the relToMoth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelToMoth() {
        return relToMoth;
    }

    /**
     * Sets the value of the relToMoth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelToMoth(String value) {
        this.relToMoth = value;
    }

}
