//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.02 at 10:07:12 PM EST 
//


package jaxb.gedcom;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.AccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import jaxb.gedcom.ChangedElement;
import jaxb.gedcom.DateElement;
import jaxb.gedcom.EnrichmentElement;
import jaxb.gedcom.EventRecElement;
import jaxb.gedcom.EvidenceElement;
import jaxb.gedcom.ExternalIDElement;
import jaxb.gedcom.NoteElement;
import jaxb.gedcom.ParticipantElement;
import jaxb.gedcom.PlaceElement;
import jaxb.gedcom.SubmitterElement;


/**
 *  event record 
 * 
 * <p>Java class for EventRec element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="EventRec">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{}Participant" maxOccurs="unbounded"/>
 *           &lt;element ref="{}Date" minOccurs="0"/>
 *           &lt;element ref="{}Place" minOccurs="0"/>
 *           &lt;element ref="{}Religion" minOccurs="0"/>
 *           &lt;element ref="{}ExternalID" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{}Submitter" minOccurs="0"/>
 *           &lt;element ref="{}Note" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{}Evidence" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{}Enrichment" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{}Changed" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;attribute name="Id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *         &lt;attribute name="Type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="VitalType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="birth"/>
 *               &lt;enumeration value="marriage"/>
 *               &lt;enumeration value="death"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/attribute>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(AccessType.FIELD)
@XmlType(name = "", propOrder = {
    "participant",
    "date",
    "place",
    "religion",
    "externalID",
    "submitter",
    "note",
    "evidence",
    "enrichment",
    "changed"
})
@XmlRootElement(name = "EventRec")
public class EventRecElement {

    @XmlElement(name = "Participant")
    protected List<ParticipantElement> participant;
    @XmlElement(name = "Date")
    protected DateElement date;
    @XmlElement(name = "Place")
    protected PlaceElement place;
    @XmlElement(name = "Religion")
    protected String religion;
    @XmlElement(name = "ExternalID")
    protected List<ExternalIDElement> externalID;
    @XmlElement(name = "Submitter")
    protected SubmitterElement submitter;
    @XmlElement(name = "Note")
    protected List<NoteElement> note;
    @XmlElement(name = "Evidence")
    protected List<EvidenceElement> evidence;
    @XmlElement(name = "Enrichment")
    protected List<EnrichmentElement> enrichment;
    @XmlElement(name = "Changed")
    protected List<ChangedElement> changed;
    @XmlAttribute(name = "Id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    @XmlAttribute(name = "Type", required = true)
    protected String type;
    @XmlAttribute(name = "VitalType")
    protected String vitalType;

    /**
     * Gets the value of the participant property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the participant property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParticipant().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParticipantElement }
     * 
     * 
     */
    public List<ParticipantElement> getParticipant() {
        if (participant == null) {
            participant = new ArrayList<ParticipantElement>();
        }
        return this.participant;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link DateElement }
     *     
     */
    public DateElement getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateElement }
     *     
     */
    public void setDate(DateElement value) {
        this.date = value;
    }

    /**
     * Gets the value of the place property.
     * 
     * @return
     *     possible object is
     *     {@link PlaceElement }
     *     
     */
    public PlaceElement getPlace() {
        return place;
    }

    /**
     * Sets the value of the place property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlaceElement }
     *     
     */
    public void setPlace(PlaceElement value) {
        this.place = value;
    }

    /**
     * Gets the value of the religion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReligion() {
        return religion;
    }

    /**
     * Sets the value of the religion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReligion(String value) {
        this.religion = value;
    }

    /**
     * Gets the value of the externalID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the externalID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExternalID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExternalIDElement }
     * 
     * 
     */
    public List<ExternalIDElement> getExternalID() {
        if (externalID == null) {
            externalID = new ArrayList<ExternalIDElement>();
        }
        return this.externalID;
    }

    /**
     * Gets the value of the submitter property.
     * 
     * @return
     *     possible object is
     *     {@link SubmitterElement }
     *     
     */
    public SubmitterElement getSubmitter() {
        return submitter;
    }

    /**
     * Sets the value of the submitter property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubmitterElement }
     *     
     */
    public void setSubmitter(SubmitterElement value) {
        this.submitter = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the note property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNote().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NoteElement }
     * 
     * 
     */
    public List<NoteElement> getNote() {
        if (note == null) {
            note = new ArrayList<NoteElement>();
        }
        return this.note;
    }

    /**
     * Gets the value of the evidence property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the evidence property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEvidence().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EvidenceElement }
     * 
     * 
     */
    public List<EvidenceElement> getEvidence() {
        if (evidence == null) {
            evidence = new ArrayList<EvidenceElement>();
        }
        return this.evidence;
    }

    /**
     * Gets the value of the enrichment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the enrichment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEnrichment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EnrichmentElement }
     * 
     * 
     */
    public List<EnrichmentElement> getEnrichment() {
        if (enrichment == null) {
            enrichment = new ArrayList<EnrichmentElement>();
        }
        return this.enrichment;
    }

    /**
     * Gets the value of the changed property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the changed property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChanged().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ChangedElement }
     * 
     * 
     */
    public List<ChangedElement> getChanged() {
        if (changed == null) {
            changed = new ArrayList<ChangedElement>();
        }
        return this.changed;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the vitalType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVitalType() {
        return vitalType;
    }

    /**
     * Sets the value of the vitalType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVitalType(String value) {
        this.vitalType = value;
    }

}
