//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.02 at 10:07:12 PM EST 
//


package jaxb.gedcom;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.AccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import jaxb.gedcom.BasedOnElement;
import jaxb.gedcom.ChangedElement;
import jaxb.gedcom.ChildElement;
import jaxb.gedcom.EnrichmentElement;
import jaxb.gedcom.EvidenceElement;
import jaxb.gedcom.ExternalIDElement;
import jaxb.gedcom.FamilyRecElement;
import jaxb.gedcom.HusbFathElement;
import jaxb.gedcom.NoteElement;
import jaxb.gedcom.SubmitterElement;
import jaxb.gedcom.WifeMothElement;


/**
 *  family record 
 * 
 * <p>Java class for FamilyRec element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="FamilyRec">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{}HusbFath" minOccurs="0"/>
 *           &lt;element ref="{}WifeMoth" minOccurs="0"/>
 *           &lt;element ref="{}Child" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{}BasedOn" minOccurs="0"/>
 *           &lt;element ref="{}ExternalID" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{}Submitter" minOccurs="0"/>
 *           &lt;element ref="{}Note" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{}Evidence" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{}Enrichment" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{}Changed" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;attribute name="Id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(AccessType.FIELD)
@XmlType(name = "", propOrder = {
    "husbFath",
    "wifeMoth",
    "child",
    "basedOn",
    "externalID",
    "submitter",
    "note",
    "evidence",
    "enrichment",
    "changed"
})
@XmlRootElement(name = "FamilyRec")
public class FamilyRecElement {

    @XmlElement(name = "HusbFath")
    protected HusbFathElement husbFath;
    @XmlElement(name = "WifeMoth")
    protected WifeMothElement wifeMoth;
    @XmlElement(name = "Child")
    protected List<ChildElement> child;
    @XmlElement(name = "BasedOn")
    protected BasedOnElement basedOn;
    @XmlElement(name = "ExternalID")
    protected List<ExternalIDElement> externalID;
    @XmlElement(name = "Submitter")
    protected SubmitterElement submitter;
    @XmlElement(name = "Note")
    protected List<NoteElement> note;
    @XmlElement(name = "Evidence")
    protected List<EvidenceElement> evidence;
    @XmlElement(name = "Enrichment")
    protected List<EnrichmentElement> enrichment;
    @XmlElement(name = "Changed")
    protected List<ChangedElement> changed;
    @XmlAttribute(name = "Id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;

    /**
     * Gets the value of the husbFath property.
     * 
     * @return
     *     possible object is
     *     {@link HusbFathElement }
     *     
     */
    public HusbFathElement getHusbFath() {
        return husbFath;
    }

    /**
     * Sets the value of the husbFath property.
     * 
     * @param value
     *     allowed object is
     *     {@link HusbFathElement }
     *     
     */
    public void setHusbFath(HusbFathElement value) {
        this.husbFath = value;
    }

    /**
     * Gets the value of the wifeMoth property.
     * 
     * @return
     *     possible object is
     *     {@link WifeMothElement }
     *     
     */
    public WifeMothElement getWifeMoth() {
        return wifeMoth;
    }

    /**
     * Sets the value of the wifeMoth property.
     * 
     * @param value
     *     allowed object is
     *     {@link WifeMothElement }
     *     
     */
    public void setWifeMoth(WifeMothElement value) {
        this.wifeMoth = value;
    }

    /**
     * Gets the value of the child property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the child property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChild().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ChildElement }
     * 
     * 
     */
    public List<ChildElement> getChild() {
        if (child == null) {
            child = new ArrayList<ChildElement>();
        }
        return this.child;
    }

    /**
     * Gets the value of the basedOn property.
     * 
     * @return
     *     possible object is
     *     {@link BasedOnElement }
     *     
     */
    public BasedOnElement getBasedOn() {
        return basedOn;
    }

    /**
     * Sets the value of the basedOn property.
     * 
     * @param value
     *     allowed object is
     *     {@link BasedOnElement }
     *     
     */
    public void setBasedOn(BasedOnElement value) {
        this.basedOn = value;
    }

    /**
     * Gets the value of the externalID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the externalID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExternalID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExternalIDElement }
     * 
     * 
     */
    public List<ExternalIDElement> getExternalID() {
        if (externalID == null) {
            externalID = new ArrayList<ExternalIDElement>();
        }
        return this.externalID;
    }

    /**
     * Gets the value of the submitter property.
     * 
     * @return
     *     possible object is
     *     {@link SubmitterElement }
     *     
     */
    public SubmitterElement getSubmitter() {
        return submitter;
    }

    /**
     * Sets the value of the submitter property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubmitterElement }
     *     
     */
    public void setSubmitter(SubmitterElement value) {
        this.submitter = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the note property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNote().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NoteElement }
     * 
     * 
     */
    public List<NoteElement> getNote() {
        if (note == null) {
            note = new ArrayList<NoteElement>();
        }
        return this.note;
    }

    /**
     * Gets the value of the evidence property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the evidence property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEvidence().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EvidenceElement }
     * 
     * 
     */
    public List<EvidenceElement> getEvidence() {
        if (evidence == null) {
            evidence = new ArrayList<EvidenceElement>();
        }
        return this.evidence;
    }

    /**
     * Gets the value of the enrichment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the enrichment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEnrichment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EnrichmentElement }
     * 
     * 
     */
    public List<EnrichmentElement> getEnrichment() {
        if (enrichment == null) {
            enrichment = new ArrayList<EnrichmentElement>();
        }
        return this.enrichment;
    }

    /**
     * Gets the value of the changed property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the changed property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChanged().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ChangedElement }
     * 
     * 
     */
    public List<ChangedElement> getChanged() {
        if (changed == null) {
            changed = new ArrayList<ChangedElement>();
        }
        return this.changed;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
