//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.02 at 10:07:12 PM EST 
//


package jaxb.gedcom;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.AccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import jaxb.gedcom.ContactRecElement;
import jaxb.gedcom.EventRecElement;
import jaxb.gedcom.FamilyRecElement;
import jaxb.gedcom.GEDCOMElement;
import jaxb.gedcom.GroupRecElement;
import jaxb.gedcom.HeaderRecElement;
import jaxb.gedcom.IndividualRecElement;
import jaxb.gedcom.LDSOrdRecElement;
import jaxb.gedcom.RepositoryRecElement;
import jaxb.gedcom.SourceRecElement;


/**
 *  GEDCOM 6.0 DTD 
 *      30 December, 2002
 *     
 *      Sample minimal GEDCOM 6.0 XML file:
 * 	(? xml version="1.0" encoding="UTF-8" ?)
 * 	(!DOCTYPE GEDCOM SYSTEM "GEDCOM60.dtd")
 * 	(GEDCOM)
 * 	( HeaderRec)
 * 	(FileCreation Date="")(/FileCreation)
 * 	(Submitter)
 * 	(Link Target="" Ref="")(/Link)
 * 	(/Submitter)
 * 	(/HeaderRec)
 * 	(IndividualRec Id="testID")
 * 	(/IndividualRec)
 * 	(/GEDCOM)
 *      (Remove extra spaces from xml and HeaderRec tags,
 *      added here to allow display in a browser.)
 * 
 *      GEDCOM 6.0 spec is available at http://www.familysearch.org/GEDCOM/GedXML60.pdf
 *  
 *  GEDCOM root 
 * 
 * <p>Java class for GEDCOM element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="GEDCOM">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{}HeaderRec"/>
 *           &lt;element ref="{}FamilyRec" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{}IndividualRec" maxOccurs="unbounded"/>
 *           &lt;element ref="{}EventRec" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{}LDSOrdRec" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{}ContactRec" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{}SourceRec" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{}RepositoryRec" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{}GroupRec" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(AccessType.FIELD)
@XmlType(name = "", propOrder = {
    "headerRec",
    "familyRec",
    "individualRec",
    "eventRec",
    "ldsOrdRec",
    "contactRec",
    "sourceRec",
    "repositoryRec",
    "groupRec"
})
@XmlRootElement(name = "GEDCOM")
public class GEDCOMElement {

    @XmlElement(name = "HeaderRec")
    protected HeaderRecElement headerRec;
    @XmlElement(name = "FamilyRec")
    protected List<FamilyRecElement> familyRec;
    @XmlElement(name = "IndividualRec")
    protected List<IndividualRecElement> individualRec;
    @XmlElement(name = "EventRec")
    protected List<EventRecElement> eventRec;
    @XmlElement(name = "LDSOrdRec")
    protected List<LDSOrdRecElement> ldsOrdRec;
    @XmlElement(name = "ContactRec")
    protected List<ContactRecElement> contactRec;
    @XmlElement(name = "SourceRec")
    protected List<SourceRecElement> sourceRec;
    @XmlElement(name = "RepositoryRec")
    protected List<RepositoryRecElement> repositoryRec;
    @XmlElement(name = "GroupRec")
    protected List<GroupRecElement> groupRec;

    /**
     * Gets the value of the headerRec property.
     * 
     * @return
     *     possible object is
     *     {@link HeaderRecElement }
     *     
     */
    public HeaderRecElement getHeaderRec() {
        return headerRec;
    }

    /**
     * Sets the value of the headerRec property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeaderRecElement }
     *     
     */
    public void setHeaderRec(HeaderRecElement value) {
        this.headerRec = value;
    }

    /**
     * Gets the value of the familyRec property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the familyRec property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFamilyRec().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FamilyRecElement }
     * 
     * 
     */
    public List<FamilyRecElement> getFamilyRec() {
        if (familyRec == null) {
            familyRec = new ArrayList<FamilyRecElement>();
        }
        return this.familyRec;
    }

    /**
     * Gets the value of the individualRec property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the individualRec property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIndividualRec().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IndividualRecElement }
     * 
     * 
     */
    public List<IndividualRecElement> getIndividualRec() {
        if (individualRec == null) {
            individualRec = new ArrayList<IndividualRecElement>();
        }
        return this.individualRec;
    }

    /**
     * Gets the value of the eventRec property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the eventRec property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEventRec().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EventRecElement }
     * 
     * 
     */
    public List<EventRecElement> getEventRec() {
        if (eventRec == null) {
            eventRec = new ArrayList<EventRecElement>();
        }
        return this.eventRec;
    }

    /**
     * Gets the value of the ldsOrdRec property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ldsOrdRec property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLDSOrdRec().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LDSOrdRecElement }
     * 
     * 
     */
    public List<LDSOrdRecElement> getLDSOrdRec() {
        if (ldsOrdRec == null) {
            ldsOrdRec = new ArrayList<LDSOrdRecElement>();
        }
        return this.ldsOrdRec;
    }

    /**
     * Gets the value of the contactRec property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contactRec property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContactRec().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContactRecElement }
     * 
     * 
     */
    public List<ContactRecElement> getContactRec() {
        if (contactRec == null) {
            contactRec = new ArrayList<ContactRecElement>();
        }
        return this.contactRec;
    }

    /**
     * Gets the value of the sourceRec property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sourceRec property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSourceRec().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SourceRecElement }
     * 
     * 
     */
    public List<SourceRecElement> getSourceRec() {
        if (sourceRec == null) {
            sourceRec = new ArrayList<SourceRecElement>();
        }
        return this.sourceRec;
    }

    /**
     * Gets the value of the repositoryRec property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the repositoryRec property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRepositoryRec().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RepositoryRecElement }
     * 
     * 
     */
    public List<RepositoryRecElement> getRepositoryRec() {
        if (repositoryRec == null) {
            repositoryRec = new ArrayList<RepositoryRecElement>();
        }
        return this.repositoryRec;
    }

    /**
     * Gets the value of the groupRec property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the groupRec property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGroupRec().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GroupRecElement }
     * 
     * 
     */
    public List<GroupRecElement> getGroupRec() {
        if (groupRec == null) {
            groupRec = new ArrayList<GroupRecElement>();
        }
        return this.groupRec;
    }

}
