//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.02 at 10:07:12 PM EST 
//


package jaxb.gedcom;

import javax.xml.bind.annotation.AccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import jaxb.gedcom.CitationElement;
import jaxb.gedcom.FileCreationElement;
import jaxb.gedcom.HeaderRecElement;
import jaxb.gedcom.NoteElement;
import jaxb.gedcom.SubmitterElement;


/**
 *  header record 
 * 
 * <p>Java class for HeaderRec element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="HeaderRec">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{}FileCreation"/>
 *           &lt;element ref="{}Citation" minOccurs="0"/>
 *           &lt;element ref="{}Submitter"/>
 *           &lt;element ref="{}Note" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(AccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fileCreation",
    "citation",
    "submitter",
    "note"
})
@XmlRootElement(name = "HeaderRec")
public class HeaderRecElement {

    @XmlElement(name = "FileCreation")
    protected FileCreationElement fileCreation;
    @XmlElement(name = "Citation")
    protected CitationElement citation;
    @XmlElement(name = "Submitter")
    protected SubmitterElement submitter;
    @XmlElement(name = "Note")
    protected NoteElement note;

    /**
     * Gets the value of the fileCreation property.
     * 
     * @return
     *     possible object is
     *     {@link FileCreationElement }
     *     
     */
    public FileCreationElement getFileCreation() {
        return fileCreation;
    }

    /**
     * Sets the value of the fileCreation property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileCreationElement }
     *     
     */
    public void setFileCreation(FileCreationElement value) {
        this.fileCreation = value;
    }

    /**
     * Gets the value of the citation property.
     * 
     * @return
     *     possible object is
     *     {@link CitationElement }
     *     
     */
    public CitationElement getCitation() {
        return citation;
    }

    /**
     * Sets the value of the citation property.
     * 
     * @param value
     *     allowed object is
     *     {@link CitationElement }
     *     
     */
    public void setCitation(CitationElement value) {
        this.citation = value;
    }

    /**
     * Gets the value of the submitter property.
     * 
     * @return
     *     possible object is
     *     {@link SubmitterElement }
     *     
     */
    public SubmitterElement getSubmitter() {
        return submitter;
    }

    /**
     * Sets the value of the submitter property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubmitterElement }
     *     
     */
    public void setSubmitter(SubmitterElement value) {
        this.submitter = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link NoteElement }
     *     
     */
    public NoteElement getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoteElement }
     *     
     */
    public void setNote(NoteElement value) {
        this.note = value;
    }

}
