//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.02 at 10:07:12 PM EST 
//


package jaxb.gedcom;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.AccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import jaxb.gedcom.AssocIndivElement;
import jaxb.gedcom.ChangedElement;
import jaxb.gedcom.DupIndivElement;
import jaxb.gedcom.EnrichmentElement;
import jaxb.gedcom.EvidenceElement;
import jaxb.gedcom.ExternalIDElement;
import jaxb.gedcom.IndivNameElement;
import jaxb.gedcom.IndividualRecElement;
import jaxb.gedcom.NoteElement;
import jaxb.gedcom.PersInfoElement;
import jaxb.gedcom.SubmitterElement;


/**
 *  individual record 
 * 
 * <p>Java class for IndividualRec element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="IndividualRec">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{}IndivName" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{}Gender" minOccurs="0"/>
 *           &lt;element ref="{}DeathStatus" minOccurs="0"/>
 *           &lt;element ref="{}PersInfo" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{}AssocIndiv" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{}DupIndiv" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{}ExternalID" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{}Submitter" minOccurs="0"/>
 *           &lt;element ref="{}Note" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{}Evidence" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{}Enrichment" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{}Changed" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;attribute name="Id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(AccessType.FIELD)
@XmlType(name = "", propOrder = {
    "indivName",
    "gender",
    "deathStatus",
    "persInfo",
    "assocIndiv",
    "dupIndiv",
    "externalID",
    "submitter",
    "note",
    "evidence",
    "enrichment",
    "changed"
})
@XmlRootElement(name = "IndividualRec")
public class IndividualRecElement {

    @XmlElement(name = "IndivName")
    protected List<IndivNameElement> indivName;
    @XmlElement(name = "Gender")
    protected String gender;
    @XmlElement(name = "DeathStatus")
    protected String deathStatus;
    @XmlElement(name = "PersInfo")
    protected List<PersInfoElement> persInfo;
    @XmlElement(name = "AssocIndiv")
    protected List<AssocIndivElement> assocIndiv;
    @XmlElement(name = "DupIndiv")
    protected List<DupIndivElement> dupIndiv;
    @XmlElement(name = "ExternalID")
    protected List<ExternalIDElement> externalID;
    @XmlElement(name = "Submitter")
    protected SubmitterElement submitter;
    @XmlElement(name = "Note")
    protected List<NoteElement> note;
    @XmlElement(name = "Evidence")
    protected List<EvidenceElement> evidence;
    @XmlElement(name = "Enrichment")
    protected List<EnrichmentElement> enrichment;
    @XmlElement(name = "Changed")
    protected List<ChangedElement> changed;
    @XmlAttribute(name = "Id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;

    /**
     * Gets the value of the indivName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the indivName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIndivName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IndivNameElement }
     * 
     * 
     */
    public List<IndivNameElement> getIndivName() {
        if (indivName == null) {
            indivName = new ArrayList<IndivNameElement>();
        }
        return this.indivName;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGender(String value) {
        this.gender = value;
    }

    /**
     * Gets the value of the deathStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeathStatus() {
        return deathStatus;
    }

    /**
     * Sets the value of the deathStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeathStatus(String value) {
        this.deathStatus = value;
    }

    /**
     * Gets the value of the persInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the persInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPersInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PersInfoElement }
     * 
     * 
     */
    public List<PersInfoElement> getPersInfo() {
        if (persInfo == null) {
            persInfo = new ArrayList<PersInfoElement>();
        }
        return this.persInfo;
    }

    /**
     * Gets the value of the assocIndiv property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the assocIndiv property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAssocIndiv().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AssocIndivElement }
     * 
     * 
     */
    public List<AssocIndivElement> getAssocIndiv() {
        if (assocIndiv == null) {
            assocIndiv = new ArrayList<AssocIndivElement>();
        }
        return this.assocIndiv;
    }

    /**
     * Gets the value of the dupIndiv property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dupIndiv property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDupIndiv().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DupIndivElement }
     * 
     * 
     */
    public List<DupIndivElement> getDupIndiv() {
        if (dupIndiv == null) {
            dupIndiv = new ArrayList<DupIndivElement>();
        }
        return this.dupIndiv;
    }

    /**
     * Gets the value of the externalID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the externalID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExternalID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExternalIDElement }
     * 
     * 
     */
    public List<ExternalIDElement> getExternalID() {
        if (externalID == null) {
            externalID = new ArrayList<ExternalIDElement>();
        }
        return this.externalID;
    }

    /**
     * Gets the value of the submitter property.
     * 
     * @return
     *     possible object is
     *     {@link SubmitterElement }
     *     
     */
    public SubmitterElement getSubmitter() {
        return submitter;
    }

    /**
     * Sets the value of the submitter property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubmitterElement }
     *     
     */
    public void setSubmitter(SubmitterElement value) {
        this.submitter = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the note property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNote().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NoteElement }
     * 
     * 
     */
    public List<NoteElement> getNote() {
        if (note == null) {
            note = new ArrayList<NoteElement>();
        }
        return this.note;
    }

    /**
     * Gets the value of the evidence property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the evidence property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEvidence().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EvidenceElement }
     * 
     * 
     */
    public List<EvidenceElement> getEvidence() {
        if (evidence == null) {
            evidence = new ArrayList<EvidenceElement>();
        }
        return this.evidence;
    }

    /**
     * Gets the value of the enrichment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the enrichment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEnrichment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EnrichmentElement }
     * 
     * 
     */
    public List<EnrichmentElement> getEnrichment() {
        if (enrichment == null) {
            enrichment = new ArrayList<EnrichmentElement>();
        }
        return this.enrichment;
    }

    /**
     * Gets the value of the changed property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the changed property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChanged().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ChangedElement }
     * 
     * 
     */
    public List<ChangedElement> getChanged() {
        if (changed == null) {
            changed = new ArrayList<ChangedElement>();
        }
        return this.changed;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
