//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.02 at 10:07:12 PM EST 
//


package jaxb.gedcom;

import javax.xml.bind.annotation.AccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import jaxb.gedcom.DateElement;
import jaxb.gedcom.OrdStatElement;


/**
 * <p>Java class for OrdStat element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="OrdStat">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{}Date" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;attribute name="Code" use="required">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="bic"/>
 *               &lt;enumeration value="canceled"/>
 *               &lt;enumeration value="child"/>
 *               &lt;enumeration value="cleared"/>
 *               &lt;enumeration value="completed"/>
 *               &lt;enumeration value="dns"/>
 *               &lt;enumeration value="qualified"/>
 *               &lt;enumeration value="stillborn"/>
 *               &lt;enumeration value="submitted"/>
 *               &lt;enumeration value="uncleared"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/attribute>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(AccessType.FIELD)
@XmlType(name = "", propOrder = {
    "date"
})
@XmlRootElement(name = "OrdStat")
public class OrdStatElement {

    @XmlElement(name = "Date")
    protected DateElement date;
    @XmlAttribute(name = "Code", required = true)
    protected String code;

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link DateElement }
     *     
     */
    public DateElement getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateElement }
     *     
     */
    public void setDate(DateElement value) {
        this.date = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

}
